/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.interapp.sm;

import de.audi.atip.interapp.sm.IInterappEvent;

public interface IInterappConBluetoothEvent
extends IInterappEvent {
    public static final int EVENT_BLUETOOTH_INIT;
    public static final int EVENT_BLUETOOTH_CONNECTING_START;
    public static final int EVENT_BLUETOOTH_CONNECTING_END;
    public static final int EVENT_BLUETOOTH_DISCONNECTING_START;
    public static final int EVENT_BLUETOOTH_DISCONNECTING_END;
    public static final int EVENT_BLUETOOTH_UPDATE_BONDING_RESULT;
    public static final int EVENT_BLUETOOTH_INQUIRY_ENTER;
    public static final int EVENT_BLUETOOTH_INQUIRY_LEAVE;
    public static final int EVENT_BLUETOOTH_NEW_DEVICE_FOUND;
    public static final int EVENT_BLUETOOTH_INQUIRY_RESUME;
    public static final int EVENT_BLUETOOTH_INQUIRY_DEVICE_SELECTED;
    public static final int EVENT_BLUETOOTH_INQUIRY_RESPONSE;
    public static final int EVENT_BLUETOOTH_INQUIRY_GET_SERVICES_RESPONSE;
    public static final int EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_START;
    public static final int EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_END;
    public static final String[] events;

    static {
        events = new String[]{"EVENT_BLUETOOTH_INIT", "EVENT_BLUETOOTH_CONNECTING_START", "EVENT_BLUETOOTH_CONNECTING_END", "EVENT_BLUETOOTH_DISCONNECTING_START", "EVENT_BLUETOOTH_DISCONNECTING_END", "EVENT_BLUETOOTH_UPDATE_BONDING_RESULT", "EVENT_BLUETOOTH_INQUIRY_ENTER", "EVENT_BLUETOOTH_INQUIRY_LEAVE", "EVENT_BLUETOOTH_NEW_DEVICE_FOUND", "EVENT_BLUETOOTH_INQUIRY_RESUME", "EVENT_BLUETOOTH_INQUIRY_DEVICE_SELECTED", "EVENT_BLUETOOTH_INQUIRY_RESPONSE", "EVENT_BLUETOOTH_INQUIRY_GET_SERVICES_RESPONSE", "EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_START", "EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_END"};
    }
}

