/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.interapp.sm;

import de.audi.atip.interapp.sm.IInterappEvent;

public interface IInterappConBluetoothEvent
extends IInterappEvent {
    public static final int EVENT_BLUETOOTH_INIT = 0;
    public static final int EVENT_BLUETOOTH_CONNECTING_START = 1;
    public static final int EVENT_BLUETOOTH_CONNECTING_END = 2;
    public static final int EVENT_BLUETOOTH_DISCONNECTING_START = 3;
    public static final int EVENT_BLUETOOTH_DISCONNECTING_END = 4;
    public static final int EVENT_BLUETOOTH_UPDATE_BONDING_RESULT = 5;
    public static final int EVENT_BLUETOOTH_INQUIRY_ENTER = 6;
    public static final int EVENT_BLUETOOTH_INQUIRY_LEAVE = 7;
    public static final int EVENT_BLUETOOTH_NEW_DEVICE_FOUND = 8;
    public static final int EVENT_BLUETOOTH_INQUIRY_RESUME = 9;
    public static final int EVENT_BLUETOOTH_INQUIRY_DEVICE_SELECTED = 10;
    public static final int EVENT_BLUETOOTH_INQUIRY_RESPONSE = 11;
    public static final int EVENT_BLUETOOTH_INQUIRY_GET_SERVICES_RESPONSE = 12;
    public static final int EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_START = 13;
    public static final int EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_END = 14;
    public static final String[] events = new String[]{"EVENT_BLUETOOTH_INIT", "EVENT_BLUETOOTH_CONNECTING_START", "EVENT_BLUETOOTH_CONNECTING_END", "EVENT_BLUETOOTH_DISCONNECTING_START", "EVENT_BLUETOOTH_DISCONNECTING_END", "EVENT_BLUETOOTH_UPDATE_BONDING_RESULT", "EVENT_BLUETOOTH_INQUIRY_ENTER", "EVENT_BLUETOOTH_INQUIRY_LEAVE", "EVENT_BLUETOOTH_NEW_DEVICE_FOUND", "EVENT_BLUETOOTH_INQUIRY_RESUME", "EVENT_BLUETOOTH_INQUIRY_DEVICE_SELECTED", "EVENT_BLUETOOTH_INQUIRY_RESPONSE", "EVENT_BLUETOOTH_INQUIRY_GET_SERVICES_RESPONSE", "EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_START", "EVENT_BLUETOOTH_REMOVE_AUTHENTICATION_END"};
}

