/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.media;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_PARENTALML = 1;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_PREFERREDLANGUAGE = 2;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_MEDIALIST = 3;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_DEVICELIST = 4;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_CUSTOMERUPDATE = 5;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_APPLICATIONVERSION = 7;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_METADATADBVERSION = 8;
    public static final int ATTRIBUTE_ID_DSIMEDIABASE_PROFILESTATE = 9;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_BROWSEMODE = 1;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_CONTENTFILTER = 2;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_BROWSEMEDIA = 3;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_BROWSEFOLDER = 4;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_LISTSIZE = 5;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_SEARCHSPELLERSTATE = 6;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_SEARCHSIZE = 7;
    public static final int ATTRIBUTE_ID_DSIMEDIABROWSER_ALPHABETICALINDEX = 8;
    public static final int ATTRIBUTE_ID_DSIMEDIAONLINE_BUFFERSTATE = 1;
    public static final int ATTRIBUTE_ID_DSIMEDIAONLINE_BUFFERFILLINFO = 2;
    public static final int ATTRIBUTE_ID_DSIMEDIAONLINE_AUDIOSETTINGS = 3;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_VIDEOFORMAT = 1;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_VIDEONORM = 2;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_CMDBLOCKINGMASK = 3;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_NUMVIDEOANGLES = 4;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKMODELIST = 5;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKMODE = 6;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKSTATE = 7;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVEMEDIA = 8;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKFOLDER = 9;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_CAPABILITIES = 10;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYPOSITION = 11;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYVIEWSIZE = 12;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVEVIDEOANGLE = 13;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_AUDIOSTREAMLIST = 14;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVEAUDIOSTREAM = 15;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_SUBTITLELIST = 16;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_ACTIVESUBTITLE = 17;
    public static final int ATTRIBUTE_ID_DSIMEDIAPLAYER_PLAYBACKCONTENTFOLDER = 18;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_ACTIVEMEDIA = 1;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_IMPORTSUMMARY = 2;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_IMPORTPROGRESS = 3;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_DELETIONPROGRESS = 4;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_DATABASESPACE = 5;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_IMPORTSTATUS = 6;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_DELETIONSTATUS = 7;
    public static final int ATTRIBUTE_ID_DSIMEDIARECORDER_TARGETMEDIA = 8;
    public static final int ATTRIBUTE_ID_DSIMEDIAROUTER_STREAMINGSTATUS = 1;
    public static final int ATTRIBUTE_ID_DSIMEDIAROUTER_ACTIVEAUDIOROUTES = 2;
    public static final int ATTRIBUTE_ID_DSIMETADATASERVICE_ONLINELOOKUPSTATUS = 1;
    public static final int ATTRIBUTE_ID_DSIRADIOTAGGING_COMPATIBLEDEVAVAIL = 1;
}

