/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.testsupport.hmi.evohighscale;

import de.audi.atip.hmi.view.HMIView;
import de.audi.atip.hmi.view.Screen;
import de.audi.tghu.testsupport.hmi.evohighscale.TestSupportScreenBag1$1;
import de.audi.tghu.testsupport.hmi.evohighscale.TestSupportScreenBag1$2;
import de.audi.tghu.testsupport.hmi.evohighscale.TestSupportScreenBag1$3;
import de.audi.tghu.testsupport.hmi.evohighscale.TestSupportScreenBag1$4;
import de.audi.tghu.testsupport.hmi.evohighscale.TestSupportScreenFactory;
import de.esolutions.hmi.widgets.audi.evo.ScreenWidgetEVO;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.CompositeRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ContainerRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.FocusCursorRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.GlassplateRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ScreenRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ScrollbarRendererKanziHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.TitleBarRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.menu.MenuRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.ContainerController;
import de.esolutions.hmi.widgets.audi.evo.widgets.FocusCursorController;
import de.esolutions.hmi.widgets.audi.evo.widgets.GlassplateController;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.ScrollbarController;
import de.esolutions.hmi.widgets.audi.evo.widgets.StatusBarStubController;
import de.esolutions.hmi.widgets.audi.evo.widgets.TitleBarWidget;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.BaseListModelAccess;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.InfoLineRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.ListController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;

public class TestSupportScreenBag1 {
    public static Screen tsMain(TestSupportScreenFactory testSupportScreenFactory, int n) {
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        MenuItemController menuItemController = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(menuItemController);
        menuItemController.setRenderer(compositeRendererHigh);
        menuItemController.setBitmaps(new int[]{39, 39, 39, 39});
        menuItemController.setEvent(10429440);
        menuItemController.setLabelId(194978816);
        menuItemController.setGlassplateInsetsBottom(6);
        menuItemController.setGlassplateInsetsTop(7);
        menuItemController.setInternalID(10429440);
        menuItemController.setType(4);
        MenuItemController menuItemController2 = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh2 = new CompositeRendererHigh(menuItemController2);
        menuItemController2.setRenderer(compositeRendererHigh2);
        menuItemController2.setBitmaps(new int[]{39, 39, 39, 39});
        menuItemController2.setEvent(43983872);
        menuItemController2.setLabelId(329196544);
        menuItemController2.setGlassplateInsetsBottom(6);
        menuItemController2.setGlassplateInsetsTop(7);
        menuItemController2.setInternalID(463414272);
        menuItemController2.setType(4);
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(testSupportScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(396305408);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(menuItemController);
        menuController.add(menuItemController2);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127});
        iconController.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(testSupportScreenFactory.getFonts(2, n));
        labelController.setTextIds(new int[]{211756032});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh2);
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController);
        titleBarWidget.addTitle(labelController);
        titleBarWidget.addBreadcrumb(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController2.setOpacitySet(1.0f, -842216386);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(10429440);
        screenWidgetEVO.setScreenFactory(testSupportScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(testSupportScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138}, new HMIView[][]{{statusBarStubController}});
        return screenWidgetEVO;
    }

    public static Screen tsProviders(TestSupportScreenFactory testSupportScreenFactory, int n) {
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        ListController listController = new ListController();
        listController.setModelID(111092736);
        listController.setEvent(27206656);
        listController.setBounds(0, 0, 0, 0);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setDataAccess(new BaseListModelAccess());
        listController.setItemFactory(new TestSupportScreenBag1$1());
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(testSupportScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(396305408);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(listController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127});
        iconController.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(testSupportScreenFactory.getFonts(2, n));
        labelController.setTextIds(new int[]{228533248});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh2);
        labelController2.setTextIds(new int[]{211756032});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController);
        titleBarWidget.addTitle(labelController);
        titleBarWidget.addBreadcrumb(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController2.setOpacitySet(1.0f, -842216386);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(27206656);
        screenWidgetEVO.setScreenFactory(testSupportScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(testSupportScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138, 111092736}, new HMIView[][]{{statusBarStubController}, {listController}});
        screenWidgetEVO.setModelIDs(new int[]{111092736});
        screenWidgetEVO.setEventIDs(new int[]{27206656});
        return screenWidgetEVO;
    }

    public static Screen tsProviderDetails(TestSupportScreenFactory testSupportScreenFactory, int n) {
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        MenuItemController menuItemController = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(menuItemController);
        menuItemController.setRenderer(compositeRendererHigh);
        menuItemController.setModelID(60761088);
        menuItemController.setLabelId(245310464);
        menuItemController.setGlassplateInsetsBottom(6);
        menuItemController.setGlassplateInsetsTop(7);
        menuItemController.setInternalID(27206656);
        menuItemController.setType(8);
        MenuItemController menuItemController2 = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh2 = new CompositeRendererHigh(menuItemController2);
        menuItemController2.setRenderer(compositeRendererHigh2);
        menuItemController2.setModelID(77538304);
        menuItemController2.setLabelId(262087680);
        menuItemController2.setGlassplateInsetsBottom(6);
        menuItemController2.setGlassplateInsetsTop(7);
        menuItemController2.setInternalID(43983872);
        menuItemController2.setType(8);
        ListController listController = new ListController();
        listController.setModelID(94315520);
        listController.setBounds(0, 0, 0, 0);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setDataAccess(new BaseListModelAccess());
        listController.setItemFactory(new TestSupportScreenBag1$2());
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(testSupportScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(396305408);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(menuItemController);
        menuController.add(menuItemController2);
        menuController.add(listController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127});
        iconController.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(testSupportScreenFactory.getFonts(2, n));
        labelController.setModelID(27206656);
        labelController.setTextIds(new int[]{278864896});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh2);
        labelController2.setTextIds(new int[]{228533248});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController);
        titleBarWidget.addTitle(labelController);
        titleBarWidget.addBreadcrumb(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController2.setOpacitySet(1.0f, -842216386);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(43983872);
        screenWidgetEVO.setScreenFactory(testSupportScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(testSupportScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138, 27206656, 60761088, 77538304, 94315520}, new HMIView[][]{{statusBarStubController}, {labelController}, {menuItemController}, {menuItemController2}, {listController}});
        return screenWidgetEVO;
    }

    public static Screen tsReceivers(TestSupportScreenFactory testSupportScreenFactory, int n) {
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        ListController listController = new ListController();
        listController.setModelID(144647168);
        listController.setEvent(27206656);
        listController.setBounds(0, 0, 0, 0);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setDataAccess(new BaseListModelAccess());
        listController.setItemFactory(new TestSupportScreenBag1$3());
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(testSupportScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(396305408);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(listController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127});
        iconController.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(testSupportScreenFactory.getFonts(2, n));
        labelController.setTextIds(new int[]{345973760});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh2);
        labelController2.setTextIds(new int[]{211756032});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController);
        titleBarWidget.addTitle(labelController);
        titleBarWidget.addBreadcrumb(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController2.setOpacitySet(1.0f, -842216386);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(60761088);
        screenWidgetEVO.setScreenFactory(testSupportScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(testSupportScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138, 144647168}, new HMIView[][]{{statusBarStubController}, {listController}});
        screenWidgetEVO.setModelIDs(new int[]{144647168});
        screenWidgetEVO.setEventIDs(new int[]{27206656});
        return screenWidgetEVO;
    }

    public static Screen tsReceiversDetails(TestSupportScreenFactory testSupportScreenFactory, int n) {
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        ListController listController = new ListController();
        listController.setModelID(127869952);
        listController.setBounds(0, 0, 0, 0);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setRecordSetColumn(3);
        listController.setDataAccess(new BaseListModelAccess());
        listController.setItemFactory(new TestSupportScreenBag1$4());
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(testSupportScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(396305408);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(listController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127});
        iconController.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(testSupportScreenFactory.getFonts(2, n));
        labelController.setModelID(161424384);
        labelController.setTextIds(new int[]{278864896});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh2);
        labelController2.setTextIds(new int[]{345973760});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController);
        titleBarWidget.addTitle(labelController);
        titleBarWidget.addBreadcrumb(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController2.setOpacitySet(1.0f, -842216386);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(77538304);
        screenWidgetEVO.setScreenFactory(testSupportScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(testSupportScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138, 127869952, 161424384}, new HMIView[][]{{statusBarStubController}, {listController}, {labelController}});
        return screenWidgetEVO;
    }
}

