/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.organizer;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWENTRYAVAILABLE = 1;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWPUBLICPROFILEENTRYAVAILABLE = 2;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWTOPDESTINATIONENTRYAVAILABLE = 3;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWPUBLICPROFILETOPDESTENTRYAVAILABLE = 4;
    public static final int ATTRIBUTE_ID_DSIADBEDIT_NEWONLINEDESTINATIONENTRYAVAILABLE = 5;
    public static final int ATTRIBUTE_ID_DSIADBINIT_DEFAULTPUBLICPROFILEVISIBILITY = 1;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXLOCALENTRIES = 2;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXPHONEENTRIES = 3;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXTOPDESTENTRIES = 4;
    public static final int ATTRIBUTE_ID_DSIADBINIT_MAXSPEEDDIALENTRIES = 5;
    public static final int ATTRIBUTE_ID_DSIADBINIT_AUTOPROFILEALLOCATION = 6;
    public static final int ATTRIBUTE_ID_DSIADBINIT_DEFAULTSOSBUTTON = 7;
    public static final int ATTRIBUTE_ID_DSIADBLIST_VIEWSIZE = 1;
    public static final int ATTRIBUTE_ID_DSIADBLIST_ALPHABETICALINDEX = 2;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_ADBSTATE = 1;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_SORTORDER = 2;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_PICTUREVISIBILITY = 3;
    public static final int ATTRIBUTE_ID_DSIADBSETUP_CONTEXTSPECIFICVISIBILITY = 4;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_PROFILEINFO = 2;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DEVICECONNECTED = 3;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADCOUNTSIM = 5;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADCOUNTME = 6;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADCOUNTOPP = 7;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADSTATE = 8;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_DOWNLOADSTATE2NDPHONE = 9;
    public static final int ATTRIBUTE_ID_DSIADBUSERPROFILE_SOSBUTTON = 10;
    public static final int ATTRIBUTE_ID_DSIADBVCARDEXCHANGE_EXPORTCOUNT = 4;
    public static final int ATTRIBUTE_ID_DSIADBVCARDEXCHANGE_IMPORTCOUNT = 5;
}

