/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.wirelesscharging.hmi.evohighscale;

import de.audi.atip.hmi.view.HMIView;
import de.audi.atip.hmi.view.Screen;
import de.audi.tghu.wirelesscharging.hmi.evohighscale.WirelessChargingScreenFactory;
import de.esolutions.hmi.widgets.audi.evo.InstructionTextContoller;
import de.esolutions.hmi.widgets.audi.evo.ScreenWidgetEVO;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.CompositeRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ContainerRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.FocusCursorRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.GlassplateRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MultiLineLabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.PartialPopupGlassplateRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.PartialPopupRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ScreenRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ScrollbarRendererKanziHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.TitleBarRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.menu.MenuRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.ContainerController;
import de.esolutions.hmi.widgets.audi.evo.widgets.FocusCursorController;
import de.esolutions.hmi.widgets.audi.evo.widgets.GlassplateController;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.PartialPopupController;
import de.esolutions.hmi.widgets.audi.evo.widgets.PartialPopupGlassplateController;
import de.esolutions.hmi.widgets.audi.evo.widgets.ScrollbarController;
import de.esolutions.hmi.widgets.audi.evo.widgets.StatusBarStubController;
import de.esolutions.hmi.widgets.audi.evo.widgets.TitleBarWidget;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.InfoLineRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;

public class WirelessChargingScreenBag1 {
    public static Screen cHARGINGPOPUPOBJECT(WirelessChargingScreenFactory wirelessChargingScreenFactory, int n) {
        PartialPopupGlassplateController partialPopupGlassplateController = new PartialPopupGlassplateController();
        PartialPopupGlassplateRendererHigh partialPopupGlassplateRendererHigh = new PartialPopupGlassplateRendererHigh(partialPopupGlassplateController);
        partialPopupGlassplateController.setRenderer(partialPopupGlassplateRendererHigh);
        partialPopupGlassplateController.setBounds(0, 0, 100, 100);
        partialPopupGlassplateController.setSeparatorVisible(true);
        partialPopupGlassplateController.setSeparatorYPosition(143);
        LabelController labelController = new LabelController();
        MultiLineLabelRendererHigh multiLineLabelRendererHigh = new MultiLineLabelRendererHigh(labelController);
        labelController.setRenderer(multiLineLabelRendererHigh);
        labelController.setTextIds(new int[]{3400006});
        labelController.setBounds(0, 0, 0, 212);
        multiLineLabelRendererHigh.setAlignment(2, 4);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(wirelessChargingScreenFactory.getFonts(1, n));
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(0, 148, 634, 101);
        menuController.setCalculatePreferredSize(true);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(focusCursorController, 1);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{3400000});
        iconController.setBounds(0, 0, 100, 100);
        InstructionTextContoller instructionTextContoller = new InstructionTextContoller();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(instructionTextContoller);
        instructionTextContoller.setRenderer(compositeRendererHigh);
        instructionTextContoller.setBounds(0, 0, 100, 100);
        instructionTextContoller.setColorIndices(new int[]{1, 0, 4, 0});
        instructionTextContoller.addHintText(labelController);
        instructionTextContoller.setOptions(menuController);
        instructionTextContoller.addHintTextIcon(iconController);
        PartialPopupController partialPopupController = new PartialPopupController(3400000);
        partialPopupController.setScreenFactory(wirelessChargingScreenFactory);
        PartialPopupRendererHigh partialPopupRendererHigh = new PartialPopupRendererHigh(partialPopupController);
        partialPopupController.setRenderer(partialPopupRendererHigh);
        partialPopupRendererHigh.setFonts(wirelessChargingScreenFactory.getFonts(0, n));
        partialPopupController.setAutoHideTime(3000);
        partialPopupController.setBounds(400, 400, 634, 0);
        partialPopupController.setColorIndices(new int[]{1, 2, 4, 0});
        partialPopupController.setColorPalettes(new int[][]{{-1, -16777216, -1, -1, -6645094, -5592406, -4868683, -6645094, -1}, {-1, -16777216, -65511, -5546136, -6645094, -5592406, -4868683, -6645094, -4703671}, {-1, -16777216, -19456, -6123155, -6645094, -5592406, -4868683, -6645094, -6123155}, {-1, -16777216, -14775126, -9594974, -6645094, -5592406, -4868683, -6645094, -9594974}, {-1, -16777216, -10180096, -9200779, -6645094, -5592406, -4868683, -6645094, -9200779}});
        partialPopupController.setConsumeDDSPress(1);
        partialPopupController.setConsumeHKReturn(1);
        partialPopupController.setConsumeKeyTurned(2);
        partialPopupController.setContentInset(10);
        partialPopupController.setDynamicSize(true);
        partialPopupController.setGreyOutBackground(true);
        partialPopupController.setID(3400000);
        partialPopupController.setSmallStageType(0);
        partialPopupController.setStyle(1);
        partialPopupController.setSurviveScreenChange(true);
        partialPopupController.setType(7);
        partialPopupController.setZpmPriority(140);
        partialPopupController.setZpmSlot(4);
        partialPopupController.setBackgroundController(partialPopupGlassplateController);
        partialPopupController.add(instructionTextContoller);
        return partialPopupController;
    }

    public static Screen cHARGINGPOPUPFOREIGNOBJECTDETECT(WirelessChargingScreenFactory wirelessChargingScreenFactory, int n) {
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127, 127});
        iconController.setBounds(0, 0, 100, 100);
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        MenuItemController menuItemController = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(menuItemController);
        menuItemController.setRenderer(compositeRendererHigh);
        menuItemController.setEvent(3400000);
        menuItemController.setLabelId(3400008);
        menuItemController.setGlassplateInsetsBottom(6);
        menuItemController.setGlassplateInsetsTop(7);
        menuItemController.setInternalID(3400000);
        menuItemController.setType(2);
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(wirelessChargingScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(3400007);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(menuItemController);
        LabelController labelController = new LabelController();
        MultiLineLabelRendererHigh multiLineLabelRendererHigh = new MultiLineLabelRendererHigh(labelController);
        labelController.setRenderer(multiLineLabelRendererHigh);
        labelController.setTextIds(new int[]{3400009});
        labelController.setBounds(0, 0, 0, 0);
        IconController iconController2 = new IconController();
        IconRendererHigh iconRendererHigh2 = new IconRendererHigh(iconController2);
        iconController2.setRenderer(iconRendererHigh2);
        iconController2.setBitmaps(new int[]{3400001});
        iconController2.setBounds(0, 0, 100, 100);
        InstructionTextContoller instructionTextContoller = new InstructionTextContoller();
        instructionTextContoller.setBounds(0, 0, 100, 100);
        instructionTextContoller.setColorIndices(new int[]{1, 0, 4, 0});
        instructionTextContoller.setOptions(menuController);
        instructionTextContoller.addHintText(labelController);
        instructionTextContoller.addHintTextIcon(iconController2);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(12.0f, 12.0f, 0.96f, 0.96f, 0.5f);
        containerController.setOptionMenuTransformation(-4.0f, 7.0f, 0.6f, 0.6f, 0.5f);
        containerController.setSelectionMenuTransformation(318.0f, 7.0f, 0.58f, 0.6f, 0.25f);
        containerController.add(instructionTextContoller);
        IconController iconController3 = new IconController();
        IconRendererHigh iconRendererHigh3 = new IconRendererHigh(iconController3);
        iconController3.setRenderer(iconRendererHigh3);
        iconController3.setBitmaps(new int[]{127});
        iconController3.setBounds(0, 0, 100, 100);
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(wirelessChargingScreenFactory.getFonts(2, n));
        labelController2.setTextIds(new int[]{3400010});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setColorIndices(new int[]{1, 2, 4, 0});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController3);
        titleBarWidget.addTitle(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(12.0f, 12.0f, 0.96f, 0.96f, 0.0f);
        containerController2.setOpacitySet(1.0f, 0.4f);
        containerController2.setOptionMenuTransformation(-4.0f, 7.0f, 0.6f, 0.6f, 0.0f);
        containerController2.setSelectionMenuTransformation(391.0f, 7.0f, 0.6f, 0.6f, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(3400001);
        screenWidgetEVO.setScreenFactory(wirelessChargingScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(wirelessChargingScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, -16777216, -1, -1, -6645094, -5592406, -4868683, -6645094, -1}, {-1, -16777216, -65511, -5546136, -6645094, -5592406, -4868683, -6645094, -4703671}, {-1, -16777216, -19456, -6123155, -6645094, -5592406, -4868683, -6645094, -6123155}, {-1, -16777216, -14775126, -9594974, -6645094, -5592406, -4868683, -6645094, -9594974}, {-1, -16777216, -10180096, -9200779, -6645094, -5592406, -4868683, -6645094, -9200779}});
        screenWidgetEVO.setSmallStageType(0);
        screenWidgetEVO.add(iconController);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138}, new HMIView[][]{{statusBarStubController}});
        return screenWidgetEVO;
    }

    public static Screen cHARGINGPOPUPREMINDER(WirelessChargingScreenFactory wirelessChargingScreenFactory, int n) {
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{127, 127});
        iconController.setBounds(0, 0, 100, 100);
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(wirelessChargingScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(3400007);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        LabelController labelController = new LabelController();
        MultiLineLabelRendererHigh multiLineLabelRendererHigh = new MultiLineLabelRendererHigh(labelController);
        labelController.setRenderer(multiLineLabelRendererHigh);
        labelController.setTextIds(new int[]{3400011});
        labelController.setBounds(0, 0, 0, 0);
        IconController iconController2 = new IconController();
        IconRendererHigh iconRendererHigh2 = new IconRendererHigh(iconController2);
        iconController2.setRenderer(iconRendererHigh2);
        iconController2.setBitmaps(new int[]{3400000});
        iconController2.setBounds(0, 0, 100, 100);
        InstructionTextContoller instructionTextContoller = new InstructionTextContoller();
        instructionTextContoller.setBounds(0, 0, 100, 100);
        instructionTextContoller.setColorIndices(new int[]{1, 0, 4, 0});
        instructionTextContoller.setOptions(menuController);
        instructionTextContoller.addHintText(labelController);
        instructionTextContoller.addHintTextIcon(iconController2);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(12.0f, 12.0f, 0.96f, 0.96f, 0.5f);
        containerController.setOptionMenuTransformation(-4.0f, 7.0f, 0.6f, 0.6f, 0.5f);
        containerController.setSelectionMenuTransformation(318.0f, 7.0f, 0.58f, 0.6f, 0.25f);
        containerController.add(instructionTextContoller);
        IconController iconController3 = new IconController();
        IconRendererHigh iconRendererHigh3 = new IconRendererHigh(iconController3);
        iconController3.setRenderer(iconRendererHigh3);
        iconController3.setBitmaps(new int[]{127});
        iconController3.setBounds(0, 0, 100, 100);
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(wirelessChargingScreenFactory.getFonts(2, n));
        labelController2.setTextIds(new int[]{3400010});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setColorIndices(new int[]{1, 2, 4, 0});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController3);
        titleBarWidget.addTitle(labelController2);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 800, 0);
        containerController2.setEntertainmentMenuTransformation(12.0f, 12.0f, 0.96f, 0.96f, 0.0f);
        containerController2.setOpacitySet(1.0f, 0.4f);
        containerController2.setOptionMenuTransformation(-4.0f, 7.0f, 0.6f, 0.6f, 0.0f);
        containerController2.setSelectionMenuTransformation(391.0f, 7.0f, 0.6f, 0.6f, 0.0f);
        containerController2.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(3400002);
        screenWidgetEVO.setScreenFactory(wirelessChargingScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(wirelessChargingScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, -16777216, -1, -1, -6645094, -5592406, -4868683, -6645094, -1}, {-1, -16777216, -65511, -5546136, -6645094, -5592406, -4868683, -6645094, -4703671}, {-1, -16777216, -19456, -6123155, -6645094, -5592406, -4868683, -6645094, -6123155}, {-1, -16777216, -14775126, -9594974, -6645094, -5592406, -4868683, -6645094, -9594974}, {-1, -16777216, -10180096, -9200779, -6645094, -5592406, -4868683, -6645094, -9200779}});
        screenWidgetEVO.setSmallStageType(0);
        screenWidgetEVO.add(iconController);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138}, new HMIView[][]{{statusBarStubController}});
        return screenWidgetEVO;
    }
}

