/*
 * Decompiled with CFR 0.152.
 */
package org.dsi.ifc.careco;

import org.dsi.ifc.base.DSIBase;
import org.dsi.ifc.careco.BCmEListUpdateInfo;
import org.dsi.ifc.careco.StartStopListUpdateInfo;

public interface DSICarEco
extends DSIBase {
    public static final String VERSION = "2.11.23";
    public static final int ATTR_BCMEVIEWOPTIONS = 1;
    public static final int ATTR_BCMELISTUPDATEINFO = 2;
    public static final int ATTR_BCMECONSUMPTION = 3;
    public static final int ATTR_BCMELIVETIP = 4;
    public static final int ATTR_BCMECONSUMERLISTCONSUMPTIONUPDATEINFO = 34;
    public static final int ATTR_BCMEENERGYFLOWCOMFORT = 35;
    public static final int ATTR_BCMERANGEGAINTOTAL = 36;
    public static final int ATTR_BCMECONSUMERLISTRANGEUPDATEINFO = 37;
    public static final int ATTR_BCMECURRENTRANGE = 38;
    public static final int ATTR_BCMECONSUMERLISTTOTALNUMBEROFELEMENTS = 39;
    public static final int ATTR_BCMECONSUMERLISTCONSUMPTIONTOTALNUMBEROFELEMENTS = 40;
    public static final int ATTR_BCMECONSUMERLISTRANGETOTALNUMBEROFELEMENTS = 41;
    public static final int ATTR_STARTSTOPPROHIBITREASONLISTUPDATEINFO = 5;
    public static final int ATTR_STARTSTOPRESTARTREASONLISTUPDATEINFO = 6;
    public static final int ATTR_STARTSTOPRESTARTPROHIBITREASONLISTUPDATEINFO = 7;
    public static final int ATTR_STARTSTOPSTATE = 8;
    public static final int ATTR_STARTSTOPPROHIBITREASONLISTTOTALNUMBEROFELEMENTS = 9;
    public static final int ATTR_STARTSTOPRESTARTREASONLISTTOTALNUMBEROFELEMENTS = 10;
    public static final int ATTR_STARTSTOPRESTARTPROHIBITREASONLISTTOTALNUMBEROFELEMENTS = 11;
    public static final int ATTR_STARTSTOPVIEWOPTIONS = 12;
    public static final int ATTR_STARTSTOPCOLLECTEDREASONS = 49;
    public static final int ATTR_RDVIEWOPTIONS = 15;
    public static final int ATTR_RDCONSUMPTIONMOTORWAY1 = 16;
    public static final int ATTR_RDCONSUMPTIONMOTORWAY2 = 17;
    public static final int ATTR_RDCONSUMPTIONHIGHWAY1 = 18;
    public static final int ATTR_RDCONSUMPTIONHIGHWAY2 = 19;
    public static final int ATTR_RDCONSUMPTIONCOUNTRYROAD1 = 20;
    public static final int ATTR_RDCONSUMPTIONCOUNTRYROAD2 = 21;
    public static final int ATTR_RDCONSUMPTIONDISTRICTROAD1 = 22;
    public static final int ATTR_RDCONSUMPTIONDISTRICTROAD2 = 23;
    public static final int ATTR_RDCONSUMPTIONLOCALROAD1 = 24;
    public static final int ATTR_RDCONSUMPTIONLOCALROAD2 = 25;
    public static final int ATTR_RDCONSUMPTIONRURALROAD1 = 26;
    public static final int ATTR_RDCONSUMPTIONRURALROAD2 = 27;
    public static final int ATTR_RDCONSUMPTIONUNCLASSIFIEDROAD1 = 28;
    public static final int ATTR_RDCONSUMPTIONUNCLASSIFIEDROAD2 = 29;
    public static final int ATTR_RDMAXRANGE1 = 30;
    public static final int ATTR_RDMAXRANGE2 = 31;
    public static final int ATTR_RDRESIDUALENERGY1 = 32;
    public static final int ATTR_RDRESIDUALENERGY2 = 33;
    public static final int ATTR_EAVIEWOPTIONS = 42;
    public static final int ATTR_EASYSTEM = 43;
    public static final int ATTR_EAPEDALJERK = 44;
    public static final int ATTR_EAFREEWHEELING = 47;
    public static final int ATTR_EASTARTSTOP = 48;
    public static final int ATTR_BCMECURRENTRANGESOC = 45;
    public static final int ATTR_BCMECATALOGUERANGE = 46;
    public static final int RT_REQUESTBCMECONSUMERLIST = 1000;
    public static final int RT_SETBCMELIVETIP = 1001;
    public static final int RT_SETBCMESETFACTORYDEFAULT = 1002;
    public static final int RT_REQUESTSTARTSTOPPROHIBITLIST = 1003;
    public static final int RT_REQUESTSTARTSTOPRESTARTLIST = 1004;
    public static final int RT_REQUESTSTARTSTOPRESTARTPROHIBITLIST = 1005;
    public static final int RT_SETRDSETFACTORYDEFAULT = 1006;
    public static final int RT_REQUESTBCMECONSUMERLISTCONSUMPTION = 1007;
    public static final int RT_REQUESTBCMECONSUMERLISTRANGE = 1008;
    public static final int RT_SETEASYSTEM = 1009;
    public static final int RT_SETEAPEDALJERK = 1010;
    public static final int RT_SETEASETFACTORYDEFAULT = 1011;
    public static final int RT_SETEAFREEWHEELING = 1012;
    public static final int RT_SETEASTARTSTOP = 1013;
    public static final int IN_RESPONSEBCMECONSUMERLIST = 3000;
    public static final int RP_ACKNOWLEDGEBCMESETFACTORYDEFAULT = 2001;
    public static final int RP_RESPONSESTARTSTOPPROHIBITREASONLIST = 2002;
    public static final int RP_RESPONSESTARTSTOPRESTARTREASONLIST = 2003;
    public static final int RP_RESPONSESTARTSTOPRESTARTPROHIBITREASONLIST = 2004;
    public static final int RP_ACKNOWLEDGERDSETFACTORYDEFAULT = 2005;
    public static final int IN_RESPONSEBCMECONSUMERLISTCONSUMPTIONRA0 = 3001;
    public static final int IN_RESPONSEBCMECONSUMERLISTCONSUMPTIONRA1 = 3002;
    public static final int IN_RESPONSEBCMECONSUMERLISTCONSUMPTIONRAF = 3003;
    public static final int IN_RESPONSEBCMECONSUMERLISTRANGERA0 = 3004;
    public static final int IN_RESPONSEBCMECONSUMERLISTRANGERA1 = 3005;
    public static final int IN_RESPONSEBCMECONSUMERLISTRANGERA2 = 3006;
    public static final int IN_RESPONSEBCMECONSUMERLISTRANGERAF = 3007;
    public static final int RP_ACKNOWLEDGEEASETFACTORYDEFAULT = 2013;
    public static final int BCMELIVETIP_NONE = 0;
    public static final int BCMELIVETIP_CLOSEWINDOW = 1;
    public static final int BCMELIVETIP_CLOSEROOF = 2;
    public static final int BCMELIVETIP_CLOSEWINDOWROOF = 3;
    public static final int BCMELIVETIP_ENGINEBRAKE = 4;
    public static final int BCMELIVETIP_ENGINESTART = 5;
    public static final int BCMELIVETIP_SHIFTGEAR = 6;
    public static final int BCMELIVETIP_STARTSTOPREADY = 7;
    public static final int BCMELIVETIP_STARTSTOPDEACTIVE = 8;
    public static final int BCMELIVETIP_ACWINDOW = 9;
    public static final int BCMELIVETIP_ACROOF = 10;
    public static final int BCMELIVETIP_ACWINDOWROOF = 11;
    public static final int BCMELIVETIP_POSD = 12;
    public static final int BCMELIVETIP_THROTTLESTANDING = 13;
    public static final int BCMELIVETIP_ACCONVERTIBLE = 14;
    public static final int BCMELIVETIP_WARMUPSTANDING = 15;
    public static final int BCMECONSUMERS_CLIMATECONTROLUNIT = 1;
    public static final int BCMECONSUMERS_AUXHEATER = 2;
    public static final int BCMECONSUMERS_REARWINDOWHEATER = 3;
    public static final int BCMECONSUMERS_SEATHEATINGFRONTLEFT = 4;
    public static final int BCMECONSUMERS_SEATHEATINGFRONTRIGHT = 5;
    public static final int BCMECONSUMERS_SEATVENTILATIONFRONLEFT = 6;
    public static final int BCMECONSUMERS_SSEATVENTILATIONFRONRIGHT = 7;
    public static final int BCMECONSUMERS_NECKHEATINGLEFT = 8;
    public static final int BCMECONSUMERS_NECKHEATINGRIGHT = 9;
    public static final int BCMECONSUMERS_FOGLIGHTFRONT = 10;
    public static final int BCMECONSUMERS_FOGLIGHTREAR = 11;
    public static final int BCMECONSUMERS_FRONTWINDOWHEATING = 12;
    public static final int BCMECONSUMERS_STEERINGWHEELHEATING = 13;
    public static final int BCMECONSUMERS_MIRRORHEATING = 14;
    public static final int BCMECONSUMERS_SEATHEATINGREAR = 15;
    public static final int BCMECONSUMERS_SEATVENTILATIONREAR = 16;
    public static final int BCMECONSUMERS_220VPLUGIN = 17;
    public static final int BCMECONSUMERS_THERMOCUPHOLDER = 18;
    public static final int BCMEARRAYCONTENT_INIT = 0;
    public static final int BCMEARRAYCONTENT_ALL = 1;
    public static final int BCMEARRAYCONTENT_ALL_FORWARD = 2;
    public static final int BCMEARRAYCONTENT_ALL_BACKWARD = 3;
    public static final int BCMEARRAYCONTENT_ONLY_CHANGES = 4;
    public static final int BCMEARRAYCONTENT_ELEMENTS_REMOVED = 5;
    public static final int BCMEARRAYCONTENT_BLOCK_INSERTED = 6;
    public static final int BCMEARRAYCONTENT_BACKWARD = 7;
    public static final int BCMERECORDCONTENT_RA0 = 0;
    public static final int BCMERECORDCONTENT_RA1 = 1;
    public static final int BCMERECORDCONTENT_RA2 = 2;
    public static final int BCMERECORDCONTENT_RAF = 15;
    public static final int BCMERANGEUNIT_KM = 0;
    public static final int BCMERANGEUNIT_MLS = 1;
    public static final int BCMERANGEUNIT_PERCENT = 2;
    public static final int BCMEENGINETYPE_NOT_INSTALLED = 0;
    public static final int BCMEENGINETYPE_PETROL = 1;
    public static final int BCMEENGINETYPE_GAS = 2;
    public static final int BCMEENGINETYPE_ELECTRIC = 3;
    public static final int BCMEENGINETYPE_UNKNOWN = 4;
    public static final int BCMEDISPLAYSTYLE_NOSTYLE = 0;
    public static final int BCMEDISPLAYSTYLE_STYLE1 = 1;
    public static final int BCMEDISPLAYSTYLE_STYLE2 = 2;
    public static final int BCMEDISPLAYSTYLE_STYLE3 = 3;
    public static final int BCMEDISPLAYSTYLE_STYLE4 = 4;
    public static final int STARTSTOPREASON_TRAILER = 0;
    public static final int STARTSTOPREASON_FOGGING = 1;
    public static final int STARTSTOPREASON_OPERATING_TEMP = 2;
    public static final int STARTSTOPREASON_DRIVER_ABSENT = 3;
    public static final int STARTSTOPREASON_KEYLESS_ENTRY = 4;
    public static final int STARTSTOPREASON_POWER_CONSUMPTION = 5;
    public static final int STARTSTOPREASON_CLIMATE_INT_SYS = 6;
    public static final int STARTSTOPREASON_ENGINE = 7;
    public static final int STARTSTOPREASON_SLOPE = 8;
    public static final int STARTSTOPREASON_NOT_AVAILABLE = 9;
    public static final int STARTSTOPREASON_EMERGENCY_BREAKING = 10;
    public static final int STARTSTOPREASON_BRAKE_SYSTEM_SYS = 11;
    public static final int STARTSTOPREASON_ENERGY_MANAGEMENT_SYS = 12;
    public static final int STARTSTOPREASON_CLIMATE_SYSTEM = 13;
    public static final int STARTSTOPREASON_STEERING = 14;
    public static final int STARTSTOPREASON_PARKING = 15;
    public static final int STARTSTOPREASON_DEFROST = 16;
    public static final int STARTSTOPREASON_DRIVER_SEATBELT = 17;
    public static final int STARTSTOPREASON_DRIVER_DOOR = 18;
    public static final int STARTSTOPREASON_THROTTLE = 19;
    public static final int STARTSTOPREASON_FRONT_SCREEN_HEATING = 20;
    public static final int STARTSTOPREASON_CLIMATE_MAX = 21;
    public static final int STARTSTOPREASON_FRONT_LID = 22;
    public static final int STARTSTOPREASON_STANDSTILL = 23;
    public static final int STARTSTOPREASON_OFFROAD = 24;
    public static final int STARTSTOPREASON_CHILD_LOCK = 25;
    public static final int STARTSTOPREASON_GEAR = 26;
    public static final int STARTSTOPREASON_BUTTON = 27;
    public static final int STARTSTOPREASON_CLIMATE_INT = 28;
    public static final int STARTSTOPREASON_ACC = 29;
    public static final int STARTSTOPREASON_PARK_ASSIST = 30;
    public static final int STARTSTOPREASON_BRAKE_SYSTEM = 31;
    public static final int STARTSTOPREASON_ENERGY_MANAGEMENT = 32;
    public static final int STARTSTOPREASON_SYSTEM = 33;
    public static final int STARTSTOPREASON_DRIVER_PERM_ABSENT_RESTART_PROHIBIT = 34;
    public static final int STARTSTOPREASON_DRIVER_DOOR_RESTART_PROHIBIT = 35;
    public static final int STARTSTOPREASON_FRONT_LID_RESTART_PROHIBIT = 36;
    public static final int STARTSTOPREASON_SEATBELT_RESTART_PROHIBIT = 37;
    public static final int STARTSTOPREASON_DRIVER_ABSENT_RESTART_PROHIBIT = 38;
    public static final int STARTSTOPREASON_COMPONENT_PROTECTION_RESTART_PROHIBIT = 39;
    public static final int STARTSTOPREASON_COORDINATOR_RESTART_PROHIBIT = 40;
    public static final int STARTSTOPREASON_MANUAL_RESTART_RESTART_PROHIBIT = 41;
    public static final int STARTSTOPREASON_PRESS_THROTTLE = 42;
    public static final int STARTSTOPREASON_PRESS_BUTTON = 43;
    public static final int STARTSTOPREASON_SWTICH_TO_R = 44;
    public static final int STARTSTOPREASON_BY_DRIVER = 45;
    public static final int STARTSTOPREASON_DEFROST_RESTART = 46;
    public static final int STARTSTOPREASON_FRONT_SCREEN_HEATING_RESTART = 47;
    public static final int STARTSTOPREASON_CLIMATE_INT_RESTART = 48;
    public static final int STARTSTOPREASON_AC_MAX = 49;
    public static final int STARTSTOPREASON_SECURITY = 50;
    public static final int STARTSTOPREASON_FOGGING_HAZARD = 51;
    public static final int STARTSTOPREASON_POWER_CONSUMPTION_RESTART = 52;
    public static final int STARTSTOPREASON_ENGINE_REQUIRED = 53;
    public static final int STARTSTOPREASON_BUTTON_PUSHED = 54;
    public static final int STARTSTOPREASON_OFFROAD_RESTART = 55;
    public static final int STARTSTOPREASON_BRAKE_SYSTEM_RESTART = 56;
    public static final int STARTSTOPREASON_ENERGY_MANAGEMENT_RESTART = 57;
    public static final int STARTSTOPREASON_CLIMATE_CONTROL_RESTART = 58;
    public static final int STARTSTOPREASON_SYSTEM_RESTART = 59;
    public static final int STARTSTOPREASON_ENGAGED_GEAR_RESTART_PROHIBIT = 60;
    public static final int STARTSTOPREASON_ACC_REQUIRES_ENGINE_RUNNING = 61;
    public static final int STARTSTOPREASON_SHIFT_BY_WIRE = 62;
    public static final int STARTSTOPREASON_S_OR_TIP_GEAR_RESTART = 63;
    public static final int STARTSTOPREASON_PLA_REQUIRES_ENGINE_RUNNING = 64;
    public static final int STARTSTOPREASON_ESC_OFF_BUTTON = 65;
    public static final int STARTSTOPREASON_GEARBOX = 66;
    public static final int STARTSTOPREASON_INIT = 67;
    public static final int STARTSTOPREASON_S_OR_TIP_GEAR = 68;
    public static final int STARTSTOPREASON_TRAFFIC_SITUATION = 69;
    public static final int STARTSTOPREASON_STOP_AND_GO = 70;
    public static final int STARTSTOPREASON_TRAFFIC_LIGHT = 71;
    public static final int STARTSTOPREASON_DOOR_OPEN = 72;
    public static final int STARTSTOPREASON_PEA = 73;
    public static final int STARTSTOPREASON_OPEN_DOOR = 74;
    public static final int STARTSTOPREASON_TRAFFIC_LIGHT_RESTART = 75;
    public static final int STARTSTOPREASON_PEA_RESTART = 76;
    public static final int STARTSTOPARRAYCONTENT_INIT = 0;
    public static final int STARTSTOPARRAYCONTENT_ALL = 1;
    public static final int STARTSTOPARRAYCONTENT_ONLY_CHANGES = 2;
    public static final int STARTSTOPSTATE_IDLE = 0;
    public static final int STARTSTOPSTATE_AVAILABLE = 1;
    public static final int STARTSTOPSTATE_STOPMODE = 2;
    public static final int STARTSTOPSTATE_CLUTCH = 3;
    public static final int STARTSTOPSTATE_CONFIRMPRESENCE = 4;
    public static final int STARTSTOPSTATE_CLUTCHENABLESSTART = 5;
    public static final int STARTSTOPSTATE_SWITCHEDOFF = 6;
    public static final int STARTSTOPSTATE_SYSTEMERROR = 7;
    public static final int STARTSTOPSTATE_NOTAVAILBLE = 8;
    public static final int STARTSTOPSTATE_STOPMODE_RESTART_BRAKE = 9;
    public static final int STARTSTOPSTATE_STOPMODE_RESTART_GAS = 10;
    public static final int STARTSTOPSTATE_STOPMODE_RESTART_GEARSHIFT = 11;
    public static final int STARTSTOPSTATE_STOPMODE_RESTART_CLUTCH = 12;
    public static final int STARTSTOPCOLLECTEDREASONS_HEATING_COOLING_PROHIBITS_STOP = 0;
    public static final int STARTSTOPCOLLECTEDREASONS_SYSTEM_NEEDS_PROHIBIT_STOP = 1;
    public static final int STARTSTOPCOLLECTEDREASONS_SYSTEM_SAFETY_PROHIBITS_STOP = 2;
    public static final int STARTSTOPCOLLECTEDREASONS_TRAFFIC_SITUATION_PROHIBITS_STOP = 3;
    public static final int STARTSTOPCOLLECTEDREASONS_DRIVER_SEATBELT_PROHIBITS_STOP = 4;
    public static final int STARTSTOPCOLLECTEDREASONS_DRIVER_DOOR_OPEN_PROHIBITS_STOP = 5;
    public static final int STARTSTOPCOLLECTEDREASONS_SYSTEM_ERROR = 6;
    public static final int STARTSTOPCOLLECTEDREASONS_DRIVER_SEATBELT_PROHIBITS_RESTART = 64;
    public static final int STARTSTOPCOLLECTEDREASONS_DRIVER_DOOR_OPEN_PROHIBITS_RESTART = 65;
    public static final int STARTSTOPCOLLECTEDREASONS_SYSTEM_SAFETY_PROHIBITS_RESTART = 66;
    public static final int STARTSTOPCOLLECTEDREASONS_STARTSTOP_SWITCHED_OFF = 128;
    public static final int STARTSTOPCOLLECTEDREASONS_STARTSTOP_AVAILABLE = 129;
    public static final int STARTSTOPCOLLECTEDREASONS_STOPMODE_RESTART_BY_BRAKE = 130;
    public static final int STARTSTOPCOLLECTEDREASONS_STOPMODE_RESTART_BY_GAS = 131;
    public static final int STARTSTOPCOLLECTEDREASONS_STOPMODE_RESTART_BY_GEAR_SHIFT = 132;
    public static final int STARTSTOPCOLLECTEDREASONS_STOPMODE_RESTART_BY_CLUTCH = 133;
    public static final int STARTSTOPCOLLECTEDREASONS_RESTART_DUE_HEATING_COOLING = 192;
    public static final int STARTSTOPCOLLECTEDREASONS_RESTART_DUE_SYSTEM_NEEDS = 193;
    public static final int STARTSTOPCOLLECTEDREASONS_RESTART_DUE_SYSTEM_SAFETY = 194;
    public static final int STARTSTOPCOLLECTEDREASONS_RESTART_DUE_TRAFFIC_SITUATION = 195;
    public static final int RDENERGYUNIT_LITER = 0;
    public static final int RDENERGYUNIT_KWH = 1;
    public static final int RDENERGYUNIT_KG = 2;
    public static final int RDENERGYUNIT_M3 = 3;

    public void requestBCmEConsumerList(BCmEListUpdateInfo var1);

    public void setBCmELiveTip(int var1, boolean var2);

    public void setBcmeSetFactoryDefault();

    public void requestStartStopProhibitList(StartStopListUpdateInfo var1);

    public void requestStartStopRestartList(StartStopListUpdateInfo var1);

    public void requestStartStopRestartProhibitList(StartStopListUpdateInfo var1);

    public void requestBCmEConsumerListConsumption(BCmEListUpdateInfo var1);

    public void requestBCmEConsumerListRange(BCmEListUpdateInfo var1);

    public void setRDSetFactoryDefault();

    public void setEASystem(boolean var1);

    public void setEAPedalJerk(boolean var1);

    public void setEASetFactoryDefault();

    public void setEAFreeWheeling(boolean var1);

    public void setEAStartStop(boolean var1);
}

