/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface HMIPopUpsSWDL {
    public static final int POPUP_SWDLPOPUP_ID = 1700000;
    public static final int POPUP_SETTINGSUPDATEINTERRUPTSD_ID = 1700001;
    public static final int POPUP_SETTINGSUPDATESUMMARYFAILURE_ID = 1700002;
    public static final int POPUP_SETTINGSUPDATESUMMARYSUCCESSFUL_ID = 1700003;
    public static final int POPUP_SETTINGS_POPUP_NAVI_NEW_DATA_AVAILABLE_LICENCE_AVAILABLE_ID = 1700005;
    public static final int POPUP_SETTINGS_POPUP_NAVI_NEW_DATA_AVAILABLE_LICENCE_NOT_AVAILABLE_ID = 1700006;
    public static final int POPUP_SETTINGS_POPUP_NAVI_LICENCE_GETTTING_INVALID_ID = 1700007;
    public static final int POPUP_SETTINGS_POPUP_GEN_NEW_DATA_AVAILABLE_ID = 1700008;
    public static final int POPUP_SETTINGS_UPDATE_SOURCE_INCOMPATIBLE_DATA_ID = 1700009;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SOURCE_CONFIRMATION_ID = 1700010;
    public static final int POPUP_SETTINGS_ONLINE_UPDATE_FAILURE_RETRY_POSSIBLE_ID = 1700011;
    public static final int POPUP_SETTINGS_ONLINE_UPDATE_FAILURE_ID = 1700012;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_ACCESS_FAILURE_ID = 1700013;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_INCOMPATIBLE_DATA_ID = 1700014;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_NO_DATA_ID = 1700015;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_SERVER_FAILURE_ID = 1700016;
    public static final int POPUP_SWDLSUMMARYCHANGED_ID = 1700017;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SYSTEM_PROPOSAL_DISCLAIMER_ID = 1700018;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SYSTEM_PROPOSAL_ID = 1700019;
    public static final int POPUP_SETTINGS_POPUP_NAVI_NEW_DATA_AVAILABLE_LICENCE_DESTINATION_ID = 1700020;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_NAV_DB_SUMMARY_UOTA_SUCCESSFUL_ID = 1700021;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_PPOI_SUMMARY_UOTA_SUCCESSFUL_ID = 1700022;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SYSTEM_PROPOSAL_DESTINATION_ID = 1700023;
}

