/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerFocusMessaging {
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_A_TELEPHONE_NUMBER = 2070395121;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_A_V_CARD = 1888106672;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_ATTACHMENTS = 582254409;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_EXTRACTED_EMAIL_ADDRESSES = -9880764;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_EXTRACTED_TELEPHONE_NUMBERS = -1803623840;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_NAVIGATION_DATA = 499923312;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_DELETED = 25539472;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_DRAFT = -1408914058;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_INBOX = -1341359564;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_OUTBOX = 312818803;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_ROOT = 990153224;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_SENT = 1989006837;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_USERDEFINED = 1456061872;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_STORED_ON_S_I_M_CARD = -212164248;
    public static final int FOCUS_MESSAGING_READOUT_OF_ELEMENT_IS_SUPPORTED_BY_THE_SYSTEM = 1883863251;
}

