/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerFocusTV {
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_DATABROADCAST__GELADEN_WIRD;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_DATABROADCAST__GERADE_UEBERPRUEFT_WIRD_BZW_IM_MOMENT_NICHT_VERFUEGBAR_IST;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_TELETEXT_GELADEN_WIRD;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_TELETEXT_NOCH_NICHT_VERFUEGBAR_IST;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_VISUAL_AUDIO_NOCH_NICHT_VERFUEGBAR_IST;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_VISUL_AUDIO_GELADEN_WIRD;
    public static final int FOCUS_T_V_DATABROADCAST_IST_FUER_DEN_SENDER_VERFGUEGBAR;
    public static final int FOCUS_T_V_ELEMENT_IST_BEREITS_ALS_FAVORIT_ABGESPEICHERT;
    public static final int FOCUS_T_V_TELETEXT_IST_FUER_DEN_SENDER_VERFUEGBAR;
    public static final int FOCUS_T_V_VISUAL_AUDIO_IST_FUER_DEN_SENDER_VERFUEGBAR;
}

