/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerFocusTV {
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_DATABROADCAST__GELADEN_WIRD = 1398074041;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_DATABROADCAST__GERADE_UEBERPRUEFT_WIRD_BZW_IM_MOMENT_NICHT_VERFUEGBAR_IST = -1838047989;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_TELETEXT_GELADEN_WIRD = 190541802;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_TELETEXT_NOCH_NICHT_VERFUEGBAR_IST = -846215156;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_VISUAL_AUDIO_NOCH_NICHT_VERFUEGBAR_IST = 1913918755;
    public static final int FOCUS_T_V_AUSGRAUEN_WEIL_VISUL_AUDIO_GELADEN_WIRD = -1825335551;
    public static final int FOCUS_T_V_DATABROADCAST_IST_FUER_DEN_SENDER_VERFGUEGBAR = -1013118362;
    public static final int FOCUS_T_V_ELEMENT_IST_BEREITS_ALS_FAVORIT_ABGESPEICHERT = -1783875994;
    public static final int FOCUS_T_V_TELETEXT_IST_FUER_DEN_SENDER_VERFUEGBAR = 614014185;
    public static final int FOCUS_T_V_VISUAL_AUDIO_IST_FUER_DEN_SENDER_VERFUEGBAR = 1639143867;
}

