/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerCategoryAddressBook {
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_ADDRESS = 764996973;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_ADDRESS_GEO_POSITION = 965955193;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_ADDRESS_NAVIGATION_DESTINATION = 1373543104;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_ADDRESS_POSTAL_ADDRESS = -1067138139;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_CONTACT = 692197399;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_EMAIL_ADDRESS = 11009108;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_INPUT_FIELD = -1021155566;
    public static final int CATEGORIE_ADDRESS_BOOK_INCLUDE_TELEPHONE_NUMBER = 141942996;
    public static final int CATEGORIE_POPUPS_ADDRESS_BOOK_ADDRESS = -1998331179;
    public static final int CATEGORIE_POPUPS_ADDRESS_BOOK_ADDRESS_GEO_POSITION = -434835632;
    public static final int CATEGORIE_POPUPS_ADDRESS_BOOK_ADDRESS_NAVIGATION_DESTINATION = -608304874;
    public static final int CATEGORIE_POPUPS_ADDRESS_BOOK_ADDRESS_POSTAL_ADDRESS = -707656616;
    public static final int CATEGORIE_POPUPS_ADDRESS_BOOK_EMAIL_ADDRESS = -1432713326;
    public static final int CATEGORIE_POPUPS_ADDRESS_BOOK_TELEPHONE_NUMBER = -96933400;
}

