/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerCategoryCar {
    public static final int CATEGORIE_FAHRZEUG_AMBIENTELICHT;
    public static final int CATEGORIE_FAHRZEUG_AMBIENTELICHT_AMBIENTEBELEUCHTUNG;
    public static final int CATEGORIE_FAHRZEUG_AMBIENTELICHT_PROFIL_INDIVIDUAL;
    public static final int CATEGORIE_FAHRZEUG_AMBIENTELICHT_PROFIL_X;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_ALLROAD;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_AUTO;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_COMFORT;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_DYNAMIC;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_EFFICIENCY;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_INDIVIDUAL;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_LIFT;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_OFFROAD;
    public static final int CATEGORIE_FAHRZEUG_DRIVE_SELECT_MODUS_RACE;
    public static final int CATEGORIE_FAHRZEUG_EINGABEFELD;
    public static final int CATEGORIE_FAHRZEUG_GARAGENTOROEFFNER;
    public static final int CATEGORIE_FAHRZEUG_LADETIMER1;
    public static final int CATEGORIE_FAHRZEUG_LADETIMER2;
    public static final int CATEGORIE_FAHRZEUG_MENUEEINTRAG;
    public static final int CATEGORIE_FAHRZEUG_SERVICEINTERVALL_ANZEIGE;
    public static final int CATEGORIE_FAHRZEUG_SOFORTSTART_STANDHEIZUNG;
    public static final int CATEGORIE_FAHRZEUG_SOFORTSTART_STANDHEIZUNGKLIMATISIERUNG;
    public static final int CATEGORIE_FAHRZEUG_STANDHEIZUNGSKLIMA_TIMER1;
    public static final int CATEGORIE_FAHRZEUG_STANDHEIZUNGSKLIMA_TIMER2;
    public static final int CATEGORIE_FAHRZEUG_STANDHEIZUNGSTIMER1;
    public static final int CATEGORIE_FAHRZEUG_STANDHEIZUNGSTIMER2;
    public static final int CATEGORIE_FAHRZEUG_STATISTIKGRAPHIK;
    public static final int CATEGORIE_FAHRZEUG_STATISTIKGRAPHIK_VERBRAUCHSSTATISTIK_H_E_V;
    public static final int CATEGORIE_FAHRZEUG_STATISTIKGRAPHIK_VERBRAUCHSSTATISTIK_P_H_E_V;
}

