/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerFocusAddressBook {
    public static final int FOCUS_ADDRESSBOOK_ADDRESS_IS_AVAILABLE = -1661899299;
    public static final int FOCUS_ADDRESSBOOK_BUSINESS_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE = -938763321;
    public static final int FOCUS_ADDRESSBOOK_BUSINESS_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE1 = -450441313;
    public static final int FOCUS_ADDRESSBOOK_EMAIL_ADDRESS_IS_AVAILABLE = -2127465198;
    public static final int FOCUS_ADDRESSBOOK_PRIVATE_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE = 899238176;
    public static final int FOCUS_ADDRESSBOOK_PRIVATE_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE1 = 1256532290;
    public static final int FOCUS_ADDRESSBOOK_TELEPHONE_NUMBER_IS_AVAILABLE = 343280564;
}

