/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerContextPhone {
    public static final int CONTEXT_POPUPS_TELEFON_ANRUFLISTE = -1170050230;
    public static final int CONTEXT_TELEPHONE_AUDI_SERVICE = 1530953419;
    public static final int CONTEXT_TELEPHONE_AUDI_SERVICE_INFO_CALL = 1700935828;
    public static final int CONTEXT_TELEPHONE_AUDI_SERVICE_SERVICE_CALL = -2107031813;
    public static final int CONTEXT_TELEPHONE_CONTACTS_INCLUDE_ADDRESS_BOOK = -399568537;
    public static final int CONTEXT_TELEPHONE_EMAIL_ONE_ENTRY_FOR_EACH_ACCOUNT = -1919187206;
    public static final int CONTEXT_TELEPHONE_EMAIL_ONE_ENTRY_FOR_EACH_ACCOUNT_D_E_T_A_I_L_V_I_E_W = -901076816;
    public static final int CONTEXT_TELEPHONE_EMAIL_ONE_ENTRY_FOR_EACH_ACCOUNT_E_D_I_T_V_I_E_W = -736506653;
    public static final int CONTEXT_TELEPHONE_EMAIL_ONE_ENTRY_FOR_EACH_ACCOUNT_L_I_S_T_V_I_E_W = 494302687;
    public static final int CONTEXT_TELEPHONE_EMAIL_ONE_ENTRY_FOR_EACH_ACCOUNT_TEMPLATE_EDITOR = -249355464;
    public static final int CONTEXT_TELEPHONE_EMAIL_ONE_ENTRY_FOR_EACH_ACCOUNT_T_E_M_P_L_A_T_E_V_I_E_W = -1305960882;
    public static final int CONTEXT_TELEPHONE_ENTER_TELEPHONE_NUMBER = -1782111656;
    public static final int CONTEXT_TELEPHONE_FAVORITES = 635321708;
    public static final int CONTEXT_TELEPHONE_INTELLICALL_FULL_VIEW = -2142410760;
    public static final int CONTEXT_TELEPHONE_INTELLICALL_REDUCED_VIEW = 877917150;
    public static final int CONTEXT_TELEPHONE_P_I_N_P_U_K_INPUT = 1782754645;
    public static final int CONTEXT_TELEPHONE_S_M_S_ONE_ENTRY_FOR_EACH_ACCOUNT = -1494997765;
    public static final int CONTEXT_TELEPHONE_S_M_S_ONE_ENTRY_FOR_EACH_ACCOUNT_D_E_T_A_I_L_V_I_E_W = 369222116;
    public static final int CONTEXT_TELEPHONE_S_M_S_ONE_ENTRY_FOR_EACH_ACCOUNT_E_D_I_T_V_I_E_W = 2128184204;
    public static final int CONTEXT_TELEPHONE_S_M_S_ONE_ENTRY_FOR_EACH_ACCOUNT_L_I_S_T_V_I_E_W = -913270519;
    public static final int CONTEXT_TELEPHONE_S_M_S_ONE_ENTRY_FOR_EACH_ACCOUNT_TEMPLATE_EDITOR = -542552192;
    public static final int CONTEXT_TELEPHONE_S_M_S_ONE_ENTRY_FOR_EACH_ACCOUNT_T_E_M_P_L_A_T_E_V_I_E_W = 1329459982;
}

