/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerCategoryEarlyApps {
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_ALLROAD;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_AUTO;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_COMFORT;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_DYNAMIC;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_EFFICIENCY;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_INDIVIDUAL;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_LIFT;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_OFFROAD;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_DRIVE_SELECT_RACE;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_EINPARKHILFE;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_KEIN_LADETIMER_AKTIV;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_KEIN_STANDKLIMATISIERUNGSKLIMA_TIMER_AKTIV;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_LADE_TIMER1;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_LADE_TIMER2;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_SOFORTSTART_STANDHEIZUNGKLIMATISIERUNG;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_STANDKLIMATISIERUNGSKLIMA_TIMER1;
    public static final int CATEGORIE_POPUPS_FAHRZEUG_CAR_STANDKLIMATISIERUNGSKLIMA_TIMER2;
}

