/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi.app;

public interface AppOnlineTextConstants {
    public static final int TEXT_CONST_RHMI_CANCEL;
    public static final int TEXT_CONST_RHMI_CONTINUE;
    public static final int TEXT_CONST_RHMI_DISTR_ALERT_SERVICES_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_BATTERYCHARGE_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_BREAKDOWNCALL_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_CAR_FINDER_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_CLIMA_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_DEALER_APPOINT_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_E_CALL;
    public static final int TEXT_CONST_RHMI_DISTR_EMAILDICTATION_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_ESIM_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_GEOFENCE_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_GOOGLE_EARTH_DESCR;
    public static final int TEXT_CONST_RHMI_DISTR_GOOGLE_EARTH_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_INFOCALL_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_LGI_DOWNLOAD_V1;
    public static final int TEXT_CONST_RHMI_DISTR_LGI_UPLOAD_V1;
    public static final int TEXT_CONST_RHMI_DISTR_MEDIA_DESCR;
    public static final int TEXT_CONST_RHMI_DISTR_MEDIA_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_MOBILE_KEY;
    public static final int TEXT_CONST_RHMI_DISTR_MY_AUDI_DESCR;
    public static final int TEXT_CONST_RHMI_DISTR_MY_AUDI_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_NOT_AVAILABLE_WHILE_DRIVING;
    public static final int TEXT_CONST_RHMI_DISTR_NOT_AVAILABLE_WHILE_DRIVING_AUDI_CONNECT;
    public static final int TEXT_CONST_RHMI_DISTR_ONLINE_BREAKDOWNCALL_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_PICNAV_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_POI_DESCR;
    public static final int TEXT_CONST_RHMI_DISTR_POI_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_POI_SDS_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_POIECHARGE_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_REMOTE_HEATING_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_REMOTE_HONK_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_REMOTE_LOCK_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_REMOTE_OTA_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_REMOTEVEHICLETRACKING_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_SATELLITE_MAP;
    public static final int TEXT_CONST_RHMI_DISTR_SIM_ALERT;
    public static final int TEXT_CONST_RHMI_DISTR_SMSDICTATION_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_SPECIAL_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_SPEED_ALERT_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_STATUS_REPORT_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_STREETVIEW_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_THEFT_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_TIMEPROGRAMMING_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_TRACKING_SERVICE_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_TRAFFICLIGHT_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_TRAFFICMAP_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_TRIPSTATISTIC_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_UPDATE_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_USER_MANAGEMENT;
    public static final int TEXT_CONST_RHMI_DISTR_VALETALERT_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_VEHICLE_TELEMETRY_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_VZO_DOWNLOAD_V1;
    public static final int TEXT_CONST_RHMI_DISTR_VZO_UPLOAD_V1;
    public static final int TEXT_CONST_RHMI_DISTR_WIFIMEDIA_MAIN;
    public static final int TEXT_CONST_RHMI_DISTR_WLAN_MAIN;
    public static final int TEXT_CONST_RHMI_DWA_PUSH_MAIN;
    public static final int TEXT_CONST_RHMI_ERROR_NOT_AVAILABLE;
    public static final int TEXT_CONST_RHMI_INFINITE_LIST_WAIT;
    public static final int TEXT_CONST_RHMI_LICENSE_BREAKDOWN_CALL;
    public static final int TEXT_CONST_RHMI_LICENSE_CONCIERGE_CALL;
    public static final int TEXT_CONST_RHMI_LICENSE_ESIM;
    public static final int TEXT_CONST_RHMI_LICENSE_EXPIRED_EXPIRED;
    public static final int TEXT_CONST_RHMI_LICENSE_EXPIRED_NOT_AVAILABLE;
    public static final int TEXT_CONST_RHMI_LICENSE_HOTSPOTWLAN;
    public static final int TEXT_CONST_RHMI_LICENSE_OPERATOR_CALL;
    public static final int TEXT_CONST_RHMI_LICENSE_POI_CALL;
    public static final int TEXT_CONST_RHMI_LICENSE_SIMCARD_ALERT;
    public static final int TEXT_CONST_RHMI_LICENSE_UNKNOWN_SERVICE;
    public static final int TEXT_CONST_RHMI_LICENSE_UOTA;
    public static final int TEXT_CONST_RHMI_LICENSE_WEATHER_IN_MAP;
    public static final int TEXT_CONST_RHMI_PREVIEW_ERROR;
    public static final int TEXT_CONST_RHMI_PREVIEW_WAIT;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_ONELINE;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_ONELINE_NEXT;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_ONELINE_PREV;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_ONELINE_PREV_NEXT;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_XLINES;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_XLINES_NEXT;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_XLINES_PREV;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_XLINES_PREV_NEXT;
    public static final int TEXT_CONST_RHMI_SDS_COMMAND_ZEROLINES;
    public static final int TEXT_CONST_RHMI_SDS_FURTHER_COMMANDS_000;
    public static final int TEXT_CONST_RHMI_SDS_FURTHER_COMMANDS_001;
    public static final int TEXT_CONST_RHMI_SDS_FURTHER_COMMANDS_002;
    public static final int TEXT_CONST_RHMI_SDS_FURTHER_COMMANDS_003;
    public static final int TEXT_CONST_RHMI_SDS_FURTHER_COMMANDS_004;
    public static final int TEXT_CONST_RHMI_SDS_INTRO_000_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_INTRO_001_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_INTRO_SHORT_000_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_INTRO_SHORT_001_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_PARDON_000_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_PARDON_001_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_PARDON_SHORT_000_PROMPT;
    public static final int TEXT_CONST_RHMI_SDS_PARDON_SHORT_001_PROMPT;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_ALL;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_DEFAULT_TEXT_SPELLER;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_EXPANDINGIINFO_INVALID_LICENSE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_EXPANDINGIINFO_LICENSE_EXPIRED;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_EXPANDINGIINFO_NO_LICENSE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_EXPANDINGIINFO_NOT_ACTIVATED;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_EXPANDINGIINFO_TEASER_EXPIRED;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_INFO_TEXT_SPELLER;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_LEFT_DRAWER_CAR_REMOTE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_LEFT_DRAWER_COMMUNICATION;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_LEFT_DRAWER_ENTERTAINMENT;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_LEFT_DRAWER_HOME;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_LEFT_DRAWER_INFORMATION;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_LEFT_DRAWER_NAVIGATION;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_ABOUT;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_ABOUT_CN;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_CONNECTIVITYMANAGER;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_LICENSE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_LOGIN;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_LOGOUT;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_MOVE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_PREVIEW_DELETE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_PRIVACY;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_RELOAD;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_USERINFO;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_USERS;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_RIGHT_DRAWER_USERSETTINGS;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_SERVICE_NOT_AVAILABLE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_SERVICE_WAITING;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_SETTINGS;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_CAR_REMOTE;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_COMMUNICATION;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_ENTERTAINMENT;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_HOME;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_INFORMATION;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_NAVIGATION;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_OFFLINE_MODE;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_TITLE;
    public static final int TEXT_CONST_RHMI_TOP_WIZARD_WAITING;
    public static final int[] TEXT_CONST_RHMI_TOP_WIZARD_WLAN;

    static {
        TEXT_CONST_RHMI_TOP_WIZARD_ALL = new int[]{2031690496};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_CAR_REMOTE = new int[]{773595904};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_COMMUNICATION = new int[]{740041472};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_ENTERTAINMENT = new int[]{756818688};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_HOME = new int[]{1998136064};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_INFORMATION = new int[]{706487040};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_NAVIGATION = new int[]{723264256};
        TEXT_CONST_RHMI_TOP_WIZARD_SUBTITLE_OFFLINE_MODE = new int[]{689709824};
        TEXT_CONST_RHMI_TOP_WIZARD_TITLE = new int[]{-2095504640};
        TEXT_CONST_RHMI_TOP_WIZARD_WLAN = new int[]{2014913280};
    }
}

