/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi.app;

public interface SDPromptTextConstants {
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_DATE_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_DATE_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_PROMPT;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_DATE_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_DATE_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_TIME_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_TIME_SUBJECT_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_SUBJECT_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_TIME_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_ONLY_DATE_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_DATE_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_DATE_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_TIME_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_ONLY_DATE_TIME_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_TIME_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_TIME_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_TIME_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_TIME_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_ALL_INFO_PROMPT;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_TIME_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_DATE_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_DATE_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_ONLY_DATE_TIME_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_TIME_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_TIME_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_WITHOUT_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_ALL_INFO_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_DATE_SUBJECT_PROMPT;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_TIME_SUBJECT_PROMPT;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_DATE_PROMPT;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_DATE_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_PROMPT;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_TIME_PROMPT;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_PROMPT;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_TIME_PROMPT;
}

