/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi.app;

public interface SDPromptTextConstants {
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_TIME_PROMPT = 3097;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_PROMPT = 3096;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_DATE_TIME_PROMPT = 3099;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_DATE_PROMPT = 3098;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_TIME_PROMPT = 3101;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_TO_PROMPT = 3100;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_DATE_TIME_PROMPT = 3103;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_DATE_PROMPT = 3102;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_WITHOUT_SUBJECT_PROMPT = 3089;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_TIME_WITHOUT_SUBJECT_PROMPT = 3088;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_TIME_SUBJECT_PROMPT = 3091;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_SUBJECT_PROMPT = 3090;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_WITHOUT_SUBJECT_PROMPT = 3093;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_TIME_WITHOUT_SUBJECT_PROMPT = 3092;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_ONLY_DATE_TIME_PROMPT = 3095;
    public static final int EPP_SMS_HEADER_DEFAULT_READOUT_FROM_DATE_PROMPT = 3094;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_DATE_WITHOUT_SUBJECT_PROMPT = 3064;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_TIME_WITHOUT_SUBJECT_PROMPT = 3080;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_ONLY_DATE_TIME_PROMPT = 3065;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_WITHOUT_SUBJECT_PROMPT = 3081;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_SUBJECT_PROMPT = 3066;
    public static final int EPP_HEADER_DRAFT_READOUT_SUBJECT_PROMPT = 3082;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_TIME_SUBJECT_PROMPT = 3067;
    public static final int EPP_HEADER_DRAFT_READOUT_TIME_SUBJECT_PROMPT = 3083;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_TIME_WITHOUT_SUBJECT_PROMPT = 3068;
    public static final int EPP_HEADER_DRAFT_READOUT_TIME_WITHOUT_SUBJECT_PROMPT = 3084;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_WITHOUT_SUBJECT_PROMPT = 3069;
    public static final int EPP_HEADER_DRAFT_READOUT_WITHOUT_SUBJECT_PROMPT = 3085;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_SUBJECT_PROMPT = 3086;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_ALL_INFO_PROMPT = 3070;
    public static final int EPP_HEADER_UNSENT_READOUT_TO_DATE_TIME_SUBJECT_PROMPT = 3087;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_DATE_SUBJECT_PROMPT = 3071;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_DATE_WITHOUT_SUBJECT_PROMPT = 3072;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_ONLY_DATE_TIME_PROMPT = 3073;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_SUBJECT_PROMPT = 3074;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_TIME_SUBJECT_PROMPT = 3075;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_TIME_WITHOUT_SUBJECT_PROMPT = 3076;
    public static final int EPP_HEADER_DEFAULT_READOUT_TO_WITHOUT_SUBJECT_PROMPT = 3077;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_ALL_INFO_PROMPT = 3062;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_SUBJECT_PROMPT = 3078;
    public static final int EPP_HEADER_DEFAULT_READOUT_FROM_DATE_SUBJECT_PROMPT = 3063;
    public static final int EPP_HEADER_DRAFT_READOUT_DATE_TIME_SUBJECT_PROMPT = 3079;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_DATE_PROMPT = 3106;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_DATE_TIME_PROMPT = 3107;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_PROMPT = 3104;
    public static final int EPP_SMS_HEADER_DRAFT_READOUT_TIME_PROMPT = 3105;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_PROMPT = 3108;
    public static final int EPP_SMS_HEADER_UNSENT_READOUT_TO_TIME_PROMPT = 3109;
}

