/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carvehiclestates;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_OILLEVELVIEWOPTION = 1;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_OILLEVELDATA = 2;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_VINVIEWOPTION = 3;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_VINDATA = 4;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_KEYVIEWOPTION = 5;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_KEYDATA = 6;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DRVSCHOOLSYSTEM = 10;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_VEHICLEINFOVIEWOPTIONS = 11;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOHIGHFREQUENTVIEWOPTIONS = 12;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOMIDFREQUENTVIEWOPTIONS = 13;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOHIGHFREQUENT = 14;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOMIDFREQUENT = 15;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_SEMISTATICVEHICLEDATAVIEWOPTIONS = 16;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_SEMISTATICVEHICLEDATA = 17;
    public static final int ATTRIBUTE_ID_DSICARVEHICLESTATES_DYNAMICVEHICLEINFOSCR = 18;
}

