/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.telephone;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_ISREVERTED = 1;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_LASTANSWEREDNUMBERS = 2;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_LASTDIALEDNUMBERS = 3;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_MISSEDNUMBERS = 4;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_MEDATAVALIDITY = 6;
    public static final int ATTRIBUTE_ID_DSICALLSTACKS_MISSEDCALLINDICATOR = 7;
    public static final int ATTRIBUTE_ID_DSIMOBILESPEECHRECOGNITION_SPEECHRECOGNITIONAVAILABLE = 1;
    public static final int ATTRIBUTE_ID_DSIMOBILESPEECHRECOGNITION_SPEECHRECOGNITIONACTIVE = 2;
    public static final int ATTRIBUTE_ID_DSIMOBILESPEECHRECOGNITION_SPEECHRECOGNITIONTYPE = 3;
    public static final int ATTRIBUTE_ID_DSINAD_SIMPINREQUIRED = 3;
    public static final int ATTRIBUTE_ID_DSINAD_ACTIVATIONSTATE = 4;
    public static final int ATTRIBUTE_ID_DSINAD_AUTOMATICPINENTRYACTIVE = 5;
    public static final int ATTRIBUTE_ID_DSINAD_LOCKSTATE = 16;
    public static final int ATTRIBUTE_ID_DSINAD_NADTEMPERATURE = 19;
    public static final int ATTRIBUTE_ID_DSINAD_PHONEINFORMATION = 20;
    public static final int ATTRIBUTE_ID_DSINAD_NETWORKPROVIDER = 21;
    public static final int ATTRIBUTE_ID_DSINAD_NETWORKTYPE = 22;
    public static final int ATTRIBUTE_ID_DSINAD_REGISTERSTATE = 24;
    public static final int ATTRIBUTE_ID_DSINAD_SIGNALQUALITY = 27;
    public static final int ATTRIBUTE_ID_DSINAD_SERVICEPROVIDER = 29;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_DTMFTONEPLAYING = 1;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_EMERGENCYNUMBERS = 2;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SIMPINREQUIRED = 3;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ACTIVATIONSTATE = 4;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_AUTOMATICPINENTRYACTIVE = 5;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_AUTOMATICREDIALACTIVE = 6;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_BATTERYCHARGELEVEL = 7;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CALLDURATIONLIST = 8;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CALLLIST = 9;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CDMATHREEWAYCALLINGSETTING = 10;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_CRADLEPLUGINSTATE = 11;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_DISCONNECTREASON = 12;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_EMERGENCYCALLACTIVE = 13;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ENHANCEDPRIVACYMODE = 14;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_HANDSFREEMODE = 15;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_LOCKSTATE = 16;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_MAILBOXCONTENT = 17;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_MICMUTESTATE = 18;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NADTEMPERATURE = 19;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PHONEINFORMATION = 20;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NETWORKPROVIDER = 21;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NETWORKTYPE = 22;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PRIVACYMODE = 23;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_REGISTERSTATE = 24;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SERVICECODETYPE = 25;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SERVICENUMBERS = 26;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SIGNALQUALITY = 27;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SUPPSERVICERESPONSE = 28;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SERVICEPROVIDER = 29;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SIMALIASINFORMATION = 30;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_MICGAINLEVEL = 31;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_OPTIMIZATIONMODE = 32;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_NADMODE = 33;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_OTHERSIMAVAILABLE = 34;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ALTERNATEPHONEACTIVITY = 35;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PREFIXCONTENT = 36;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PHONEREMINDERSETTING = 37;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ACTIVATIONSTATEASSOCIATED = 38;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PREFIXACTIVATED = 39;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_WIDEBANDSPEECH = 40;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_PHONERINGTONE = 41;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_FAVORITES = 42;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_SAPUPGRADEACTIVE = 43;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_EUICCID = 44;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ESIMMSISDN = 45;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ESIMACTIVE = 46;
    public static final int ATTRIBUTE_ID_DSITELEPHONE_ESIMB2BMODE = 47;
}

