/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.telephone;

public interface DSINAD {
    public static final String IPL_COMM_UUID = "e6d19d10-eec6-5b6e-ba92-01cd5c77eae5";
    public static final String IPL_COMM_INTERFACE_KEY = "ee793349-0356-55d5-9b90-060fc513b7bb";
    public static final String IPL_COMM_INTERFACE_VERSION = "2.11.27";
    public static final String IPL_COMM_MODULE_VERSION = "2.11.27";

    public static interface Consts {
        public static final String VERSION = "2.11.27";
        public static final int ACTIVATIONSTATE_INIT = 0;
        public static final int ACTIVATIONSTATE_NOT_ATTACHED = 1;
        public static final int ACTIVATIONSTATE_TEL_ACTIVE_CALL = 2;
        public static final int ACTIVATIONSTATE_PHONE_OFF = 4;
        public static final int ACTIVATIONSTATE_PHONE_ON = 5;
        public static final int ACTIVATIONSTATE_ATTACHED_NOT_READY = 7;
        public static final int ACTIVATIONSTATE_ATTACHED_NOT_FUNC = 9;
        public static final int ACTIVATIONSTATE_ME_RECONNECT = 12;
        public static final int PHONEMODULESTATE_N_A = 0;
        public static final int PHONEMODULESTATE_OFF_TEMP = 1;
        public static final int PHONEMODULESTATE_ON = 2;
        public static final int PHONEMODULESTATE_OFF = 3;
        public static final int PHONEMODULESTATE_OFF_DIAG = 4;
        public static final int PHONEMODULESTATE_NOT_FUNCTION = 5;
        public static final int PHONEMODULESTATE_INIT = 6;
        public static final int NADTEMPLEVEL_NORMAL = 0;
        public static final int NADTEMPLEVEL_UNDER = 1;
        public static final int NADTEMPLEVEL_WARNING = 2;
        public static final int NADTEMPLEVEL_HIGH = 3;
        public static final int NADTEMPLEVEL_UNKNOWN = 4;
        public static final int POWER_OFF_PERS = 0;
        public static final int POWER_ON_PERS = 1;
        public static final int LOCKSTATE_UNKNOWN = 0;
        public static final int LOCKSTATE_UNLOCK_INPR = 1;
        public static final int LOCKSTATE_NO_LOCK = 2;
        public static final int LOCKSTATE_PIN_REQUIRED = 3;
        public static final int LOCKSTATE_PIN2_REQUIRED = 4;
        public static final int LOCKSTATE_PUK_REQUIRED = 5;
        public static final int LOCKSTATE_PUK2_REQUIRED = 6;
        public static final int LOCKSTATE_PUK_BLOCKED = 7;
        public static final int LOCKSTATE_PUK2_BLOCKED = 8;
        public static final int LOCKSTATE_SECCO_REQUIRED = 9;
        public static final int LOCKSTATE_SECCO_BLOCKED = 10;
        public static final int LOCKSTATE_SIMNOTFUNC = 11;
        public static final int REGISTERSTATE_UNKNOWN = 0;
        public static final int REGISTERSTATE_REGISTERED = 1;
        public static final int REGISTERSTATE_ROAMING = 2;
        public static final int REGISTERSTATE_SEARCHING = 3;
        public static final int REGISTERSTATE_NOT_SEARCHING = 4;
        public static final int REGISTERSTATE_DENIED = 5;
        public static final int REGMODE_MANUAL = 0;
        public static final int REGMODE_AUTOMATIC = 1;
        public static final int NETTYPE_UNKNOWN = 0;
        public static final int NETTYPE_GSM = 1;
        public static final int NETTYPE_CDMA = 2;
        public static final int NETTYPE_PDC = 3;
        public static final int NETTYPE_UMTS = 4;
        public static final int NETTYPE_LTE = 5;
        public static final int LOCKCODE_PIN = 0;
        public static final int LOCKCODE_PIN2 = 1;
        public static final int LOCKCODE_PUK = 2;
        public static final int LOCKCODE_PUK2 = 3;
        public static final int LOCKCODE_SECCO = 4;
        public static final int SERVICESTATE_IDLE = 0;
        public static final int SERVICESTATE_SESSION = 1;
        public static final int SERVICESTATE_TERMINATED = 2;
        public static final int SERVICESTATE_RESPONDED = 3;
        public static final int SERVICESTATE_NOSUP = 4;
        public static final int SERVICESTATE_ERROR = 5;
        public static final int RESULT_OK = 0;
        public static final int RESULT_ABORTED = 1;
        public static final int RESULT_ERROR_NOSUP_PHONE = 2;
        public static final int RESULT_ERROR_NOSUP_NW = 3;
        public static final int RESULT_ERROR_UNSPECIFIED = 4;
        public static final int RESULT_ERROR_CODE_WRONG = 5;
        public static final int RESULT_ERROR_SERV_BUSY = 6;
        public static final int RESULT_ERROR_NOT_ALLOWED = 7;
        public static final int RESULT_ERROR_SIM_FAILURE = 8;
        public static final int RESULT_ERROR_CODE_INVALID_FORMAT = 9;
        public static final int RESULT_ERROR_STRING_TOO_LONG = 11;
        public static final int RESULT_ERROR_NO_NW_REPLY = 12;
        public static final int RESULT_ERROR_NO_NW_ACCESS = 13;
        public static final int RESULT_ERROR_INVALID_CALL_ID = 14;
        public static final int RESULT_ERROR_NW_REGISTRATION_NOT_ALLOWED = 15;
        public static final int RESULT_ERROR_VOICE_NOT_POSSIBLE_CARPLAY_ACTIVE = 17;
        public static final int RESULT_ERROR_VOICE_NOT_POSSIBLE_ANDROID_AUTO_ACTIVE = 18;
        public static final int PROVIDERSTATE_UNKNOWN = 0;
        public static final int PROVIDERSTATE_SELECTED = 1;
        public static final int PROVIDERSTATE_FORBIDDEN = 2;
        public static final int PROVIDERSTATE_AVAILABLE = 3;
        public static final int FACMODE_LOCK = 0;
        public static final int FACMODE_UNLOCK = 1;
        public static final int FACMODE_QUERY = 2;
        public static final int FACILITY_UNKNOWN = 0;
        public static final int FACILITY_SC = 1;
        public static final int FACSTATE_NOT_ACTIVE = 0;
        public static final int FACSTATE_ACTIVE = 1;
        public static final int NETIDAVAIL_TEMP_NOT_AVAIL = 0;
        public static final int NETIDAVAIL_NOT_AVAIL = 1;
        public static final int NETIDAVAIL_AVAIL = 2;
        public static final int SERVICECODEREQTYPE_UNKNOWN = 0;
        public static final int SERVICECODEREQTYPE_ACTIVATION = 1;
        public static final int SERVICECODEREQTYPE_DEACTIVATION = 2;
        public static final int SERVICECODEREQTYPE_INTERROGATION = 3;
        public static final int SERVICECODEREQTYPE_REGISTRATION = 4;
        public static final int SERVICECODEREQTYPE_ERASURE = 5;
        public static final String DEVICE_NAME = "DEVICE_NAME";
        public static final String DEVICE_INSTANCE = "DEVICE_INSTANCE";
    }
}

