/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.hmi.widgets.audi.base;

import de.audi.atip.log.LogChannel;
import de.esolutions.hmi.widgets.audi.base.AbstractWidget;

public interface IWidgetLogChannel {
    public static final LogChannel logChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.Main");
    public static final LogChannel screenLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.Screen");
    public static final LogChannel iconLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.icon");
    public static final LogChannel sideBarLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.Sidebar");
    public static final LogChannel mixedListLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.MixedList");
    public static final LogChannel mixedListItemLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.MixedList.Item");
    public static final LogChannel mixedListCallbackLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.MixedList.Callback");
    public static final LogChannel mixedListAfterPaint = AbstractWidget.framework.getLogChannel("Fw.Widgets.MixedList.AfterPaint");
    public static final LogChannel tpLogChannelKeypanel = AbstractWidget.framework.getLogChannel("Fw.Widgets.TouchPad.Keypanel");
    public static final LogChannel tpLogChannelInternal = AbstractWidget.framework.getLogChannel("Fw.Widgets.TouchPad.Internal");
    public static final LogChannel logPRPEngine = AbstractWidget.framework.getLogChannel("Fw.Widgets.TouchPad.PRPengine");
    public static final LogChannel menuLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.Menu");
    public static final LogChannel menuLayoutLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.Menu.Layout");
    public static final LogChannel menuItemLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.MenuItem");
    public static final LogChannel listLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.List");
    public static final LogChannel logScrollbar = AbstractWidget.framework.getLogChannel("Fw.Widgets.Scrollbar");
    public static final LogChannel navMapInfotextLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.MapInfotext");
    public static final LogChannel pictureWallLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.PictureWall");
    public static final LogChannel pictureWallScrollingLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.PictureWall.Scrolling");
    public static final LogChannel logChannelCoverStack = AbstractWidget.framework.getLogChannel("Fw.Widgets.CoverStack");
    public static final LogChannel mapOverlayLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.MapOverlays");
    public static final LogChannel textDescriptorLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.TextDescriptor");
    public static final LogChannel mapControllerLogCh = AbstractWidget.framework.getLogChannel("Fw.MapController");
    public static final LogChannel pictureFrameLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.PictureFrame");
    public static final LogChannel iconLabelLogCh = AbstractWidget.framework.getLogChannel("Fw.Widgets.IconLabel");
    public static final LogChannel spellerLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.Speller");
    public static final LogChannel canditateMatrixLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.CanditateMatrix");
    public static final LogChannel logChannelEvent = AbstractWidget.framework.getLogChannel("Fw.ATIPEventQueue");
    public static final LogChannel binSizeLogChannel = AbstractWidget.framework.getLogChannel("Ext.BinSizes");
    public static final LogChannel imageLoaderLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.ImageLoader");
    public static final LogChannel imageLoaderStatisticsLogChannel = AbstractWidget.framework.getLogChannel("Fw.Widgets.ImageLoader.Statistics");
    public static final LogChannel lRULogChannel = AbstractWidget.framework.getLogChannel("Ext.LRUCache");
    public static final LogChannel logChannelWizardController = AbstractWidget.framework.getLogChannel("Fw.Widgets.Wizard.Controller");
    public static final LogChannel logChannelWizardRenderer = AbstractWidget.framework.getLogChannel("Fw.Widgets.Wizard.Renderer");
    public static final LogChannel logChannel3DEngine = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine");
    public static final LogChannel logChannel3DEngineLayersAndViewports = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.LayersAndViewports");
    public static final LogChannel logChannel3DEngineDestroy = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.destroy");
    public static final LogChannel logChannel3DEngineNodeNames = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.nodeNames");
    public static final LogChannel logChannel3DEngineTextureDestroyCheck = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.textureDestroyCheck");
    public static final LogChannel logChannel3DEngineCache = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.Cache");
    public static final LogChannel logChannel3DEngineCacheSize = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.CacheSize");
    public static final LogChannel logChannel3DCar = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DCar");
    public static final LogChannel logChannelParking = AbstractWidget.framework.getLogChannel("Fw.Widgets.Parking");
    public static final LogChannel logChannelDriveSelect = AbstractWidget.framework.getLogChannel("Fw.Widgets.DriveSelect");
    public static final LogChannel logWidgetRegistry = AbstractWidget.framework.getLogChannel("Fw.Widgets.Registry");
    public static final LogChannel logLayout = AbstractWidget.framework.getLogChannel("Fw.Widgets.Layout");
    public static final LogChannel logAnimation = AbstractWidget.framework.getLogChannel("Fw.Animation");
    public static final LogChannel logAnimationSport = AbstractWidget.framework.getLogChannel("Fw.Animation.Sportskin");
    public static final LogChannel logDrawer = AbstractWidget.framework.getLogChannel("Fw.Widgets.Drawer");
    public static final LogChannel logSelectionDrawerController = AbstractWidget.framework.getLogChannel("Fw.Widgets.SelectionDrawer.Controller");
    public static final LogChannel logSelectionDrawerRenderer = AbstractWidget.framework.getLogChannel("Fw.Widgets.SelectionDrawer.Renderer");
    public static final LogChannel logPlaceholderMenuListController = AbstractWidget.framework.getLogChannel("Fw.Widgets.PlaceholderMenuListController");
    public static final LogChannel logScreenChange = AbstractWidget.framework.getLogChannel("Fw.Widgets.ScreenChange");
    public static final LogChannel logContainer = AbstractWidget.framework.getLogChannel("Fw.Widgets.Container");
    public static final LogChannel logDrawerFocus = AbstractWidget.framework.getLogChannel("Fw.Widgets.DrawerFocusManager");
    public static final LogChannel logDrawerFocusMain = AbstractWidget.framework.getLogChannel("Fw.Widgets.DrawerFocus");
    public static final LogChannel logDisclaimer = AbstractWidget.framework.getLogChannel("Fw.Widgets.Disclaimer");
    public static final LogChannel logDrawerAnimation = AbstractWidget.framework.getLogChannel("Fw.Widgets.DrawerAnimation");
    public static final LogChannel logDrawerAnimationDrawer = AbstractWidget.framework.getLogChannel("Fw.Widgets.DrawerAnimation.Drawer");
    public static final LogChannel logDrawerAnimationScreen = AbstractWidget.framework.getLogChannel("Fw.Widgets.DrawerAnimation.Screen");
    public static final LogChannel logDrawerCondtionEngine = AbstractWidget.framework.getLogChannel("Fw.Widgets.DrawerConditionEngine");
    public static final LogChannel logViewSize = AbstractWidget.framework.getLogChannel("Fw.Widgets.ViewSize");
    public static final LogChannel logViewSizeAnimation = AbstractWidget.framework.getLogChannel("Fw.Widgets.ViewSize.Animation");
    public static final LogChannel logOperationalPanel = AbstractWidget.framework.getLogChannel("Fw.Widgets.OperationalPanel");
    public static final LogChannel logChannelPopups = AbstractWidget.framework.getLogChannel("Fw.Widgets.Popups");
    public static final LogChannel logChannelSeat = AbstractWidget.framework.getLogChannel("Fw.Widgets.Seat");
    public static final LogChannel logChannelPPMMICombi = AbstractWidget.framework.getLogChannel("Fw.Widgets.Popups.MMICombi");
    public static final LogChannel logPreset = AbstractWidget.framework.getLogChannel("Fw.Widgets.Preset");
    public static final LogChannel logPresetInput = AbstractWidget.framework.getLogChannel("Fw.Widgets.Preset.Input");
    public static final LogChannel logUserHints = AbstractWidget.framework.getLogChannel("Fw.Widgets.UserHints");
    public static final LogChannel logRepaintCause = AbstractWidget.framework.getLogChannel("Fw.Widgets.RepaintCause");
    public static final LogChannel logWidgetPerformance = AbstractWidget.framework.getLogChannel("Fw.Widgets.Performance");
    public static final LogChannel logWidgetSharedTexture = AbstractWidget.framework.getLogChannel("Fw.Widgets.SharedTextures");
    public static final LogChannel logBenchmark = AbstractWidget.framework.getLogChannel("Ext.Startup");
    public static final LogChannel logWidgetStartup = AbstractWidget.framework.getLogChannel("Fw.Widgets.Startup");
    public static final LogChannel logKDK = AbstractWidget.framework.getLogChannel("Fw.Widgets.KDK");
    public static final LogChannel logEntertainmentDrawer = AbstractWidget.framework.getLogChannel("Fw.Widgets.EntertainmentDrawer");
    public static final LogChannel logEntertainmentStateUpdater = AbstractWidget.framework.getLogChannel("Fw.Widgets.EntertainmentDrawer.StateUpdater");
    public static final LogChannel logEntertainmentDrawerAnimationManager = AbstractWidget.framework.getLogChannel("Fw.Widgets.EntertainmentDrawer.AnimationManager");
    public static final LogChannel logEntertainmentDrawerEvents = AbstractWidget.framework.getLogChannel("Fw.Widgets.EntertainmentDrawer.Events");
    public static final LogChannel logBalanceFader = AbstractWidget.framework.getLogChannel("Fw.Widgets.BalanceFader");
    public static final LogChannel logBalanceFaderKeyEvents = AbstractWidget.framework.getLogChannel("Fw.Widgets.BalanceFader.KeyEvents");
    public static final LogChannel logMessagingMultiline = AbstractWidget.framework.getLogChannel("Fw.Widgets.Multiline");
    public static final LogChannel logMessagingMultilineRenderer = AbstractWidget.framework.getLogChannel("Fw.Widgets.Multiline.Renderer");
    public static final LogChannel logMessagingMultilineEvents = AbstractWidget.framework.getLogChannel("Fw.Widgets.Multiline.Events");
    public static final LogChannel logMessagingMultilineAnimations = AbstractWidget.framework.getLogChannel("Fw.Widgets.Multiline.Animations");
    public static final LogChannel logMessagingStatusBar = AbstractWidget.framework.getLogChannel("Fw.Widgets.Messaging.StatusBar");
    public static final LogChannel logPLA = AbstractWidget.framework.getLogChannel("Fw.Widgets.PLA");
    public static final LogChannel logCarCoding = AbstractWidget.framework.getLogChannel("Fw.Widgets.CarCoding");
    public static final LogChannel logImageDecorator = AbstractWidget.framework.getLogChannel("Fw.Widgets.ImageDecorator");
    public static final LogChannel logStatisticsStackedBarChart = AbstractWidget.framework.getLogChannel("Fw.Widgets.Statistics.StackedBarChart");
    public static final LogChannel logImage = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.Loader.Image");
    public static final LogChannel logImageAsync = AbstractWidget.framework.getLogChannel("Fw.Widgets.3DEngine.Loader.ImageAsync");
    public static final LogChannel logLocking = AbstractWidget.framework.getLogChannel("Fw.Widgets.Locking");
}

