/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.hmi.widgets.audi.base;

public interface Layout {
    public static final int MAP_FONT_SIZE_POINTS_TO_PIXELS = 0;
    public static final int MAP_FONT_SIZE_PIXELS_TO_POINTS = 1;
    public static final int LINE_DESCRIPTION_SUBMENU = 0;
    public static final int LINE_DESCRIPTION_CHECK_BOX = 1;
    public static final int LINE_DESCRIPTION_COMBO_BOX = 2;
    public static final int LINE_DESCRIPTION_ROTARY_ACTION = 3;
    public static final int LINE_DESCRIPTION_SUBMENU_CHECK_BOX = 4;
    public static final int LINE_DESCRIPTION_SUBMENU_PREVIEW = 5;
    public static final int LINE_DESCRIPTION_MAX = 6;
    public static final int DISTANCE_DISPLAY_WIDTH = 1;
    public static final int DISTANCE_DISPLAY_HEIGHT = 2;
    public static final int DISTANCE_MENU_CLIPPING_WIDTH = 3;
    public static final int DISTANCE_SUBTITLE_LINE_X = 4;
    public static final int DISTANCE_SUBTITLE_LINE_Y = 5;
    public static final int DISTANCE_SUBTITLE_OFFSET_X = 6;
    public static final int DISTANCE_SUBTITLE_OFFSET_X_ICON_RIGHT_ALIGNED = 7;
    public static final int DISTANCE_TOOLTIP_DISTANCE_TO_BORDER_H = 8;
    public static final int DISTANCE_TOOLTIP_DISTANCE_TO_BORDER_V = 9;
    public static final int DISTANCE_FONT_SIZE_ROADICON = 10;
    public static final int DISTANCE_TOOLTIP_BOTTOM_LINE_Y = 11;
    public static final int DISTANCE_SDS_SYMBOL_WIDTH = 12;
    public static final int DISTANCE_SDS_SYMBOL_Y_OFFSET = 13;
    public static final int DISTANCE_TOOLTIP_OFFSET_TOP_LINE_Y = 14;
    public static final int DISTANCE_MOVE_CURSOR_X_OFFSET = 15;
    public static final int DISTANCE_UNSUPPORTED_DEVELOPMENT_BUILD_IMAGE_ID = 16;
    public static final int DISTANCE_MAX_MENU_LINES = 17;
    public static final int DISTANCE_TEXTFIELD_LEFT_BOUNDS = 18;
    public static final int DISTANCE_POPIN_DELTA_TURNOVER = 19;
    public static final int DISTANCE_SUBTITLE_BASELINE_Y = 20;
    public static final int DISTANCE_OSD_LINE_OFFSET_Y = 21;
    public static final int DISTANCE_DISPLAY_OFFSET_X = 22;
    public static final int DISTANCE_DISPLAY_OFFSET_Y = 23;
    public static final int DISTANCE_MIXED_LIST_ITEM_HEIGHT = 24;
    public static final int DISTANCE_MIXED_LIST_ITEM_GAP = 25;
    public static final int DISTANCE_MIXED_LIST_LOCATION_HEIGHT = 26;
    public static final int DISTANCE_MIXED_LIST_ITEM_LOCATION_GAP = 27;
    public static final int DISTANCE_MIXED_LIST_HORIZONTAL_OFFSET = 28;
    public static final int DISTANCE_MIXED_LIST_ROW_HEIGHT_TOP = 29;
    public static final int DISTANCE_MIXED_LIST_ROW_HEIGHT_CENTER = 30;
    public static final int DISTANCE_MIXED_LIST_ROW_HEIGHT_BOTTOM = 31;
    public static final int DISTANCE_MIXED_LIST_BORDER_WIDTH = 32;
    public static final int DISTANCE_MIXED_LIST_SHIFT_TURN_ARROW_DOWN = 33;
    public static final int DISTANCE_TMC_DETAIL_ROW_OVERALL = 34;
    public static final int DISTANCE_CELL_Y_OFFSET = 35;
    public static final int DISTANCE_MENU_CLIPPING_X = 36;
    public static final int DISTANCE_TOOLTIP_MAX_TOP_Y = 37;
    public static final int DISTANCE_MENU_SCROLLBAR_WIDTH = 38;
    public static final int DISTANCE_BALANCE_FADER_MIDDLE_POS_X = 39;
    public static final int DISTANCE_BALANCE_FADER_MIDDLE_POS_Y = 40;
    public static final int DISTANCE_BALANCE_FADER_MOVEABLE_WIDTH = 41;
    public static final int DISTANCE_BALANCE_FADER_MOVEABLE_HEIGHT = 42;
    public static final int DISTANCE_FONT_XDPI = 43;
    public static final int DISTANCE_FONT_YDPI = 44;
    public static final int DISTANCE_ROUTE_SELECT_NUMBER_X = 45;
    public static final int DISTANCE_ROUTE_SELECT_NUMBER_Y = 46;
    public static final int DISTANCE_SEPARATOR_LINE_X_OFFSET = 47;
    public static final int DISTANCE_SEPARATOR_LINE_Y_OFFSET = 48;
    public static final int DISTANCE_MENU_SCROLLER_TICKS_TO_TRIGGER_FASTSCROLL = 49;
    public static final int DISTANCE_BORDERWIDGETD4_BORDER_X_OFFSET = 50;
    public static final int DISTANCE_BORDERWIDGETD4_BORDER_Y_OFFSET_UPPER = 51;
    public static final int DISTANCE_BORDERWIDGETD4_OVERLAY_STATUSBAR = 52;
    public static final int DISTANCE_BORDERWIDGETD4_MIN_SK_WIDTH = 53;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_NO_BORDER_SPELLER_X_OFFSET_LEFT = 54;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_NO_BORDER_SPELLER_X_OFFSET_RIGHT = 55;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_NO_BORDER_SPELLER_Y_OFFSET_LOWER = 56;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_NO_BORDER_SPELLER_Y_OFFSET_UPPER = 57;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_SHADOW_LOWER_HEIGHT = 58;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_SHADOW_RIGHT_WIDTH = 59;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_X_OFFSET_LEFT = 60;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_X_OFFSET_RIGHT = 61;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_Y_OFFSET_LOWER = 62;
    public static final int DISTANCE_BORDERWIDGETD4_NEW_WINDOW_Y_OFFSET_UPPER = 63;
    public static final int DISTANCE_BORDERWIDGETD4_SOFTKEY_LABEL_MARGIN = 64;
    public static final int DISTANCE_BORDERWIDGETD4_VERTICAL_LINE_NONSKSIDE_MIN_DISTANCE = 65;
    public static final int DISTANCE_BORDERWIDGETD4_SKLINE_SHADOW_OFFSET = 66;
    public static final int DISTANCE_BORDERWIDGETD4_BORDER_Y_OFFSET_TURNOVER = 67;
    public static final int DISTANCE_CURSORBARWIDGETD4_MASK_WIDTH = 68;
    public static final int DISTANCE_CHECKBOXCELLWIDGETD4_BOX_SIZE = 69;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_SIZE_GLOW = 70;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_HEIGHT_SINGLE = 71;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_HEIGHT_DOUBLE = 72;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_GAP = 73;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_MARGIN_HOR = 74;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_SPACING_HOR = 75;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_LABEL_OFFSET_Y = 76;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_ARROW_HEIGHT = 77;
    public static final int DISTANCE_WIZARDWIDGET_C2_HEIGHT_SINGLE = 78;
    public static final int DISTANCE_WIZARDWIDGET_C2_HEIGHT_DOUBLE = 79;
    public static final int DISTANCE_WIZARDWIDGET_PREVIEW_LABEL_GAP = 80;
    public static final int DISTANCE_BALANCE_FADER_CROSSHAIR_MIDDLE_POS_X = 81;
    public static final int DISTANCE_BALANCE_FADER_CROSSHAIR_MIDDLE_POS_Y = 82;
    public static final int DISTANCE_CURSORBARWIDGETD4_MOVECURSOR_FILL_OFFSET_X = 83;
    public static final int DISTANCE_CURSORBARWIDGETD4_MOVECURSOR_ARROW_DOWN_Y_OFFSET = 84;
    public static final int DISTANCE_CURSORBARWIDGETD4_MOVECURSOR_ARROW_UP_POS_Y = 85;
    public static final int DISTANCE_CURSORBARWIDGETD4_MOVECURSOR_ARROW_X_OFFSET = 86;
    public static final int DISTANCE_MENU_X_OFFSET = 87;
    public static final int DISTANCE_CURSOR_BACKGROUND_PIXEL_OFFSET = 88;
    public static final int DISTANCE_CURSOR_POS_Y_OFFSET = 89;
    public static final int DISTANCE_CURSOR_X_POS_DENOMINATOR = 90;
    public static final int DISTANCE_MIXEDLISTBACKGROUNDRENDERER_TOP_BITMAP_HEIGHT = 91;
    public static final int DISTANCE_MIXEDLISTBACKGROUNDRENDERER_SCALE_FACTOR_MIDDLE = 92;
    public static final int DISTANCE_SCROLLBAR_RADIUS = 93;
    public static final int DISTANCE_BACKGROUND_TEXTURE_LEFT_ARC_WIDTH = 96;
    public static final int DISTANCE_TIMERWIDGETD4_INDENT_SIZE = 97;
    public static final int DISTANCE_TIMERWIDGETD4_GPS_CELL_RIGHT_OFFSET = 98;
    public static final int DISTANCE_SHADOW_LABEL_OFFSET_LEFT = 99;
    public static final int DISTANCE_SHADOW_LABEL_OFFSET_RIGHT = 100;
    public static final int DISTANCE_SHADOW_LABEL_OFFSET_TOP = 101;
    public static final int DISTANCE_CURSOR_ARROW_OFFSET_X = 102;
    public static final int DISTANCE_CURSOR_ARROW_UP_OFFSET_Y = 103;
    public static final int DISTANCE_CURSOR_ARROW_DOWN_OFFSET_Y = 104;
    public static final int DISTANCE_TEXTFIELD_OFFSET_RIGHT = 105;
    public static final int DISTANCE_ROTARY_CELL_BASE_RADIUS = 106;
    public static final int DISTANCE_ROTARY_CELL_VISIBLE_ARROW_WIDTH = 107;
    public static final int DISTANCE_ROTARY_CELL_CENTER_IMAGE_WIDTH = 108;
    public static final int DISTANCE_CURSOR_C2_OFFSET_RIGHT = 109;
    public static final int DISTANCE_MENU_CLIPPING_BOTTOM = 110;
    public static final int DISTANCE_PRESET_SYMBOL_X_OFFSET = 111;
    public static final int DISTANCE_PRESET_SYMBOL_Y_OFFSET = 112;
    public static final int DISTANCE_PRESET_NUMBER_Y_POSITION = 113;
    public static final int DISTANCE_TIMEZONEWIDGETD4_COUNTRY_BORDERS_IMAGE_POS_X = 114;
    public static final int DISTANCE_TIMEZONEWIDGETD4_COUNTRY_BORDERS_IMAGE_POS_Y = 115;
    public static final int DISTANCE_ROUTE_SELECT_GAS_PUMP_X = 116;
    public static final int DISTANCE_ROUTE_SELECT_GAS_PUMP_Y = 117;
    public static final int DISTANCE_ROUTE_SELECT_CONSUMPTION_TEXT_Y = 118;
    public static final int DISTANCE_SIDEBAR_DROP_SHADOW_OFFSET_X = 119;
    public static final int DISTANCE_FASTSCROLL_BAR_WIDTH = 120;
    public static final int DISTANCE_FASTSCROLL_BAR_HEIGHT = 121;
    public static final int DISTANCE_FASTSCROLL_BAR_CONTENT_HEIGHT = 122;
    public static final int DISTANCE_FASTSCROLL_SLIDER_TEXTURE_X = 123;
    public static final int DISTANCE_FASTSCROLL_SLIDER_TEXTURE_WIDTH = 124;
    public static final int DISTANCE_FASTSCROLL_MIN_HEIGHT = 125;
    public static final int DISTANCE_FASTSCROLL_MAX_HEIGHT = 126;
    public static final int DISTANCE_FASTSCROLL_BAR_X = 127;
    public static final int DISTANCE_FASTSCROLL_BAR_Y = 128;
    public static final int DISTANCE_FASTSCROLL_TEXT_X = 129;
    public static final int DISTANCE_FASTSCROLL_TEXT_Y = 130;
    public static final int DISTANCE_DROP_SHADOW_OFFSET = 131;
    public static final int DISTANCE_DROP_SHADOW_HEIGHT = 132;
    public static final int DISTANCE_DROP_SHADOW_CORNER_X_OFFSET = 133;
    public static final int DISTANCE_DROP_SHADOW_CORNER_Y_OFFSET = 134;
    public static final int DISTANCE_DROP_SHADOW_RIGHT_TOP_X_OFFSET = 135;
    public static final int DISTANCE_DROP_SHADOW_RIGHT_Y_OFFSET = 136;
    public static final int DISTANCE_DROP_SHADOW_RIGHT_HEIGHT_OFFSET = 137;
    public static final int DISTANCE_NAVI_INFOTEXT_LINE_SPACING = 138;
    public static final int DISTANCE_NAVI_INFOTEXT_CROSSHAIR_LINE_OFFSET_X = 139;
    public static final int DISTANCE_NAVI_INFOTEXT_CROSSHAIR_LINE_OFFSET_Y = 140;
    public static final int DISTANCE_NAVI_INFOTEXT_LEFT_BORDER_OFFSET = 141;
    public static final int DISTANCE_NAVI_INFOTEXT_MAX_WIDTH = 142;
    public static final int DISTANCE_NAVI_INFOTEXT_FRAME_MIN_WIDTH = 143;
    public static final int DISTANCE_NAVI_INFOTEXT_FRAME_MAX_WIDTH = 144;
    public static final int DISTANCE_NAVI_INFOTEXT_FRAME_TEXTURE_WIDTH = 145;
    public static final int DISTANCE_NAVI_INFOTEXT_FRAME_TEXTURE_HEIGHT = 146;
    public static final int DISTANCE_NAVI_INFOTEXT_FIRST_LINE_OFFSET = 147;
    public static final int DISTANCE_NAVI_INFOTEXT_HEIGHT_OFFSET = 148;
    public static final int DISTANCE_INFOBOXWIDGETD4_SPLIT_SCREEN_SPACING = 149;
    public static final int DISTANCE_WIZARDWIDGET_TOOLTIP_LINE_SPACING = 150;
    public static final int DISTANCE_SUBMENU_PREVIEW_FRAME_TO_TEXT_OFFSET = 151;
    public static final int DISTANCE_SUBMENU_PREVIEW_CELL_TABULATOR_OFFSET = 152;
    public static final int DISTANCE_PICTURE_CONFIG_COVERART_WIDTH = 153;
    public static final int DISTANCE_PICTURE_CONFIG_COVERART_HEIGHT = 154;
    public static final int DISTANCE_PICTURE_CONFIG_PICTUREVIEWER_WIDTH = 155;
    public static final int DISTANCE_PICTURE_CONFIG_PICTUREVIEWER_HEIGHT = 156;
    public static final int DISTANCE_PICTURE_CONFIG_THUMBNAILICONS_WIDTH = 157;
    public static final int DISTANCE_PICTURE_CONFIG_THUMBNAILICONS_HEIGHT = 158;
    public static final int DISTANCE_PICTURE_CONFIG_ADDRESSBOOK_WIDTH = 159;
    public static final int DISTANCE_PICTURE_CONFIG_ADDRESSBOOK_HEIGHT = 160;
    public static final int DISTANCE_PICTURE_CONFIG_TUNERPRESETSTATIONS_WIDTH = 161;
    public static final int DISTANCE_PICTURE_CONFIG_TUNERPRESETSTATIONS_HEIGHT = 162;
    public static final int DISTANCE_PICTURE_CONFIG_TUNERSLIDESHOW_WIDTH = 163;
    public static final int DISTANCE_PICTURE_CONFIG_TUNERSLIDESHOW_HEIGHT = 164;
    public static final int DISTANCE_TIMER_OFFSET_HOURS_ONE_DIGIT = 165;
    public static final int DISTANCE_TIMER_OFFSET_HOURS_TWO_DIGITS = 166;
    public static final int DISTANCE_GEOPOSWIDGET_DISTANCE_TO_BORDER = 167;
    public static final int DISTANCE_MIXED_LIST_BOX_WIDTH = 168;
    public static final int DISTANCE_TOOLTIP_SHADOW_SIZE = 169;
    public static final int DISTANCE_FASTSCROLL_LINE_X_OFFSET = 170;
    public static final int DISTANCE_FASTSCROLL_LINE_Y_OFFSET = 171;
    public static final int DISTANCE_NAVI_INFOTEXT_ONLINE_ICON_OFFSET = 172;
    public static final int DISTANCE_MIXED_LIST_SHIFT_ALLOWED_VELOCITY_DOWN = 173;
    public static final int DISTANCE_MIXED_LIST_SHIFT_BORDER_FLAG_DOWN = 174;
    public static final int DISTANCE_MIXED_LIST_PICTURE_NAV_IMAGE_Y_TOP = 175;
    public static final int DISTANCE_MIXED_LIST_PICTURE_NAV_IMAGE_Y_BOTTOM = 176;
    public static final int DISTANCE_MIXED_LIST_PICTURE_NAV_IMAGE_HEIGHT = 177;
    public static final int DISTANCE_MIXED_LIST_SHIFT_BORDER_FLAG_UP_SINGLE_BOX = 178;
    public static final int DISTANCE_NAVI_INFOTEXT_TEXT_SMALL_ICON = 179;
    public static final int DISTANCE_NAVI_INFOTEXT_TEXT_BIG_ICON = 180;
    public static final int DISTANCE_NAVI_INFOTEXT_MIN_LINES_FOR_BIG_ICON = 181;
    public static final int DISTANCE_NAVI_INFOTEXT_RIGHT_BORDER_OFFSET = 182;
    public static final int DISTANCE_TOOLTIP_X_OFFSET = 183;
    public static final int DISTANCE_TOOLTIP_WIDTH_OFFSET = 184;
    public static final int DISTANCE_MIXED_LIST_TURN_ICON_WIDTH = 185;
    public static final int DISTANCE_MIXED_LIST_BOX_INSETS = 186;
    public static final int DISTANCE_WIZARD_TOOLTIP_CENTER_Y = 187;
    public static final int DISTANCE_WIZARD_TOOLTIP_TOP_Y = 188;
    public static final int DISTANCE_WIZARD_TOOLTIP_CENTER_X = 189;
    public static final int DISTANCE_ROTARY_VALUE_ANGLE_LB = 190;
    public static final int DISTANCE_ROTARY_VALUE_ANGLE_HB = 191;
    public static final int DISTANCE_WAIT_ANIM_KZB_W = 192;
    public static final int DISTANCE_WAIT_ANIM_KZB_H = 193;
    public static final int DISTANCE_STATUSBAR_BOTTOM = 194;
    public static final int DISTANCE_SIDEBAR_RIGHT = 195;
    public static final int DISTANCE_SIDEBAR_AR_RIGHT = 196;
    public static final int DISTANCE_ROUTEINFO_LEFT = 197;
    public static final int DISTANCE_MAPTOOLTIP_TOP = 198;
    public static final int DISTANCE_MAPTOOLTIP_LEFT = 199;
    public static final int DISTANCE_INFOLINE_BOTTOM = 200;
    public static final int DISTANCE_REITERLINE_TOP = 201;
    public static final int DISTANCE_ROUTECRITERIABOX_LEFT = 202;
    public static final int DISTANCE_TUBE_LEFT = 203;
    public static final int DISTANCE_TUBE_RIGHT = 204;
    public static final int DISTANCE_TUBE_LEFT_KB = 205;
    public static final int DISTANCE_TUBE_RIGHT_KB = 206;
    public static final int DISTANCE_SIDEBAR_BOTTOM = 207;
    public static final int DISTANCE_ROUTECRITERIABOX_TOP = 208;
    public static final int DISTANCE_LEFT_DRAWER_ICON_LEFT = 209;
    public static final int DISTANCE_CURSOR_WAIT_ANIM_NO_ICON_X_OFFSET = 210;
    public static final int DISTANCE_CURSOR_WAIT_ANIM_WITH_ICON_X_OFFSET = 211;
    public static final int DISTANCE_CURSOR_WAIT_ANIM_MAX_Y_OFFSET = 212;
    public static final int DISTANCE_GAP_SUBMENU_PREVIEW_LEFT_RIGHT = 213;
    public static final int DISTANCE_SDS_CMD_LINE_BOTTOM = 214;
    public static final int DISTANCE_MAPTOOLTIP_BOTTOM = 215;
    public static final int DISTANCE_MATRIX_MARGIN_LEFT_GRID = 216;
    public static final int DISTANCE_MATRIX_MARGIN_RIGHT_GRID = 217;
    public static final int DISTANCE_MATRIX_MARGIN_BOTTOM_GRID = 218;
    public static final int DISTANCE_RAINRADAR_TIMESTAMP_X = 219;
    public static final int DISTANCE_RAINRADAR_TIMESTAMP_Y = 220;
    public static final int DISTANCE_RAINRADAR_TIMESTAMP_WIDTH = 221;
    public static final int DISTANCE_RAINRADAR_TIMESTAMP_HEIGHT = 222;
    public static final int DISTANCE_MATRIX_VERTICAL_SEPARATOR_HEIGHT = 223;
    public static final int DISTANCE_SPELLER_CONVERSION_LINE_CURSOR_BOX_HEIGHT = 224;
    public static final int DISTANCE_SPELLER_CONVERSION_LINE_Y_TOP_OFFSET_ABOVE_SPELLER = 225;
    public static final int DISTANCE_SPELLER_CONVERSION_LINE_TEMPLATE_NODE_Y_OFFSET = 226;
    public static final int DISTANCE_SPELLER_CONVERSION_LINE_OFFSET_CELL = 227;
    public static final int DISTANCE_GRID_WIDTH = 228;
    public static final int DISTANCE_CONVERSION_MATRIX_PADDING_LEFT_RIGHT_GRID_CELL = 229;
    public static final int DISTANCE_COUNT = 230;
    public static final int DEPTH_STATISTICS = 1;
    public static final int DEPTH_SCREEN_POPIN = 2;
    public static final int DEPTH_TA_OVERLAY = 3;
    public static final int DEPTH_OSD = 4;
    public static final int DEPTH_CURSOR = 5;
    public static final int DEPTH_SOFTKEY = 6;
    public static final int DEPTH_SIDE_BAR_ITEMS = 7;
    public static final int DEPTH_TITLE_LINE = 8;
    public static final int DEPTH_STATUS_LINE = 9;
    public static final int DEPTH_SIDE_BAR = 10;
    public static final int DEPTH_MIXED_LIST = 11;
    public static final int DEPTH_COMBOBOX_OPEN = 12;
    public static final int DEPTH_TOOLTIP = 13;
    public static final int DEPTH_MENU = 14;
    public static final int DEPTH_SUBTITLE = 15;
    public static final int DEPTH_ROTARY = 16;
    public static final int DEPTH_SPELLER = 17;
    public static final int DEPTH_FUNC_WHEEL = 18;
    public static final int DEPTH_WIZARD = 19;
    public static final int DEPTH_WIZARD_TOOLTIP = 20;
    public static final int DEPTH_SCREEN_OVERLAY = 21;
    public static final int DEPTH_SCREEN_STANDARD = 22;
    public static final int DEPTH_SCREEN_BACKGROUND = 23;
    public static final int DEPTH_SCREENSHOT_FOREGROUND = 24;
    public static final int DEPTH_SCREENSHOT_BACKGROUND = 25;
    public static final int DEPTH_DRAWER = 26;
    public static final int DEPTH_WIZARD_INFOBOX = 27;
    public static final int DEPTH_COUNT = 28;
    public static final int FC_SCROLLBAR_STROKE_WIDTH = 0;
    public static final int FC_ROTARYBUTTONWIDGETD4_SCALE_STROKE_WIDTH = 1;
    public static final int FC_ROTARYWIDGETD4_MED_MARKER_ANGLE_OF_CORNERS_TO_LINE = 2;
    public static final int FC_ROTARYWIDGETD4_MED_MARKER_OUTER_CORNERS_RADIUS_OFFSET = 3;
    public static final int FC_ROTARYWIDGETD4_MED_MARKER_PIKE_RADIUS_OFFSET = 4;
    public static final int FC_ROTARYWIDGETD4_SCALE_BOLD_MARKERS_RADIUS_ADDITION = 5;
    public static final int FC_ROTARYWIDGETD4_SCALE_STROKE_WIDTH_BOLD = 6;
    public static final int FC_ROTARYWIDGETD4_SCALE_STROKE_WIDTH_DEFAULT = 7;
    public static final int FC_NAVI_INFOTEXT_ARC_WIDTH = 8;
    public static final int FC_NAVI_INFOTEXT_ARC_HEIGHT = 9;
    public static final int FC_CURSOR_SCROLLBAR_CENTER_FACTOR_6LINE = 10;
    public static final int FC_CURSOR_SCROLLBAR_CENTER_FACTOR_5LINE = 11;
    public static final int FC_CURSOR_SCROLLBAR_CENTER_FACTOR_4LINE = 12;
    public static final int FC_CURSOR_SCROLLBAR_CENTER_FACTOR_3LINE = 13;
    public static final int FC_STATUSBAR_SCALE_FACTOR = 14;
    public static final int FC_SMALL_STAGE_APP_ICON_OPACITY = 15;
    public static final int FC_SDS_MENU_SCALING = 16;
    public static final int FC_MENU_TOUCH_SWIPE_DISTANCE_FACTOR = 17;
    public static final int FC_COUNT = 18;
    public static final int DIRECTION_DOWN = 1;
    public static final int DIRECTION_UP = 2;
    public static final int FONT_PLAIN = 0;
    public static final int FONT_BOLD = 1;
    public static final int FONT_LIGHT = 2;
    public static final int FONT_BASE = 3;
    public static final int TEXT_EXPORT_NO_DESIRED_VALUE = -1;
    public static final int TEXT_EXPORT_MAX_MENU_ITEM_WIDTH = 0;
    public static final int TEXT_EXPORT_CURSOR_BAR_WIDTH = 1;
    public static final int TEXT_EXPORT_TEXT_GAP = 2;
    public static final int TEXT_EXPORT_INNER_COMBOBOX_GAP = 3;
    public static final int TEXT_EXPORT_FAKE_VALUE = 4;
    public static final int TEXT_EXPORT_ARROW_WIDTH_COMBOBOX = 5;
    public static final int TEXT_EXPORT_CHECKBOX_WIDTH = 6;
    public static final int TEXT_EXPORT_ROTARY_ACTION_WIDTH = 7;
    public static final int TEXT_EXPORT_ARROW_WIDTH_SUBMENU = 8;
    public static final int TEXT_EXPORT_INNER_TEXTFIELD_GAP = 9;
    public static final int TEXT_EXPORT_MAX_DATE_WIDTH = 10;
    public static final int TEXT_EXPORT_SUBMENU_PREVIEW_ARROW_GAP = 11;
    public static final int TEXT_EXPORT_SUBMENU_CHECKBOX_ARROW_GAP = 12;
    public static final int TEXT_EXPORT_SUBMENU_CHECKBOX_PREVIEW_ARROW_WIDTH = 13;
    public static final int TEXT_EXPORT_SUBMENU_CHECKBOX_TEXT_CHECKBOX_GAP = 14;
    public static final int TEXT_EXPORT_SUBMENU_CHECKBOX_WIDTH = 15;
    public static final int TEXT_EXPORT_TEXT_GAP_TEXTFIELD = 16;
    public static final int TEXT_EXPORT_RETURN_ICON_WIDTH = 17;
    public static final int TEXT_EXPORT_BUTTONMANAGER_BUTTON_WIDTH = 18;
    public static final int TEXT_EXPORT_TEXTFIELD_MAX_WIDTH = 19;
    public static final int TEXT_EXPORT_COUNT = 20;
    public static final int IC_COMBOBOX_CURSOR_MIN_WIDTH = 0;
    public static final int IC_COMBOBOX_MAX_WIDTH_NO_SCROLLBAR = 1;
    public static final int IC_COMBOBOX_MAX_WIDTH_WITH_SCROLLBAR = 2;
    public static final int IC_COMBOBOX_MIN_WIDTH_NO_SCROLLBAR = 3;
    public static final int IC_COMBOBOX_LEFT_DISTANCE_GLASSPLATE_TO_CURSOR = 4;
    public static final int IC_COMBOBOX_OPEN_LEFT_DISTANCE_CURSOR_TO_C2ICON = 5;
    public static final int IC_COMBOBOX_OPEN_LEFT_DISTANCE_C2ICON_TO_LABEL = 6;
    public static final int IC_COMBOBOX_OPEN_RIGHT_DISTANCE_LABEL_TO_CURSOR = 7;
    public static final int IC_COMBOBOX_OPEN_RIGHT_DISTANCE_CURSOR_TO_GLASSPLATE = 8;
    public static final int IC_COMBOBOX_CLOSED_LEFT_DISTANCE_GLASSPLATE_TO_CLOSED_ICON = 9;
    public static final int IC_COMBOBOX_CLOSED_RIGHT_DISTANCE_LABEL_TO_GLASSPLATE = 10;
    public static final int IC_COMBOBOX_TOP_DISTANCE_GLASSPLATE_TO_LABEL = 11;
    public static final int IC_INFOLINE_HEIGHT_1_LINE = 12;
    public static final int IC_INFOLINE_HEIGHT_2_LINE = 13;
    public static final int IC_MULTILINE_MENUITEM_GAP_TOP = 14;
    public static final int IC_MULTILINE_MENUITEM_GAP_BOTTOM = 15;
    public static final int IC_MULTILINE_MENUITEM_GAP_LEFT = 16;
    public static final int IC_MULTILINE_MENUITEM_GAP_RIGHT = 17;
    public static final int IC_COMBOBOX_CONTENT_LEFT_OFFSET = 18;
    public static final int IC_COMBOBOX_CONTENT_RIGHT_OFFSET = 19;
    public static final int IC_COMBOBOX_SCROLLBAR_WIDTH = 20;
    public static final int IC_COMBOBOX_SCROLLBAR_MENU_RIGHT_OFFSET = 21;
    public static final int IC_COMBOBOX_SCROLLBAR_MENU_TOP_OFFSET = 22;
    public static final int IC_COMBOBOX_SCROLLBAR_MENU_BOTTOM_OFFSET = 23;
    public static final int IC_COMBOBOX_MIN_DISTANCE_LABEL_COMBOBOX = 24;
    public static final int IC_COMBOBOX_CLOSED_MIN_HEIGHT = 25;
    public static final int IC_COMBOBOX_CLOSED_MAX_HEIGHT = 26;
    public static final int IC_COMBOBOX_INSETS_PREVIEW_VERT = 27;
    public static final int IC_TITLE_SHIFT_Y_FOR_OPTION_SCREENS = 28;
    public static final int IC_PRESET_HEIGHT_TOUCH = 29;
    public static final int IC_PRESET_Y_LONG_TOUCH = 30;
    public static final int IC_PRESET_HEIGHT_LONG_TOUCH = 31;
    public static final int IC_COMBOBOX_ICON_LABEL_GAP = 32;
    public static final int IC_COMBOBOX_ICON_OFFSET_X = 33;
    public static final int IC_COMBOBOX_MENU_CURSOR_DISTANCE = 34;
    public static final int IC_COMBOBOX_CLOSED_ICON_WIDTH = 35;
    public static final int IC_COMBOBOX_MENU_OFFSETX = 36;
    public static final int IC_COMBOBOX_CONTENT_TOP_OFFSET = 37;
    public static final int IC_COMBOBOX_CONTENT_BOTTOM_OFFSET = 38;
    public static final int IC_COMBOBOX_SCROLLBAR_TOP_OFFSET = 39;
    public static final int IC_COMBOBOX_BOTTOM_OFFSET = 40;
    public static final int IC_COMBOBOX_SCROOLBAR_WIDTH = 41;
    public static final int IC_COMBOBOX_CONTENT_SROLLBAR_DISTANCE = 42;
    public static final int IC_COMBOBOX_SCROLLBAR_BACKGROUND_DISTANCE = 43;
    public static final int IC_STATUSBAR_ICON_GAP = 44;
    public static final int IC_STATUSBAR_GAP_SCREEN_BORDER = 45;
    public static final int IC_STATUSBAR_ICON_Y_OFFSET = 46;
    public static final int IC_STATUSBAR_LEFT_GROUP_MIN_WIDTH = 47;
    public static final int IC_STATUSBAR_RIGHT_GROUP_MIN_WIDTH = 48;
    public static final int IC_STATUSBAR_CONTAINER_HEIGHT = 49;
    public static final int IC_PP_SMALL_STAGE_MAX_WIDTH = 50;
    public static final int IC_PP_BIG_STAGE_MIN_WIDTH = 51;
    public static final int IC_CHECKBOX_WIDTH = 52;
    public static final int IC_CHECKBOX_HEIGHT = 53;
    public static final int IC_PRESET_AIT_X = 54;
    public static final int IC_PRESET_AIT_Y = 55;
    public static final int IC_PRESET_AIT_WIDTH = 56;
    public static final int IC_PRESET_AIT_HEIGHT = 57;
    public static final int IC_POS_X_KDK_IN_TUBE = 58;
    public static final int IC_POS_Y_KDK_IN_TUBE = 59;
    public static final int IC_POS_X_KDK_ABOVE_TUBE = 60;
    public static final int IC_POS_Y_KDK_ABOVE_TUBE = 61;
    public static final int IC_TTS_SKIN_HORIZONTAL_SHIFT_SELECTION_DRAWER = 62;
    public static final int IC_INFOLINE_LINE_SPACING = 63;
    public static final int IC_EAL_DEFAULT_MEMORY_SIZE = 64;
    public static final int IC_OPEN_COMBOBOX_TO_PARENT_GLASSPLATE_DISTANCE = 67;
    public static final int IC_SUBMENU_PREVIEW_MIN_WIDTH = 68;
    public static final int IC_SUBMENU_PREVIEW_MAX_WIDTH = 69;
    public static final int IC_SUBMENU_PREVIEW_GAP_BEFORE = 70;
    public static final int IC_OPEN_COMBOBOX_OFFSET_Y = 71;
    public static final int IC_COMBOBOX_LABEL_RIGHT_GAP = 72;
    public static final int IC_STATUSBAR_ICON_GAP_DATA_RATE = 73;
    public static final int IC_SUBMENU_WIDTH_MIN = 74;
    public static final int IC_SUBMENU_WIDTH_MAX = 75;
    public static final int IC_STATUSBAR_LABEL_Y_OFFSET = 76;
    public static final int IC_COMBOBOX_MAX_HEIGHT = 77;
    public static final int IC_STATUSBAR_ICON_GAP_CLOCK = 78;
    public static final int IC_STATUSBAR_Y_OFFSET_SYSTEM_UPDATE = 79;
    public static final int IC_OFFSET_SMALL_STAGE_SCREEN_X = 80;
    public static final int IC_OFFSET_SMALL_STAGE_SCREEN_Y = 81;
    public static final int IC_OFFSET_BIG_STAGE_SCREEN_X = 82;
    public static final int IC_OFFSET_BIG_STAGE_SCREEN_Y = 83;
    public static final int IC_OFFSET_SMALL_STAGE_POPUP_X = 84;
    public static final int IC_OFFSET_SMALL_STAGE_POPUP_Y = 85;
    public static final int IC_OFFSET_BIG_STAGE_POPUP_X = 86;
    public static final int IC_OFFSET_BIG_STAGE_POPUP_Y = 87;
    public static final int IC_OFFSET_SMALL_STAGE_SELECTION_DRAWER_X = 88;
    public static final int IC_OFFSET_SMALL_STAGE_SELECTION_DRAWER_Y = 89;
    public static final int IC_OFFSET_BIG_STAGE_SELECTION_DRAWER_X = 90;
    public static final int IC_OFFSET_BIG_STAGE_SELECTION_DRAWER_Y = 91;
    public static final int IC_STATUSBAR_TTS_X_OFFSET = 92;
    public static final int IC_STATUSBAR_TTS_Y_OFFSET = 93;
    public static final int IC_SPELLER_OFFSET_INFOLINE_TEXT_TOP = 94;
    public static final int IC_SCREENSHOT_TYPE_OFFSET_Y = 95;
    public static final int IC_STATUSBAR_ICON_ROAMING_Y_OFFSET = 96;
    public static final int IC_OFFSET_SMALL_STAGE_SELECTION_DRAWER_CLOSED_X = 97;
    public static final int IC_OFFSET_SMALL_STAGE_SELECTION_DRAWER_CLOSED_Y = 98;
    public static final int IC_OFFSET_SMALL_STAGE_OPTION_DRAWER_CLOSED_X = 99;
    public static final int IC_OFFSET_SMALL_STAGE_OPTION_DRAWER_CLOSED_Y = 100;
    public static final int IC_OFFSET_BIG_STAGE_SELECTION_DRAWER_CLOSED_X = 101;
    public static final int IC_OFFSET_BIG_STAGE_SELECTION_DRAWER_CLOSED_Y = 102;
    public static final int IC_OFFSET_BIG_STAGE_OPTION_DRAWER_CLOSED_X = 103;
    public static final int IC_OFFSET_BIG_STAGE_OPTION_DRAWER_CLOSED_Y = 104;
    public static final int IC_MATRIX_COLUMNS_AMOUNT = 105;
    public static final int IC_USER_HINT_SEPERATOR_POSITION_Y = 106;
    public static final int IC_KDK_IMAGE_ID = 107;
    public static final int IC_OFFSET_NAVI_BACKGROUND_MAP_X = 108;
    public static final int IC_OFFSET_NAVI_BACKGROUND_MAP_Y = 109;
    public static final int IC_STATUSBAR_Y_OFFSET_DATA_STATUS = 110;
    public static final int IC_GRID_DEFAULT_TRANSLATION = 111;
    public static final int IC_GRID_GYRO_TRANSLATION = 112;
    public static final int IC_CONVERSIONLINE_COLUMNS_AMOUNT = 113;
    public static final int IC_MAP_WIDTH = 114;
    public static final int IC_MAP_HEIGHT = 115;
    public static final int IC_INPUTFIELD_SUGGESTION_OFFSET = 116;
    public static final int IC_SPELLER_SUGGESTION_OFFSET = 117;
    public static final int IC_CROP_X_KDK_BIG_STAGE = 118;
    public static final int IC_CROP_Y_KDK_BIG_STAGE = 119;
    public static final int IC_CROP_WIDTH_KDK_BIG_STAGE = 120;
    public static final int IC_CROP_HEIGHT_KDK_BIG_STAGE = 121;
    public static final int IC_CROP_X_KDK_SMALL_STAGE = 122;
    public static final int IC_CROP_Y_KDK_SMALL_STAGE = 123;
    public static final int IC_CROP_WIDTH_KDK_SMALL_STAGE = 124;
    public static final int IC_CROP_HEIGHT_KDK_SMALL_STAGE = 125;
    public static final int IC_RADIOBUTTON_WIDTH = 126;
    public static final int IC_RADIOBUTTON_HEIGHT = 127;
    public static final int IC_ROTARY_PREVIEW_WIDTH = 128;
    public static final int IC_ROTARY_PREVIEW_HEIGHT = 129;
    public static final int IC_FORMFIELD_INPUT_DROP_SHADOW_WIDTH = 130;
    public static final int IC_STATUSBAR_TTS_X_OFFSET_RTL = 131;
    public static final int IC_COUNT = 132;
    public static final int INDEX_ICON = 0;
    public static final int INDEX_DECORATOR = 1;

    public int[] getStaticBitmapParameters(int var1);

    public int getRowHeight();

    public int getRowOverall();

    public int getRowHeightToolTip();

    public int getRowOverallToolTip();

    public int getMenuLineWidth();

    public int getDistance(int var1);

    public int getDepth(int var1);

    public int getTextExportWidth(int var1);

    public float getFloatConstant(int var1);

    public int getIntegerConstant(int var1);

    public int[] getTextPattern(int var1);

    public int getMappedFontSize(int var1, int var2);

    public int getRotationalDirection(int var1);

    public String getSplashscreenPath();

    public String getFontName(int var1);

    public int[][] getTimeZoneImagePositions();

    public int[] getInstructionTextLayoutParams();

    public int[][] getMainWizardIconDecoratorMapping();

    public int[] getMainWizardTextOffset();

    public int[] getDisplayablePosition(int var1);

    public int getUserHintLabelOffset();
}

