/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carhybrid;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDVIEWOPTIONS = 1;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDCHARGE = 2;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYFLOWSTATE = 3;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDRECOVEREDENERGY = 4;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYFLOW = 5;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLVIEWOPTIONS = 6;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPLUG = 7;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLCHARGESTATE = 8;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLCLIMATESTATE = 9;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMERSTATE = 10;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER1 = 11;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER2 = 12;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER3 = 13;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTIMER4 = 14;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTOTALNUMBEROFPROFILES = 15;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPROFILESLISTUPDATEINFO = 16;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLTOTALNUMBEROFPOWERPROVIDER = 17;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPOWERPROVIDERLISTUPDATEINFO = 18;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDTARGETRANGE = 19;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYASSISTCONTROL = 20;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDENERGYASSISTSTATE = 21;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPASTERRORREASON = 22;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLPLUGDISPLAYSTATE = 23;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLREMAININGCHARGETIME = 24;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_BATTERYCONTROLLOWESTMAXCURRENT = 25;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDINHIBITREASON = 26;
    public static final int ATTRIBUTE_ID_DSICARHYBRID_HYBRIDACTIVEPEDAL = 27;
}

