/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.careco;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARECO_BCMEVIEWOPTIONS = 1;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMELISTUPDATEINFO = 2;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMPTION = 3;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMELIVETIP = 4;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTCONSUMPTIONUPDATEINFO = 34;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMEENERGYFLOWCOMFORT = 35;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMERANGEGAINTOTAL = 36;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTRANGEUPDATEINFO = 37;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECURRENTRANGE = 38;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTTOTALNUMBEROFELEMENTS = 39;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTCONSUMPTIONTOTALNUMBEROFELEMENTS = 40;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECONSUMERLISTRANGETOTALNUMBEROFELEMENTS = 41;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPPROHIBITREASONLISTUPDATEINFO = 5;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTREASONLISTUPDATEINFO = 6;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTPROHIBITREASONLISTUPDATEINFO = 7;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPSTATE = 8;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPPROHIBITREASONLISTTOTALNUMBEROFELEMENTS = 9;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTREASONLISTTOTALNUMBEROFELEMENTS = 10;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPRESTARTPROHIBITREASONLISTTOTALNUMBEROFELEMENTS = 11;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPVIEWOPTIONS = 12;
    public static final int ATTRIBUTE_ID_DSICARECO_STARTSTOPCOLLECTEDREASONS = 49;
    public static final int ATTRIBUTE_ID_DSICARECO_RDVIEWOPTIONS = 15;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONMOTORWAY1 = 16;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONMOTORWAY2 = 17;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONHIGHWAY1 = 18;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONHIGHWAY2 = 19;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONCOUNTRYROAD1 = 20;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONCOUNTRYROAD2 = 21;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONDISTRICTROAD1 = 22;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONDISTRICTROAD2 = 23;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONLOCALROAD1 = 24;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONLOCALROAD2 = 25;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONRURALROAD1 = 26;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONRURALROAD2 = 27;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONUNCLASSIFIEDROAD1 = 28;
    public static final int ATTRIBUTE_ID_DSICARECO_RDCONSUMPTIONUNCLASSIFIEDROAD2 = 29;
    public static final int ATTRIBUTE_ID_DSICARECO_RDMAXRANGE1 = 30;
    public static final int ATTRIBUTE_ID_DSICARECO_RDMAXRANGE2 = 31;
    public static final int ATTRIBUTE_ID_DSICARECO_RDRESIDUALENERGY1 = 32;
    public static final int ATTRIBUTE_ID_DSICARECO_RDRESIDUALENERGY2 = 33;
    public static final int ATTRIBUTE_ID_DSICARECO_EAVIEWOPTIONS = 42;
    public static final int ATTRIBUTE_ID_DSICARECO_EASYSTEM = 43;
    public static final int ATTRIBUTE_ID_DSICARECO_EAPEDALJERK = 44;
    public static final int ATTRIBUTE_ID_DSICARECO_EAFREEWHEELING = 47;
    public static final int ATTRIBUTE_ID_DSICARECO_EASTARTSTOP = 48;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECURRENTRANGESOC = 45;
    public static final int ATTRIBUTE_ID_DSICARECO_BCMECATALOGUERANGE = 46;
}

