/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.navi.app.map.utils;

public class ConstantUtils {
    public static String[] CALCULATIONSTATE = new String[]{"0:not_calculated", "1:calculating", "2:preliminary_calculated", "3:calculated", "4:calculation_failed", "5:rgactive"};
    public static String[] ROUTECALCULATIONSTATE = new String[]{"0:idle", "1:calculating", "2:ready", "3:rubberbandready"};
    public static String[] MAPVIEWERRUNLEVEL = new String[]{"0:SUSPENSION_IN_PROGRESS", "1:SUSPENDED", "2:WAKEUP_IN_PROGRESS", "3:-", "4:AWAKE", "5:ERROR_SUSPENSION_NOT_POSSIBLE", "6:ERROR_WAKEUP_NOT_POSSIBLE"};
    public static String[] MAPLAYER = new String[]{"0:SDARS_RADAR", "1:SDARS_WEATHER", "2:SDARS_ISOBARE"};
    public static String[] MAPMODE = new String[]{"0:ROUTEMAP", "1:POSITIONMAP", "2:FREEMAP", "3:CROSSHAIRMAP", "4:POIMAP", "5:ROUTESCROLLMAP", "6:ALTERNATIVEROUTEMAP", "7:RCCIMAP", "8:ROUTEBROWSERMAP", "9:DESTINATIONMAP", "10:OVERVIEWMAP", "11:ALTERNATIVEROUTEMAP_DIFFERENTCOLORS", "12:ROUTEBRIEFING", "13:COUNTRY_OVERVIEW", "14:MOBILITY_HORIZON", "15:MAPOVERLAY", "255:INVALID_MAPMODE"};
    public static String[] LOCATION = new String[]{"0:CAR", "1:DESTINATION", "2:STOPOVER", "3:INVALID_LOCATION"};
    public static String[] MAPVIEWTYPE = new String[]{"0:VIEW2D", "1:BIRDVIEW", "3:VIEW3D", "255:INVALID_MAPVIEWTYPE"};
    public static String[] POSITIONINFOTYPE = new String[]{"0:LOCATION", "1:POI", "2:POI_3D", "3:POI_CONTAINER", "4:TMC_MESSAGE", "5:PERSONAL_DEST", "6:INVALID_POSITION", "7:AREA", "8:XT_REPRESENTATION", "9:PICTURE_DESTINATION", "10:PICTURE_DESTINATION_STACK", "11:POI_BY_UID", "12:POI_STACK_BY_UID", "13:ROUTESEGMENT", "14:WEATHERINFORMATION", "15:CURRENT_CAR_POSITION", "16:LANDMARK", "17:SDARS_WEATHERSTATION", "18:SDARS_SKIRESORT", "19:SDARS_STORMINFO", "255:INVALID_POSITIONINFOTYPE"};
    public static String[] MAPTYPE = new String[]{"0:CITYMAPREAL", "1:CITYMAPDRAWING", "2:TERRAINMAP", "3:IMAGEMAP", "255:INVALID_MAPTYPE"};
    public static String[] ROUTETYPE = new String[]{"0:NOTYPE", "1:CURRENT", "2:BLOCKED", "3:PLANNED", "4:ALTERNATIVE", "5:TRAVELLED", "6:TRAIL", "255:INVALID_ROUTETYPE"};
    public static String[] COMMAND = new String[]{"0:ADD", "1:CLEAR", "2:REMOVE", "3:REPLACE", "255:INVALID_COMMAND"};
    public static String[] STARTPOS = new String[]{"0:START_AT_DESTINATION", "1:START_AT_CARPOSITION", "255:INVALID_STARTPOS"};
    public static String[] SCROLLRAMP = new String[]{"0:RAMP_1", "1:RAMP_2", "2:RAMP_3", "3:RAMP_4", "4:ABSOLUTE_PIXELS", "255:INVALID_SCROLLRAMP"};
    public static String[] METRICSYSTEM = new String[]{"0:RESERVED", "1:DEFAULT", "2:KILOMETERS_METERS", "3:IMPERIAL_GB_MILES_YARDS", "4:IMPERIAL_US_MILES_FEET"};
    public static String[] CITYMODELMODE = new String[]{"0:OFF", "1:STANDARD", "2:ENHANCED"};
    public static String[] RESULTCODE = new String[]{"0:OK", "1:FAIL", "2:UNSUPPORTED"};
    public static String[] BRANDICONSTYLE = new String[]{"0:ACTUALBRANDICON", "1:GENERIC"};
    public static String[] GUIDANCESYMBOL = new String[]{"0:NONE", "1:ARROW"};
    public static String[] FRAMERATEMODE = new String[]{"0:IMAGE_FROZEN", "1:NORMAL_FRAMERATE", "2:BACKGROUND_RENDERING", "3:BOOST_FRAMERATE", "4:THROTTELED_FRAMERATE"};
    public static String[] ROUTECOLORINGPOLICY = new String[]{"0:COLOR_BY_ROUTETOPTION", "1:COLOR_BY_ROUTEALTERNATIVE"};
    public static String[] CROSSHAIRSCOLOR = new String[]{"1:BLUE", "2:GREEN"};
    public static String[] VIEWPORTBORDER = new String[]{"1:NONE", "2:STYLE1", "3:STYLE2"};
    public static String[] MAPVIEWERSUSPENSIONSUPPORTED = new String[]{"0:NO", "1:YES"};
    public static String[] MOBILITYHORIZONZOOMMODE = new String[]{"0:HORIZON", "1:HORIZON_CARPOS", "2:HORIZON_ROUTE"};
    public static String[] DRAGROUTEMARKERSTYLE = new String[]{"0:NOMARKER", "1:SMALLMARKER", "2:BIGMARKER"};
    public static String[] ROUTEHIGHLIGHTSTYLE = new String[]{"0:NONE", "1:SIMPLE", "2:BLOCKPREVIEW"};
    public static String[] MAPSTYLETYPE = new String[]{"0:STANDARD", "1:SATELLITE", "2:TRAFFIC"};
    public static String[] MAPOVERLAYTYPE = new String[]{"0:UNDEFINED", "1:WEATHERRADAR"};
    public static String[] TEMPERATURESCALE = new String[]{"0:UNDEFINED", "1:CELSIUS", "2:FAHRENHEIT"};
    public static String[] MANEUVERELEMENTELEMENT = new String[]{"0:NOSYMBOL", "1:NOINFO", "2:DIRECTIONTODESTINATION", "3:ARRIVED", "4:NEARDESTINATION", "5:ARRIVEDDESTINATIONOFFROAD", "6:OFFROAD", "7:OFFMAP", "8:NOROUTE", "9:CALCROUTE", "10:RECALCROUTE", "11:FOLLOWSTREET", "12:CHANGELANE", "13:TURN", "14:TURNONMAINROAD", "15:EXITRIGHT", "16:EXITLEFT", "17:SERVICEROADRIGHT", "18:SERVICEROADLEFT", "19:FORK2", "20:FORK3", "21:ROUNDABOUTTRSRIGHT", "22:ROUNDABOUTTRSLEFT", "23:SQUARETRSRIGHT", "24:SQUARETRSLEFT", "25:UTURN", "26:EXITROUNDABOUTTRSRIGHT", "27:EXITROUNDABOUTTRSLEFT", "28:PREPARETURN", "29:PREPAREROUNDABOUT", "30:PREPARESQUARE", "31:PREPAREUTURN", "32:EXITRIGHTRAMPUP", "33:EXITRIGHTRAMPDOWN", "34:MICHIGANTURN", "35:DOUBLETURN", "36:EXITLEFTRAMPUP", "37:EXITLEFTRAMPDOWN", "38:DIRECTIONTOWAYPOINT"};
}

