/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.info.hmi.evohighscale;

import de.audi.atip.hmi.model.menu.focus.FocusAdvice;
import de.audi.atip.hmi.view.HMIView;
import de.audi.atip.hmi.view.Screen;
import de.audi.tghu.info.hmi.evohighscale.InfoScreenBag1$1;
import de.audi.tghu.info.hmi.evohighscale.InfoScreenBag1$2;
import de.audi.tghu.info.hmi.evohighscale.InfoScreenBag1$3;
import de.audi.tghu.info.hmi.evohighscale.InfoScreenFactory;
import de.esolutions.hmi.widgets.audi.base.AbstractWidget;
import de.esolutions.hmi.widgets.audi.base.widgets.AbstractWidgetController;
import de.esolutions.hmi.widgets.audi.base.widgets.IdleTimerController;
import de.esolutions.hmi.widgets.audi.base.widgets.VirtualButton;
import de.esolutions.hmi.widgets.audi.evo.InstructionTextContoller;
import de.esolutions.hmi.widgets.audi.evo.ScreenWidgetEVO;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.AxisConstraints;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayout;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayoutHints;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.CompositeRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ContainerRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.FocusCursorRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.GlassplateRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconLabelController;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconLabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MirrorRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MirroredContainerController;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MultiLineLabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ScreenRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ScrollbarRendererKanziHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.SharedTextureRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.TitleBarRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.menu.MenuRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.ContainerController;
import de.esolutions.hmi.widgets.audi.evo.widgets.FocusCursorController;
import de.esolutions.hmi.widgets.audi.evo.widgets.GlassplateController;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.ProgressIconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.ScrollbarController;
import de.esolutions.hmi.widgets.audi.evo.widgets.SharedTextureController;
import de.esolutions.hmi.widgets.audi.evo.widgets.SmallStageApplicationIconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.StatusBarStubController;
import de.esolutions.hmi.widgets.audi.evo.widgets.TitleBarWidget;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.BaseListModelAccess;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.DefaultTiledListModelAccess;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.InfoLineRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.ListController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemColumnsConstraints;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.SeparatingLineController;

public class InfoScreenBag1 {
    public static Screen mAPTRAFFICREFTEMPLATE(InfoScreenFactory infoScreenFactory, int n) {
        AbstractWidgetController abstractWidgetController = infoScreenFactory.getRefWidget(n, 0, infoScreenFactory);
        SmallStageApplicationIconController smallStageApplicationIconController = new SmallStageApplicationIconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(smallStageApplicationIconController);
        smallStageApplicationIconController.setRenderer(iconRendererHigh);
        smallStageApplicationIconController.setBitmaps(new int[]{127, 127, 127, 127, 127, 127, 127, 127, 127, 127});
        smallStageApplicationIconController.setModelID(138);
        smallStageApplicationIconController.setBounds(646, 325, 100, 100);
        smallStageApplicationIconController.setCoordinateSets(new int[]{2, 646, 325, 100, 100, 666, 240, 100, 100});
        iconRendererHigh.setScaleFactor(2.0f, 2.0f);
        AbstractWidgetController abstractWidgetController2 = infoScreenFactory.getRefWidget(n, 1, infoScreenFactory);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(580978432);
        screenWidgetEVO.setScreenFactory(infoScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(infoScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(abstractWidgetController);
        screenWidgetEVO.add(smallStageApplicationIconController);
        screenWidgetEVO.add(abstractWidgetController2, 15);
        screenWidgetEVO.setViews(new int[]{138}, new HMIView[][]{{smallStageApplicationIconController, infoScreenFactory.refWidgets[n][2]}});
        return screenWidgetEVO;
    }

    public static Screen mAPTRAFFICDETAILS(InfoScreenFactory infoScreenFactory, int n) {
        AbstractWidgetController abstractWidgetController = infoScreenFactory.getRefWidget(n, 0, infoScreenFactory);
        VirtualButton virtualButton = new VirtualButton();
        virtualButton.setModelID(-794753280);
        virtualButton.setEvent(580978432);
        virtualButton.setBounds(0, 0, 100, 100);
        virtualButton.setEventConfiguration(1);
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        ListController listController = new ListController();
        listController.setModelID(-811530496);
        listController.setEvent(-1608907264);
        listController.getLayoutCalculator().setCacheItemHeights(false);
        listController.setBounds(0, 0, 0, 0);
        listController.setFocusableColumn(11);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setPropertyColumn(12);
        listController.setRecordSetColumn(0);
        listController.setWidgetID(10);
        listController.setDataAccess(new BaseListModelAccess());
        listController.setItemFactory(new InfoScreenBag1$1());
        SeparatingLineController separatingLineController = new SeparatingLineController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(separatingLineController);
        separatingLineController.setRenderer(iconRendererHigh);
        separatingLineController.setBitmaps(new int[]{451});
        separatingLineController.setBounds(0, 0, 100, 100);
        separatingLineController.setColorIndices(new int[]{1, 2, 2, 4});
        separatingLineController.setPredecessor(10);
        separatingLineController.setProcessStateChange(2);
        separatingLineController.setSuccessor(20);
        iconRendererHigh.setScaleMode(1);
        MenuItemController menuItemController = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(menuItemController);
        menuItemController.setRenderer(compositeRendererHigh);
        menuItemController.setModelID(-794753280);
        menuItemController.setEvent(580978432);
        menuItemController.setLabelId(1218512640);
        menuItemController.setGlassplateInsetsBottom(6);
        menuItemController.setGlassplateInsetsTop(7);
        menuItemController.setInternalID(580978432);
        menuItemController.setKeyHandler(0);
        menuItemController.setType(2);
        menuItemController.setWidgetID(20);
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(infoScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(1403062016);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getInitialization().setInitialFocusAdvice(FocusAdvice.VIEWPORT_FIRST_POSITION);
        menuController.getInitialization().setInitialFocusWidgetIDs(new int[]{10});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(listController);
        menuController.add(separatingLineController, 7);
        menuController.add(menuItemController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(virtualButton);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh2 = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh2);
        iconController.setBitmaps(new int[]{254});
        iconController.setBounds(501, 77, 277, 324);
        iconController.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController.setR8Distinction(true);
        SharedTextureController sharedTextureController = new SharedTextureController();
        SharedTextureRendererHigh sharedTextureRendererHigh = new SharedTextureRendererHigh(sharedTextureController);
        sharedTextureController.setRenderer(sharedTextureRendererHigh);
        sharedTextureController.setBounds(517, 80, 260, 318);
        sharedTextureController.setCaptureRect(0, 0, 260, 318);
        sharedTextureController.setCoordinateSets(new int[]{1, 517, 80, 260, 318, 517, 80, 260, 318});
        sharedTextureController.setDisplayableID(19);
        sharedTextureController.setR8Distinction(true);
        sharedTextureController.setUpdateInterval(500);
        sharedTextureController.setUpdateMode(2);
        ProgressIconController progressIconController = new ProgressIconController();
        CompositeRendererHigh compositeRendererHigh2 = new CompositeRendererHigh(progressIconController);
        progressIconController.setRenderer(compositeRendererHigh2);
        progressIconController.setBitmaps(new int[]{224});
        progressIconController.setModelID(162);
        progressIconController.setBounds(699, 360, 0, 0);
        progressIconController.setCoordinateSets(new int[]{1, 699, 360, 0, 0, 699, 360, 0, 0});
        progressIconController.setProcessStateChange(2);
        progressIconController.setProgressBarXOffset(0);
        IconController iconController2 = new IconController();
        IconRendererHigh iconRendererHigh3 = new IconRendererHigh(iconController2);
        iconController2.setRenderer(iconRendererHigh3);
        iconController2.setBitmaps(new int[]{235});
        iconController2.setBounds(694, 360, 0, 0);
        iconController2.setCoordinateSets(new int[]{1, 694, 360, 0, 0, 694, 360, 0, 0});
        iconController2.setProcessStateChange(2);
        IconLabelController iconLabelController = new IconLabelController();
        IconLabelRendererHigh iconLabelRendererHigh = new IconLabelRendererHigh(iconLabelController);
        iconLabelController.setRenderer(iconLabelRendererHigh);
        iconLabelController.setModelID(1663370752);
        iconLabelController.setBounds(675, 355, 100, 40);
        IconController iconController3 = new IconController();
        IconRendererHigh iconRendererHigh4 = new IconRendererHigh(iconController3);
        iconController3.setRenderer(iconRendererHigh4);
        iconController3.setBitmaps(new int[]{127});
        iconController3.setBounds(728, 77, 277, 324);
        iconController3.setCoordinateSets(new int[]{1, 728, 77, 277, 324, 728, 77, 277, 324});
        iconController3.setR8Distinction(true);
        IconController iconController4 = new IconController();
        IconRendererHigh iconRendererHigh5 = new IconRendererHigh(iconController4);
        iconController4.setRenderer(iconRendererHigh5);
        iconController4.setBitmaps(new int[]{954});
        iconController4.setBounds(501, 77, 277, 324);
        iconController4.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController4.setProcessStateChange(2);
        IconController iconController5 = new IconController();
        IconRendererHigh iconRendererHigh6 = new IconRendererHigh(iconController5);
        iconController5.setRenderer(iconRendererHigh6);
        iconController5.setBitmaps(new int[]{955});
        iconController5.setBounds(516, 77, 277, 324);
        iconController5.setColorIndices(new int[]{1, 2, 4, 0});
        iconController5.setCoordinateSets(new int[]{1, 516, 77, 277, 324, 516, 77, 277, 324});
        iconController5.setProcessStateChange(2);
        MirroredContainerController mirroredContainerController = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh = new MirrorRendererHigh(mirroredContainerController);
        mirroredContainerController.setRenderer(mirrorRendererHigh);
        mirroredContainerController.setBounds(0, 0, 468, 480);
        mirroredContainerController.setMirrorEnabled(false);
        mirroredContainerController.add(iconController);
        mirroredContainerController.add(sharedTextureController);
        mirroredContainerController.add(progressIconController);
        mirroredContainerController.add(iconController2);
        mirroredContainerController.add(iconLabelController);
        mirroredContainerController.add(iconController3);
        mirroredContainerController.add(iconController4);
        mirroredContainerController.add(iconController5);
        MirroredContainerController mirroredContainerController2 = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh2 = new MirrorRendererHigh(mirroredContainerController2);
        mirroredContainerController2.setRenderer(mirrorRendererHigh2);
        mirroredContainerController2.setBounds(0, 0, 800, 480);
        mirroredContainerController2.setMirrorEnabled(false);
        mirroredContainerController2.add(mirroredContainerController);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 100, 100);
        containerController2.setColorIndices(new int[]{1, 0, 4, 0});
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController2.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController2.add(mirroredContainerController2);
        IconController iconController6 = new IconController();
        IconRendererHigh iconRendererHigh7 = new IconRendererHigh(iconController6);
        iconController6.setRenderer(iconRendererHigh7);
        iconController6.setBitmaps(new int[]{127});
        iconController6.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(infoScreenFactory.getFonts(2, n));
        labelController.setTextIds(new int[]{614532864});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh2);
        labelRendererHigh2.setFonts(infoScreenFactory.getFonts(2, n));
        labelController2.setTextIds(new int[]{1486948096});
        labelController2.setReplacementModelIds(new int[]{-392100096, -408877312});
        labelController2.setBounds(0, 0, 0, 30);
        labelController2.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController3 = new LabelController();
        LabelRendererHigh labelRendererHigh3 = new LabelRendererHigh(labelController3);
        labelController3.setRenderer(labelRendererHigh3);
        labelController3.setTextIds(new int[]{631310080});
        labelController3.setBounds(0, 0, 0, 30);
        labelController3.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController6);
        titleBarWidget.addTitle(labelController);
        titleBarWidget.addTitle(labelController2);
        titleBarWidget.addBreadcrumb(labelController3);
        ContainerController containerController3 = new ContainerController();
        ContainerRendererHigh containerRendererHigh3 = new ContainerRendererHigh(containerController3);
        containerController3.setRenderer(containerRendererHigh3);
        containerController3.setBounds(0, 0, 800, 0);
        containerController3.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController3.setOpacitySet(1.0f, -842216386);
        containerController3.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        AbstractWidgetController abstractWidgetController2 = infoScreenFactory.getRefWidget(n, 1, infoScreenFactory);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(597755648);
        screenWidgetEVO.setScreenFactory(infoScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(infoScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(abstractWidgetController);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 7);
        screenWidgetEVO.add(containerController3, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.add(abstractWidgetController2, 15);
        screenWidgetEVO.setViews(new int[]{138, 162, 1663370752, -811530496, -794753280}, new HMIView[][]{{statusBarStubController, infoScreenFactory.refWidgets[n][2]}, {progressIconController}, {iconLabelController}, {listController}, {virtualButton, menuItemController}});
        screenWidgetEVO.setModelIDs(new int[]{-811530496, -794753280});
        screenWidgetEVO.setEventIDs(new int[]{-1608907264, 580978432});
        screenWidgetEVO.setConditionWidgets(new int[]{93, 162, 361, 376, 522, 556, 5624, 958137856, 1780221440, -1591867904, 656475648, -794753280}, new AbstractWidget[][]{{iconController2}, {progressIconController, iconController2, iconLabelController}, {virtualButton, menuItemController, labelController3}, {labelController}, {mirroredContainerController2, mirroredContainerController}, {iconController, sharedTextureController, progressIconController, iconController2, iconLabelController, iconController3, iconController4, iconController5}, {iconController2, iconLabelController}, {sharedTextureController}, {progressIconController, iconController2, iconLabelController}, {iconController, sharedTextureController, progressIconController, iconController2, iconLabelController, iconController3, iconController4, iconController5}, {virtualButton, menuItemController, labelController3}, {menuItemController}});
        screenWidgetEVO.setReplacementWidgets(new int[]{-408877312, -392100096}, new HMIView[][]{{labelController2}, {labelController2}});
        return screenWidgetEVO;
    }

    public static Screen mAPTRAFFICDETAILSOVERVIEW(InfoScreenFactory infoScreenFactory, int n) {
        AbstractWidgetController abstractWidgetController = infoScreenFactory.getRefWidget(n, 0, infoScreenFactory);
        VirtualButton virtualButton = new VirtualButton();
        virtualButton.setModelID(-694089984);
        virtualButton.setBounds(0, 0, 100, 100);
        virtualButton.setEventConfiguration(2);
        virtualButton.setPreferredHeight(1);
        virtualButton.setPreferredWidth(1);
        virtualButton.setRotationalDirectionClockwise(false);
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        ScrollbarController scrollbarController2 = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh2 = new ScrollbarRendererKanziHigh(scrollbarController2);
        scrollbarController2.setRenderer(scrollbarRendererKanziHigh2);
        scrollbarController2.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{597755648});
        iconController.setPreferredHeight(1);
        iconRendererHigh.setAlignment(1, 5);
        LabelController labelController = new LabelController();
        MultiLineLabelRendererHigh multiLineLabelRendererHigh = new MultiLineLabelRendererHigh(labelController);
        labelController.setRenderer(multiLineLabelRendererHigh);
        labelController.setModelID(-1331624192);
        labelController.setTextIds(new int[]{1151403776, 1168180992, 1184958208, 1201735424});
        LabelController labelController2 = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController2);
        labelController2.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(infoScreenFactory.getFonts(1, n));
        labelController2.setModelID(-1331624192);
        labelController2.setTextIds(new int[]{1352730368, 1352730368, 1268844288, 1285621504});
        labelController2.setColorIndices(new int[]{1, 7, 4, 2});
        LabelController labelController3 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController3);
        labelController3.setRenderer(labelRendererHigh2);
        labelRendererHigh2.setFonts(infoScreenFactory.getFonts(1, n));
        labelController3.setModelID(-1969158400);
        labelController3.setColorIndices(new int[]{1, 7, 4, 2});
        MenuItemController menuItemController = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(menuItemController);
        menuItemController.setRenderer(compositeRendererHigh);
        menuItemController.setModelID(-1314846976);
        menuItemController.setEvent(614532864);
        menuItemController.setGlassplateInsetsBottom(6);
        menuItemController.setGlassplateInsetsTop(7);
        menuItemController.setInternalID(547424000);
        menuItemController.setType(16);
        menuItemController.setWidgetID(10);
        GridLayout gridLayout = new GridLayout();
        MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
        menuItemColumnsConstraints.gaps = new int[]{0, 15, 0};
        menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f};
        menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f};
        menuItemColumnsConstraints.hidemode = new int[]{2, 0};
        gridLayout.setColumnConstraints(menuItemColumnsConstraints);
        AxisConstraints axisConstraints = new AxisConstraints(2);
        axisConstraints.alignment = new int[]{5, 9};
        axisConstraints.hidemode = new int[]{0, 2};
        gridLayout.setRowConstraints(axisConstraints);
        GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
        GridLayout gridLayout2 = new GridLayout();
        MenuItemColumnsConstraints menuItemColumnsConstraints2 = new MenuItemColumnsConstraints(1);
        gridLayout2.setColumnConstraints(menuItemColumnsConstraints2);
        AxisConstraints axisConstraints2 = new AxisConstraints(1);
        gridLayout2.setRowConstraints(axisConstraints2);
        GridLayoutHints gridLayoutHints2 = new GridLayoutHints(0, 0);
        gridLayout2.setCellConstraints(new GridLayoutHints[]{gridLayoutHints2}, new Object[]{labelController});
        GridLayoutHints gridLayoutHints3 = new GridLayoutHints(1, 0);
        GridLayout gridLayout3 = new GridLayout();
        MenuItemColumnsConstraints menuItemColumnsConstraints3 = new MenuItemColumnsConstraints(2);
        menuItemColumnsConstraints3.gaps = new int[]{0, 12, 0};
        gridLayout3.setColumnConstraints(menuItemColumnsConstraints3);
        AxisConstraints axisConstraints3 = new AxisConstraints(1);
        axisConstraints3.hidemode = new int[]{2};
        gridLayout3.setRowConstraints(axisConstraints3);
        GridLayoutHints gridLayoutHints4 = new GridLayoutHints(0, 0);
        GridLayoutHints gridLayoutHints5 = new GridLayoutHints(1, 0);
        gridLayout3.setCellConstraints(new GridLayoutHints[]{gridLayoutHints4, gridLayoutHints5}, new Object[]{labelController2, labelController3});
        GridLayoutHints gridLayoutHints6 = new GridLayoutHints(1, 1);
        gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints3, gridLayoutHints6}, new Object[]{iconController, gridLayout2, gridLayout3});
        menuItemController.setLayoutManager(gridLayout);
        menuItemController.add(iconController);
        menuItemController.add(labelController);
        menuItemController.add(labelController2);
        menuItemController.add(labelController3);
        SeparatingLineController separatingLineController = new SeparatingLineController();
        IconRendererHigh iconRendererHigh2 = new IconRendererHigh(separatingLineController);
        separatingLineController.setRenderer(iconRendererHigh2);
        separatingLineController.setBitmaps(new int[]{451});
        separatingLineController.setBounds(0, 0, 100, 100);
        separatingLineController.setColorIndices(new int[]{1, 2, 2, 4});
        separatingLineController.setPredecessor(10);
        separatingLineController.setProcessStateChange(2);
        separatingLineController.setSuccessor(20);
        ListController listController = new ListController();
        listController.setBitmaps(new int[]{451});
        listController.setModelID(-1583282432);
        listController.setEvent(547424000);
        listController.setBounds(0, 0, 0, 0);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setPropertyColumn(11);
        listController.setRecordSetColumn(0);
        listController.setSeparatingLineColumn(10);
        listController.setWidgetID(20);
        listController.setDataAccess(new DefaultTiledListModelAccess());
        listController.setItemFactory(new InfoScreenBag1$2(infoScreenFactory, n));
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(infoScreenFactory.getFonts(1, n));
        menuController.setModelID(-1381955840);
        menuController.setDefaultDisabledInfolineTextId(1436616448);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.setHideOverlayDecoratorDuringScrolling(false);
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(scrollbarController2, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(menuItemController);
        menuController.add(separatingLineController, 7);
        menuController.add(listController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(virtualButton);
        containerController.add(menuController);
        IconController iconController2 = new IconController();
        IconRendererHigh iconRendererHigh3 = new IconRendererHigh(iconController2);
        iconController2.setRenderer(iconRendererHigh3);
        iconController2.setBitmaps(new int[]{254});
        iconController2.setBounds(501, 77, 277, 324);
        iconController2.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController2.setR8Distinction(true);
        SharedTextureController sharedTextureController = new SharedTextureController();
        SharedTextureRendererHigh sharedTextureRendererHigh = new SharedTextureRendererHigh(sharedTextureController);
        sharedTextureController.setRenderer(sharedTextureRendererHigh);
        sharedTextureController.setBounds(517, 80, 260, 318);
        sharedTextureController.setCaptureRect(0, 0, 260, 318);
        sharedTextureController.setCoordinateSets(new int[]{1, 517, 80, 260, 318, 517, 80, 260, 318});
        sharedTextureController.setDisplayableID(19);
        sharedTextureController.setR8Distinction(true);
        sharedTextureController.setUpdateInterval(500);
        sharedTextureController.setUpdateMode(2);
        ProgressIconController progressIconController = new ProgressIconController();
        CompositeRendererHigh compositeRendererHigh2 = new CompositeRendererHigh(progressIconController);
        progressIconController.setRenderer(compositeRendererHigh2);
        progressIconController.setBitmaps(new int[]{224});
        progressIconController.setModelID(162);
        progressIconController.setBounds(699, 360, 0, 0);
        progressIconController.setCoordinateSets(new int[]{1, 699, 360, 0, 0, 699, 360, 0, 0});
        progressIconController.setProcessStateChange(2);
        progressIconController.setProgressBarXOffset(0);
        IconController iconController3 = new IconController();
        IconRendererHigh iconRendererHigh4 = new IconRendererHigh(iconController3);
        iconController3.setRenderer(iconRendererHigh4);
        iconController3.setBitmaps(new int[]{235});
        iconController3.setBounds(694, 360, 0, 0);
        iconController3.setCoordinateSets(new int[]{1, 694, 360, 0, 0, 694, 360, 0, 0});
        iconController3.setProcessStateChange(2);
        IconLabelController iconLabelController = new IconLabelController();
        IconLabelRendererHigh iconLabelRendererHigh = new IconLabelRendererHigh(iconLabelController);
        iconLabelController.setRenderer(iconLabelRendererHigh);
        iconLabelController.setModelID(1663370752);
        iconLabelController.setBounds(675, 355, 100, 40);
        IconController iconController4 = new IconController();
        IconRendererHigh iconRendererHigh5 = new IconRendererHigh(iconController4);
        iconController4.setRenderer(iconRendererHigh5);
        iconController4.setBitmaps(new int[]{127});
        iconController4.setBounds(728, 77, 277, 324);
        iconController4.setCoordinateSets(new int[]{1, 728, 77, 277, 324, 728, 77, 277, 324});
        iconController4.setR8Distinction(true);
        IconController iconController5 = new IconController();
        IconRendererHigh iconRendererHigh6 = new IconRendererHigh(iconController5);
        iconController5.setRenderer(iconRendererHigh6);
        iconController5.setBitmaps(new int[]{954});
        iconController5.setBounds(501, 77, 277, 324);
        iconController5.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController5.setProcessStateChange(2);
        IconController iconController6 = new IconController();
        IconRendererHigh iconRendererHigh7 = new IconRendererHigh(iconController6);
        iconController6.setRenderer(iconRendererHigh7);
        iconController6.setBitmaps(new int[]{955});
        iconController6.setBounds(516, 77, 277, 324);
        iconController6.setColorIndices(new int[]{1, 2, 4, 0});
        iconController6.setCoordinateSets(new int[]{1, 516, 77, 277, 324, 516, 77, 277, 324});
        iconController6.setProcessStateChange(2);
        MirroredContainerController mirroredContainerController = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh = new MirrorRendererHigh(mirroredContainerController);
        mirroredContainerController.setRenderer(mirrorRendererHigh);
        mirroredContainerController.setBounds(0, 0, 468, 480);
        mirroredContainerController.setMirrorEnabled(false);
        mirroredContainerController.add(iconController2);
        mirroredContainerController.add(sharedTextureController);
        mirroredContainerController.add(progressIconController);
        mirroredContainerController.add(iconController3);
        mirroredContainerController.add(iconLabelController);
        mirroredContainerController.add(iconController4);
        mirroredContainerController.add(iconController5);
        mirroredContainerController.add(iconController6);
        MirroredContainerController mirroredContainerController2 = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh2 = new MirrorRendererHigh(mirroredContainerController2);
        mirroredContainerController2.setRenderer(mirrorRendererHigh2);
        mirroredContainerController2.setBounds(0, 0, 800, 480);
        mirroredContainerController2.setMirrorEnabled(false);
        mirroredContainerController2.add(mirroredContainerController);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 100, 100);
        containerController2.setColorIndices(new int[]{1, 0, 4, 0});
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController2.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController2.add(mirroredContainerController2);
        IconController iconController7 = new IconController();
        IconRendererHigh iconRendererHigh8 = new IconRendererHigh(iconController7);
        iconController7.setRenderer(iconRendererHigh8);
        iconController7.setBitmaps(new int[]{127});
        iconController7.setBounds(0, 0, 100, 100);
        LabelController labelController4 = new LabelController();
        LabelRendererHigh labelRendererHigh3 = new LabelRendererHigh(labelController4);
        labelController4.setRenderer(labelRendererHigh3);
        labelRendererHigh3.setFonts(infoScreenFactory.getFonts(2, n));
        labelController4.setTextIds(new int[]{681641728});
        labelController4.setBounds(0, 0, 0, 30);
        labelController4.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController5 = new LabelController();
        LabelRendererHigh labelRendererHigh4 = new LabelRendererHigh(labelController5);
        labelController5.setRenderer(labelRendererHigh4);
        labelRendererHigh4.setFonts(infoScreenFactory.getFonts(2, n));
        labelController5.setBounds(0, 0, 0, 30);
        labelController5.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController7);
        titleBarWidget.addTitle(labelController4);
        titleBarWidget.addBreadcrumb(labelController5);
        ContainerController containerController3 = new ContainerController();
        ContainerRendererHigh containerRendererHigh3 = new ContainerRendererHigh(containerController3);
        containerController3.setRenderer(containerRendererHigh3);
        containerController3.setBounds(0, 0, 800, 0);
        containerController3.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController3.setOpacitySet(1.0f, -842216386);
        containerController3.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        AbstractWidgetController abstractWidgetController2 = infoScreenFactory.getRefWidget(n, 1, infoScreenFactory);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(614532864);
        screenWidgetEVO.setScreenFactory(infoScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(infoScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setOpenSelectionDrawerByHkReturn(true);
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(abstractWidgetController);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 7);
        screenWidgetEVO.add(containerController3, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.add(abstractWidgetController2, 15);
        screenWidgetEVO.setViews(new int[]{138, 162, 1663370752, -1969158400, -1583282432, -1381955840, -1331624192, -1314846976, -694089984}, new HMIView[][]{{statusBarStubController, infoScreenFactory.refWidgets[n][2]}, {progressIconController}, {iconLabelController}, {labelController3}, {listController}, {menuController}, {labelController, labelController2}, {menuItemController}, {virtualButton}});
        screenWidgetEVO.setModelIDs(new int[]{-1583282432, -1314846976});
        screenWidgetEVO.setEventIDs(new int[]{547424000, 614532864});
        screenWidgetEVO.setConditionWidgets(new int[]{93, 162, 522, 556, 5624, 958137856, 1780221440, -1591867904, -1331624192, -694089984, -526317824}, new AbstractWidget[][]{{iconController3}, {progressIconController, iconController3, iconLabelController}, {mirroredContainerController2, mirroredContainerController}, {scrollbarController, scrollbarController2, iconController2, sharedTextureController, progressIconController, iconController3, iconLabelController, iconController4, iconController5, iconController6}, {iconController3, iconLabelController}, {sharedTextureController}, {progressIconController, iconController3, iconLabelController}, {scrollbarController, scrollbarController2, iconController2, sharedTextureController, progressIconController, iconController3, iconLabelController, iconController4, iconController5, iconController6}, {menuItemController, menuItemController, iconController, labelController2, labelController3, separatingLineController}, {virtualButton}, {screenWidgetEVO}});
        return screenWidgetEVO;
    }

    public static Screen mAPTRAFFICNOMESSAGES(InfoScreenFactory infoScreenFactory, int n) {
        AbstractWidgetController abstractWidgetController = infoScreenFactory.getRefWidget(n, 0, infoScreenFactory);
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(infoScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(1419839232);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        LabelController labelController = new LabelController();
        MultiLineLabelRendererHigh multiLineLabelRendererHigh = new MultiLineLabelRendererHigh(labelController);
        labelController.setRenderer(multiLineLabelRendererHigh);
        labelController.setTextIds(new int[]{1067517696});
        labelController.setBounds(0, 0, 0, 0);
        InstructionTextContoller instructionTextContoller = new InstructionTextContoller();
        instructionTextContoller.setBounds(0, 0, 100, 100);
        instructionTextContoller.setColorIndices(new int[]{1, 0, 4, 0});
        instructionTextContoller.setOptions(menuController);
        instructionTextContoller.addHintText(labelController);
        GlassplateController glassplateController2 = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh2 = new GlassplateRendererHigh(glassplateController2);
        glassplateController2.setRenderer(glassplateRendererHigh2);
        glassplateController2.setBounds(0, 0, 100, 100);
        glassplateController2.setSdsNumbersGapWidth(4);
        glassplateController2.setSdsNumbersWidth(64);
        MenuController menuController2 = new MenuController();
        MenuRendererHigh menuRendererHigh2 = new MenuRendererHigh(menuController2);
        menuController2.setRenderer(menuRendererHigh2);
        menuController2.createInfolineWidgets(new InfoLineRendererHigh());
        menuController2.getInfoline().getInfolineRenderer().setFonts(infoScreenFactory.getFonts(1, n));
        menuController2.getInfolineTimer().setIdleTime(800);
        menuController2.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController2.getLayout().setBackgroundInsetsVert(7);
        menuController2.getLayout().setContentLeftOffset(12);
        menuController2.getLayout().setContentRightOffset(25);
        menuController2.getLayout().setContentRightOffsetSmallStage(25);
        menuController2.getLayout().setItemsGap(9);
        menuController2.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController2.setBounds(62, 77, 716, 324);
        menuController2.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController2.add(glassplateController2, 4);
        LabelController labelController2 = new LabelController();
        MultiLineLabelRendererHigh multiLineLabelRendererHigh2 = new MultiLineLabelRendererHigh(labelController2);
        labelController2.setRenderer(multiLineLabelRendererHigh2);
        labelController2.setTextIds(new int[]{1570834176});
        labelController2.setBounds(84, 77, 630, 324);
        labelController2.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        multiLineLabelRendererHigh2.setAlignment(2, 5);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(instructionTextContoller);
        containerController.add(menuController2);
        containerController.add(labelController2);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{254});
        iconController.setBounds(501, 77, 277, 324);
        iconController.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController.setR8Distinction(true);
        SharedTextureController sharedTextureController = new SharedTextureController();
        SharedTextureRendererHigh sharedTextureRendererHigh = new SharedTextureRendererHigh(sharedTextureController);
        sharedTextureController.setRenderer(sharedTextureRendererHigh);
        sharedTextureController.setBounds(517, 80, 260, 318);
        sharedTextureController.setCaptureRect(0, 0, 260, 318);
        sharedTextureController.setCoordinateSets(new int[]{1, 517, 80, 260, 318, 517, 80, 260, 318});
        sharedTextureController.setDisplayableID(19);
        sharedTextureController.setR8Distinction(true);
        sharedTextureController.setUpdateInterval(500);
        sharedTextureController.setUpdateMode(2);
        ProgressIconController progressIconController = new ProgressIconController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(progressIconController);
        progressIconController.setRenderer(compositeRendererHigh);
        progressIconController.setBitmaps(new int[]{224});
        progressIconController.setModelID(162);
        progressIconController.setBounds(699, 360, 0, 0);
        progressIconController.setCoordinateSets(new int[]{1, 699, 360, 0, 0, 699, 360, 0, 0});
        progressIconController.setProcessStateChange(2);
        progressIconController.setProgressBarXOffset(0);
        IconController iconController2 = new IconController();
        IconRendererHigh iconRendererHigh2 = new IconRendererHigh(iconController2);
        iconController2.setRenderer(iconRendererHigh2);
        iconController2.setBitmaps(new int[]{235});
        iconController2.setBounds(694, 360, 0, 0);
        iconController2.setCoordinateSets(new int[]{1, 694, 360, 0, 0, 694, 360, 0, 0});
        iconController2.setProcessStateChange(2);
        IconLabelController iconLabelController = new IconLabelController();
        IconLabelRendererHigh iconLabelRendererHigh = new IconLabelRendererHigh(iconLabelController);
        iconLabelController.setRenderer(iconLabelRendererHigh);
        iconLabelController.setModelID(1663370752);
        iconLabelController.setBounds(675, 355, 100, 40);
        IconController iconController3 = new IconController();
        IconRendererHigh iconRendererHigh3 = new IconRendererHigh(iconController3);
        iconController3.setRenderer(iconRendererHigh3);
        iconController3.setBitmaps(new int[]{127});
        iconController3.setBounds(728, 77, 277, 324);
        iconController3.setCoordinateSets(new int[]{1, 728, 77, 277, 324, 728, 77, 277, 324});
        iconController3.setR8Distinction(true);
        IconController iconController4 = new IconController();
        IconRendererHigh iconRendererHigh4 = new IconRendererHigh(iconController4);
        iconController4.setRenderer(iconRendererHigh4);
        iconController4.setBitmaps(new int[]{954});
        iconController4.setBounds(501, 77, 277, 324);
        iconController4.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController4.setProcessStateChange(2);
        IconController iconController5 = new IconController();
        IconRendererHigh iconRendererHigh5 = new IconRendererHigh(iconController5);
        iconController5.setRenderer(iconRendererHigh5);
        iconController5.setBitmaps(new int[]{955});
        iconController5.setBounds(516, 77, 277, 324);
        iconController5.setColorIndices(new int[]{1, 2, 4, 0});
        iconController5.setCoordinateSets(new int[]{1, 516, 77, 277, 324, 516, 77, 277, 324});
        iconController5.setProcessStateChange(2);
        MirroredContainerController mirroredContainerController = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh = new MirrorRendererHigh(mirroredContainerController);
        mirroredContainerController.setRenderer(mirrorRendererHigh);
        mirroredContainerController.setBounds(0, 0, 468, 480);
        mirroredContainerController.setMirrorEnabled(false);
        mirroredContainerController.add(iconController);
        mirroredContainerController.add(sharedTextureController);
        mirroredContainerController.add(progressIconController);
        mirroredContainerController.add(iconController2);
        mirroredContainerController.add(iconLabelController);
        mirroredContainerController.add(iconController3);
        mirroredContainerController.add(iconController4);
        mirroredContainerController.add(iconController5);
        MirroredContainerController mirroredContainerController2 = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh2 = new MirrorRendererHigh(mirroredContainerController2);
        mirroredContainerController2.setRenderer(mirrorRendererHigh2);
        mirroredContainerController2.setBounds(0, 0, 800, 480);
        mirroredContainerController2.setMirrorEnabled(false);
        mirroredContainerController2.add(mirroredContainerController);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 100, 100);
        containerController2.setColorIndices(new int[]{1, 0, 4, 0});
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController2.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController2.add(mirroredContainerController2);
        IconController iconController6 = new IconController();
        IconRendererHigh iconRendererHigh6 = new IconRendererHigh(iconController6);
        iconController6.setRenderer(iconRendererHigh6);
        iconController6.setBitmaps(new int[]{127});
        iconController6.setBounds(0, 0, 100, 100);
        LabelController labelController3 = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController3);
        labelController3.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(infoScreenFactory.getFonts(2, n));
        labelController3.setTextIds(new int[]{681641728});
        labelController3.setBounds(0, 0, 0, 30);
        labelController3.setColorIndices(new int[]{1, 2, 4, 0});
        LabelController labelController4 = new LabelController();
        LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController4);
        labelController4.setRenderer(labelRendererHigh2);
        labelRendererHigh2.setFonts(infoScreenFactory.getFonts(2, n));
        labelController4.setBounds(0, 0, 0, 30);
        labelController4.setCoordinateSets(new int[]{1, 0, 0, 0, 30, 0, 0, 0, 30});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController6);
        titleBarWidget.addTitle(labelController3);
        titleBarWidget.addBreadcrumb(labelController4);
        ContainerController containerController3 = new ContainerController();
        ContainerRendererHigh containerRendererHigh3 = new ContainerRendererHigh(containerController3);
        containerController3.setRenderer(containerRendererHigh3);
        containerController3.setBounds(0, 0, 800, 0);
        containerController3.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController3.setOpacitySet(1.0f, -842216386);
        containerController3.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.add(titleBarWidget);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(631310080);
        screenWidgetEVO.setScreenFactory(infoScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(infoScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setOpenSelectionDrawerByHkReturn(true);
        screenWidgetEVO.setOptionIconVisible(true);
        screenWidgetEVO.setSmallStageType(0);
        screenWidgetEVO.add(abstractWidgetController);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 7);
        screenWidgetEVO.add(containerController3, 2);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.setViews(new int[]{138, 162, 1663370752}, new HMIView[][]{{statusBarStubController}, {progressIconController}, {iconLabelController}});
        screenWidgetEVO.setConditionWidgets(new int[]{93, 162, 522, 556, 5624, 958137856, 1780221440, -1591867904, -526317824}, new AbstractWidget[][]{{iconController2}, {progressIconController, iconController2, iconLabelController}, {instructionTextContoller, menuController2, labelController2, mirroredContainerController2, mirroredContainerController}, {iconController, sharedTextureController, progressIconController, iconController2, iconLabelController, iconController3, iconController4, iconController5}, {iconController2, iconLabelController}, {sharedTextureController}, {progressIconController, iconController2, iconLabelController}, {iconController, sharedTextureController, progressIconController, iconController2, iconLabelController, iconController3, iconController4, iconController5}, {screenWidgetEVO}});
        return screenWidgetEVO;
    }

    public static Screen mAPPOPUPSHOWURGENTWARNINGMAIN(InfoScreenFactory infoScreenFactory, int n) {
        AbstractWidgetController abstractWidgetController = infoScreenFactory.getRefWidget(n, 0, infoScreenFactory);
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        glassplateController.setSdsNumbersGapWidth(4);
        glassplateController.setSdsNumbersWidth(64);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        ListController listController = new ListController();
        listController.setModelID(44173056);
        listController.setEvent(-1608907264);
        listController.getLayoutCalculator().setCacheItemHeights(false);
        listController.setBounds(0, 0, 0, 0);
        listController.setFocusableColumn(11);
        listController.setGlassplateInsetsBottom(new int[0]);
        listController.setGlassplateInsetsTop(new int[0]);
        listController.setIdColumn(0);
        listController.setNoFocusAreasBottom(new int[0]);
        listController.setNoFocusAreasTop(new int[0]);
        listController.setRecordSetColumn(0);
        listController.setWidgetID(10);
        listController.setDataAccess(new BaseListModelAccess());
        listController.setItemFactory(new InfoScreenBag1$3());
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(infoScreenFactory.getFonts(1, n));
        menuController.setDefaultDisabledInfolineTextId(1403062016);
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getInitialization().setInitialFocusAdvice(FocusAdvice.VIEWPORT_FIRST_POSITION);
        menuController.getInitialization().setInitialFocusWidgetIDs(new int[]{10});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(listController);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        IconController iconController = new IconController();
        IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
        iconController.setRenderer(iconRendererHigh);
        iconController.setBitmaps(new int[]{254});
        iconController.setBounds(501, 77, 277, 324);
        iconController.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController.setR8Distinction(true);
        SharedTextureController sharedTextureController = new SharedTextureController();
        SharedTextureRendererHigh sharedTextureRendererHigh = new SharedTextureRendererHigh(sharedTextureController);
        sharedTextureController.setRenderer(sharedTextureRendererHigh);
        sharedTextureController.setBounds(517, 80, 260, 318);
        sharedTextureController.setCaptureRect(0, 0, 260, 318);
        sharedTextureController.setCoordinateSets(new int[]{1, 517, 80, 260, 318, 517, 80, 260, 318});
        sharedTextureController.setDisplayableID(19);
        sharedTextureController.setR8Distinction(true);
        sharedTextureController.setUpdateInterval(500);
        sharedTextureController.setUpdateMode(2);
        ProgressIconController progressIconController = new ProgressIconController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(progressIconController);
        progressIconController.setRenderer(compositeRendererHigh);
        progressIconController.setBitmaps(new int[]{224});
        progressIconController.setModelID(162);
        progressIconController.setBounds(699, 360, 0, 0);
        progressIconController.setCoordinateSets(new int[]{1, 699, 360, 0, 0, 699, 360, 0, 0});
        progressIconController.setProcessStateChange(2);
        progressIconController.setProgressBarXOffset(0);
        IconController iconController2 = new IconController();
        IconRendererHigh iconRendererHigh2 = new IconRendererHigh(iconController2);
        iconController2.setRenderer(iconRendererHigh2);
        iconController2.setBitmaps(new int[]{235});
        iconController2.setBounds(694, 360, 0, 0);
        iconController2.setCoordinateSets(new int[]{1, 694, 360, 0, 0, 694, 360, 0, 0});
        iconController2.setProcessStateChange(2);
        IconLabelController iconLabelController = new IconLabelController();
        IconLabelRendererHigh iconLabelRendererHigh = new IconLabelRendererHigh(iconLabelController);
        iconLabelController.setRenderer(iconLabelRendererHigh);
        iconLabelController.setModelID(1663370752);
        iconLabelController.setBounds(675, 355, 100, 40);
        IconController iconController3 = new IconController();
        IconRendererHigh iconRendererHigh3 = new IconRendererHigh(iconController3);
        iconController3.setRenderer(iconRendererHigh3);
        iconController3.setBitmaps(new int[]{127});
        iconController3.setBounds(728, 77, 277, 324);
        iconController3.setCoordinateSets(new int[]{1, 728, 77, 277, 324, 728, 77, 277, 324});
        iconController3.setR8Distinction(true);
        IconController iconController4 = new IconController();
        IconRendererHigh iconRendererHigh4 = new IconRendererHigh(iconController4);
        iconController4.setRenderer(iconRendererHigh4);
        iconController4.setBitmaps(new int[]{954});
        iconController4.setBounds(501, 77, 277, 324);
        iconController4.setCoordinateSets(new int[]{1, 501, 77, 277, 324, 501, 77, 277, 324});
        iconController4.setProcessStateChange(2);
        IconController iconController5 = new IconController();
        IconRendererHigh iconRendererHigh5 = new IconRendererHigh(iconController5);
        iconController5.setRenderer(iconRendererHigh5);
        iconController5.setBitmaps(new int[]{955});
        iconController5.setBounds(516, 77, 277, 324);
        iconController5.setColorIndices(new int[]{1, 2, 4, 0});
        iconController5.setCoordinateSets(new int[]{1, 516, 77, 277, 324, 516, 77, 277, 324});
        iconController5.setProcessStateChange(2);
        MirroredContainerController mirroredContainerController = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh = new MirrorRendererHigh(mirroredContainerController);
        mirroredContainerController.setRenderer(mirrorRendererHigh);
        mirroredContainerController.setBounds(0, 0, 468, 480);
        mirroredContainerController.setMirrorEnabled(false);
        mirroredContainerController.add(iconController);
        mirroredContainerController.add(sharedTextureController);
        mirroredContainerController.add(progressIconController);
        mirroredContainerController.add(iconController2);
        mirroredContainerController.add(iconLabelController);
        mirroredContainerController.add(iconController3);
        mirroredContainerController.add(iconController4);
        mirroredContainerController.add(iconController5);
        MirroredContainerController mirroredContainerController2 = new MirroredContainerController();
        MirrorRendererHigh mirrorRendererHigh2 = new MirrorRendererHigh(mirroredContainerController2);
        mirroredContainerController2.setRenderer(mirrorRendererHigh2);
        mirroredContainerController2.setBounds(0, 0, 800, 480);
        mirroredContainerController2.setMirrorEnabled(false);
        mirroredContainerController2.add(mirroredContainerController);
        ContainerController containerController2 = new ContainerController();
        ContainerRendererHigh containerRendererHigh2 = new ContainerRendererHigh(containerController2);
        containerController2.setRenderer(containerRendererHigh2);
        containerController2.setBounds(0, 0, 100, 100);
        containerController2.setColorIndices(new int[]{1, 0, 4, 0});
        containerController2.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController2.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController2.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController2.add(mirroredContainerController2);
        IconController iconController6 = new IconController();
        IconRendererHigh iconRendererHigh6 = new IconRendererHigh(iconController6);
        iconController6.setRenderer(iconRendererHigh6);
        iconController6.setBitmaps(new int[]{127});
        iconController6.setBounds(0, 0, 100, 100);
        LabelController labelController = new LabelController();
        LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
        labelController.setRenderer(labelRendererHigh);
        labelRendererHigh.setFonts(infoScreenFactory.getFonts(2, n));
        labelController.setTextIds(new int[]{950077184});
        labelController.setBounds(0, 0, 0, 30);
        labelController.setColorIndices(new int[]{1, 2, 4, 0});
        TitleBarWidget titleBarWidget = new TitleBarWidget();
        TitleBarRendererHigh titleBarRendererHigh = new TitleBarRendererHigh(titleBarWidget);
        titleBarWidget.setRenderer(titleBarRendererHigh);
        titleBarWidget.setBitmaps(new int[]{58, 58});
        titleBarWidget.getTitleLayout().setGapInsideBreadcrumbs(15);
        titleBarWidget.getTitleLayout().setGapInsideTitles(15);
        titleBarWidget.setBounds(75, 28, 650, 22);
        titleBarWidget.setColorIndices(new int[]{1, 8, 4, 0});
        titleBarWidget.addLeftIcon(iconController6);
        titleBarWidget.addTitle(labelController);
        ContainerController containerController3 = new ContainerController();
        ContainerRendererHigh containerRendererHigh3 = new ContainerRendererHigh(containerController3);
        containerController3.setRenderer(containerRendererHigh3);
        containerController3.setBounds(0, 0, 800, 0);
        containerController3.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 0.0f);
        containerController3.setOpacitySet(1.0f, -842216386);
        containerController3.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.setSelectionMenuTransformation(8438595, 57408, -1701242561, -1701242561, 0.0f);
        containerController3.add(titleBarWidget);
        IdleTimerController idleTimerController = new IdleTimerController();
        idleTimerController.setEvent(564201216);
        idleTimerController.setBounds(0, 0, 100, 100);
        idleTimerController.setIdleTimeout(10000);
        idleTimerController.setTriggerType(1);
        StatusBarStubController statusBarStubController = new StatusBarStubController();
        statusBarStubController.setModelID(138);
        statusBarStubController.setBounds(0, 0, 100, 100);
        AbstractWidgetController abstractWidgetController2 = infoScreenFactory.getRefWidget(n, 1, infoScreenFactory);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(648087296);
        screenWidgetEVO.setScreenFactory(infoScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(infoScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setDrawerVisibility(3);
        screenWidgetEVO.setLargeViewSizePreferred(true);
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(abstractWidgetController);
        screenWidgetEVO.add(containerController, 1);
        screenWidgetEVO.add(containerController2, 7);
        screenWidgetEVO.add(containerController3, 2);
        screenWidgetEVO.add(idleTimerController);
        screenWidgetEVO.add(statusBarStubController);
        screenWidgetEVO.add(abstractWidgetController2, 15);
        screenWidgetEVO.setViews(new int[]{138, 162, 1663370752, 44173056}, new HMIView[][]{{statusBarStubController, infoScreenFactory.refWidgets[n][2]}, {progressIconController}, {iconLabelController}, {listController}});
        screenWidgetEVO.setModelIDs(new int[]{44173056});
        screenWidgetEVO.setEventIDs(new int[]{-1608907264});
        screenWidgetEVO.setConditionWidgets(new int[]{93, 162, 522, 556, 5624, 958137856, 1780221440, -1591867904}, new AbstractWidget[][]{{iconController2}, {progressIconController, iconController2, iconLabelController}, {mirroredContainerController2, mirroredContainerController}, {iconController, sharedTextureController, progressIconController, iconController2, iconLabelController, iconController3, iconController4, iconController5}, {iconController2, iconLabelController}, {sharedTextureController}, {progressIconController, iconController2, iconLabelController}, {iconController, sharedTextureController, progressIconController, iconController2, iconLabelController, iconController3, iconController4, iconController5}});
        return screenWidgetEVO;
    }

    public static Screen iNFOTEXTCONSTANT(InfoScreenFactory infoScreenFactory, int n) {
        GlassplateController glassplateController = new GlassplateController();
        GlassplateRendererHigh glassplateRendererHigh = new GlassplateRendererHigh(glassplateController);
        glassplateController.setRenderer(glassplateRendererHigh);
        glassplateController.setBounds(0, 0, 100, 100);
        ScrollbarController scrollbarController = new ScrollbarController();
        ScrollbarRendererKanziHigh scrollbarRendererKanziHigh = new ScrollbarRendererKanziHigh(scrollbarController);
        scrollbarController.setRenderer(scrollbarRendererKanziHigh);
        scrollbarController.setBounds(703, 11, 5, 302);
        FocusCursorController focusCursorController = new FocusCursorController();
        FocusCursorRendererHigh focusCursorRendererHigh = new FocusCursorRendererHigh(focusCursorController);
        focusCursorController.setRenderer(focusCursorRendererHigh);
        focusCursorController.setBounds(0, 0, 100, 100);
        focusCursorController.setColorIndices(new int[]{1, 2, 4, 0});
        focusCursorController.setOptionsIconVisible(false);
        focusCursorController.setWaitAnimOffsetX(600);
        focusCursorController.setWaitAnimOffsetY(15);
        MenuItemController menuItemController = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(menuItemController);
        menuItemController.setRenderer(compositeRendererHigh);
        menuItemController.setLabelId(1537279744);
        menuItemController.setGlassplateInsetsBottom(6);
        menuItemController.setGlassplateInsetsTop(7);
        menuItemController.setInternalID(631310080);
        menuItemController.setType(2);
        MenuItemController menuItemController2 = new MenuItemController();
        CompositeRendererHigh compositeRendererHigh2 = new CompositeRendererHigh(menuItemController2);
        menuItemController2.setRenderer(compositeRendererHigh2);
        menuItemController2.setLabelId(1554056960);
        menuItemController2.setGlassplateInsetsBottom(6);
        menuItemController2.setGlassplateInsetsTop(7);
        menuItemController2.setInternalID(648087296);
        menuItemController2.setType(2);
        MenuController menuController = new MenuController();
        MenuRendererHigh menuRendererHigh = new MenuRendererHigh(menuController);
        menuController.setRenderer(menuRendererHigh);
        menuController.createInfolineWidgets(new InfoLineRendererHigh());
        menuController.getInfoline().getInfolineRenderer().setFonts(infoScreenFactory.getFonts(1, n));
        menuController.getInfolineTimer().setIdleTime(800);
        menuController.getInfoline().setColorIndices(new int[]{2, 0, 4, 3});
        menuController.getLayout().setBackgroundInsetsVert(7);
        menuController.getLayout().setContentLeftOffset(12);
        menuController.getLayout().setContentRightOffset(25);
        menuController.getLayout().setContentRightOffsetSmallStage(25);
        menuController.getLayout().setItemsGap(9);
        menuController.getLayout().setOptionsIconAdditionalRightInsets(16);
        menuController.setBounds(62, 77, 716, 324);
        menuController.setColorIndices(new int[]{1, 0, 4, 0, 2, 3});
        menuController.add(glassplateController, 4);
        menuController.add(scrollbarController, 3);
        menuController.add(focusCursorController, 1);
        menuController.add(menuItemController);
        menuController.add(menuItemController2);
        ContainerController containerController = new ContainerController();
        ContainerRendererHigh containerRendererHigh = new ContainerRendererHigh(containerController);
        containerController.setRenderer(containerRendererHigh);
        containerController.setBounds(0, 0, 0, 0);
        containerController.setEntertainmentMenuTransformation(16449, 16449, -1883081409, -1883081409, 63);
        containerController.setOpacitySet(1.0f, -842216386);
        containerController.setOptionMenuTransformation(32960, 57408, -1701242561, -1701242561, 63);
        containerController.setSelectionMenuTransformation(40771, 57408, -512093121, -1701242561, 32830);
        containerController.add(menuController);
        ScreenWidgetEVO screenWidgetEVO = new ScreenWidgetEVO(681641728);
        screenWidgetEVO.setScreenFactory(infoScreenFactory);
        ScreenRendererHigh screenRendererHigh = new ScreenRendererHigh(screenWidgetEVO);
        screenWidgetEVO.setRenderer(screenRendererHigh);
        screenRendererHigh.setFonts(infoScreenFactory.getFonts(0, n));
        screenWidgetEVO.setColorIndices(new int[]{1, 2, 4, 0});
        screenWidgetEVO.setColorPalettes(new int[][]{{-1, 255, -1, -1, -1701143809, -1431655681, -1246382593, -1701143809, -1}, {-1, 255, 419495935, 1751100415, -1701143809, -1431655681, -1246382593, -1701143809, 1228585215}, {-1, 255, -19456, 1838260991, -1701143809, -1431655681, -1246382593, -1701143809, 1838260991}, {-1, 255, -1433657601, -1567134209, -1701143809, -1431655681, -1246382593, -1701143809, -1567134209}, {-1, 255, 11166975, 1973122047, -1701143809, -1431655681, -1246382593, -1701143809, 1973122047}});
        screenWidgetEVO.setSmallStageType(3);
        screenWidgetEVO.add(containerController, 1);
        return screenWidgetEVO;
    }
}

