/*
 * Decompiled with CFR 0.152.
 */
package org.dsi.ifc.displaymanagement;

public interface Constants {
    public static final int DISPLAYABLE_INVALID = -1;
    public static final int DISPLAYABLE_RESERVED = 15;
    public static final int DISPLAYABLE_HMI = 16;
    public static final int DISPLAYABLE_REAR_VIEW_CAM = 17;
    public static final int DISPLAYABLE_BROWSER = 18;
    public static final int DISPLAYABLE_MAPVIEWER = 19;
    public static final int DISPLAYABLE_MAP_ROUTE_GUIDANCE = 20;
    public static final int DISPLAYABLE_MAP_INTERSECTION_VIEW = 21;
    public static final int DISPLAYABLE_MAP_3D_INTERSECTION_VIEW = 22;
    public static final int DISPLAYABLE_MAP_JUNCTION_VIEW = 23;
    public static final int DISPLAYABLE_MAP_LANDMARK_VIEW = 24;
    public static final int DISPLAYABLE_DVD_VIDEO = 25;
    public static final int DISPLAYABLE_TV_TUNER = 26;
    public static final int DISPLAYABLE_AMI = 27;
    public static final int DISPLAYABLE_OPS = 28;
    public static final int DISPLAYABLE_TV_AUX1 = 29;
    public static final int DISPLAYABLE_TV_AUX2 = 30;
    public static final int DISPLAYABLE_TV_VIDEOTEXT = 31;
    public static final int DISPLAYABLE_SIDE_VIEW_CAM = 32;
    public static final int DISPLAYABLE_KOMBI_MAP_VIEW = 33;
    public static final int DISPLAYABLE_EXTERNAL_DVD_VIDEO = 34;
    public static final int DISPLAYABLE_COVERFLOW = 35;
    public static final int DISPLAYABLE_HMI2 = 36;
    public static final int DISPLAYABLE_FILE_VIDEO = 37;
    public static final int DISPLAYABLE_COVERFLOW2 = 38;
    public static final int DISPLAYABLE_GOOGLE_EARTH = 39;
    public static final int DISPLAYABLE_PUBLIC_SPLASHSCREEN = 40;
    public static final int DISPLAYABLE_3D = 41;
    public static final int DISPLAYABLE_DIGITAL_VIDEOPLAYER_1 = 43;
    public static final int DISPLAYABLE_DIGITAL_VIDEOPLAYER_2 = 44;
    public static final int DISPLAYABLE_REMOTE_HMI = 45;
    public static final int DISPLAYABLE_JAPANMAP = 46;
    public static final int DISPLAYABLE_FBAS_1 = 47;
    public static final int DISPLAYABLE_FBAS_2 = 48;
    public static final int DISPLAYABLE_FBAS_3 = 49;
    public static final int DISPLAYABLE_MAP_IN_MAP = 50;
    public static final int DISPLAYABLE_STREETVIEW = 51;
    public static final int DISPLAYABLE_CRUISING_RANGE = 52;
    public static final int DISPLAYABLE_TRAFFIC_INFORMATION = 53;
    public static final int DISPLAYABLE_REALISTIC_PICTURE = 54;
    public static final int DISPLAYABLE_KANBAN = 55;
    public static final int DISPLAYABLE_MIRRORLINK = 56;
    public static final int DISPLAYABLE_SFA = 57;
    public static final int DISPLAYABLE_GOOGLE_EARTH_KOMBI_MAP_VIEW = 58;
    public static final int DISPLAYABLE_EXTERNAL_SMARTPHONE = 59;
    public static final int DISPLAYABLE_HUD_MAP_VIEW = 60;
    public static final int DISPLAYSTATE_UNKNOWN = -1;
    public static final int DISPLAYSTATE_OFF = 0;
    public static final int DISPLAYSTATE_ON = 1;
    public static final int DISPLAYSTATE_GAUGES = 2;
    public static final int DISPLAYSTATE_FASTOPEN = 3;
    public static final int DISPLAYSTATE_LEARNING = 4;
    public static final int DISPLAYID_PRIMARY_DEFAULT = 0;
    public static final int DISPLAYID_SECONDARY = 1;
    public static final int DISPLAYID_RSE_LEFT = 2;
    public static final int DISPLAYID_RSE_RIGHT = 3;
    public static final int DISPLAYID_CLUSTER = 4;
    public static final int DISPLAYID_HUD = 5;
    public static final int DISPLAYID_LOWER = 6;
    public static final int DISPLAYTYPE_UNDEFINED = 0;
    public static final int DISPLAYTYPE_LVDS = 1;
    public static final int DISPLAYTYPE_H264_MOST = 2;
    public static final int RESULTCODE_OK = 0;
    public static final int RESULTCODE_NOT_OPERABLE = 1;
    public static final int RESULTCODE_ERROR = 2;
    public static final int RESULTCODE_NOT_SUPPORTED = 3;
    public static final int RESULTCODE_INVALID_RANGE = 4;
    public static final int DISPLAYABLEINFO_NOT_SUPPORTED = 0;
    public static final int DISPLAYABLEINFO_SUPPORTED_VIDEO_PARAMETRIZABLE = 1;
    public static final int DISPLAYABLEINFO_SUPPORTED_VIDEO_NOT_PARAMETRIZABLE = 2;
    public static final int SCALEMODE_ASPECT_RATIO = 0;
    public static final int SCALEMODE_FIT_HORIZONTAL = 1;
    public static final int SCALEMODE_FIT_VERTICAL = 2;
    public static final int SCALEMODE_CLIP_TOP_LEFT = 3;
    public static final int SCALEMODE_CLIP_MIDDLE = 4;
    public static final int SCREENSHOTRESULTCODE_OK = 0;
    public static final int SCREENSHOTRESULTCODE_NO_MEDIUM = 1;
    public static final int SCREENSHOTRESULTCODE_ERROR = 2;
}

