/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.model;

public interface ICoreTrafficInfoJPModelBank {
    public static final int VICS_MENU_ENTER_EMERGENCY_BUTTON = 900003;
    public static final int TRAFFIC_INFO_JP_POPUP_CANCEL_BUTTON = 900045;
    public static final int TRAFFIC_INFO_JP_VICS_DSRC_FIGURE_POPUP_ROTATE_RANGE = 900037;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_CLOSE_POPUP_BUTTON = 900049;
    public static final int TRAFFIC_INFO_JP_FM_FIGURE_BASE_LIST = 900012;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_MESSAGE_TYPE_CHOICE = 900055;
    public static final int TRAFFIC_INFO_JP_DSRC_VICS_RECEPTION_ICON_CHOICE = 900033;
    public static final int TRAFFIC_INFO_JP_VICS_IMAGE_RESOURCE_LOCATOR = 900009;
    public static final int TRAFFIC_INFO_JP_WAIT_SYNC_CHOICE = 900006;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_SHOW_ON_MAP_BUTTON = 900048;
    public static final int TRAFFIC_INFO_JP_VICS_DSRC_FIGURE_POPUP_ROTATE_VIRTUAL_BUTTON = 900035;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_DETAIL_INFORMATION_LABEL_LABEL = 900057;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_SHOW_NEXT_MESSAGE_BUTTON = 900050;
    public static final int TRAFFIC_INFO_JP_FM_TEXT_MENU = 900017;
    public static final int TRAFFIC_INFO_JP_VICS_RECEPTION_TIME_METRICS = 900030;
    public static final int TRAFFIC_INFO_JP_SETUP_DSRC_UPLOAD_CHOICE = 900024;
    public static final int TRAFFIC_INFO_JP_POPUP_TITLE_TEXT_CHOICE = 900044;
    public static final int TRAFFIC_INFO_JP_SETUP_DSRC_VOICE_POPUPS_CHOICE = 900025;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_EVENT_NAME_LABEL = 900051;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_TIME_STAMP_METRICS = 900052;
    public static final int TRAFFIC_INFO_JP_FM_EMERGENCY_BASE_LIST = 900021;
    public static final int TRAFFIC_INFO_JP_TMC_DETAIL_TIMESTAMP_LABEL = 900042;
    public static final int TRAFFIC_INFO_JP_DSRC_VICS_POPUP_TIMEOUT_CHOICE = 900039;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_POPUP_TITLE_LABEL_LABEL = 900058;
    public static final int TRAFFIC_INFO_JP_VICS_IMAGE_CHOICE = 900040;
    public static final int TRAFFIC_INFO_JP_TMC_DETAIL_BASE_LIST = 900067;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_DETAIL_TIME_PERIOD_LABEL_LABEL = 900059;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_POPUP_TEXT_LABEL = 900053;
    public static final int TRAFFIC_INFO_JP_FM_EMERGENCY_MENU = 900018;
    public static final int TRAFFIC_INFO_JP_SETUP_POPUP_DURATION_CHOICE = 900020;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_DETAIL_EVENT_NAME_LABEL_LABEL = 900060;
    public static final int TRAFFIC_INFO_JP_VICS_ONLINE_STATUS_CHOICE = 900028;
    public static final int VICS_MENU_ENTER_DSRC_BUTTON = 900001;
    public static final int TRAFFIC_INFO_JP_FM_FIGURE_MENU = 900019;
    public static final int TRAFFIC_INFO_JP_VICS_DSRC_FIGURE_POPUP_CHOICE = 900034;
    public static final int TRAFFIC_INFO_JP_NO_DATA_AVAILABLE_CHOICE = 900011;
    public static final int TRAFFIC_INFO_JP_POPUP_HIDE_BUTTON = 900046;
    public static final int TRAFFIC_INFO_JP_VICS_DSRC_FIGURE_POPUP_CLOSE_VIRTUAL_BUTTON = 900036;
    public static final int TRAFFIC_INFO_JP_HISTORY_VOICE_MESSAGE_TEXT_CHOICE = 900056;
    public static final int TRAFFIC_INFO_JP_SETUP_TRAFFIC_EVENT_NOTICE_MAP_CHOICE = 900026;
    public static final int TRAFFIC_INFO_JP_DSRC_VOICE_POPUP_CHOICE = 900010;
    public static final int TRAFFIC_INFO_JP_PHONETIC_STRING_SPEAKING_CHOICE = 900061;
    public static final int TRAFFIC_INFO_JP_SETUP_ITS_SPOT_VOICE_AUTO_PLAY_CHOICE = 900064;
    public static final int TRAFFIC_INFO_JP_VICS_RECEPTION_STATUS_CHOICE = 900029;
    public static final int TRAFFIC_INFO_JP_DSRC_MENU = 900015;
    public static final int TRAFFIC_INFO_JP_DSRC_VOICE_MESSAGE_PENDING_CHOICE = 900032;
    public static final int TRAFFIC_INFO_JP_VICS_DATA_AVAILABLE_CHOICE = 900008;
    public static final int TRAFFIC_INFO_JP_POPUP_NEXT_BUTTON = 900062;
    public static final int VICS_MENU_ENTER_FM_FIGURE_BUTTON = 900004;
    public static final int VICS_MENU_ENTER_FM_TEXT_BUTTON = 900005;
    public static final int TRAFFIC_INFO_JP_SETUP_DSRC_GENERAL_POPUPS_CHOICE = 900023;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_DETAIL_ICON_RESOURCE_LOCATOR = 900065;
    public static final int TRAFFIC_INFO_JP_POPUP_PREVIOUS_PICTURE_BUTTON = 900063;
    public static final int VICS_MENU_ENTER_DSRC_VOICE_BUTTON = 900002;
    public static final int TRAFFIC_INFO_JP_VICS_GEN2_DETAIL_TEXT_LABEL = 900054;
    public static final int TRAFFIC_INFO_JP_VICS_DSRC_FIGURE_POPUP_PICTURE_CHOICE = 900041;
    public static final int TRAFFIC_INFO_JP_FM_TEXT_BASE_LIST = 900014;
    public static final int TRAFFIC_INFO_JP_VICS_DSRC_FIGURE_POPUP_RESOURCE_LOCATOR = 900038;
    public static final int TRAFFIC_INFO_JP_DSRC_BASE_LIST = 900007;
    public static final int TRAFFIC_INFO_JP_VICS_STATION_NAME_LABEL = 900031;
    public static final int TRAFFIC_INFO_JP_POPUP_DEACTIVATE_BUTTON = 900047;
    public static final int TRAFFIC_INFO_JP_SETUP_DSRC_DRIVING_SUPPORT_CAUTION_CHOICE = 900022;
    public static final int TRAFFIC_INFO_JP_SETUP_VICS_TRAFFIC_MESSAGE_POPUPS_CHOICE = 900027;
}

