/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carseat;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATVIEWOPTIONS = 1;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATRADIOKEYAUTOMATIC = 2;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSPECIALPOSITION = 3;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFRONTLEFTSTOPBUTTON = 4;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFRONTRIGHTSTOPBUTTON = 5;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCODRIVERSETTINGSFROMDRIVER = 6;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCODRIVERSETTINGSFROMREAR = 7;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA1RL = 8;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA1RR = 9;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP1RL = 10;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN1RL = 11;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD1RL = 12;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK1RL = 13;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP1RR = 14;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN1RR = 15;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD1RR = 16;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK1RR = 17;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCONTENT = 18;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYFRONTLEFT = 19;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYFRONTRIGHT = 20;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYREARLEFT = 21;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATEASYENTRYREARRIGHT = 22;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICVIEWOPTIONS = 23;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICCODRIVERSETTINGSFROMDRIVER = 24;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICMASSAGEDATA1RL = 25;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICMASSAGEDATA1RR = 26;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAUP1RL = 27;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATADOWN1RL = 28;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAFORWARD1RL = 29;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATABACK1RL = 30;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAUP1RR = 31;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATADOWN1RR = 32;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATAFORWARD1RR = 33;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICSWITCHERDATABACK1RR = 34;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPNEUMATICCONTENT = 35;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATREARLEFTSTOPBUTTON = 36;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATREARRIGHTSTOPBUTTON = 37;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA2RL = 38;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGEDATA2RR = 39;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP2RL = 40;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN2RL = 41;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD2RL = 42;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK2RL = 43;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAUP2RR = 44;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATADOWN2RR = 45;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATAFORWARD2RR = 46;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSWITCHERDATABACK2RR = 47;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT1RL = 48;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT1RR = 49;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT2RL = 50;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATADJUSTMENT2RR = 51;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATSPECIALPOSITIONREARCODRIVER = 52;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATCODRIVERSETTINGSFROMREARACTIVATION = 53;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATRESTSEATSTATUS = 54;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFOLDHEADRESTREARDRIVER = 55;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATFOLDHEADRESTREARCODRIVER = 56;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA1RL = 57;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA1RR = 58;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA2RL = 59;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGEDATA2RR = 60;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER1RL = 61;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER1RR = 62;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER2RL = 63;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATPREMIUMMASSAGESWITCHER2RR = 64;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER1RL = 65;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER1RR = 66;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER2RL = 67;
    public static final int ATTRIBUTE_ID_DSICARSEAT_SEATMASSAGESWITCHER2RR = 68;
}

