/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.telephoneng;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_DTMFTONEPLAYING = 1;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_EMERGENCYNUMBERS = 2;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SIMPINREQUIRED = 3;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ACTIVATIONSTATE = 4;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_AUTOMATICPINENTRYACTIVE = 5;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_AUTOMATICREDIALACTIVE = 6;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_BATTERYCHARGELEVEL = 7;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CALLDURATIONLIST = 8;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CALLLIST = 9;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CDMATHREEWAYCALLINGSETTING = 10;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CRADLEPLUGINSTATE = 11;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_DISCONNECTREASON = 12;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_EMERGENCYCALLACTIVE = 13;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ENHANCEDPRIVACYMODE = 14;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_HANDSFREEMODE = 15;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_LOCKSTATE = 16;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MAILBOXCONTENT = 17;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MICMUTESTATE = 18;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NADTEMPERATURE = 19;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PHONEINFORMATION = 20;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NETWORKPROVIDER = 21;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NETWORKTYPE = 22;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PRIVACYMODE = 23;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_REGISTERSTATE = 24;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SERVICECODETYPE = 25;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SERVICENUMBERS = 26;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SIGNALQUALITY = 27;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SUPPSERVICERESPONSE = 28;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SERVICEPROVIDER = 29;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SIMALIASINFORMATION = 30;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MICGAINLEVEL = 31;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_OPTIMIZATIONMODE = 32;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_NADMODE = 33;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_OTHERSIMAVAILABLE = 34;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PREFIXCONTENT = 35;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PHONEREMINDERSETTING = 36;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PREFIXACTIVATED = 37;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_WIDEBANDSPEECH = 38;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_PHONERINGTONE = 39;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_FAVORITES = 40;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SAPUPGRADEACTIVE = 41;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_EUICCID = 42;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ESIMMSISDN = 43;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ESIMACTIVE = 44;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_ESIMB2BMODE = 45;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_CALLSTACKSISREVERTED = 46;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_LASTANSWEREDNUMBERS = 47;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_LASTDIALEDNUMBERS = 48;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MISSEDNUMBERS = 49;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MEDATAVALIDITY = 50;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_MISSEDCALLINDICATOR = 51;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SPEECHRECOGNITIONAVAILABLE = 52;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SPEECHRECOGNITIONACTIVE = 53;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENT_SPEECHRECOGNITIONTYPE = 54;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENTTOPOLOGY_TOPOLOGY = 1;
    public static final int ATTRIBUTE_ID_DSIMOBILEEQUIPMENTTOPOLOGY_USAGE = 2;
}

