/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.navi.app.map;

import de.audi.atip.interapp.NaviOnlineService$NaviOnlineMapOverlay;
import de.audi.atip.timer.Timer;
import de.audi.atip.timer.TimerListener;
import de.audi.tghu.navi.app.favorite.IFavorite;
import de.audi.tghu.navi.app.map.IMapContent;
import de.audi.tghu.navi.app.map.utils.MapPin;
import de.audi.tghu.navi.app.poi.online.OnlinePOIResultList;
import org.dsi.ifc.global.NavLocation;
import org.dsi.ifc.global.NavLocationWgs84;
import org.dsi.ifc.global.NavRectangle;
import org.dsi.ifc.global.ResourceLocator;
import org.dsi.ifc.map.PosInfo;
import org.dsi.ifc.navigation.CalculatedRouteListElement;
import org.dsi.ifc.organizer.AdbEntry;
import org.dsi.ifc.tmc.TmcListElement;
import org.dsi.ifc.tmc.TmcMessage;

public class MapDataContainer {
    public int iShowTrigger = -1;
    public boolean isInNavi = false;
    public int[] sBackupPoiVisibleUid = null;
    public boolean[] sBackupPoiVisibleStatus = null;
    public boolean sPoiTypeVisibilityDirty = false;
    boolean sRCCIEnabled = false;
    TmcMessage sTmcMessage = null;
    public OnlinePOIResultList sOnlinePOIResultList = null;
    public OnlinePOIResultList sRemoteHMIResultList = null;
    AdbEntry sHomeDestination = null;
    public AdbEntry[] sTopDestinations = null;
    public NavLocation sHomeAddress = null;
    public NavLocation sOfficeAddress = null;
    public TmcMessage mapToolTipTMCMessage = null;
    public MapPin[] sPins = null;
    int sSwitchBackToContext = 0;
    int sDisplayNightDesign = -1;
    TmcMessage[] sTMCMessageAhead = null;
    public boolean sRGActive = false;
    boolean sRequestedVisibility = false;
    boolean sRequestedFreeze = false;
    boolean sSDSDialogActive = false;
    public NavLocation sEnterInMapLocation = null;
    public boolean keepLocationFocus = false;
    public NavLocation sFocusedPosition = null;
    public float sFocusedZoom = 32959;
    public short sFocusedRotation = 0;
    public boolean sForceUseEnterInMapLocation = false;
    public boolean sForceUseEnterInMapRestoreZoom = false;
    public NavLocation sPicNavMapLocation = null;
    public int sPicNavMapFilterId = -1;
    public boolean sPicNavMapShowPicNavIcons = false;
    public String sPicNavMapTooltipString = null;
    public ResourceLocator sPicNavMapTooltipLocator = null;
    public float fUserZoomLevel = 32959;
    public float lastZoomLevelInCrossHairMode = 32959;
    int sFrozenLevel = 0;
    int sKeptContext = 0;
    public int sDistanceToNextManeuver = 0;
    String sDistString = null;
    public boolean sManoeuvreZoomDisabledWithReturn = false;
    public boolean sAutozoomTemporarilyDisabled = false;
    public boolean sForceRestoreUserZoomLevel = false;
    public boolean sSwitchDisplayContextImmediately = true;
    public int sVisibleDisplayContextID = 0;
    public int sRequestedDisplayContextID = 0;
    public boolean sDisplayContextAnimationRunning = false;
    public IMapContent sMapContentList = null;
    public boolean isInMap = false;
    private boolean isInMapMain = false;
    public boolean isInOnlineMap = false;
    public boolean isInVia = false;
    public int viewSize = 2;
    public int requestedViewSize = 2;
    public TimerListener gridMaskDelayTimer = null;
    public TimerListener gridMaskWatchdogTimer = null;
    public Object refreshGoogleDataConnectionStateMutex = new Object();
    public int mobilityHorizonStatus = 0;
    public boolean carIsMoving = false;
    public boolean googleTempDisabled = false;
    public boolean sInitalization = true;
    public String s3DLandmarkString = null;
    public PosInfo s3DLandmarkPositionInfo = null;
    public int s3DLandmarkX = -1;
    public int s3DLandmarkY = -1;
    public boolean sShowManeuverViews = false;
    public boolean sShowMapInMap = false;
    public int sToolTipMode = 0;
    public long[] sMapInMapFlagHandles = null;
    public boolean sJoystickIdle = true;
    public boolean sScrollByCrossHairsEnabled = true;
    public boolean sNeedToSetScrollOnRoutePosition = true;
    public NavLocationWgs84 sOldLocationAfterTMCMap = null;
    public int sSavedZoomIndexAfterTMCMap = -1;
    public short sSavedRotationAfterTMCMap = 0;
    public NavLocationWgs84 sOldLocationAfterCrosshairMap = null;
    public int sSavedZoomIndexAfterCrosshairMap = -1;
    public short sSavedRotationAfterCrosshairMap = 0;
    public boolean sScrollToDirectionActive = false;
    public int sMapScrollDir = -1;
    public boolean sStartPoint;
    public boolean unblockOnExit = true;
    public TimerListener sZoomDisableTimer = null;
    public boolean sZoomTimerActivateMZ = false;
    public boolean sZoomTimerDeactivateMZ = false;
    public int sSavedOrientationWhileManoeuvre = -1;
    public int oldBapManoeuvreState = -1;
    public int actualBapManoeuvreState = -1;
    public boolean zoomTempDeactivated = false;
    public NavRectangle focusRectangle;
    public TimerListener sHideToolTipTimer = null;
    public int sAutoOrientationThreshold = -1;
    public float sOrientationThresholdPM = 32959;
    public int sRcciEnterTrigger = -1;
    public CalculatedRouteListElement[] rcciRoutes;
    public int rcciFocusedRoute;
    public CalculatedRouteListElement[] altRoutes;
    public int altFocusedRoute;
    public boolean enterAltRoutesFromRightDrawer = false;
    public Object switchToMapMutex = new Object();
    public boolean switchBackToCalculation = true;
    public TimerListener sInfoTimer = null;
    public TimerListener sCcpChangeTimer = null;
    public TimerListener sDdsChangeTimer = null;
    public boolean sCrosshairMode = false;
    public String sMessage;
    public int sTMCNumber;
    public int sTMCTotal;
    public PosInfo sPositionInfo = null;
    public long sMessageId;
    public long[] sTmcMessageIds = new long[0];
    public TmcMessage tmcMessageToBeShown = null;
    public NavRectangle sTmcNavRectangle = null;
    public TmcListElement sTmcListElement = null;
    public TmcMessage trafficNoticeMessage = null;
    public NavRectangle trafficNoticeRectangle = null;
    public int trafficNoticeSoundID = -1;
    public Timer sRefreshETATimer = null;
    public volatile NavLocationWgs84 sPicNavCarouselMapPosition = null;
    public TimerListener sLongPressSnapshotTimer = null;
    public boolean showSVnotWhileDrivingPopUp = false;
    public int sPreviewMapWidth;
    public int sPreviewMapHeight;
    public int sPreviewMapOffsetX;
    public int sPreviewMapOffsetY;
    public int distToNextDest = 0;
    public int weatherSetId;
    public NaviOnlineService$NaviOnlineMapOverlay[] weatherData = null;
    public int weatherDelayInMillisBetweenImages;
    public NavLocationWgs84 sRubberbandPoint = null;
    public boolean enterRbbFromRightDrawer = false;
    public NavRectangle rubberbandViewPort = null;
    public boolean sEnterInMapShowPin = false;
    public IFavorite sEnterInMapFavorite = null;
    public boolean sEnterInMapHidePois = false;
    public NavLocationWgs84 operatorCallResultLocation = null;
    public boolean vicsEmergencyPopupShown = false;
    public boolean ignoreAutomaticMapSwitchOnStartGuidance = false;
    public int currentVehicleHeading = -1;
    public boolean showLastTmcFromCtxCrosshairEnterInMapRequested = false;
    public boolean newToolTipInformationRequested = false;
    public int activeNaviOrMapContext = 0;
    public boolean sDisableKDKTemporarily = false;
    public boolean isShowLocFromDest = false;
    public boolean isShowDetailsFromDest = false;
    public boolean isShowTmcFromDest = false;
    public NavLocation locInMap;
    public TmcMessage tmcInMap;
    public int selectedItemCtxRCCIMap;
    public boolean showPreviewMapItemInMap = false;
    public boolean showLastTmcFromCtxCrosshairInMapGeneral = false;
    public int currentNavTab;
    public boolean hkBackInCtxHidden;
    public boolean isInPreviewMap;
    public boolean isInPredictiveaNavigation;
    public boolean ctxDestinationMapPCoreToCrosshairMapPCore_keepOrientation = false;
    public short ctxDestinationMapPCoreToCrosshairMapPCore_touchScreenRotateAngle;
    public boolean ctxCrosshairEnterInMapPCoreToCrosshairMapPCore_keepOrientation = false;
    public int ctxCrosshairEnterInMapPCoreToCrosshairMapPCore_orientation;
    public short ctxCrosshairEnterInMapPCoreToCrosshairMapPCore_touchScreenRotateAngle = 0;

    public boolean isInMapMain() {
        return this.isInMapMain;
    }

    public void setInMapMain(boolean bl) {
        this.isInMapMain = bl;
    }
}

