/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.generalvehiclestates;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_AIRBAGDATA = 2;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_TANKINFO = 4;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DIMMEDHEADLIGHT = 5;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_ACOUSTICPARKINGSYSTEM = 6;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_CARVELOCITYTHRESHOLD = 7;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_TVVELOCITYTHRESHOLD = 8;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_HDDVELOCITYTHRESHOLD = 9;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERSLIDESHOWVELOCITYTHRESHOLD = 10;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERBORDBOOKVELOCITYTHRESHOLD = 11;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERTRAVELAGENTVELOCITYTHRESHOLD = 12;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BROWSERWEBVELOCITYTHRESHOLD = 13;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BWSVELOCITYTHRESHOLD = 14;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_RADIOTEXTVELOCITYTHRESHOLD = 15;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DISPLAYDAYNIGHTDESIGN = 16;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_BTBONDINGVELOCITYTHRESHOLD = 17;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_MESSAGINGVELOCITYTHRESHOLD = 18;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DESTINATIONINPUTVELOCITYTHRESHOLD = 19;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_REVERSEGEAR = 20;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_DSSSVIEWOPTION = 21;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_VEHICLESTANDSTILL = 22;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_SERVICEKEYDATA = 23;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_SERVICEKEYVIEWOPTION = 24;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_PERSONALIZATIONSTATUS = 25;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_TLOVIEWOPTIONS = 26;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_EMERGENCYASSISTVOLLOWERING = 27;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_PARKINGBRAKE = 28;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_APPCONNECTTRIGGER = 30;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_STPSTATE = 31;
    public static final int ATTRIBUTE_ID_DSIGENERALVEHICLESTATES_AUTOMATICGEARSHIFTTRANSMODE = 32;
}

