/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.kombisync2;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBICOMMUNICATIONSTATE = 1;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEDISPLAYIDENTIFICATION = 2;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEDISPLAYREQUESTRESPONSE = 3;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEDISPLAYSTATUS = 4;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEPOPUPACTIONREQUEST = 5;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEPOPUPREGISTERRESPONSE = 6;
    public static final int ATTRIBUTE_ID_DSIKOMBISYNC_KOMBIMESSAGESTATEPOPUPSTATUS = 7;
}

