/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.interapp.media;

import de.esolutions.fw.util.commons.SimpleIntIntMap;

public class DVDVideoSettingsLanguageMapping {
    public static final int TEXT_UNKNOWN;
    public static final int TEXT_AF_AFR;
    public static final int TEXT_AR_ARA;
    public static final int TEXT_AZ_AZE;
    public static final int TEXT_BE_BEL;
    public static final int TEXT_BG_BUL;
    public static final int TEXT_BR_BRE;
    public static final int TEXT_CA_CAT;
    public static final int TEXT_CS_CZE_CES;
    public static final int TEXT_CY_WEL;
    public static final int TEXT_DA_DAN;
    public static final int TEXT_DE_GER_DEU;
    public static final int TEXT_EL_GRE_ELL;
    public static final int TEXT_EN_ENG;
    public static final int TEXT_EO_EPO;
    public static final int TEXT_ES_SPA;
    public static final int TEXT_ET_EST;
    public static final int TEXT_EU_BAQ_EUS;
    public static final int TEXT_FI_FIN;
    public static final int TEXT_FO_FAO;
    public static final int TEXT_FR_FRE_FRA;
    public static final int TEXT_FY_FRY;
    public static final int TEXT_GA_GLE;
    public static final int TEXT_GD_GLA;
    public static final int TEXT_GV_GLV;
    public static final int TEXT_HE_HEB;
    public static final int TEXT_HR_HRV;
    public static final int TEXT_HU_HUN;
    public static final int TEXT_ID_IND;
    public static final int TEXT_IS_ICE_ISL;
    public static final int TEXT_IT_ITA;
    public static final int TEXT_JA_JPN;
    public static final int TEXT_KL_KAL;
    public static final int TEXT_KU_KUR;
    public static final int TEXT_LA_LAT;
    public static final int TEXT_LB_LTZ;
    public static final int TEXT_LT_LIT;
    public static final int TEXT_LV_LAV;
    public static final int TEXT_MK_MAC_MKD;
    public static final int TEXT_MT_MLT;
    public static final int TEXT_NL_DUT_NLD;
    public static final int TEXT_NO_NOR;
    public static final int TEXT_PL_POL;
    public static final int TEXT_PT_POR;
    public static final int TEXT_RM_ROH;
    public static final int TEXT_RO_RUM_RON;
    public static final int TEXT_RU_RUS;
    public static final int TEXT_SE_SME;
    public static final int TEXT_SK_SLO_SLK;
    public static final int TEXT_SL_SLV;
    public static final int TEXT_SO_SOM;
    public static final int TEXT_SQ_ALB_SQI;
    public static final int TEXT_SR_SRP;
    public static final int TEXT_SV_SWE;
    public static final int TEXT_SW_SWA;
    public static final int TEXT_TR_TUR;
    public static final int TEXT_UK_UKR;
    public static final int TEXT_VI_VIE;
    public static final int TEXT_YI_YID;
    public static final int TEXT_ZH_CHI_ZHO;
    public static final int TEXT_IW;
    public static final int TEXT_JI;
    public static final int TEXT_AA_AAR;
    public static final int TEXT_AB_ABK;
    public static final int TEXT_AM_AMH;
    public static final int TEXT_AS_ASM;
    public static final int TEXT_AY_AYM;
    public static final int TEXT_BA_BAK;
    public static final int TEXT_BH_BIH;
    public static final int TEXT_BI_BIS;
    public static final int TEXT_BN_BEN;
    public static final int TEXT_BO_TIB_BOD;
    public static final int TEXT_CO_COS;
    public static final int TEXT_DZ_DZO;
    public static final int TEXT_FA_PER_FAS;
    public static final int TEXT_FJ_FIJ;
    public static final int TEXT_GL_GLG;
    public static final int TEXT_GN_GRN;
    public static final int TEXT_GU_GUJ;
    public static final int TEXT_HA_HAU;
    public static final int TEXT_HI_HIN;
    public static final int TEXT_HY_ARM_HYE;
    public static final int TEXT_IA_INA;
    public static final int TEXT_IE_ILE;
    public static final int TEXT_IK_IPK;
    public static final int TEXT_IN;
    public static final int TEXT_JW_JAV_JAW;
    public static final int TEXT_KA_GEO_KAT;
    public static final int TEXT_KK_KAZ;
    public static final int TEXT_KM_KHM;
    public static final int TEXT_KN_KAN;
    public static final int TEXT_KO_KOR;
    public static final int TEXT_KS_KAS;
    public static final int TEXT_KY_KIR;
    public static final int TEXT_LN_LIN;
    public static final int TEXT_LO_LAO;
    public static final int TEXT_MG_MLG;
    public static final int TEXT_MI_MAO_MRI;
    public static final int TEXT_ML_MAL;
    public static final int TEXT_MN_MON;
    public static final int TEXT_MO_MOL;
    public static final int TEXT_MR_MAR;
    public static final int TEXT_MS_MAY_MSA;
    public static final int TEXT_MY_BUR_MYA;
    public static final int TEXT_NA_NAU;
    public static final int TEXT_NE_NEP;
    public static final int TEXT_OC_OCI;
    public static final int TEXT_OR_ORI;
    public static final int TEXT_OM_ORM;
    public static final int TEXT_QU_QUE;
    public static final int TEXT_PA_PAN;
    public static final int TEXT_PS_PUS;
    public static final int TEXT_RN_RUN;
    public static final int TEXT_RW_KIN;
    public static final int TEXT_SA_SAN;
    public static final int TEXT_SD_SND;
    public static final int TEXT_SG_SAG;
    public static final int TEXT_SH_SCR;
    public static final int TEXT_SI_SIN;
    public static final int TEXT_SM_SMO;
    public static final int TEXT_SN_SNA;
    public static final int TEXT_SS_SSW;
    public static final int TEXT_ST_SOT;
    public static final int TEXT_SU_SUN;
    public static final int TEXT_TA_TAM;
    public static final int TEXT_TE_TEL;
    public static final int TEXT_TG_TGK;
    public static final int TEXT_TH_THA;
    public static final int TEXT_TI_TIR;
    public static final int TEXT_TK_TUK;
    public static final int TEXT_TL_TGL;
    public static final int TEXT_TN_TSN;
    public static final int TEXT_TO_TON;
    public static final int TEXT_TS_TSO;
    public static final int TEXT_TT_TAT;
    public static final int TEXT_TW_TWI;
    public static final int TEXT_UR_URD;
    public static final int TEXT_UZ_UZB;
    public static final int TEXT_VO_VOL;
    public static final int TEXT_WO_WOL;
    public static final int TEXT_XH_XHO;
    public static final int TEXT_YO_YOR;
    public static final int TEXT_ZU_ZUL;
    public static final int TEXT_OFF;
    public static final int NUMBER_OF_TEXT_IDS;
    public static final int LC_UNKNOWN;
    private static final int OFF;
    private static final int LC_AA;
    private static final int LC_AB;
    private static final int LC_AF;
    private static final int LC_AM;
    private static final int LC_AR;
    private static final int LC_AS;
    private static final int LC_AZ;
    private static final int LC_AY;
    private static final int LC_BA;
    private static final int LC_BE;
    private static final int LC_BH;
    private static final int LC_BG;
    private static final int LC_BI;
    private static final int LC_BN;
    private static final int LC_BO;
    private static final int LC_BR;
    private static final int LC_CA;
    private static final int LC_CO;
    private static final int LC_CS;
    private static final int LC_CY;
    private static final int LC_DA;
    private static final int LC_DE;
    private static final int LC_DZ;
    private static final int LC_EL;
    private static final int LC_EN;
    private static final int LC_EO;
    private static final int LC_ES;
    private static final int LC_ET;
    private static final int LC_EU;
    private static final int LC_FA;
    private static final int LC_FI;
    private static final int LC_FJ;
    private static final int LC_FO;
    private static final int LC_FR;
    private static final int LC_FY;
    private static final int LC_GA;
    private static final int LC_GD;
    private static final int LC_GL;
    private static final int LC_GN;
    private static final int LC_GU;
    private static final int LC_GV;
    private static final int LC_HA;
    private static final int LC_HE;
    private static final int LC_HI;
    private static final int LC_HR;
    private static final int LC_HU;
    private static final int LC_HY;
    private static final int LC_IA;
    private static final int LC_ID;
    private static final int LC_IE;
    private static final int LC_IK;
    private static final int LC_IN;
    private static final int LC_IS;
    private static final int LC_IT;
    private static final int LC_IW;
    private static final int LC_JA;
    private static final int LC_JI;
    private static final int LC_JW;
    private static final int LC_KA;
    private static final int LC_KK;
    private static final int LC_KL;
    private static final int LC_KM;
    private static final int LC_KN;
    private static final int LC_KO;
    private static final int LC_KS;
    private static final int LC_KU;
    private static final int LC_KY;
    private static final int LC_LA;
    private static final int LC_LB;
    private static final int LC_LN;
    private static final int LC_LO;
    private static final int LC_LT;
    private static final int LC_LV;
    private static final int LC_MG;
    private static final int LC_MI;
    private static final int LC_MK;
    private static final int LC_ML;
    private static final int LC_MN;
    private static final int LC_MO;
    private static final int LC_MR;
    private static final int LC_MS;
    private static final int LC_MT;
    private static final int LC_MY;
    private static final int LC_NA;
    private static final int LC_NE;
    private static final int LC_NL;
    private static final int LC_NO;
    private static final int LC_OC;
    private static final int LC_OR;
    private static final int LC_OM;
    private static final int LC_QU;
    private static final int LC_PA;
    private static final int LC_PL;
    private static final int LC_PS;
    private static final int LC_PT;
    private static final int LC_RN;
    private static final int LC_RM;
    private static final int LC_RO;
    private static final int LC_RU;
    private static final int LC_RW;
    private static final int LC_SA;
    private static final int LC_SD;
    private static final int LC_SE;
    private static final int LC_SG;
    private static final int LC_SH;
    private static final int LC_SI;
    private static final int LC_SK;
    private static final int LC_SL;
    private static final int LC_SM;
    private static final int LC_SN;
    private static final int LC_SO;
    private static final int LC_SQ;
    private static final int LC_SR;
    private static final int LC_SS;
    private static final int LC_ST;
    private static final int LC_SU;
    private static final int LC_SV;
    private static final int LC_SW;
    private static final int LC_TA;
    private static final int LC_TE;
    private static final int LC_TG;
    private static final int LC_TH;
    private static final int LC_TI;
    private static final int LC_TK;
    private static final int LC_TL;
    private static final int LC_TN;
    private static final int LC_TO;
    private static final int LC_TS;
    private static final int LC_TT;
    private static final int LC_TR;
    private static final int LC_TW;
    private static final int LC_UK;
    private static final int LC_UR;
    private static final int LC_UZ;
    private static final int LC_VI;
    private static final int LC_VO;
    private static final int LC_WO;
    private static final int LC_XH;
    private static final int LC_YI;
    private static final int LC_YO;
    private static final int LC_ZH;
    private static final int LC_ZU;
    private final SimpleIntIntMap languageCodeMap = new SimpleIntIntMap(144);

    public DVDVideoSettingsLanguageMapping() {
        this.initMapping();
    }

    public int getArrayPosition(int n) {
        int n2 = this.languageCodeMap.get(n);
        if (n2 != -1) {
            return n2;
        }
        return this.languageCodeMap.get(0);
    }

    private void initMapping() {
        this.languageCodeMap.add(0, 0);
        this.languageCodeMap.add(26209, 1);
        this.languageCodeMap.add(29281, 2);
        this.languageCodeMap.add(31329, 3);
        this.languageCodeMap.add(25954, 4);
        this.languageCodeMap.add(26466, 5);
        this.languageCodeMap.add(29282, 6);
        this.languageCodeMap.add(24931, 7);
        this.languageCodeMap.add(29539, 8);
        this.languageCodeMap.add(31075, 9);
        this.languageCodeMap.add(24932, 10);
        this.languageCodeMap.add(25956, 11);
        this.languageCodeMap.add(27749, 12);
        this.languageCodeMap.add(28261, 13);
        this.languageCodeMap.add(28517, 14);
        this.languageCodeMap.add(29541, 15);
        this.languageCodeMap.add(29797, 16);
        this.languageCodeMap.add(30053, 17);
        this.languageCodeMap.add(26982, 18);
        this.languageCodeMap.add(28518, 19);
        this.languageCodeMap.add(29286, 20);
        this.languageCodeMap.add(31078, 21);
        this.languageCodeMap.add(24935, 22);
        this.languageCodeMap.add(25703, 23);
        this.languageCodeMap.add(30311, 24);
        this.languageCodeMap.add(25960, 25);
        this.languageCodeMap.add(29288, 26);
        this.languageCodeMap.add(30056, 27);
        this.languageCodeMap.add(25705, 28);
        this.languageCodeMap.add(29545, 29);
        this.languageCodeMap.add(29801, 30);
        this.languageCodeMap.add(24938, 31);
        this.languageCodeMap.add(27755, 32);
        this.languageCodeMap.add(30059, 33);
        this.languageCodeMap.add(24940, 34);
        this.languageCodeMap.add(25196, 35);
        this.languageCodeMap.add(29804, 36);
        this.languageCodeMap.add(30316, 37);
        this.languageCodeMap.add(27501, 38);
        this.languageCodeMap.add(29805, 39);
        this.languageCodeMap.add(27758, 40);
        this.languageCodeMap.add(28526, 41);
        this.languageCodeMap.add(27760, 42);
        this.languageCodeMap.add(29808, 43);
        this.languageCodeMap.add(28018, 44);
        this.languageCodeMap.add(28530, 45);
        this.languageCodeMap.add(30066, 46);
        this.languageCodeMap.add(25971, 47);
        this.languageCodeMap.add(27507, 48);
        this.languageCodeMap.add(27763, 49);
        this.languageCodeMap.add(28531, 50);
        this.languageCodeMap.add(29043, 51);
        this.languageCodeMap.add(29299, 52);
        this.languageCodeMap.add(30323, 53);
        this.languageCodeMap.add(30579, 54);
        this.languageCodeMap.add(29300, 55);
        this.languageCodeMap.add(27509, 56);
        this.languageCodeMap.add(26998, 57);
        this.languageCodeMap.add(27001, 58);
        this.languageCodeMap.add(26746, 59);
        this.languageCodeMap.add(30569, 60);
        this.languageCodeMap.add(26986, 61);
        this.languageCodeMap.add(24929, 62);
        this.languageCodeMap.add(25185, 63);
        this.languageCodeMap.add(28001, 64);
        this.languageCodeMap.add(29537, 65);
        this.languageCodeMap.add(31073, 66);
        this.languageCodeMap.add(24930, 67);
        this.languageCodeMap.add(26722, 68);
        this.languageCodeMap.add(26978, 69);
        this.languageCodeMap.add(28258, 70);
        this.languageCodeMap.add(28514, 71);
        this.languageCodeMap.add(28515, 72);
        this.languageCodeMap.add(31332, 73);
        this.languageCodeMap.add(24934, 74);
        this.languageCodeMap.add(27238, 75);
        this.languageCodeMap.add(27751, 76);
        this.languageCodeMap.add(28263, 77);
        this.languageCodeMap.add(30055, 78);
        this.languageCodeMap.add(24936, 79);
        this.languageCodeMap.add(26984, 80);
        this.languageCodeMap.add(31080, 81);
        this.languageCodeMap.add(24937, 82);
        this.languageCodeMap.add(25961, 83);
        this.languageCodeMap.add(27497, 84);
        this.languageCodeMap.add(28265, 85);
        this.languageCodeMap.add(30570, 86);
        this.languageCodeMap.add(24939, 87);
        this.languageCodeMap.add(27499, 88);
        this.languageCodeMap.add(28011, 89);
        this.languageCodeMap.add(28267, 90);
        this.languageCodeMap.add(28523, 91);
        this.languageCodeMap.add(29547, 92);
        this.languageCodeMap.add(31083, 93);
        this.languageCodeMap.add(28268, 94);
        this.languageCodeMap.add(28524, 95);
        this.languageCodeMap.add(26477, 96);
        this.languageCodeMap.add(26733, 97);
        this.languageCodeMap.add(27757, 98);
        this.languageCodeMap.add(28269, 99);
        this.languageCodeMap.add(28525, 100);
        this.languageCodeMap.add(29293, 101);
        this.languageCodeMap.add(29549, 102);
        this.languageCodeMap.add(31085, 103);
        this.languageCodeMap.add(24942, 104);
        this.languageCodeMap.add(25966, 105);
        this.languageCodeMap.add(25455, 106);
        this.languageCodeMap.add(29295, 107);
        this.languageCodeMap.add(28015, 108);
        this.languageCodeMap.add(28533, 109);
        this.languageCodeMap.add(24944, 110);
        this.languageCodeMap.add(29552, 111);
        this.languageCodeMap.add(27762, 112);
        this.languageCodeMap.add(30578, 113);
        this.languageCodeMap.add(24947, 114);
        this.languageCodeMap.add(25715, 115);
        this.languageCodeMap.add(26483, 116);
        this.languageCodeMap.add(26739, 117);
        this.languageCodeMap.add(26995, 118);
        this.languageCodeMap.add(28275, 119);
        this.languageCodeMap.add(28531, 120);
        this.languageCodeMap.add(29555, 121);
        this.languageCodeMap.add(29811, 122);
        this.languageCodeMap.add(30067, 123);
        this.languageCodeMap.add(24948, 124);
        this.languageCodeMap.add(25972, 125);
        this.languageCodeMap.add(26484, 126);
        this.languageCodeMap.add(26740, 127);
        this.languageCodeMap.add(26996, 128);
        this.languageCodeMap.add(27508, 129);
        this.languageCodeMap.add(27764, 130);
        this.languageCodeMap.add(28276, 131);
        this.languageCodeMap.add(28532, 132);
        this.languageCodeMap.add(29556, 133);
        this.languageCodeMap.add(29812, 134);
        this.languageCodeMap.add(30580, 135);
        this.languageCodeMap.add(29301, 136);
        this.languageCodeMap.add(31349, 137);
        this.languageCodeMap.add(28534, 138);
        this.languageCodeMap.add(28535, 139);
        this.languageCodeMap.add(26744, 140);
        this.languageCodeMap.add(28537, 141);
        this.languageCodeMap.add(30074, 142);
        this.languageCodeMap.add(1, 143);
    }
}

