/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.media.hmi.evohighscale;

import de.audi.atip.hmi.model.ListCell;
import de.audi.tghu.media.hmi.evohighscale.MediaScreenFactory;
import de.esolutions.hmi.widgets.audi.base.widgets.AbstractWidgetController;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.AxisConstraints;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayout;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayoutHints;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.CompositeRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MenuItemRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.ProgressBarRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LayoutContainerController;
import de.esolutions.hmi.widgets.audi.evo.widgets.ProgressBarController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemColumnsConstraints;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.list.ListItemFactory;

final class MediaScreenBag1$3
implements ListItemFactory {
    private final /* synthetic */ MediaScreenFactory val$factory;
    private final /* synthetic */ int val$terminalID;

    MediaScreenBag1$3(MediaScreenFactory mediaScreenFactory, int n) {
        this.val$factory = mediaScreenFactory;
        this.val$terminalID = n;
    }

    @Override
    public AbstractWidgetController createListItem(int n, ListCell[] listCellArray) {
        switch (n) {
            case 0: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.alignment = new int[]{8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 11, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController2 = this.createCell(1);
                GridLayoutHints gridLayoutHints2 = new GridLayoutHints(1, 0);
                gridLayoutHints2.hidemode = 0;
                GridLayout gridLayout2 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints2 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints2.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints2.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints2.hidemode = new int[]{2, 2, 2};
                gridLayout2.setColumnConstraints(menuItemColumnsConstraints2);
                AxisConstraints axisConstraints2 = new AxisConstraints(1);
                gridLayout2.setRowConstraints(axisConstraints2);
                AbstractWidgetController abstractWidgetController3 = this.createCell(2);
                GridLayoutHints gridLayoutHints3 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController4 = this.createCell(3);
                GridLayoutHints gridLayoutHints4 = new GridLayoutHints(1, 0);
                gridLayoutHints4.hidemode = 2;
                AbstractWidgetController abstractWidgetController5 = this.createCell(4);
                GridLayoutHints gridLayoutHints5 = new GridLayoutHints(2, 0);
                gridLayout2.setCellConstraints(new GridLayoutHints[]{gridLayoutHints3, gridLayoutHints4, gridLayoutHints5}, new Object[]{abstractWidgetController3, abstractWidgetController4, abstractWidgetController5});
                GridLayoutHints gridLayoutHints6 = new GridLayoutHints(0, 1);
                gridLayoutHints6.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2, gridLayoutHints6}, new Object[]{abstractWidgetController, abstractWidgetController2, gridLayout2});
                GridLayout gridLayout3 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints3 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints3.alignment = new int[]{8, 8};
                menuItemColumnsConstraints3.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints3.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints3.max = new int[]{-1, -1};
                menuItemColumnsConstraints3.min = new int[]{-1, -1};
                menuItemColumnsConstraints3.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints3.size = new int[]{-1, -1};
                menuItemColumnsConstraints3.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints3.hidemode = new int[]{0, 0};
                gridLayout3.setColumnConstraints(menuItemColumnsConstraints3);
                AxisConstraints axisConstraints3 = new AxisConstraints(2);
                axisConstraints3.alignment = new int[]{9, 9};
                axisConstraints3.gaps = new int[]{0, 11, 0};
                axisConstraints3.grow = new float[]{0.0f, 0.0f};
                axisConstraints3.max = new int[]{-1, -1};
                axisConstraints3.min = new int[]{-1, -1};
                axisConstraints3.shrink = new float[]{1.0f, 0.0f};
                axisConstraints3.size = new int[]{-1, -1};
                axisConstraints3.hidemode = new int[]{0, 0};
                gridLayout3.setRowConstraints(axisConstraints3);
                GridLayoutHints gridLayoutHints7 = new GridLayoutHints(0, 0);
                gridLayoutHints7.hidemode = 0;
                GridLayoutHints gridLayoutHints8 = new GridLayoutHints(1, 0);
                gridLayoutHints8.hidemode = 0;
                GridLayout gridLayout4 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints4 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints4.alignment = new int[]{8, 8, 8};
                menuItemColumnsConstraints4.gaps = new int[]{0, 10, 10, 0};
                menuItemColumnsConstraints4.grow = new float[]{0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints4.max = new int[]{-1, -1, -1};
                menuItemColumnsConstraints4.min = new int[]{-1, -1, -1};
                menuItemColumnsConstraints4.shrink = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints4.size = new int[]{-1, -1, -1};
                menuItemColumnsConstraints4.tabulatorIDs = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints4.hidemode = new int[]{0, 2, 0};
                gridLayout4.setColumnConstraints(menuItemColumnsConstraints4);
                AxisConstraints axisConstraints4 = new AxisConstraints(1);
                gridLayout4.setRowConstraints(axisConstraints4);
                GridLayoutHints gridLayoutHints9 = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints10 = new GridLayoutHints(1, 0);
                gridLayoutHints10.hidemode = 2;
                GridLayoutHints gridLayoutHints11 = new GridLayoutHints(2, 0);
                gridLayoutHints11.hidemode = 0;
                gridLayout4.setCellConstraints(new GridLayoutHints[]{gridLayoutHints9, gridLayoutHints10, gridLayoutHints11}, new Object[]{abstractWidgetController3, abstractWidgetController4, abstractWidgetController5});
                GridLayoutHints gridLayoutHints12 = new GridLayoutHints(0, 1);
                gridLayoutHints12.hidemode = 0;
                gridLayout3.setCellConstraints(new GridLayoutHints[]{gridLayoutHints7, gridLayoutHints8, gridLayoutHints12}, new Object[]{abstractWidgetController, abstractWidgetController2, gridLayout4});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout3});
                menuItemController.add(abstractWidgetController4);
                menuItemController.add(abstractWidgetController2);
                menuItemController.add(abstractWidgetController5);
                menuItemController.add(abstractWidgetController3);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 1: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.alignment = new int[]{8};
                menuItemColumnsConstraints.gaps = new int[]{0, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                menuItemColumnsConstraints.max = new int[]{-1};
                menuItemColumnsConstraints.min = new int[]{-1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f};
                menuItemColumnsConstraints.size = new int[]{-1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.gaps = new int[]{0, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints}, new Object[]{abstractWidgetController});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 2: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.alignment = new int[]{8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 10, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.alignmentHoriz = 8;
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController6 = this.createCell(5);
                GridLayoutHints gridLayoutHints13 = new GridLayoutHints(1, 0);
                gridLayoutHints13.hidemode = 0;
                GridLayout gridLayout5 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints5 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints5.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints5.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints5.hidemode = new int[]{2, 2, 2};
                gridLayout5.setColumnConstraints(menuItemColumnsConstraints5);
                AxisConstraints axisConstraints5 = new AxisConstraints(1);
                gridLayout5.setRowConstraints(axisConstraints5);
                AbstractWidgetController abstractWidgetController7 = this.createCell(2);
                GridLayoutHints gridLayoutHints14 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController8 = this.createCell(3);
                GridLayoutHints gridLayoutHints15 = new GridLayoutHints(1, 0);
                gridLayoutHints15.hidemode = 2;
                AbstractWidgetController abstractWidgetController9 = this.createCell(4);
                GridLayoutHints gridLayoutHints16 = new GridLayoutHints(2, 0);
                gridLayout5.setCellConstraints(new GridLayoutHints[]{gridLayoutHints14, gridLayoutHints15, gridLayoutHints16}, new Object[]{abstractWidgetController7, abstractWidgetController8, abstractWidgetController9});
                GridLayoutHints gridLayoutHints17 = new GridLayoutHints(0, 1);
                gridLayoutHints17.alignmentHoriz = 8;
                gridLayoutHints17.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints13, gridLayoutHints17}, new Object[]{abstractWidgetController, abstractWidgetController6, gridLayout5});
                GridLayout gridLayout6 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints6 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints6.gaps = new int[]{10, 15, 0, 0};
                menuItemColumnsConstraints6.grow = new float[]{0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints6.shrink = new float[]{0.0f, 1.0f, 0.0f};
                gridLayout6.setColumnConstraints(menuItemColumnsConstraints6);
                AxisConstraints axisConstraints6 = new AxisConstraints(6);
                axisConstraints6.alignment = new int[]{9, 9, 9, 9, 5, 9};
                axisConstraints6.gaps = new int[]{0, 0, 25, 18, 79, 0, 0};
                axisConstraints6.grow = new float[]{0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f};
                axisConstraints6.size = new int[]{42, -1, -1, -1, -1, -1};
                axisConstraints6.hidemode = new int[]{0, 1, 1, 0, 0, 0};
                gridLayout6.setRowConstraints(axisConstraints6);
                AbstractWidgetController abstractWidgetController10 = this.createCell(6);
                GridLayoutHints gridLayoutHints18 = new GridLayoutHints(0, 1);
                gridLayoutHints18.hidemode = 1;
                AbstractWidgetController abstractWidgetController11 = this.createCell(7);
                GridLayoutHints gridLayoutHints19 = new GridLayoutHints(1, 1);
                gridLayoutHints19.hidemode = 1;
                AbstractWidgetController abstractWidgetController12 = this.createCell(8);
                GridLayoutHints gridLayoutHints20 = new GridLayoutHints(2, 1);
                gridLayoutHints20.rowSpan = 4;
                gridLayoutHints20.widthMin = 18;
                gridLayoutHints20.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController13 = this.createCell(9);
                GridLayoutHints gridLayoutHints21 = new GridLayoutHints(0, 2);
                AbstractWidgetController abstractWidgetController14 = this.createCell(10);
                GridLayoutHints gridLayoutHints22 = new GridLayoutHints(1, 2);
                AbstractWidgetController abstractWidgetController15 = this.createCell(11);
                GridLayoutHints gridLayoutHints23 = new GridLayoutHints(0, 3);
                AbstractWidgetController abstractWidgetController16 = this.createCell(12);
                GridLayoutHints gridLayoutHints24 = new GridLayoutHints(1, 3);
                AbstractWidgetController abstractWidgetController17 = this.createCell(13);
                GridLayoutHints gridLayoutHints25 = new GridLayoutHints(0, 4);
                gridLayoutHints25.columnSpan = 2;
                gridLayout6.setCellConstraints(new GridLayoutHints[]{gridLayoutHints18, gridLayoutHints19, gridLayoutHints20, gridLayoutHints21, gridLayoutHints22, gridLayoutHints23, gridLayoutHints24, gridLayoutHints25}, new Object[]{abstractWidgetController10, abstractWidgetController11, abstractWidgetController12, abstractWidgetController13, abstractWidgetController14, abstractWidgetController15, abstractWidgetController16, abstractWidgetController17});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout6});
                menuItemController.add(abstractWidgetController8);
                menuItemController.add(abstractWidgetController9);
                menuItemController.add(abstractWidgetController7);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController11);
                menuItemController.add(abstractWidgetController14);
                menuItemController.add(abstractWidgetController16);
                menuItemController.add(abstractWidgetController17);
                menuItemController.add(abstractWidgetController6);
                menuItemController.add(abstractWidgetController10);
                menuItemController.add(abstractWidgetController13);
                menuItemController.add(abstractWidgetController15);
                menuItemController.add(abstractWidgetController12);
                return menuItemController;
            }
            case 3: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.gaps = new int[]{0, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController18 = this.createCell(5);
                GridLayoutHints gridLayoutHints26 = new GridLayoutHints(1, 0);
                gridLayoutHints26.alignmentHoriz = 3;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints26}, new Object[]{abstractWidgetController, abstractWidgetController18});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController18);
                return menuItemController;
            }
            case 4: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout7 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints7 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints7.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints7.hidemode = new int[]{2, 0};
                gridLayout7.setColumnConstraints(menuItemColumnsConstraints7);
                AxisConstraints axisConstraints7 = new AxisConstraints(1);
                gridLayout7.setRowConstraints(axisConstraints7);
                AbstractWidgetController abstractWidgetController = this.createCell(14);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController19 = this.createCell(15);
                GridLayoutHints gridLayoutHints27 = new GridLayoutHints(1, 0);
                gridLayout7.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints27}, new Object[]{abstractWidgetController, abstractWidgetController19});
                GridLayoutHints gridLayoutHints28 = new GridLayoutHints(0, 0);
                gridLayoutHints28.hidemode = 0;
                AbstractWidgetController abstractWidgetController20 = this.createCell(16);
                GridLayoutHints gridLayoutHints29 = new GridLayoutHints(1, 0);
                gridLayoutHints29.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints28, gridLayoutHints29}, new Object[]{gridLayout7, abstractWidgetController20});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController20);
                menuItemController.add(abstractWidgetController19);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 5: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout8 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints8 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints8.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints8.hidemode = new int[]{2, 0};
                gridLayout8.setColumnConstraints(menuItemColumnsConstraints8);
                AxisConstraints axisConstraints8 = new AxisConstraints(1);
                gridLayout8.setRowConstraints(axisConstraints8);
                AbstractWidgetController abstractWidgetController = this.createCell(14);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController21 = this.createCell(15);
                GridLayoutHints gridLayoutHints30 = new GridLayoutHints(1, 0);
                gridLayoutHints30.hidemode = 2;
                gridLayout8.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints30}, new Object[]{abstractWidgetController, abstractWidgetController21});
                GridLayoutHints gridLayoutHints31 = new GridLayoutHints(0, 0);
                gridLayoutHints31.hidemode = 0;
                AbstractWidgetController abstractWidgetController22 = this.createCell(16);
                GridLayoutHints gridLayoutHints32 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints31, gridLayoutHints32}, new Object[]{gridLayout8, abstractWidgetController22});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController22);
                menuItemController.add(abstractWidgetController21);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 6: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout9 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints9 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints9.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints9.hidemode = new int[]{2, 0};
                gridLayout9.setColumnConstraints(menuItemColumnsConstraints9);
                AxisConstraints axisConstraints9 = new AxisConstraints(1);
                gridLayout9.setRowConstraints(axisConstraints9);
                AbstractWidgetController abstractWidgetController = this.createCell(14);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController23 = this.createCell(15);
                GridLayoutHints gridLayoutHints33 = new GridLayoutHints(1, 0);
                gridLayout9.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints33}, new Object[]{abstractWidgetController, abstractWidgetController23});
                GridLayoutHints gridLayoutHints34 = new GridLayoutHints(0, 0);
                gridLayoutHints34.hidemode = 0;
                AbstractWidgetController abstractWidgetController24 = this.createCell(16);
                GridLayoutHints gridLayoutHints35 = new GridLayoutHints(1, 0);
                gridLayoutHints35.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints34, gridLayoutHints35}, new Object[]{gridLayout9, abstractWidgetController24});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController24);
                menuItemController.add(abstractWidgetController23);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 7: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout10 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints10 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints10.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints10.hidemode = new int[]{2, 0};
                gridLayout10.setColumnConstraints(menuItemColumnsConstraints10);
                AxisConstraints axisConstraints10 = new AxisConstraints(1);
                gridLayout10.setRowConstraints(axisConstraints10);
                AbstractWidgetController abstractWidgetController = this.createCell(14);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController25 = this.createCell(15);
                GridLayoutHints gridLayoutHints36 = new GridLayoutHints(1, 0);
                gridLayout10.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints36}, new Object[]{abstractWidgetController, abstractWidgetController25});
                GridLayoutHints gridLayoutHints37 = new GridLayoutHints(0, 0);
                gridLayoutHints37.hidemode = 0;
                AbstractWidgetController abstractWidgetController26 = this.createCell(16);
                GridLayoutHints gridLayoutHints38 = new GridLayoutHints(1, 0);
                gridLayoutHints38.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints37, gridLayoutHints38}, new Object[]{gridLayout10, abstractWidgetController26});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController26);
                menuItemController.add(abstractWidgetController25);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 8: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.alignment = new int[]{8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 11, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController27 = this.createCell(1);
                GridLayoutHints gridLayoutHints39 = new GridLayoutHints(1, 0);
                gridLayoutHints39.hidemode = 0;
                GridLayout gridLayout11 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints11 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints11.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints11.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints11.hidemode = new int[]{2, 2, 2};
                gridLayout11.setColumnConstraints(menuItemColumnsConstraints11);
                AxisConstraints axisConstraints11 = new AxisConstraints(1);
                gridLayout11.setRowConstraints(axisConstraints11);
                AbstractWidgetController abstractWidgetController28 = this.createCell(2);
                GridLayoutHints gridLayoutHints40 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController29 = this.createCell(3);
                GridLayoutHints gridLayoutHints41 = new GridLayoutHints(1, 0);
                gridLayoutHints41.hidemode = 2;
                AbstractWidgetController abstractWidgetController30 = this.createCell(4);
                GridLayoutHints gridLayoutHints42 = new GridLayoutHints(2, 0);
                gridLayout11.setCellConstraints(new GridLayoutHints[]{gridLayoutHints40, gridLayoutHints41, gridLayoutHints42}, new Object[]{abstractWidgetController28, abstractWidgetController29, abstractWidgetController30});
                GridLayoutHints gridLayoutHints43 = new GridLayoutHints(0, 1);
                gridLayoutHints43.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints39, gridLayoutHints43}, new Object[]{abstractWidgetController, abstractWidgetController27, gridLayout11});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController29);
                menuItemController.add(abstractWidgetController27);
                menuItemController.add(abstractWidgetController30);
                menuItemController.add(abstractWidgetController28);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 9: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.alignment = new int[]{8};
                menuItemColumnsConstraints.gaps = new int[]{0, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                menuItemColumnsConstraints.max = new int[]{-1};
                menuItemColumnsConstraints.min = new int[]{-1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f};
                menuItemColumnsConstraints.size = new int[]{-1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.gaps = new int[]{0, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints}, new Object[]{abstractWidgetController});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 10: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.alignment = new int[]{8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 10, 0};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.alignmentHoriz = 8;
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController31 = this.createCell(5);
                GridLayoutHints gridLayoutHints44 = new GridLayoutHints(1, 0);
                gridLayoutHints44.hidemode = 0;
                GridLayout gridLayout12 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints12 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints12.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints12.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints12.hidemode = new int[]{2, 2, 2};
                gridLayout12.setColumnConstraints(menuItemColumnsConstraints12);
                AxisConstraints axisConstraints12 = new AxisConstraints(1);
                gridLayout12.setRowConstraints(axisConstraints12);
                AbstractWidgetController abstractWidgetController32 = this.createCell(2);
                GridLayoutHints gridLayoutHints45 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController33 = this.createCell(3);
                GridLayoutHints gridLayoutHints46 = new GridLayoutHints(1, 0);
                gridLayoutHints46.hidemode = 2;
                AbstractWidgetController abstractWidgetController34 = this.createCell(4);
                GridLayoutHints gridLayoutHints47 = new GridLayoutHints(2, 0);
                gridLayout12.setCellConstraints(new GridLayoutHints[]{gridLayoutHints45, gridLayoutHints46, gridLayoutHints47}, new Object[]{abstractWidgetController32, abstractWidgetController33, abstractWidgetController34});
                GridLayoutHints gridLayoutHints48 = new GridLayoutHints(0, 1);
                gridLayoutHints48.alignmentHoriz = 8;
                gridLayoutHints48.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints44, gridLayoutHints48}, new Object[]{abstractWidgetController, abstractWidgetController31, gridLayout12});
                GridLayout gridLayout13 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints13 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints13.gaps = new int[]{10, 15, 0, 0};
                menuItemColumnsConstraints13.grow = new float[]{0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints13.shrink = new float[]{0.0f, 1.0f, 0.0f};
                gridLayout13.setColumnConstraints(menuItemColumnsConstraints13);
                AxisConstraints axisConstraints13 = new AxisConstraints(7);
                axisConstraints13.alignment = new int[]{9, 9, 5, 5, 9, 9, 9};
                axisConstraints13.gaps = new int[]{0, 0, 25, 18, 30, 16, 0, 0};
                axisConstraints13.grow = new float[]{1.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 1.0f};
                axisConstraints13.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f, 1.0f, 1.0f, 1.0f};
                axisConstraints13.size = new int[]{42, -1, -1, -1, -1, -1, -1};
                axisConstraints13.hidemode = new int[]{0, 1, 1, 1, 0, 0, 0};
                gridLayout13.setRowConstraints(axisConstraints13);
                AbstractWidgetController abstractWidgetController35 = this.createCell(6);
                GridLayoutHints gridLayoutHints49 = new GridLayoutHints(0, 1);
                gridLayoutHints49.hidemode = 1;
                AbstractWidgetController abstractWidgetController36 = this.createCell(7);
                GridLayoutHints gridLayoutHints50 = new GridLayoutHints(1, 1);
                AbstractWidgetController abstractWidgetController37 = this.createCell(8);
                GridLayoutHints gridLayoutHints51 = new GridLayoutHints(2, 1);
                gridLayoutHints51.rowSpan = 5;
                gridLayoutHints51.widthMin = 18;
                gridLayoutHints51.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController38 = this.createCell(9);
                GridLayoutHints gridLayoutHints52 = new GridLayoutHints(0, 2);
                AbstractWidgetController abstractWidgetController39 = this.createCell(10);
                GridLayoutHints gridLayoutHints53 = new GridLayoutHints(1, 2);
                AbstractWidgetController abstractWidgetController40 = this.createCell(11);
                GridLayoutHints gridLayoutHints54 = new GridLayoutHints(0, 3);
                AbstractWidgetController abstractWidgetController41 = this.createCell(12);
                GridLayoutHints gridLayoutHints55 = new GridLayoutHints(1, 3);
                GridLayout gridLayout14 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints14 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints14.gaps = new int[]{0, 22, 22, 22, 0};
                gridLayout14.setColumnConstraints(menuItemColumnsConstraints14);
                AxisConstraints axisConstraints14 = new AxisConstraints(1);
                gridLayout14.setRowConstraints(axisConstraints14);
                AbstractWidgetController abstractWidgetController42 = this.createCell(17);
                GridLayoutHints gridLayoutHints56 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController43 = this.createCell(18);
                GridLayoutHints gridLayoutHints57 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController44 = this.createCell(19);
                GridLayoutHints gridLayoutHints58 = new GridLayoutHints(2, 0);
                AbstractWidgetController abstractWidgetController45 = this.createCell(20);
                GridLayoutHints gridLayoutHints59 = new GridLayoutHints(3, 0);
                gridLayout14.setCellConstraints(new GridLayoutHints[]{gridLayoutHints56, gridLayoutHints57, gridLayoutHints58, gridLayoutHints59}, new Object[]{abstractWidgetController42, abstractWidgetController43, abstractWidgetController44, abstractWidgetController45});
                GridLayoutHints gridLayoutHints60 = new GridLayoutHints(0, 4);
                gridLayoutHints60.columnSpan = 2;
                AbstractWidgetController abstractWidgetController46 = this.createCell(13);
                GridLayoutHints gridLayoutHints61 = new GridLayoutHints(0, 5);
                gridLayoutHints61.columnSpan = 2;
                gridLayout13.setCellConstraints(new GridLayoutHints[]{gridLayoutHints49, gridLayoutHints50, gridLayoutHints51, gridLayoutHints52, gridLayoutHints53, gridLayoutHints54, gridLayoutHints55, gridLayoutHints60, gridLayoutHints61}, new Object[]{abstractWidgetController35, abstractWidgetController36, abstractWidgetController37, abstractWidgetController38, abstractWidgetController39, abstractWidgetController40, abstractWidgetController41, gridLayout14, abstractWidgetController46});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout13});
                menuItemController.add(abstractWidgetController33);
                menuItemController.add(abstractWidgetController42);
                menuItemController.add(abstractWidgetController43);
                menuItemController.add(abstractWidgetController45);
                menuItemController.add(abstractWidgetController44);
                menuItemController.add(abstractWidgetController34);
                menuItemController.add(abstractWidgetController32);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController36);
                menuItemController.add(abstractWidgetController39);
                menuItemController.add(abstractWidgetController41);
                menuItemController.add(abstractWidgetController46);
                menuItemController.add(abstractWidgetController31);
                menuItemController.add(abstractWidgetController35);
                menuItemController.add(abstractWidgetController38);
                menuItemController.add(abstractWidgetController40);
                menuItemController.add(abstractWidgetController37);
                return menuItemController;
            }
        }
        return null;
    }

    @Override
    public AbstractWidgetController createListItemNoData() {
        MenuItemController menuItemController = new MenuItemController();
        menuItemController.setType(16);
        menuItemController.setRenderer(new CompositeRendererHigh(menuItemController));
        GridLayout gridLayout = new GridLayout();
        MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
        menuItemColumnsConstraints.shrink = new float[]{0.0f};
        gridLayout.setColumnConstraints(menuItemColumnsConstraints);
        AxisConstraints axisConstraints = new AxisConstraints(2);
        axisConstraints.gaps = new int[]{0, 0, 0};
        gridLayout.setRowConstraints(axisConstraints);
        AbstractWidgetController abstractWidgetController = this.createCell(21);
        GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
        gridLayoutHints.hidemode = 0;
        AbstractWidgetController abstractWidgetController2 = this.createCell(22);
        GridLayoutHints gridLayoutHints2 = new GridLayoutHints(0, 1);
        gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2}, new Object[]{abstractWidgetController, abstractWidgetController2});
        menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
        menuItemController.add(abstractWidgetController);
        menuItemController.add(abstractWidgetController2);
        return menuItemController;
    }

    public AbstractWidgetController createCell(int n) {
        switch (n) {
            case 0: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setBounds(0, 0, 0, 0);
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(3);
                LabelController labelController2 = new LabelController();
                LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
                labelController2.setRenderer(labelRendererHigh2);
                labelController2.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -266992896, -954924288, -938147072, -921369856, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -233438464, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, 723190528, -334167296, -317390080, -300612864, -283835648, 656081664, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController2.setBounds(0, 0, 0, 0);
                labelController2.setChainedAction(1, 1);
                labelController2.setModelColumn(4);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setChainedAction(1, 1);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 10, 0};
                axisConstraints.hidemode = new int[]{2, 2};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints2 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints2);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints2 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2}, new Object[]{labelController2, labelController});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController2);
                return layoutContainerController;
            }
            case 1: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -888274176, -871496960});
                iconController.setChainedAction(1, 1);
                iconController.setModelColumn(20);
                iconController.setPreferredHeight(22);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 2: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(5);
                LabelController labelController3 = new LabelController();
                LabelRendererHigh labelRendererHigh3 = new LabelRendererHigh(labelController3);
                labelController3.setRenderer(labelRendererHigh3);
                labelRendererHigh3.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController3.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -1457782016, -954924288, -938147072, -921369856, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -1927412992, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, -350944512, -334167296, -317390080, -300612864, -283835648, -267058432, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController3.setBounds(0, 0, 0, 0);
                labelController3.setChainedAction(1, 1);
                labelController3.setColorIndices(new int[]{1, 7, 4, 2});
                labelController3.setModelColumn(6);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setChainedAction(1, 1);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.hidemode = new int[]{2, 2};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints3 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints3);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                GridLayoutHints gridLayoutHints3 = new GridLayoutHints(1, 0);
                gridLayoutHints3.hidemode = 2;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints3}, new Object[]{labelController, labelController3});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController3);
                return layoutContainerController;
            }
            case 3: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setTextIds(new int[]{588907264, 588907264, 606077696});
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(18);
                return labelController;
            }
            case 4: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(7);
                LabelController labelController4 = new LabelController();
                LabelRendererHigh labelRendererHigh4 = new LabelRendererHigh(labelController4);
                labelController4.setRenderer(labelRendererHigh4);
                labelRendererHigh4.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController4.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -266992896, -954924288, -938147072, 0x3200300, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -1927412992, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, -350944512, -334167296, -317390080, -300612864, -283835648, -267058432, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController4.setBounds(0, 0, 0, 0);
                labelController4.setChainedAction(1, 1);
                labelController4.setColorIndices(new int[]{1, 7, 4, 2});
                labelController4.setModelColumn(8);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setChainedAction(1, 1);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints4 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints4);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                GridLayoutHints gridLayoutHints4 = new GridLayoutHints(1, 0);
                gridLayoutHints4.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints4}, new Object[]{labelController, labelController4});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController4);
                return layoutContainerController;
            }
            case 5: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(9);
                return labelController;
            }
            case 6: {
                AbstractWidgetController abstractWidgetController = this.val$factory.getRefWidget(this.val$terminalID, 8, this.val$factory);
                return abstractWidgetController;
            }
            case 7: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(3, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setModelColumn(3);
                LabelController labelController5 = new LabelController();
                LabelRendererHigh labelRendererHigh5 = new LabelRendererHigh(labelController5);
                labelController5.setRenderer(labelRendererHigh5);
                labelRendererHigh5.setFonts(this.val$factory.getFonts(3, this.val$terminalID));
                labelController5.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -266992896, -954924288, -938147072, -921369856, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -233438464, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, 723190528, -334167296, -317390080, -300612864, -283835648, 656081664, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController5.setBounds(0, 0, 0, 0);
                labelController5.setModelColumn(4);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 10, 0};
                axisConstraints.hidemode = new int[]{2, 2};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints5 = new AxisConstraints(1);
                axisConstraints5.hidemode = new int[]{2};
                gridLayout.setRowConstraints(axisConstraints5);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints5 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints5}, new Object[]{labelController5, labelController});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController5);
                return layoutContainerController;
            }
            case 8: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                return labelController;
            }
            case 9: {
                AbstractWidgetController abstractWidgetController = this.val$factory.getRefWidget(this.val$terminalID, 9, this.val$factory);
                return abstractWidgetController;
            }
            case 10: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(5);
                LabelController labelController6 = new LabelController();
                LabelRendererHigh labelRendererHigh6 = new LabelRendererHigh(labelController6);
                labelController6.setRenderer(labelRendererHigh6);
                labelRendererHigh6.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController6.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -971701504, -954924288, -938147072, -921369856, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -518716672, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, -350944512, -334167296, -317390080, -300612864, -283835648, -267058432, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController6.setBounds(0, 0, 0, 0);
                labelController6.setColorIndices(new int[]{1, 7, 4, 2});
                labelController6.setModelColumn(6);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setColorIndices(new int[]{1, 6, 4, 0});
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints6 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints6);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints6 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints6}, new Object[]{labelController, labelController6});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController6);
                return layoutContainerController;
            }
            case 11: {
                AbstractWidgetController abstractWidgetController = this.val$factory.getRefWidget(this.val$terminalID, 10, this.val$factory);
                return abstractWidgetController;
            }
            case 12: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(7);
                LabelController labelController7 = new LabelController();
                LabelRendererHigh labelRendererHigh7 = new LabelRendererHigh(labelController7);
                labelController7.setRenderer(labelRendererHigh7);
                labelRendererHigh7.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController7.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -266992896, -954924288, -938147072, -250215680, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -518716672, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, -350944512, -334167296, -317390080, -300612864, -283835648, -267058432, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController7.setBounds(0, 0, 0, 0);
                labelController7.setColorIndices(new int[]{1, 7, 4, 2});
                labelController7.setModelColumn(8);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setColorIndices(new int[]{1, 6, 4, 0});
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints7 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints7);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints7 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints7}, new Object[]{labelController, labelController7});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController7);
                return layoutContainerController;
            }
            case 13: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setModelColumn(10);
                labelRendererHigh.setAlignment(3, 4);
                ProgressBarController progressBarController = new ProgressBarController();
                ProgressBarRendererHigh progressBarRendererHigh = new ProgressBarRendererHigh(progressBarController);
                progressBarController.setRenderer(progressBarRendererHigh);
                progressBarController.setBitmaps(new int[]{40, 41, 42, 43, 44, 45});
                progressBarController.setColorIndices(new int[]{1, 2, 4, 0});
                progressBarController.setMaximumModelValue(100);
                progressBarController.setMinimumModelValue(0);
                progressBarController.setModelColumn(11);
                progressBarController.setPreferredHeight(15);
                LabelController labelController8 = new LabelController();
                LabelRendererHigh labelRendererHigh8 = new LabelRendererHigh(labelController8);
                labelController8.setRenderer(labelRendererHigh8);
                labelRendererHigh8.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController8.setBounds(0, 0, 0, 0);
                labelController8.setModelColumn(9);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setShouldBackmirrorProgressBarInArabic(true);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(3);
                axisConstraints.gaps = new int[]{0, 15, 10, 0};
                axisConstraints.grow = new float[]{0.0f, 1.0f, 0.0f};
                axisConstraints.min = new int[]{67, -1, 75};
                axisConstraints.shrink = new float[]{0.0f, 1.0f, 0.0f};
                axisConstraints.hidemode = new int[]{0, 2, 0};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints8 = new AxisConstraints(1);
                axisConstraints8.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints8 = new GridLayoutHints(1, 0);
                GridLayoutHints gridLayoutHints9 = new GridLayoutHints(2, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints8, gridLayoutHints9}, new Object[]{labelController8, progressBarController, labelController});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(progressBarController);
                layoutContainerController.add(labelController8);
                return layoutContainerController;
            }
            case 14: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -266992896, -954924288, -938147072, -921369856, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -233438464, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, 723190528, -334167296, -317390080, -300612864, -283835648, -954531072, -753532160, -736754944, -719977728});
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(4);
                return labelController;
            }
            case 15: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setChainedAction(1, 1);
                labelController.setEnabled(false);
                labelController.setModelColumn(3);
                return labelController;
            }
            case 16: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{359, 452, 162, 162, 163, -2045902080, -1995570432, -1995570432});
                iconController.setChainedAction(1, 1);
                iconController.setModelColumn(2);
                iconController.setPreferredHeight(22);
                iconRendererHigh.setAlignment(2, 5);
                return iconController;
            }
            case 17: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setTextIds(new int[]{-1340734720});
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                return labelController;
            }
            case 18: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(16);
                return labelController;
            }
            case 19: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setTextIds(new int[]{-1172962560});
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                return labelController;
            }
            case 20: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(15);
                return labelController;
            }
            case 21: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{-753728768});
                return labelController;
            }
            case 22: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                return labelController;
            }
        }
        return null;
    }
}

