/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.media.hmi.evohighscale;

import de.audi.atip.hmi.model.ListCell;
import de.audi.tghu.media.hmi.evohighscale.MediaScreenFactory;
import de.esolutions.hmi.widgets.audi.base.widgets.AbstractWidgetController;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.AxisConstraints;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayout;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayoutHints;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.CompositeRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MenuItemRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LayoutContainerController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemColumnsConstraints;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.list.ListItemFactory;

final class MediaScreenBag1$1
implements ListItemFactory {
    private final /* synthetic */ MediaScreenFactory val$factory;
    private final /* synthetic */ int val$terminalID;

    MediaScreenBag1$1(MediaScreenFactory mediaScreenFactory, int n) {
        this.val$factory = mediaScreenFactory;
        this.val$terminalID = n;
    }

    @Override
    public AbstractWidgetController createListItem(int n, ListCell[] listCellArray) {
        switch (n) {
            case 0: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints.alignment = new int[]{8, 8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController2 = this.createCell(1);
                GridLayoutHints gridLayoutHints2 = new GridLayoutHints(1, 0);
                gridLayoutHints2.hidemode = 0;
                AbstractWidgetController abstractWidgetController3 = this.createCell(2);
                GridLayoutHints gridLayoutHints3 = new GridLayoutHints(2, 0);
                gridLayoutHints3.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2, gridLayoutHints3}, new Object[]{abstractWidgetController, abstractWidgetController2, abstractWidgetController3});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController3);
                menuItemController.add(abstractWidgetController2);
                return menuItemController;
            }
            case 1: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints.alignment = new int[]{8, 8, 8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 10, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0, 0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController4 = this.createCell(1);
                GridLayoutHints gridLayoutHints4 = new GridLayoutHints(1, 0);
                gridLayoutHints4.hidemode = 0;
                AbstractWidgetController abstractWidgetController5 = this.createCell(3);
                GridLayoutHints gridLayoutHints5 = new GridLayoutHints(2, 0);
                gridLayoutHints5.hidemode = 0;
                AbstractWidgetController abstractWidgetController6 = this.createCell(2);
                GridLayoutHints gridLayoutHints6 = new GridLayoutHints(3, 0);
                gridLayoutHints6.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints4, gridLayoutHints5, gridLayoutHints6}, new Object[]{abstractWidgetController, abstractWidgetController4, abstractWidgetController5, abstractWidgetController6});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController6);
                menuItemController.add(abstractWidgetController5);
                menuItemController.add(abstractWidgetController4);
                return menuItemController;
            }
            case 2: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints.alignment = new int[]{8, 8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController7 = this.createCell(4);
                GridLayoutHints gridLayoutHints7 = new GridLayoutHints(1, 0);
                gridLayoutHints7.hidemode = 0;
                AbstractWidgetController abstractWidgetController8 = this.createCell(2);
                GridLayoutHints gridLayoutHints8 = new GridLayoutHints(2, 0);
                gridLayoutHints8.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints7, gridLayoutHints8}, new Object[]{abstractWidgetController, abstractWidgetController7, abstractWidgetController8});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController8);
                menuItemController.add(abstractWidgetController7);
                return menuItemController;
            }
            case 3: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints.alignment = new int[]{8, 8, 8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 10, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 2, 0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController9 = this.createCell(4);
                GridLayoutHints gridLayoutHints9 = new GridLayoutHints(1, 0);
                gridLayoutHints9.hidemode = 0;
                AbstractWidgetController abstractWidgetController10 = this.createCell(3);
                GridLayoutHints gridLayoutHints10 = new GridLayoutHints(2, 0);
                gridLayoutHints10.hidemode = 0;
                AbstractWidgetController abstractWidgetController11 = this.createCell(2);
                GridLayoutHints gridLayoutHints11 = new GridLayoutHints(3, 0);
                gridLayoutHints11.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints9, gridLayoutHints10, gridLayoutHints11}, new Object[]{abstractWidgetController, abstractWidgetController9, abstractWidgetController10, abstractWidgetController11});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController11);
                menuItemController.add(abstractWidgetController9);
                menuItemController.add(abstractWidgetController10);
                return menuItemController;
            }
            case 4: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.alignment = new int[]{8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(1);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController12 = this.createCell(2);
                GridLayoutHints gridLayoutHints12 = new GridLayoutHints(1, 0);
                gridLayoutHints12.hidemode = 0;
                AbstractWidgetController abstractWidgetController13 = this.createCell(5);
                GridLayoutHints gridLayoutHints13 = new GridLayoutHints(0, 1);
                gridLayoutHints13.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints12, gridLayoutHints13}, new Object[]{abstractWidgetController, abstractWidgetController12, abstractWidgetController13});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController12);
                menuItemController.add(abstractWidgetController13);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 5: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints.alignment = new int[]{8, 8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 10, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{2, 0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(1);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController14 = this.createCell(3);
                GridLayoutHints gridLayoutHints14 = new GridLayoutHints(1, 0);
                gridLayoutHints14.hidemode = 0;
                AbstractWidgetController abstractWidgetController15 = this.createCell(2);
                GridLayoutHints gridLayoutHints15 = new GridLayoutHints(2, 0);
                gridLayoutHints15.hidemode = 0;
                AbstractWidgetController abstractWidgetController16 = this.createCell(5);
                GridLayoutHints gridLayoutHints16 = new GridLayoutHints(0, 1);
                gridLayoutHints16.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints14, gridLayoutHints15, gridLayoutHints16}, new Object[]{abstractWidgetController, abstractWidgetController14, abstractWidgetController15, abstractWidgetController16});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController15);
                menuItemController.add(abstractWidgetController14);
                menuItemController.add(abstractWidgetController16);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 6: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.alignment = new int[]{8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(1);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController17 = this.createCell(2);
                GridLayoutHints gridLayoutHints17 = new GridLayoutHints(1, 0);
                gridLayoutHints17.hidemode = 0;
                GridLayout gridLayout2 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints2 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints2.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints2.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints2.hidemode = new int[]{2, 1, 2};
                gridLayout2.setColumnConstraints(menuItemColumnsConstraints2);
                AxisConstraints axisConstraints2 = new AxisConstraints(1);
                gridLayout2.setRowConstraints(axisConstraints2);
                AbstractWidgetController abstractWidgetController18 = this.createCell(5);
                GridLayoutHints gridLayoutHints18 = new GridLayoutHints(0, 0);
                gridLayoutHints18.hidemode = 0;
                AbstractWidgetController abstractWidgetController19 = this.createCell(6);
                GridLayoutHints gridLayoutHints19 = new GridLayoutHints(1, 0);
                gridLayoutHints19.hidemode = 0;
                AbstractWidgetController abstractWidgetController20 = this.createCell(7);
                GridLayoutHints gridLayoutHints20 = new GridLayoutHints(2, 0);
                gridLayoutHints20.hidemode = 0;
                gridLayout2.setCellConstraints(new GridLayoutHints[]{gridLayoutHints18, gridLayoutHints19, gridLayoutHints20}, new Object[]{abstractWidgetController18, abstractWidgetController19, abstractWidgetController20});
                GridLayoutHints gridLayoutHints21 = new GridLayoutHints(0, 1);
                gridLayoutHints21.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints17, gridLayoutHints21}, new Object[]{abstractWidgetController, abstractWidgetController17, gridLayout2});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController19);
                menuItemController.add(abstractWidgetController17);
                menuItemController.add(abstractWidgetController20);
                menuItemController.add(abstractWidgetController18);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 7: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints.alignment = new int[]{8, 8, 8};
                menuItemColumnsConstraints.gaps = new int[]{0, 10, 10, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.max = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.min = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints.size = new int[]{-1, -1, -1};
                menuItemColumnsConstraints.tabulatorIDs = new int[]{-1, -1, -1, -1};
                menuItemColumnsConstraints.hidemode = new int[]{0, 0, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(1);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                AbstractWidgetController abstractWidgetController21 = this.createCell(3);
                GridLayoutHints gridLayoutHints22 = new GridLayoutHints(1, 0);
                gridLayoutHints22.hidemode = 0;
                AbstractWidgetController abstractWidgetController22 = this.createCell(2);
                GridLayoutHints gridLayoutHints23 = new GridLayoutHints(2, 0);
                gridLayoutHints23.hidemode = 0;
                GridLayout gridLayout3 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints3 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints3.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints3.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints3.hidemode = new int[]{2, 2, 2};
                gridLayout3.setColumnConstraints(menuItemColumnsConstraints3);
                AxisConstraints axisConstraints3 = new AxisConstraints(1);
                gridLayout3.setRowConstraints(axisConstraints3);
                AbstractWidgetController abstractWidgetController23 = this.createCell(5);
                GridLayoutHints gridLayoutHints24 = new GridLayoutHints(0, 0);
                gridLayoutHints24.hidemode = 0;
                AbstractWidgetController abstractWidgetController24 = this.createCell(6);
                GridLayoutHints gridLayoutHints25 = new GridLayoutHints(1, 0);
                gridLayoutHints25.hidemode = 0;
                AbstractWidgetController abstractWidgetController25 = this.createCell(7);
                GridLayoutHints gridLayoutHints26 = new GridLayoutHints(2, 0);
                gridLayoutHints26.hidemode = 0;
                gridLayout3.setCellConstraints(new GridLayoutHints[]{gridLayoutHints24, gridLayoutHints25, gridLayoutHints26}, new Object[]{abstractWidgetController23, abstractWidgetController24, abstractWidgetController25});
                GridLayoutHints gridLayoutHints27 = new GridLayoutHints(0, 1);
                gridLayoutHints27.hidemode = 0;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints22, gridLayoutHints23, gridLayoutHints27}, new Object[]{abstractWidgetController, abstractWidgetController21, abstractWidgetController22, gridLayout3});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController24);
                menuItemController.add(abstractWidgetController22);
                menuItemController.add(abstractWidgetController21);
                menuItemController.add(abstractWidgetController25);
                menuItemController.add(abstractWidgetController23);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 8: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout4 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints4 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints4.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints4.hidemode = new int[]{2, 2};
                gridLayout4.setColumnConstraints(menuItemColumnsConstraints4);
                AxisConstraints axisConstraints4 = new AxisConstraints(1);
                gridLayout4.setRowConstraints(axisConstraints4);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController26 = this.createCell(9);
                GridLayoutHints gridLayoutHints28 = new GridLayoutHints(1, 0);
                gridLayoutHints28.hidemode = 2;
                gridLayout4.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints28}, new Object[]{abstractWidgetController, abstractWidgetController26});
                GridLayoutHints gridLayoutHints29 = new GridLayoutHints(0, 0);
                gridLayoutHints29.hidemode = 0;
                AbstractWidgetController abstractWidgetController27 = this.createCell(10);
                GridLayoutHints gridLayoutHints30 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints29, gridLayoutHints30}, new Object[]{gridLayout4, abstractWidgetController27});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController27);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController26);
                return menuItemController;
            }
            case 9: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout5 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints5 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints5.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints5.hidemode = new int[]{2, 2};
                gridLayout5.setColumnConstraints(menuItemColumnsConstraints5);
                AxisConstraints axisConstraints5 = new AxisConstraints(1);
                gridLayout5.setRowConstraints(axisConstraints5);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController28 = this.createCell(9);
                GridLayoutHints gridLayoutHints31 = new GridLayoutHints(1, 0);
                gridLayoutHints31.hidemode = 2;
                gridLayout5.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints31}, new Object[]{abstractWidgetController, abstractWidgetController28});
                GridLayoutHints gridLayoutHints32 = new GridLayoutHints(0, 0);
                gridLayoutHints32.hidemode = 0;
                AbstractWidgetController abstractWidgetController29 = this.createCell(10);
                GridLayoutHints gridLayoutHints33 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints32, gridLayoutHints33}, new Object[]{gridLayout5, abstractWidgetController29});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController29);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController28);
                return menuItemController;
            }
            case 10: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout6 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints6 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints6.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints6.hidemode = new int[]{2, 2};
                gridLayout6.setColumnConstraints(menuItemColumnsConstraints6);
                AxisConstraints axisConstraints6 = new AxisConstraints(1);
                gridLayout6.setRowConstraints(axisConstraints6);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController30 = this.createCell(9);
                GridLayoutHints gridLayoutHints34 = new GridLayoutHints(1, 0);
                gridLayoutHints34.hidemode = 2;
                gridLayout6.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints34}, new Object[]{abstractWidgetController, abstractWidgetController30});
                GridLayoutHints gridLayoutHints35 = new GridLayoutHints(0, 0);
                gridLayoutHints35.hidemode = 0;
                AbstractWidgetController abstractWidgetController31 = this.createCell(10);
                GridLayoutHints gridLayoutHints36 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints35, gridLayoutHints36}, new Object[]{gridLayout6, abstractWidgetController31});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController31);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController30);
                return menuItemController;
            }
            case 11: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout7 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints7 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints7.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints7.hidemode = new int[]{2, 2};
                gridLayout7.setColumnConstraints(menuItemColumnsConstraints7);
                AxisConstraints axisConstraints7 = new AxisConstraints(1);
                gridLayout7.setRowConstraints(axisConstraints7);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController32 = this.createCell(9);
                GridLayoutHints gridLayoutHints37 = new GridLayoutHints(1, 0);
                gridLayoutHints37.hidemode = 2;
                gridLayout7.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints37}, new Object[]{abstractWidgetController, abstractWidgetController32});
                GridLayoutHints gridLayoutHints38 = new GridLayoutHints(0, 0);
                gridLayoutHints38.hidemode = 0;
                AbstractWidgetController abstractWidgetController33 = this.createCell(10);
                GridLayoutHints gridLayoutHints39 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints38, gridLayoutHints39}, new Object[]{gridLayout7, abstractWidgetController33});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController33);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController32);
                return menuItemController;
            }
            case 12: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout8 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints8 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints8.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints8.hidemode = new int[]{2, 2};
                gridLayout8.setColumnConstraints(menuItemColumnsConstraints8);
                AxisConstraints axisConstraints8 = new AxisConstraints(1);
                gridLayout8.setRowConstraints(axisConstraints8);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController34 = this.createCell(9);
                GridLayoutHints gridLayoutHints40 = new GridLayoutHints(1, 0);
                gridLayoutHints40.hidemode = 2;
                gridLayout8.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints40}, new Object[]{abstractWidgetController, abstractWidgetController34});
                GridLayoutHints gridLayoutHints41 = new GridLayoutHints(0, 0);
                gridLayoutHints41.hidemode = 0;
                AbstractWidgetController abstractWidgetController35 = this.createCell(10);
                GridLayoutHints gridLayoutHints42 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints41, gridLayoutHints42}, new Object[]{gridLayout8, abstractWidgetController35});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController35);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController34);
                return menuItemController;
            }
            case 13: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout9 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints9 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints9.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints9.hidemode = new int[]{2, 2};
                gridLayout9.setColumnConstraints(menuItemColumnsConstraints9);
                AxisConstraints axisConstraints9 = new AxisConstraints(1);
                gridLayout9.setRowConstraints(axisConstraints9);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController36 = this.createCell(9);
                GridLayoutHints gridLayoutHints43 = new GridLayoutHints(1, 0);
                gridLayoutHints43.hidemode = 2;
                gridLayout9.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints43}, new Object[]{abstractWidgetController, abstractWidgetController36});
                GridLayoutHints gridLayoutHints44 = new GridLayoutHints(0, 0);
                gridLayoutHints44.hidemode = 0;
                AbstractWidgetController abstractWidgetController37 = this.createCell(10);
                GridLayoutHints gridLayoutHints45 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints44, gridLayoutHints45}, new Object[]{gridLayout9, abstractWidgetController37});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController37);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController36);
                return menuItemController;
            }
            case 14: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout10 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints10 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints10.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints10.hidemode = new int[]{2, 2};
                gridLayout10.setColumnConstraints(menuItemColumnsConstraints10);
                AxisConstraints axisConstraints10 = new AxisConstraints(1);
                gridLayout10.setRowConstraints(axisConstraints10);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController38 = this.createCell(9);
                GridLayoutHints gridLayoutHints46 = new GridLayoutHints(1, 0);
                gridLayoutHints46.hidemode = 2;
                gridLayout10.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints46}, new Object[]{abstractWidgetController, abstractWidgetController38});
                GridLayoutHints gridLayoutHints47 = new GridLayoutHints(0, 0);
                gridLayoutHints47.hidemode = 0;
                AbstractWidgetController abstractWidgetController39 = this.createCell(10);
                GridLayoutHints gridLayoutHints48 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints47, gridLayoutHints48}, new Object[]{gridLayout10, abstractWidgetController39});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController39);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController38);
                return menuItemController;
            }
            case 15: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 12, 0};
                menuItemColumnsConstraints.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints.shrink = new float[]{1.0f, 0.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                axisConstraints.alignment = new int[]{5};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout11 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints11 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints11.gaps = new int[]{0, 10, 0};
                menuItemColumnsConstraints11.hidemode = new int[]{2, 2};
                gridLayout11.setColumnConstraints(menuItemColumnsConstraints11);
                AxisConstraints axisConstraints11 = new AxisConstraints(1);
                gridLayout11.setRowConstraints(axisConstraints11);
                AbstractWidgetController abstractWidgetController = this.createCell(8);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                AbstractWidgetController abstractWidgetController40 = this.createCell(9);
                GridLayoutHints gridLayoutHints49 = new GridLayoutHints(1, 0);
                gridLayoutHints49.hidemode = 2;
                gridLayout11.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints49}, new Object[]{abstractWidgetController, abstractWidgetController40});
                GridLayoutHints gridLayoutHints50 = new GridLayoutHints(0, 0);
                gridLayoutHints50.hidemode = 0;
                AbstractWidgetController abstractWidgetController41 = this.createCell(10);
                GridLayoutHints gridLayoutHints51 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints50, gridLayoutHints51}, new Object[]{gridLayout11, abstractWidgetController41});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController41);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController40);
                return menuItemController;
            }
        }
        return null;
    }

    @Override
    public AbstractWidgetController createListItemNoData() {
        MenuItemController menuItemController = new MenuItemController();
        menuItemController.setType(16);
        menuItemController.setRenderer(new CompositeRendererHigh(menuItemController));
        GridLayout gridLayout = new GridLayout();
        MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
        menuItemColumnsConstraints.gaps = new int[]{0, 0};
        menuItemColumnsConstraints.grow = new float[]{0.0f};
        menuItemColumnsConstraints.min = new int[]{32};
        menuItemColumnsConstraints.shrink = new float[]{0.0f};
        gridLayout.setColumnConstraints(menuItemColumnsConstraints);
        AxisConstraints axisConstraints = new AxisConstraints(2);
        axisConstraints.gaps = new int[]{0, 0, 0};
        gridLayout.setRowConstraints(axisConstraints);
        AbstractWidgetController abstractWidgetController = this.createCell(11);
        GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
        gridLayoutHints.hidemode = 0;
        GridLayoutHints gridLayoutHints2 = new GridLayoutHints(0, 1);
        gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2}, new Object[]{abstractWidgetController, abstractWidgetController});
        menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
        menuItemController.add(abstractWidgetController);
        return menuItemController;
    }

    public AbstractWidgetController createCell(int n) {
        switch (n) {
            case 0: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 127, 127, 127, 127, 127, 127, 127, 164, 127, 165, 165, 1913520896, 127, 127, 127, 127, 127, 127, 127, 127, 127, 127, 167, 168, 169, 169, 170, 170, 171, 172, 127, 172, 172, 172, 172, 172, 172, 172, 172, 172, 172, 165, 165, 167, 165, 165, 165, 165, 165, 127});
                iconController.setChainedAction(1, 1);
                iconController.setModelColumn(2);
                iconController.setPreferredHeight(22);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 1: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{-1022033152, -1005255936, -988478720, 1494287104, 1511064320, -938147072, -250215680, 1561395968, -887815424, 1594950400, 1611727616, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, 1745945344, 1762722560, 1779499776, 1796276992, 1813054208, 1829831424, 1846608640, 1863385856, 1880163072, 1896940288, 1913717504, 1913717504, 1947271936, 1964049152, 1980826368, 1997603584, 2014380800, 2031158016, 2047935232, 2064712448, -384498944, -367721728, 2115044096, -334167296, -317390080, -300612864, 1880163072, -2096037120, 739771136, 873988864, 119210752, 404751104, 421528320, 438305536});
                labelController.setBounds(0, 0, 0, 0);
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(5);
                LabelController labelController2 = new LabelController();
                LabelRendererHigh labelRendererHigh2 = new LabelRendererHigh(labelController2);
                labelController2.setRenderer(labelRendererHigh2);
                labelController2.setBounds(0, 0, 0, 0);
                labelController2.setChainedAction(1, 1);
                labelController2.setModelColumn(4);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setChainedAction(1, 1);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.gaps = new int[]{0, 10, 0};
                axisConstraints.hidemode = new int[]{2, 2};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints2 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints2);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                GridLayoutHints gridLayoutHints2 = new GridLayoutHints(1, 0);
                gridLayoutHints2.hidemode = 2;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2}, new Object[]{labelController, labelController2});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController2);
                return layoutContainerController;
            }
            case 2: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -888274176, -871496960});
                iconController.setChainedAction(1, 1);
                iconController.setModelColumn(16);
                iconController.setPreferredHeight(22);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 3: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{39});
                iconController.setChainedAction(1, 1);
                iconController.setPreferredHeight(22);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 4: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(3);
                return labelController;
            }
            case 5: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(8);
                LabelController labelController3 = new LabelController();
                LabelRendererHigh labelRendererHigh3 = new LabelRendererHigh(labelController3);
                labelController3.setRenderer(labelRendererHigh3);
                labelRendererHigh3.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController3.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -1055784192, -954924288, -938147072, -921369856, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -602799360, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, -350944512, -334167296, -317390080, -300612864, -283835648, -267058432, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController3.setBounds(0, 0, 0, 0);
                labelController3.setChainedAction(1, 1);
                labelController3.setColorIndices(new int[]{1, 7, 4, 2});
                labelController3.setModelColumn(9);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setChainedAction(1, 1);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.hidemode = new int[]{2, 2};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints3 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints3);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayoutHints gridLayoutHints3 = new GridLayoutHints(1, 0);
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints3}, new Object[]{labelController, labelController3});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController3);
                return layoutContainerController;
            }
            case 6: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setTextIds(new int[]{-1022033152, -1022033152, 1712849664});
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(14);
                return labelController;
            }
            case 7: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setBounds(0, 0, 0, 0);
                labelController.setChainedAction(1, 1);
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(6);
                LabelController labelController4 = new LabelController();
                LabelRendererHigh labelRendererHigh4 = new LabelRendererHigh(labelController4);
                labelController4.setRenderer(labelRendererHigh4);
                labelRendererHigh4.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController4.setTextIds(new int[]{-1022033152, -1005255936, -988478720, -266992896, -954924288, -938147072, 203096832, -904592640, -887815424, -871038208, -854260992, -837483776, -820706560, -803929344, -787152128, -770374912, -753597696, -736820480, -720043264, -703266048, -686488832, -669711616, -652934400, -636157184, -619379968, -602602752, -585825536, -569048320, -552271104, -535493888, -233438464, -501939456, -485162240, -468385024, -451607808, -434830592, -418053376, -401276160, -384498944, -367721728, -350944512, -334167296, -317390080, -300612864, -283835648, -267058432, -753532160, -736754944, -719977728, 958399232, 488637184, 505414400});
                labelController4.setBounds(0, 0, 0, 0);
                labelController4.setChainedAction(1, 1);
                labelController4.setColorIndices(new int[]{1, 7, 4, 2});
                labelController4.setModelColumn(7);
                LayoutContainerController layoutContainerController = new LayoutContainerController();
                CompositeRendererHigh compositeRendererHigh = new CompositeRendererHigh(layoutContainerController);
                layoutContainerController.setRenderer(compositeRendererHigh);
                layoutContainerController.setBounds(0, 0, 100, 100);
                layoutContainerController.setChainedAction(1, 1);
                GridLayout gridLayout = new GridLayout();
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.hidemode = new int[]{2, 2};
                gridLayout.setColumnConstraints(axisConstraints);
                AxisConstraints axisConstraints4 = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints4);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 2;
                GridLayoutHints gridLayoutHints4 = new GridLayoutHints(1, 0);
                gridLayoutHints4.hidemode = 2;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints4}, new Object[]{labelController, labelController4});
                layoutContainerController.setLayoutManager(gridLayout);
                layoutContainerController.add(labelController);
                layoutContainerController.add(labelController4);
                return layoutContainerController;
            }
            case 8: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{-1022033152, 974586624, 991363840, 253428480, 1125778176, 1008141056, 270205696, -685833472, 1024918272, 1109000960, 672858880, 1041695488, 1058472704, 1075249920, 1092027136, -350813440, 1108804352, 1125581568, 1745945344, 303760128, 1779499776, 1796276992, 1813054208, 1829831424, 1846608640, 404423424, 421200640, 437977856, 454755072, 0x200300, 471532288, 488309504, 505086720, 1997603584, 538641152, 555418368, 2047935232, 2064712448, 1142358784, 1159136000, 2115044096, 773325568, 2115044096, 890766080, 790102784, 689636096, 739771136, 605750016, 1511523072});
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(5);
                return labelController;
            }
            case 9: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setChainedAction(1, 1);
                labelController.setModelColumn(4);
                return labelController;
            }
            case 10: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{359, 452, 162, 162, 163, -2045902080, -1995570432, -1995570432});
                iconController.setChainedAction(1, 1);
                iconController.setModelColumn(2);
                iconController.setPreferredHeight(22);
                iconRendererHigh.setAlignment(2, 5);
                return iconController;
            }
            case 11: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{-753728768});
                return labelController;
            }
        }
        return null;
    }
}

