/*
 * Decompiled with CFR 0.152.
 */
package de.audi.remotehmi.ui.ql;

import de.audi.remotehmi.ui.core.PropertiesCore;

public interface PropertiesQL
extends PropertiesCore {
    public static final String PROP_SOFTKEY = "softkey";
    public static final String PROP_SOFTKEYID = "softkeyIds";
    public static final String PROP_SOFTKEYENABLED = "softkeyEnabled";
    public static final String PROP_SOFTKEYHIGHLIGHTED = "softkeyHighlighted";
    public static final String PROP_TTS = "tts";
    public static final String PROP_TTS_STOP = "ttsStop";
    public static final String PROP_PPTEXTS = "pptexts";
    public static final String PROP_OPEN_MEDIA = "openMedia";
    public static final String PROP_OPEN_MEDIA_TYPE = "openMediaType";
    public static final String PROP_LISTTEXT = "listText";
    public static final String PROP_LISTTEXT2 = "listText2";
    public static final String PROP_LISTTEXTENABLED = "listTextEnabled";
    public static final String PROP_LISTTEXTFOCUSABLE = "listTextFocusable";
    public static final String PROP_LISTLEFTICONURL = "listLeftIconUrl";
    public static final String PROP_LISTRIGHTICONURL = "listRightIconUrl";
    public static final String PROP_LISTLLDMAPPING = "listLLDMapping";
    public static final String PROP_LISTTEXTID = "listTextId";
    public static final String PROP_LISTTEXTTYPE = "listTextType";
    public static final String PROP_LISTTEXTIMAGE = "listTextImage";
    public static final String PROP_LISTTEXTDATA = "listTextData";
    public static final String PROP_LISTINPUTTYPES = "listInputTypes";
    public static final String PROP_LISTINPUTIDS = "listInputIds";
    public static final String PROP_LISTTEXTFIELDTEXT = "listTextFieldText";
    public static final String PROP_LISTTEXTFIELDDEFAULT = "listTextFieldDefault";
    public static final String PROP_LISTTEXTFIELDMAXLEN = "listTextFieldMaxLen";
    public static final String PROP_LISTTEXTFIELDTYPE = "listTextFieldType";
    public static final String PROP_LISTTEXTFIELDENABLED = "listTextFieldEnabled";
    public static final String PROP_LISTCHECKBOXTEXT = "listCheckBoxText";
    public static final String PROP_LISTCHECKBOXCHECKED = "listCheckBoxChecked";
    public static final String PROP_LISTCHECKBOXENABLED = "listCheckBoxEnabled";
    public static final String PROP_LISTPULLDOWNTEXT = "listPullDownText";
    public static final String PROP_LISTPULLDOWNCHOICES = "listPullDownChoices";
    public static final String PROP_LISTPULLDOWNSELECTED = "listPullDownSelected";
    public static final String PROP_LISTPULLDOWNENABLED = "listPullDownEnabled";
    public static final String PROP_LISTACTIONITEMTEXT = "listActionItemText";
    public static final String PROP_LISTACTIONITEMENABLED = "listActionItemEnabled";
    public static final String PROP_HELPTEXT = "helpText";
    public static final String PROP_DEFAULTTEXT = "defaultText";
    public static final String PROP_MAXLEN = "maxLen";
    public static final String PROP_SPELLERTYPE = "spellerType";
    public static final String PROP_CALLURL = "callUrl";
    public static final String PROP_SCROLLMODE = "scrollMode";
    public static final String PROP_EFILINK = "efiLink";
    public static final String PROP_PICTUREURL = "pictureUrl";
    public static final String PROP_ITEMTEXT = "itemText";
    public static final String PROP_ITEMURL = "itemUrl";
    public static final String PROP_MINVALUE = "minValue";
    public static final String PROP_MAXVALUE = "maxValue";
    public static final String PROP_ICONSET = "iconSet";
    public static final String PROP_ICONSTATES = "iconStates";
    public static final String PROP_LONGITUDE = "lon";
    public static final String PROP_LATITUDE = "lat";
    public static final String PROP_ZOOM = "zoom";
    public static final String PROP_CENTERPOS = "centerPos";
    public static final String PROP_COUNTRY = "locCountry";
    public static final String PROP_CITY = "locCity";
    public static final String PROP_POSTALCODE = "locPostalCode";
    public static final String PROP_STREETNAME = "locStreetName";
    public static final String PROP_HOUSENUMBER = "locHouseNumber";
    public static final String PROP_INFINITE_LIST_START = "infiniteListStart";
    public static final String PROP_INFINITE_LIST_UPDATE = "infiniteListUpdate";
    public static final String PROP_INFINITE_LIST_BORDER_SIZE = "infiniteListBorderSize";
    public static final String PROP_INFINITE_LIST_TOTAL_SIZE = "infiniteListTotalSize";
    public static final String PROP_PROVIDERLOGO = "providerLogo";
    public static final String PROP_COLORCHOICE = "colorChoice";
    public static final String PROP_MEDIA_PROCESS_POSITION = "mediaProcessPosition";
    public static final String PROP_CAR_REVISION = "carRevision";
    public static final String PROP_CAR_VIN = "carVin";
    public static final String PROP_CAR_TYPE = "carType";
    public static final String PROP_CAR_LAN = "carLan";
    public static final String PROP_CAR_DAY = "carDay";
    public static final String PROP_CAR_OEM = "carOem";
    public static final String PROP_CAR_XRES = "carXres";
    public static final String PROP_CAR_YRES = "carYres";
    public static final String PROP_CAR_UNITDIST = "carUnitDist";
    public static final String PROP_CAR_UNITVEL = "carUnitVel";
    public static final String PROP_CAR_UNITTEMP = "carUnitTemp";
    public static final String PROP_CAR_UNITPRESS = "carUnitPress";
    public static final String PROP_CAR_UNITFUEL = "carUnitFuel";
    public static final String PROP_CAR_UNITVOLUME = "carUnitVolume";
    public static final String PROP_CAR_LONGITUDE = "carLon";
    public static final String PROP_CAR_LATITUDE = "carLat";
    public static final String PROP_CAR_COUNTRY_ABBREVIATION = "carCountryAbbrev";
    public static final String PROP_CAR_DESTINATION_LONGITUDE = "carDestLon";
    public static final String PROP_CAR_DESTINATION_LATITUDE = "carDestLat";
    public static final String PROP_CAR_KOMBITIMEDIFF = "carKombiTimeDiff";
    public static final String PROP_MIB_TAKE_SCREENSHOT = "mibTakeScreenshot";
    public static final String PROP_WAITING_SCREEN = "waitingScreen";
    public static final String PROP_NO_HISTORY_BACK = "noHistoryBack";
    public static final String PROP_HMI_BASE = "hmiBase";
    public static final String PROP_PRIVACY_FEATURE_ACTIVATED = "privacyFeatureActivated";
    public static final String PROP_SCROLL_INDEX = "scrollIndex";
}

