/*
 * Decompiled with CFR 0.152.
 */
package de.audi.remotehmi.ui.ql;

import de.audi.remotehmi.ui.core.PropertiesCore;

public interface PropertiesQL
extends PropertiesCore {
    public static final String PROP_SOFTKEY;
    public static final String PROP_SOFTKEYID;
    public static final String PROP_SOFTKEYENABLED;
    public static final String PROP_SOFTKEYHIGHLIGHTED;
    public static final String PROP_TTS;
    public static final String PROP_TTS_STOP;
    public static final String PROP_PPTEXTS;
    public static final String PROP_OPEN_MEDIA;
    public static final String PROP_OPEN_MEDIA_TYPE;
    public static final String PROP_LISTTEXT;
    public static final String PROP_LISTTEXT2;
    public static final String PROP_LISTTEXTENABLED;
    public static final String PROP_LISTTEXTFOCUSABLE;
    public static final String PROP_LISTLEFTICONURL;
    public static final String PROP_LISTRIGHTICONURL;
    public static final String PROP_LISTLLDMAPPING;
    public static final String PROP_LISTTEXTID;
    public static final String PROP_LISTTEXTTYPE;
    public static final String PROP_LISTTEXTIMAGE;
    public static final String PROP_LISTTEXTDATA;
    public static final String PROP_LISTINPUTTYPES;
    public static final String PROP_LISTINPUTIDS;
    public static final String PROP_LISTTEXTFIELDTEXT;
    public static final String PROP_LISTTEXTFIELDDEFAULT;
    public static final String PROP_LISTTEXTFIELDMAXLEN;
    public static final String PROP_LISTTEXTFIELDTYPE;
    public static final String PROP_LISTTEXTFIELDENABLED;
    public static final String PROP_LISTCHECKBOXTEXT;
    public static final String PROP_LISTCHECKBOXCHECKED;
    public static final String PROP_LISTCHECKBOXENABLED;
    public static final String PROP_LISTPULLDOWNTEXT;
    public static final String PROP_LISTPULLDOWNCHOICES;
    public static final String PROP_LISTPULLDOWNSELECTED;
    public static final String PROP_LISTPULLDOWNENABLED;
    public static final String PROP_LISTACTIONITEMTEXT;
    public static final String PROP_LISTACTIONITEMENABLED;
    public static final String PROP_HELPTEXT;
    public static final String PROP_DEFAULTTEXT;
    public static final String PROP_MAXLEN;
    public static final String PROP_SPELLERTYPE;
    public static final String PROP_CALLURL;
    public static final String PROP_SCROLLMODE;
    public static final String PROP_EFILINK;
    public static final String PROP_PICTUREURL;
    public static final String PROP_ITEMTEXT;
    public static final String PROP_ITEMURL;
    public static final String PROP_MINVALUE;
    public static final String PROP_MAXVALUE;
    public static final String PROP_ICONSET;
    public static final String PROP_ICONSTATES;
    public static final String PROP_LONGITUDE;
    public static final String PROP_LATITUDE;
    public static final String PROP_ZOOM;
    public static final String PROP_CENTERPOS;
    public static final String PROP_COUNTRY;
    public static final String PROP_CITY;
    public static final String PROP_POSTALCODE;
    public static final String PROP_STREETNAME;
    public static final String PROP_HOUSENUMBER;
    public static final String PROP_INFINITE_LIST_START;
    public static final String PROP_INFINITE_LIST_UPDATE;
    public static final String PROP_INFINITE_LIST_BORDER_SIZE;
    public static final String PROP_INFINITE_LIST_TOTAL_SIZE;
    public static final String PROP_PROVIDERLOGO;
    public static final String PROP_COLORCHOICE;
    public static final String PROP_MEDIA_PROCESS_POSITION;
    public static final String PROP_CAR_REVISION;
    public static final String PROP_CAR_VIN;
    public static final String PROP_CAR_TYPE;
    public static final String PROP_CAR_LAN;
    public static final String PROP_CAR_DAY;
    public static final String PROP_CAR_OEM;
    public static final String PROP_CAR_XRES;
    public static final String PROP_CAR_YRES;
    public static final String PROP_CAR_UNITDIST;
    public static final String PROP_CAR_UNITVEL;
    public static final String PROP_CAR_UNITTEMP;
    public static final String PROP_CAR_UNITPRESS;
    public static final String PROP_CAR_UNITFUEL;
    public static final String PROP_CAR_UNITVOLUME;
    public static final String PROP_CAR_LONGITUDE;
    public static final String PROP_CAR_LATITUDE;
    public static final String PROP_CAR_COUNTRY_ABBREVIATION;
    public static final String PROP_CAR_DESTINATION_LONGITUDE;
    public static final String PROP_CAR_DESTINATION_LATITUDE;
    public static final String PROP_CAR_KOMBITIMEDIFF;
    public static final String PROP_MIB_TAKE_SCREENSHOT;
    public static final String PROP_WAITING_SCREEN;
    public static final String PROP_NO_HISTORY_BACK;
    public static final String PROP_HMI_BASE;
    public static final String PROP_PRIVACY_FEATURE_ACTIVATED;
    public static final String PROP_SCROLL_INDEX;
}

