/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.messaging;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMESSAGING_SYNCHINPROGRESS = 4;
    public static final int ATTRIBUTE_ID_DSIMESSAGING_MESSAGINGACCOUNTS = 5;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SMSCNUMBER = 1;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SMSDELIVERYREPORT = 2;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_STORESMSONSENT = 3;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SHORTMESSAGEVALIDITYPERIOD = 4;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_PHONESYSTEMRINGINGVOLUME = 5;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_PHONESYSTEMRINGINGTYPE = 6;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_EMAILINCLUDEOLDMAILINREPLY = 7;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_EMAILEMPTYSUBJECTNOTIFICATION = 8;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_FOLDERVIEWMODE = 9;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_ACCOUNTPREFERENCES = 10;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_SMSINDICATIONS = 11;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_EMAILINDICATIONS = 12;
    public static final int ATTRIBUTE_ID_DSIMESSAGINGSERVICECONFIGURATION_PUSHSMS = 13;
}

