/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.hmi.widgets.audi.base;

public interface WidgetConstants {
    public static final boolean BENCHMARK;
    public static final int VIS_BACKGROUND;
    public static final int VIS_ENABLED;
    public static final int VIS_DISABLED;
    public static final int VIS_HIGHLIGHTED;
    public static final int VIS_PRESSED;
    public static final int VIS_PRESSED_HIGHLIGHTED;
    public static final int VIS_DISABLED_HIGHLIGHTED;
    public static final int VIS_MAX;
    public static final int NO_EVENT;
    public static final int ROLE_MENU_ITEM;
    public static final int ROLE_MENU_MANAGER;
    public static final int ROLE_MENU_CURSOR;
    public static final int ROLE_CURSOR_BACKGROUND;
    public static final int ROLE_CHAINED;
    public static final int ROLE_CELL_MANAGER;
    public static final int ROLE_SOFTKEY;
    public static final int ROLE_REFERENCE;
    public static final int ROLE_MIXED_LIST;
    public static final int ROLE_BUTTON_MANAGER;
    public static final int ROLE_DEFERRED_EXIT_MANAGER;
    public static final int ROLE_SIDEBAR_ITEM;
    public static final int ROLE_SIDEBAR_MENU_MANAGER;
    public static final int ROLE_POPIN_SCREEN;
    public static final int ROLE_DIALOG;
    public static final int ROLE_MENU_SCROLLBAR;
    public static final int ROLE_SCREEN;
    public static final int ROLE_INFOBOX;
    public static final int ROLE_STATUSBAR;
    public static final int ROLE_WIZARD;
    public static final int ROLE_PARTIAL_POPUP;
    public static final int ROLE_LAYOUT_MANAGER;
    public static final int ROLE_LAYOUT_COMPONENT;
    public static final int ROLE_SUBMENU_PREVIEW_CONTAINER;
    public static final int ROLE_USERHINT_TEXT;
    public static final int ROLE_LOCKING_IMAGES_SHADE;
    public static final int ROLE_LOCKING_IMAGES_INVISIBLE;
    public static final int ROLE_LOCKING_INPUT_SPELLER;
    public static final int ROLE_LOCKING_INPUT_ALL;
    public static final int ACTION_ENABLED;
    public static final int ACTION_HIGHLIGHTED;
    public static final int ACTION_VISIBLE;
    public static final int ACTION_PRESSED;
    public static final int ACTION_MAX;
    public static final int CONNECTION_STATE_THIS_CONNECTED;
    public static final int CONNECTION_STATE_SUBTREE_CONNECTED;
    public static final int CONNECTION_STATE_CHILDREN_DISCONNECTED;
    public static final int CONNECTION_STATE_SUBTREE_DISCONNECTED;
    public static final int STATE_VISIBLE;
    public static final int STATE_ON_SCREEN;
    public static final int STATE_ENABLED;
    public static final int STATE_HIGHLIGHTED;
    public static final int STATE_TRANSPARENT;
    public static final int STATE_ACTIVE;
    public static final int STATE_INVALID;
    public static final int STATE_FOCUSED;
    public static final int STATE_FUNCTIONAL;
    public static final int STATE_VISIBLE_ON_CURRENT_STAGE;
    public static final int CELL_LABEL;
    public static final int CELL_CHOICE_LABEL;
    public static final int CELL_IMAGE;
    public static final int CELL_CHOICE_IMAGE;
    public static final int CELL_CHECK_BOX;
    public static final int CELL_COMBO_BOX;
    public static final int CELL_RANGE;
    public static final int CELL_CONTAINER;
    public static final int CELL_IMAGE_STATE;
    public static final int CELL_IMAGE_LABEL;
    public static final int CELL_COMBI_SIGN;
    public static final int CELL_CHOICE_IMAGE_STATE;
    public static final int CELL_IMAGE_MODULATE;
    public static final int CELL_PLAYBAR_D4;
    public static final int CELL_PROGRESSBAR_D4;
    public static final int CELL_DECORATOR_ANIMATED;
    public static final int CELL_CHOICE_IMAGE_MODULATE;
    public static final int CELL_MAX;
    public static final int TABULATOR_ID_NO_COLUMN;
    public static final int TABULATOR_ID_FIRST_COLUMN;
    public static final int TABULATOR_ID_SECOND_COLUMN;
    public static final int TABULATOR_ID_DROP_DOWN_COLUMN;
    public static final int TABULATOR_ID_TEXTFIELD_COLUMN;
    public static final int TABULATOR_ID_SUBMENU_PREVIEW_COLUMN;
    public static final int TABULATOR_ID_MAX;
    public static final float ROUNDING;
    public static final String EMPTY_STRING;
    public static final char[] EMPTY_CHAR_ARRAY;
    public static final String[] EMPTY_STRING_ARRAY;
    public static final String DOT_STRING;
    public static final int NONE;
    public static final int SCREEN_HMI_ONLY;
    public static final int SCREEN_MAP;
    public static final int SCREEN_TV;
    public static final int SCREEN_VIDEO;
    public static final int SCREEN_BROWSER;
    public static final int SCREEN_REAR_VIEW;
    public static final int SCREEN_STANDBY;
    public static final int SCREEN_POPUP_UNBOUND;
    public static final int SCREEN_POPUP_BOUND;
    public static final int SCREEN_FULLSCREEN_SDS_POPUP;
    public static final int SCREEN_UNBOUND_PARTIAL_POPUP_CONTAINER;
    public static final int SCREEN_DRAWER_SELECTION;
    public static final int SCREEN_DRAWER_OPTION;
    public static final int SCREEN_REMOTE_HMI;
    public static final int SCREEN_REMOTE_HMI_BROWSER;
    public static final int CACHE_BEHAVIOUR_KEEP_ALWAYS;
    public static final int CACHE_BEHAVIOUR_DYNAMICALLY;
    public static final int CACHE_BEHAVIOUR_DO_NOT_CACHE;
    public static final double DEG_TO_RAD;
    public static final double RAD_TO_DEG;
    public static final int SETTINGS_CONTEXT;
    public static final int LOCKING_ACTION_IMAGES_NONE;
    public static final int LOCKING_ACTION_IMAGES_SHADE;
    public static final int LOCKING_ACTION_IMAGES_INVISIBLE;
    public static final int LOCKING_DEFAULT_SHADING_OPACITY;

    static {
        EMPTY_CHAR_ARRAY = "".toCharArray();
        EMPTY_STRING_ARRAY = new String[0];
    }
}

