/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.tuner.hmi.evohighscale;

import de.audi.atip.hmi.model.ListCell;
import de.audi.tghu.tuner.hmi.evohighscale.TunerScreenFactory;
import de.esolutions.hmi.widgets.audi.base.widgets.AbstractWidgetController;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.AxisConstraints;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayout;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayoutHints;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MenuItemRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemColumnsConstraints;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.list.ListItemFactory;

final class TunerScreenBag1$14
implements ListItemFactory {
    private final /* synthetic */ TunerScreenFactory val$factory;
    private final /* synthetic */ int val$terminalID;

    TunerScreenBag1$14(TunerScreenFactory tunerScreenFactory, int n) {
        this.val$factory = tunerScreenFactory;
        this.val$terminalID = n;
    }

    @Override
    public AbstractWidgetController createListItem(int n, ListCell[] listCellArray) {
        switch (n) {
            case 0: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.size = new int[]{30, -1};
                menuItemColumnsConstraints.hidemode = new int[]{1, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 1;
                GridLayout gridLayout2 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints2 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints2.gaps = new int[]{0, 12, 0, 0};
                menuItemColumnsConstraints2.grow = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints2.min = new int[]{0, -1, -1};
                menuItemColumnsConstraints2.shrink = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints2.hidemode = new int[]{0, 0, 2};
                gridLayout2.setColumnConstraints(menuItemColumnsConstraints2);
                AxisConstraints axisConstraints2 = new AxisConstraints(1);
                axisConstraints2.alignment = new int[]{5};
                gridLayout2.setRowConstraints(axisConstraints2);
                AbstractWidgetController abstractWidgetController2 = this.createCell(1);
                GridLayoutHints gridLayoutHints2 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController3 = this.createCell(2);
                GridLayoutHints gridLayoutHints3 = new GridLayoutHints(1, 0);
                gridLayoutHints3.widthMax = 40;
                gridLayoutHints3.widthMin = 40;
                gridLayoutHints3.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController4 = this.createCell(3);
                GridLayoutHints gridLayoutHints4 = new GridLayoutHints(2, 0);
                gridLayoutHints4.visibleConditions = -4;
                gridLayout2.setCellConstraints(new GridLayoutHints[]{gridLayoutHints2, gridLayoutHints3, gridLayoutHints4}, new Object[]{abstractWidgetController2, abstractWidgetController3, abstractWidgetController4});
                GridLayoutHints gridLayoutHints5 = new GridLayoutHints(1, 0);
                gridLayoutHints5.hidemode = 0;
                GridLayout gridLayout3 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints3 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints3.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints3.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints3.hidemode = new int[]{2, 2, 2};
                gridLayout3.setColumnConstraints(menuItemColumnsConstraints3);
                AxisConstraints axisConstraints3 = new AxisConstraints(1);
                axisConstraints3.hidemode = new int[]{2};
                gridLayout3.setRowConstraints(axisConstraints3);
                AbstractWidgetController abstractWidgetController5 = this.createCell(4);
                GridLayoutHints gridLayoutHints6 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController6 = this.createCell(5);
                GridLayoutHints gridLayoutHints7 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController7 = this.createCell(6);
                GridLayoutHints gridLayoutHints8 = new GridLayoutHints(2, 0);
                gridLayout3.setCellConstraints(new GridLayoutHints[]{gridLayoutHints6, gridLayoutHints7, gridLayoutHints8}, new Object[]{abstractWidgetController5, abstractWidgetController6, abstractWidgetController7});
                GridLayoutHints gridLayoutHints9 = new GridLayoutHints(1, 1);
                gridLayoutHints9.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints5, gridLayoutHints9}, new Object[]{abstractWidgetController, gridLayout2, gridLayout3});
                GridLayout gridLayout4 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints4 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints4.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints4.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints4.shrink = new float[]{1.0f, 0.0f};
                gridLayout4.setColumnConstraints(menuItemColumnsConstraints4);
                AxisConstraints axisConstraints4 = new AxisConstraints(5);
                axisConstraints4.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints4.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints4.size = new int[]{20, 16, 16, 16, 16};
                gridLayout4.setRowConstraints(axisConstraints4);
                GridLayout gridLayout5 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints5 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints5.alignment = new int[]{1, 8};
                menuItemColumnsConstraints5.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints5.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints5.shrink = new float[]{1.0f, 0.0f};
                gridLayout5.setColumnConstraints(menuItemColumnsConstraints5);
                AxisConstraints axisConstraints5 = new AxisConstraints(1);
                axisConstraints5.alignment = new int[]{5};
                gridLayout5.setRowConstraints(axisConstraints5);
                AbstractWidgetController abstractWidgetController8 = this.createCell(7);
                GridLayoutHints gridLayoutHints10 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController9 = this.createCell(8);
                GridLayoutHints gridLayoutHints11 = new GridLayoutHints(1, 0);
                gridLayout5.setCellConstraints(new GridLayoutHints[]{gridLayoutHints10, gridLayoutHints11}, new Object[]{abstractWidgetController8, abstractWidgetController9});
                GridLayoutHints gridLayoutHints12 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController10 = this.createCell(9);
                GridLayoutHints gridLayoutHints13 = new GridLayoutHints(1, 0);
                gridLayoutHints13.alignmentVert = 9;
                gridLayoutHints13.rowSpan = 5;
                gridLayoutHints13.widthMax = 216;
                gridLayoutHints13.widthMin = 216;
                gridLayoutHints13.visibleConditions = -13;
                GridLayout gridLayout6 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints6 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints6.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints6.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints6.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints6.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints6.hidemode = new int[]{2, 2, 2, 1};
                gridLayout6.setColumnConstraints(menuItemColumnsConstraints6);
                AxisConstraints axisConstraints6 = new AxisConstraints(1);
                axisConstraints6.alignment = new int[]{5};
                axisConstraints6.hidemode = new int[]{2};
                gridLayout6.setRowConstraints(axisConstraints6);
                AbstractWidgetController abstractWidgetController11 = this.createCell(10);
                GridLayoutHints gridLayoutHints14 = new GridLayoutHints(0, 0);
                gridLayoutHints14.afterEffects = new int[]{0, -1, 0, 0};
                AbstractWidgetController abstractWidgetController12 = this.createCell(11);
                GridLayoutHints gridLayoutHints15 = new GridLayoutHints(1, 0);
                gridLayout6.setCellConstraints(new GridLayoutHints[]{gridLayoutHints14, gridLayoutHints15}, new Object[]{abstractWidgetController11, abstractWidgetController12});
                GridLayoutHints gridLayoutHints16 = new GridLayoutHints(0, 1);
                AbstractWidgetController abstractWidgetController13 = this.createCell(12);
                GridLayoutHints gridLayoutHints17 = new GridLayoutHints(0, 2);
                AbstractWidgetController abstractWidgetController14 = this.createCell(13);
                GridLayoutHints gridLayoutHints18 = new GridLayoutHints(0, 3);
                gridLayout4.setCellConstraints(new GridLayoutHints[]{gridLayoutHints12, gridLayoutHints13, gridLayoutHints16, gridLayoutHints17, gridLayoutHints18}, new Object[]{gridLayout5, abstractWidgetController10, gridLayout6, abstractWidgetController13, abstractWidgetController14});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout4});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController2);
                menuItemController.add(abstractWidgetController8);
                menuItemController.add(abstractWidgetController12);
                menuItemController.add(abstractWidgetController11);
                menuItemController.add(abstractWidgetController3);
                menuItemController.add(abstractWidgetController4);
                menuItemController.add(abstractWidgetController9);
                menuItemController.add(abstractWidgetController5);
                menuItemController.add(abstractWidgetController13);
                menuItemController.add(abstractWidgetController6);
                menuItemController.add(abstractWidgetController7);
                menuItemController.add(abstractWidgetController14);
                menuItemController.add(abstractWidgetController10);
                return menuItemController;
            }
            case 1: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.size = new int[]{30, -1};
                menuItemColumnsConstraints.hidemode = new int[]{1, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 1;
                GridLayout gridLayout7 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints7 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints7.gaps = new int[]{0, 12, 0, 0};
                menuItemColumnsConstraints7.grow = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints7.min = new int[]{0, -1, -1};
                menuItemColumnsConstraints7.shrink = new float[]{1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints7.hidemode = new int[]{0, 0, 2};
                gridLayout7.setColumnConstraints(menuItemColumnsConstraints7);
                AxisConstraints axisConstraints7 = new AxisConstraints(1);
                axisConstraints7.alignment = new int[]{5};
                gridLayout7.setRowConstraints(axisConstraints7);
                AbstractWidgetController abstractWidgetController15 = this.createCell(1);
                GridLayoutHints gridLayoutHints19 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController16 = this.createCell(2);
                GridLayoutHints gridLayoutHints20 = new GridLayoutHints(1, 0);
                gridLayoutHints20.widthMax = 40;
                gridLayoutHints20.widthMin = 40;
                gridLayoutHints20.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController17 = this.createCell(3);
                GridLayoutHints gridLayoutHints21 = new GridLayoutHints(2, 0);
                gridLayoutHints21.visibleConditions = -4;
                gridLayout7.setCellConstraints(new GridLayoutHints[]{gridLayoutHints19, gridLayoutHints20, gridLayoutHints21}, new Object[]{abstractWidgetController15, abstractWidgetController16, abstractWidgetController17});
                GridLayoutHints gridLayoutHints22 = new GridLayoutHints(1, 0);
                gridLayoutHints22.hidemode = 0;
                GridLayout gridLayout8 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints8 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints8.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints8.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints8.hidemode = new int[]{2, 2, 2};
                gridLayout8.setColumnConstraints(menuItemColumnsConstraints8);
                AxisConstraints axisConstraints8 = new AxisConstraints(1);
                axisConstraints8.hidemode = new int[]{2};
                gridLayout8.setRowConstraints(axisConstraints8);
                AbstractWidgetController abstractWidgetController18 = this.createCell(4);
                GridLayoutHints gridLayoutHints23 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController19 = this.createCell(5);
                GridLayoutHints gridLayoutHints24 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController20 = this.createCell(6);
                GridLayoutHints gridLayoutHints25 = new GridLayoutHints(2, 0);
                gridLayout8.setCellConstraints(new GridLayoutHints[]{gridLayoutHints23, gridLayoutHints24, gridLayoutHints25}, new Object[]{abstractWidgetController18, abstractWidgetController19, abstractWidgetController20});
                GridLayoutHints gridLayoutHints26 = new GridLayoutHints(1, 1);
                gridLayoutHints26.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints22, gridLayoutHints26}, new Object[]{abstractWidgetController, gridLayout7, gridLayout8});
                GridLayout gridLayout9 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints9 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints9.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints9.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints9.shrink = new float[]{1.0f, 0.0f};
                gridLayout9.setColumnConstraints(menuItemColumnsConstraints9);
                AxisConstraints axisConstraints9 = new AxisConstraints(5);
                axisConstraints9.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints9.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints9.size = new int[]{20, 16, 16, 16, 16};
                gridLayout9.setRowConstraints(axisConstraints9);
                GridLayout gridLayout10 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints10 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints10.alignment = new int[]{1, 8};
                menuItemColumnsConstraints10.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints10.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints10.shrink = new float[]{1.0f, 0.0f};
                gridLayout10.setColumnConstraints(menuItemColumnsConstraints10);
                AxisConstraints axisConstraints10 = new AxisConstraints(1);
                axisConstraints10.alignment = new int[]{5};
                gridLayout10.setRowConstraints(axisConstraints10);
                AbstractWidgetController abstractWidgetController21 = this.createCell(7);
                GridLayoutHints gridLayoutHints27 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController22 = this.createCell(8);
                GridLayoutHints gridLayoutHints28 = new GridLayoutHints(1, 0);
                gridLayout10.setCellConstraints(new GridLayoutHints[]{gridLayoutHints27, gridLayoutHints28}, new Object[]{abstractWidgetController21, abstractWidgetController22});
                GridLayoutHints gridLayoutHints29 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController23 = this.createCell(9);
                GridLayoutHints gridLayoutHints30 = new GridLayoutHints(1, 0);
                gridLayoutHints30.alignmentVert = 9;
                gridLayoutHints30.rowSpan = 5;
                gridLayoutHints30.widthMax = 216;
                gridLayoutHints30.widthMin = 216;
                gridLayoutHints30.visibleConditions = -13;
                GridLayout gridLayout11 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints11 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints11.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints11.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints11.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints11.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints11.hidemode = new int[]{2, 2, 2, 1};
                gridLayout11.setColumnConstraints(menuItemColumnsConstraints11);
                AxisConstraints axisConstraints11 = new AxisConstraints(1);
                axisConstraints11.alignment = new int[]{5};
                axisConstraints11.hidemode = new int[]{2};
                gridLayout11.setRowConstraints(axisConstraints11);
                AbstractWidgetController abstractWidgetController24 = this.createCell(10);
                GridLayoutHints gridLayoutHints31 = new GridLayoutHints(0, 0);
                gridLayoutHints31.afterEffects = new int[]{0, -1, 0, 0};
                AbstractWidgetController abstractWidgetController25 = this.createCell(11);
                GridLayoutHints gridLayoutHints32 = new GridLayoutHints(1, 0);
                gridLayout11.setCellConstraints(new GridLayoutHints[]{gridLayoutHints31, gridLayoutHints32}, new Object[]{abstractWidgetController24, abstractWidgetController25});
                GridLayoutHints gridLayoutHints33 = new GridLayoutHints(0, 1);
                AbstractWidgetController abstractWidgetController26 = this.createCell(12);
                GridLayoutHints gridLayoutHints34 = new GridLayoutHints(0, 2);
                AbstractWidgetController abstractWidgetController27 = this.createCell(13);
                GridLayoutHints gridLayoutHints35 = new GridLayoutHints(0, 3);
                gridLayout9.setCellConstraints(new GridLayoutHints[]{gridLayoutHints29, gridLayoutHints30, gridLayoutHints33, gridLayoutHints34, gridLayoutHints35}, new Object[]{gridLayout10, abstractWidgetController23, gridLayout11, abstractWidgetController26, abstractWidgetController27});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout9});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController15);
                menuItemController.add(abstractWidgetController21);
                menuItemController.add(abstractWidgetController25);
                menuItemController.add(abstractWidgetController24);
                menuItemController.add(abstractWidgetController16);
                menuItemController.add(abstractWidgetController17);
                menuItemController.add(abstractWidgetController22);
                menuItemController.add(abstractWidgetController18);
                menuItemController.add(abstractWidgetController26);
                menuItemController.add(abstractWidgetController19);
                menuItemController.add(abstractWidgetController20);
                menuItemController.add(abstractWidgetController27);
                menuItemController.add(abstractWidgetController23);
                return menuItemController;
            }
            case 2: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(1);
                gridLayout.setRowConstraints(axisConstraints);
                gridLayout.setCellConstraints(new GridLayoutHints[0], new Object[0]);
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                return menuItemController;
            }
            case 3: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.size = new int[]{30, -1};
                menuItemColumnsConstraints.hidemode = new int[]{1, 0};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(14);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                GridLayout gridLayout12 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints12 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints12.gaps = new int[]{0, 12, 12, 0, 0};
                menuItemColumnsConstraints12.grow = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints12.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints12.hidemode = new int[]{0, 0, 0, 2};
                gridLayout12.setColumnConstraints(menuItemColumnsConstraints12);
                AxisConstraints axisConstraints12 = new AxisConstraints(1);
                axisConstraints12.alignment = new int[]{5};
                gridLayout12.setRowConstraints(axisConstraints12);
                AbstractWidgetController abstractWidgetController28 = this.createCell(15);
                GridLayoutHints gridLayoutHints36 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController29 = this.createCell(16);
                GridLayoutHints gridLayoutHints37 = new GridLayoutHints(1, 0);
                gridLayoutHints37.widthMax = 162;
                gridLayoutHints37.widthMin = 162;
                gridLayoutHints37.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController30 = this.createCell(2);
                GridLayoutHints gridLayoutHints38 = new GridLayoutHints(2, 0);
                gridLayoutHints38.widthMax = 40;
                gridLayoutHints38.widthMin = 40;
                gridLayoutHints38.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController31 = this.createCell(3);
                GridLayoutHints gridLayoutHints39 = new GridLayoutHints(3, 0);
                gridLayoutHints39.visibleConditions = -4;
                gridLayout12.setCellConstraints(new GridLayoutHints[]{gridLayoutHints36, gridLayoutHints37, gridLayoutHints38, gridLayoutHints39}, new Object[]{abstractWidgetController28, abstractWidgetController29, abstractWidgetController30, abstractWidgetController31});
                GridLayoutHints gridLayoutHints40 = new GridLayoutHints(1, 0);
                GridLayout gridLayout13 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints13 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints13.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints13.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints13.hidemode = new int[]{2, 2, 2};
                gridLayout13.setColumnConstraints(menuItemColumnsConstraints13);
                AxisConstraints axisConstraints13 = new AxisConstraints(1);
                axisConstraints13.hidemode = new int[]{2};
                gridLayout13.setRowConstraints(axisConstraints13);
                AbstractWidgetController abstractWidgetController32 = this.createCell(4);
                GridLayoutHints gridLayoutHints41 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController33 = this.createCell(5);
                GridLayoutHints gridLayoutHints42 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController34 = this.createCell(6);
                GridLayoutHints gridLayoutHints43 = new GridLayoutHints(2, 0);
                gridLayout13.setCellConstraints(new GridLayoutHints[]{gridLayoutHints41, gridLayoutHints42, gridLayoutHints43}, new Object[]{abstractWidgetController32, abstractWidgetController33, abstractWidgetController34});
                GridLayoutHints gridLayoutHints44 = new GridLayoutHints(1, 1);
                gridLayoutHints44.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints40, gridLayoutHints44}, new Object[]{abstractWidgetController, gridLayout12, gridLayout13});
                GridLayout gridLayout14 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints14 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints14.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints14.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints14.shrink = new float[]{1.0f, 0.0f};
                gridLayout14.setColumnConstraints(menuItemColumnsConstraints14);
                AxisConstraints axisConstraints14 = new AxisConstraints(5);
                axisConstraints14.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints14.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints14.size = new int[]{20, 16, 16, 16, 16};
                gridLayout14.setRowConstraints(axisConstraints14);
                GridLayout gridLayout15 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints15 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints15.alignment = new int[]{1, 8};
                menuItemColumnsConstraints15.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints15.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints15.shrink = new float[]{1.0f, 0.0f};
                gridLayout15.setColumnConstraints(menuItemColumnsConstraints15);
                AxisConstraints axisConstraints15 = new AxisConstraints(1);
                axisConstraints15.alignment = new int[]{5};
                gridLayout15.setRowConstraints(axisConstraints15);
                AbstractWidgetController abstractWidgetController35 = this.createCell(7);
                GridLayoutHints gridLayoutHints45 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController36 = this.createCell(8);
                GridLayoutHints gridLayoutHints46 = new GridLayoutHints(1, 0);
                gridLayout15.setCellConstraints(new GridLayoutHints[]{gridLayoutHints45, gridLayoutHints46}, new Object[]{abstractWidgetController35, abstractWidgetController36});
                GridLayoutHints gridLayoutHints47 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController37 = this.createCell(9);
                GridLayoutHints gridLayoutHints48 = new GridLayoutHints(1, 0);
                gridLayoutHints48.alignmentVert = 9;
                gridLayoutHints48.rowSpan = 5;
                gridLayoutHints48.widthMax = 216;
                gridLayoutHints48.widthMin = 216;
                gridLayoutHints48.visibleConditions = -13;
                GridLayout gridLayout16 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints16 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints16.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints16.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints16.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints16.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints16.hidemode = new int[]{2, 2, 2, 1};
                gridLayout16.setColumnConstraints(menuItemColumnsConstraints16);
                AxisConstraints axisConstraints16 = new AxisConstraints(1);
                axisConstraints16.alignment = new int[]{5};
                axisConstraints16.hidemode = new int[]{2};
                gridLayout16.setRowConstraints(axisConstraints16);
                AbstractWidgetController abstractWidgetController38 = this.createCell(10);
                GridLayoutHints gridLayoutHints49 = new GridLayoutHints(0, 0);
                gridLayoutHints49.afterEffects = new int[]{0, -1, 0, 0};
                AbstractWidgetController abstractWidgetController39 = this.createCell(11);
                GridLayoutHints gridLayoutHints50 = new GridLayoutHints(1, 0);
                gridLayout16.setCellConstraints(new GridLayoutHints[]{gridLayoutHints49, gridLayoutHints50}, new Object[]{abstractWidgetController38, abstractWidgetController39});
                GridLayoutHints gridLayoutHints51 = new GridLayoutHints(0, 1);
                AbstractWidgetController abstractWidgetController40 = this.createCell(12);
                GridLayoutHints gridLayoutHints52 = new GridLayoutHints(0, 2);
                AbstractWidgetController abstractWidgetController41 = this.createCell(13);
                GridLayoutHints gridLayoutHints53 = new GridLayoutHints(0, 3);
                gridLayout14.setCellConstraints(new GridLayoutHints[]{gridLayoutHints47, gridLayoutHints48, gridLayoutHints51, gridLayoutHints52, gridLayoutHints53}, new Object[]{gridLayout15, abstractWidgetController37, gridLayout16, abstractWidgetController40, abstractWidgetController41});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout14});
                menuItemController.add(abstractWidgetController28);
                menuItemController.add(abstractWidgetController35);
                menuItemController.add(abstractWidgetController29);
                menuItemController.add(abstractWidgetController39);
                menuItemController.add(abstractWidgetController38);
                menuItemController.add(abstractWidgetController30);
                menuItemController.add(abstractWidgetController31);
                menuItemController.add(abstractWidgetController36);
                menuItemController.add(abstractWidgetController32);
                menuItemController.add(abstractWidgetController40);
                menuItemController.add(abstractWidgetController33);
                menuItemController.add(abstractWidgetController34);
                menuItemController.add(abstractWidgetController41);
                menuItemController.add(abstractWidgetController37);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
            case 4: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints.grow = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.shrink = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints.size = new int[]{30, -1};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                AbstractWidgetController abstractWidgetController = this.createCell(14);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.hidemode = 0;
                GridLayout gridLayout17 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints17 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints17.gaps = new int[]{0, 15, 12, 0, 0};
                menuItemColumnsConstraints17.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints17.shrink = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints17.hidemode = new int[]{0, 0, 0, 2};
                gridLayout17.setColumnConstraints(menuItemColumnsConstraints17);
                AxisConstraints axisConstraints17 = new AxisConstraints(1);
                axisConstraints17.alignment = new int[]{5};
                gridLayout17.setRowConstraints(axisConstraints17);
                AbstractWidgetController abstractWidgetController42 = this.createCell(17);
                GridLayoutHints gridLayoutHints54 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController43 = this.createCell(15);
                GridLayoutHints gridLayoutHints55 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController44 = this.createCell(2);
                GridLayoutHints gridLayoutHints56 = new GridLayoutHints(2, 0);
                gridLayoutHints56.widthMax = 40;
                gridLayoutHints56.widthMin = 40;
                gridLayoutHints56.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController45 = this.createCell(3);
                GridLayoutHints gridLayoutHints57 = new GridLayoutHints(3, 0);
                gridLayoutHints57.visibleConditions = -4;
                gridLayout17.setCellConstraints(new GridLayoutHints[]{gridLayoutHints54, gridLayoutHints55, gridLayoutHints56, gridLayoutHints57}, new Object[]{abstractWidgetController42, abstractWidgetController43, abstractWidgetController44, abstractWidgetController45});
                GridLayoutHints gridLayoutHints58 = new GridLayoutHints(1, 0);
                GridLayout gridLayout18 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints18 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints18.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints18.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints18.hidemode = new int[]{2, 2, 2};
                gridLayout18.setColumnConstraints(menuItemColumnsConstraints18);
                AxisConstraints axisConstraints18 = new AxisConstraints(1);
                axisConstraints18.hidemode = new int[]{2};
                gridLayout18.setRowConstraints(axisConstraints18);
                AbstractWidgetController abstractWidgetController46 = this.createCell(4);
                GridLayoutHints gridLayoutHints59 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController47 = this.createCell(5);
                GridLayoutHints gridLayoutHints60 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController48 = this.createCell(6);
                GridLayoutHints gridLayoutHints61 = new GridLayoutHints(2, 0);
                gridLayout18.setCellConstraints(new GridLayoutHints[]{gridLayoutHints59, gridLayoutHints60, gridLayoutHints61}, new Object[]{abstractWidgetController46, abstractWidgetController47, abstractWidgetController48});
                GridLayoutHints gridLayoutHints62 = new GridLayoutHints(1, 1);
                gridLayoutHints62.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints58, gridLayoutHints62}, new Object[]{abstractWidgetController, gridLayout17, gridLayout18});
                GridLayout gridLayout19 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints19 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints19.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints19.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints19.shrink = new float[]{1.0f, 0.0f};
                gridLayout19.setColumnConstraints(menuItemColumnsConstraints19);
                AxisConstraints axisConstraints19 = new AxisConstraints(5);
                axisConstraints19.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints19.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints19.size = new int[]{20, 16, 16, 16, 16};
                gridLayout19.setRowConstraints(axisConstraints19);
                GridLayout gridLayout20 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints20 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints20.alignment = new int[]{1, 8};
                menuItemColumnsConstraints20.gaps = new int[]{0, 22, 0};
                menuItemColumnsConstraints20.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints20.shrink = new float[]{1.0f, 0.0f};
                gridLayout20.setColumnConstraints(menuItemColumnsConstraints20);
                AxisConstraints axisConstraints20 = new AxisConstraints(1);
                axisConstraints20.alignment = new int[]{5};
                gridLayout20.setRowConstraints(axisConstraints20);
                AbstractWidgetController abstractWidgetController49 = this.createCell(7);
                GridLayoutHints gridLayoutHints63 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController50 = this.createCell(8);
                GridLayoutHints gridLayoutHints64 = new GridLayoutHints(1, 0);
                gridLayout20.setCellConstraints(new GridLayoutHints[]{gridLayoutHints63, gridLayoutHints64}, new Object[]{abstractWidgetController49, abstractWidgetController50});
                GridLayoutHints gridLayoutHints65 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController51 = this.createCell(9);
                GridLayoutHints gridLayoutHints66 = new GridLayoutHints(1, 0);
                gridLayoutHints66.alignmentVert = 9;
                gridLayoutHints66.rowSpan = 5;
                gridLayoutHints66.widthMax = 216;
                gridLayoutHints66.widthMin = 216;
                gridLayoutHints66.visibleConditions = -13;
                GridLayout gridLayout21 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints21 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints21.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints21.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints21.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints21.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints21.hidemode = new int[]{2, 2, 2, 1};
                gridLayout21.setColumnConstraints(menuItemColumnsConstraints21);
                AxisConstraints axisConstraints21 = new AxisConstraints(1);
                axisConstraints21.alignment = new int[]{5};
                axisConstraints21.hidemode = new int[]{2};
                gridLayout21.setRowConstraints(axisConstraints21);
                AbstractWidgetController abstractWidgetController52 = this.createCell(10);
                GridLayoutHints gridLayoutHints67 = new GridLayoutHints(0, 0);
                gridLayoutHints67.afterEffects = new int[]{0, -1, 0, 0};
                AbstractWidgetController abstractWidgetController53 = this.createCell(11);
                GridLayoutHints gridLayoutHints68 = new GridLayoutHints(1, 0);
                gridLayout21.setCellConstraints(new GridLayoutHints[]{gridLayoutHints67, gridLayoutHints68}, new Object[]{abstractWidgetController52, abstractWidgetController53});
                GridLayoutHints gridLayoutHints69 = new GridLayoutHints(0, 1);
                AbstractWidgetController abstractWidgetController54 = this.createCell(12);
                GridLayoutHints gridLayoutHints70 = new GridLayoutHints(0, 2);
                AbstractWidgetController abstractWidgetController55 = this.createCell(13);
                GridLayoutHints gridLayoutHints71 = new GridLayoutHints(0, 3);
                gridLayout19.setCellConstraints(new GridLayoutHints[]{gridLayoutHints65, gridLayoutHints66, gridLayoutHints69, gridLayoutHints70, gridLayoutHints71}, new Object[]{gridLayout20, abstractWidgetController51, gridLayout21, abstractWidgetController54, abstractWidgetController55});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout19});
                menuItemController.add(abstractWidgetController42);
                menuItemController.add(abstractWidgetController43);
                menuItemController.add(abstractWidgetController49);
                menuItemController.add(abstractWidgetController53);
                menuItemController.add(abstractWidgetController52);
                menuItemController.add(abstractWidgetController44);
                menuItemController.add(abstractWidgetController45);
                menuItemController.add(abstractWidgetController50);
                menuItemController.add(abstractWidgetController46);
                menuItemController.add(abstractWidgetController54);
                menuItemController.add(abstractWidgetController47);
                menuItemController.add(abstractWidgetController48);
                menuItemController.add(abstractWidgetController55);
                menuItemController.add(abstractWidgetController51);
                menuItemController.add(abstractWidgetController);
                return menuItemController;
            }
        }
        return null;
    }

    @Override
    public AbstractWidgetController createListItemNoData() {
        return null;
    }

    public AbstractWidgetController createCell(int n) {
        switch (n) {
            case 0: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{-813301504, -796524288, 127, 127, 127});
                iconController.setModelColumn(4);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 1: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(1);
                return labelController;
            }
            case 2: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -1400504064, -1417281280});
                iconController.setModelColumn(3);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 3: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -1400504064, -1417281280});
                iconController.setModelColumn(3);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 4: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(10);
                return labelController;
            }
            case 5: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setTextIds(new int[]{-1316224768, -1316224768, -1299447552});
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(12);
                return labelController;
            }
            case 6: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(11);
                return labelController;
            }
            case 7: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setModelColumn(0);
                return labelController;
            }
            case 8: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -1400504064, -1417281280});
                iconController.setModelColumn(3);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 9: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                return labelController;
            }
            case 10: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 344391936, -1383726848});
                iconController.setModelColumn(14);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 11: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -343539456, -1366949632});
                iconController.setModelColumn(15);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 12: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(10);
                return labelController;
            }
            case 13: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(11);
                return labelController;
            }
            case 14: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127});
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 15: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(0);
                return labelController;
            }
            case 16: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{1418395904, 1435173120, 1451950336, 1468727552, 1485504768, 1502281984, 1519059200, 1535836416, 1552613632, 1569390848, 1586168064, 1602945280, 1619722496, 1636499712, 1653276928, 1670054144, -1198915328, 1703608576, 1720385792, 1737163008, 1753940224, 1770717440, 1787494656, 1804271872, 1821049088, 1837826304, 1854603520, 1871380736, 1888157952, 1904935168, 1921712384, 1938489600});
                labelController.setModelColumn(2);
                return labelController;
            }
            case 17: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{194});
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
        }
        return null;
    }
}

