/*
 * Decompiled with CFR 0.152.
 * 
 * Could not load the following classes:
 *  de.audi.atip.utils.reactive.properties.LoggingPropertyFactory
 */
package de.audi.app.terminalmode.core;

import de.audi.app.terminalmode.ITerminalLogger$LogScope;
import de.audi.app.terminalmode.ITerminalModeConfiguration;
import de.audi.app.terminalmode.SmartphoneManager$SmartphoneType;
import de.audi.app.terminalmode.core.TerminalModeApplication;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$1;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$2;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$3;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$4;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$5;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$6;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$7;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$8;
import de.audi.app.terminalmode.core.TerminalModeApplication$1$9;
import de.audi.app.terminalmode.logging.TerminalModeLogger;
import de.audi.atip.base.IFrameworkAccess;
import de.audi.atip.job.JobLogger;
import de.audi.atip.log.LogChannel;
import de.audi.atip.utils.dispatching.DispatcherBaseAdapter;
import de.audi.atip.utils.injector.Injector$Binder;
import de.audi.atip.utils.injector.Injector$IConfig;
import de.audi.atip.utils.reactive.bindings.ServiceBindings;
import de.audi.atip.utils.reactive.properties.LoggingPropertyFactory;
import de.esolutions.fw.util.commons.job.DispatcherBase;
import de.esolutions.fw.util.commons.job.StatisticInterceptor;
import org.osgi.framework.BundleContext;

class TerminalModeApplication$1
implements Injector$IConfig {
    private final /* synthetic */ IFrameworkAccess val$pFramework;
    private final /* synthetic */ ITerminalModeConfiguration val$pConfiguration;
    private final /* synthetic */ BundleContext val$pContext;
    private final /* synthetic */ TerminalModeApplication this$0;

    TerminalModeApplication$1(TerminalModeApplication terminalModeApplication, IFrameworkAccess iFrameworkAccess, ITerminalModeConfiguration iTerminalModeConfiguration, BundleContext bundleContext) {
        this.this$0 = terminalModeApplication;
        this.val$pFramework = iFrameworkAccess;
        this.val$pConfiguration = iTerminalModeConfiguration;
        this.val$pContext = bundleContext;
    }

    @Override
    public void configure(Injector$Binder injector$Binder) {
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$base$IFrameworkAccess == null ? (TerminalModeApplication.class$de$audi$atip$base$IFrameworkAccess = TerminalModeApplication.class$("de.audi.atip.base.IFrameworkAccess")) : TerminalModeApplication.class$de$audi$atip$base$IFrameworkAccess).toInstance(this.val$pFramework);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$ITerminalModeConfiguration == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$ITerminalModeConfiguration = TerminalModeApplication.class$("de.audi.app.terminalmode.ITerminalModeConfiguration")) : TerminalModeApplication.class$de$audi$app$terminalmode$ITerminalModeConfiguration).toInstance(this.val$pConfiguration);
        injector$Binder.bind(TerminalModeApplication.class$org$osgi$framework$BundleContext == null ? (TerminalModeApplication.class$org$osgi$framework$BundleContext = TerminalModeApplication.class$("org.osgi.framework.BundleContext")) : TerminalModeApplication.class$org$osgi$framework$BundleContext).toInstance(this.val$pContext);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$hmi$IHMIServiceApp == null ? (TerminalModeApplication.class$de$audi$atip$hmi$IHMIServiceApp = TerminalModeApplication.class$("de.audi.atip.hmi.IHMIServiceApp")) : TerminalModeApplication.class$de$audi$atip$hmi$IHMIServiceApp).toInstance(this.val$pFramework.getHmiServiceApp());
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$storage$IStorageAccess == null ? (TerminalModeApplication.class$de$audi$atip$storage$IStorageAccess = TerminalModeApplication.class$("de.audi.atip.storage.IStorageAccess")) : TerminalModeApplication.class$de$audi$atip$storage$IStorageAccess).toInstance(this.val$pFramework.getStorageMgr());
        injector$Binder.bind(TerminalModeApplication.class$de$esolutions$fw$util$commons$timeout$ITimeSource == null ? (TerminalModeApplication.class$de$esolutions$fw$util$commons$timeout$ITimeSource = TerminalModeApplication.class$("de.esolutions.fw.util.commons.timeout.ITimeSource")) : TerminalModeApplication.class$de$esolutions$fw$util$commons$timeout$ITimeSource).toInstance(this.val$pFramework.getMonotonicTimeSource());
        TerminalModeLogger terminalModeLogger = new TerminalModeLogger(this.val$pFramework);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$ITerminalLogger == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$ITerminalLogger = TerminalModeApplication.class$("de.audi.app.terminalmode.ITerminalLogger")) : TerminalModeApplication.class$de$audi$app$terminalmode$ITerminalLogger).toInstance(terminalModeLogger);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$log$LogChannel == null ? (TerminalModeApplication.class$de$audi$atip$log$LogChannel = TerminalModeApplication.class$("de.audi.atip.log.LogChannel")) : TerminalModeApplication.class$de$audi$atip$log$LogChannel).toInstance(terminalModeLogger.main());
        injector$Binder.forScope(ITerminalLogger$LogScope.HMI).bind(TerminalModeApplication.class$de$audi$atip$log$LogChannel == null ? (TerminalModeApplication.class$de$audi$atip$log$LogChannel = TerminalModeApplication.class$("de.audi.atip.log.LogChannel")) : TerminalModeApplication.class$de$audi$atip$log$LogChannel).toInstance(terminalModeLogger.hmi());
        DispatcherBase dispatcherBase = this.val$pFramework.getDispatcherManager().createDispatcher("TerminalMode", new JobLogger(terminalModeLogger.dispatcher()));
        dispatcherBase.addInterceptor(new StatisticInterceptor(dispatcherBase, new JobLogger(terminalModeLogger.dispatcher()), 1000, 0));
        injector$Binder.bind(TerminalModeApplication.class$de$esolutions$fw$util$commons$job$DispatcherBase == null ? (TerminalModeApplication.class$de$esolutions$fw$util$commons$job$DispatcherBase = TerminalModeApplication.class$("de.esolutions.fw.util.commons.job.DispatcherBase")) : TerminalModeApplication.class$de$esolutions$fw$util$commons$job$DispatcherBase).toInstance(dispatcherBase);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$utils$dispatching$IDispatcher == null ? (TerminalModeApplication.class$de$audi$atip$utils$dispatching$IDispatcher = TerminalModeApplication.class$("de.audi.atip.utils.dispatching.IDispatcher")) : TerminalModeApplication.class$de$audi$atip$utils$dispatching$IDispatcher).toInstance(new DispatcherBaseAdapter(dispatcherBase));
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager$ISmartphoneProperties")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$SmartphoneProperties == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$SmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.SmartphoneProperties")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$SmartphoneProperties).asSingleton();
        this.bindAndroidAuto2(injector$Binder);
        this.bindCarplay(injector$Binder);
        this.bindCarlife(injector$Binder);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$util$IStreamableStorageContainer == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$util$IStreamableStorageContainer = TerminalModeApplication.class$("de.audi.app.terminalmode.util.IStreamableStorageContainer")) : TerminalModeApplication.class$de$audi$app$terminalmode$util$IStreamableStorageContainer).toProvider(new TerminalModeApplication$1$1(this)).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$audio$IAudioManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$audio$IAudioManager = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.IAudioManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$audio$IAudioManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$audio$AudioManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$audio$AudioManager = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.AudioManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$audio$AudioManager).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$device$TMDeviceFactory == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$device$TMDeviceFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.device.TMDeviceFactory")) : TerminalModeApplication.class$de$audi$app$terminalmode$device$TMDeviceFactory).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$IContext == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$IContext = TerminalModeApplication.class$("de.audi.app.terminalmode.IContext")) : TerminalModeApplication.class$de$audi$app$terminalmode$IContext).to(TerminalModeApplication.class$de$audi$app$terminalmode$core$TerminalModeContext == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$core$TerminalModeContext = TerminalModeApplication.class$("de.audi.app.terminalmode.core.TerminalModeContext")) : TerminalModeApplication.class$de$audi$app$terminalmode$core$TerminalModeContext).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.DSISmartphoneManagerProxy")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$tghu$command$CommandListManager == null ? (TerminalModeApplication.class$de$audi$tghu$command$CommandListManager = TerminalModeApplication.class$("de.audi.tghu.command.CommandListManager")) : TerminalModeApplication.class$de$audi$tghu$command$CommandListManager).toProvider(new TerminalModeApplication$1$2(this)).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.HardKeyDSIListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$device$IDeviceManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$device$IDeviceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.device.IDeviceManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$device$IDeviceManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$device$DeviceManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$device$DeviceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.device.DeviceManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$device$DeviceManager).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.ISMIDSIControllerListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener).toProvider(new TerminalModeApplication$1$3(this)).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$osgi$IServiceManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$osgi$IServiceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.osgi.IServiceManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$osgi$IServiceManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$osgi$ServiceManagerImpl == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$osgi$ServiceManagerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.osgi.ServiceManagerImpl")) : TerminalModeApplication.class$de$audi$app$terminalmode$osgi$ServiceManagerImpl).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$PhoneAppHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$PhoneAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.PhoneAppHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$PhoneAppHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$NaviAppHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$NaviAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.NaviAppHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$NaviAppHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMKeyEventsHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.keypanel.TMDSIKeyPanelControllerImpl")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl).asSingleton();
        Class clazz = this.val$pConfiguration.isTouchScreenInputWidget() ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMTouchscreenVBListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener) : (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMVirtualButtonListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener);
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMVirtualButtonListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener).to(clazz).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider = TerminalModeApplication.class$("de.audi.app.terminalmode.bt.dsi.IBTDSIControllerListenerUpdateProvider")) : TerminalModeApplication.class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider).to(TerminalModeApplication.class$de$audi$app$terminalmode$bt$dsi$BTDSIController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$bt$dsi$BTDSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.bt.dsi.BTDSIController")) : TerminalModeApplication.class$de$audi$app$terminalmode$bt$dsi$BTDSIController).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.IDiagnosisManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisManagerImpl")) : TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$events$IEventBus == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$events$IEventBus = TerminalModeApplication.class$("de.audi.app.terminalmode.events.IEventBus")) : TerminalModeApplication.class$de$audi$app$terminalmode$events$IEventBus).to(TerminalModeApplication.class$de$audi$app$terminalmode$events$TerminalModeEventBus == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$events$TerminalModeEventBus = TerminalModeApplication.class$("de.audi.app.terminalmode.events.TerminalModeEventBus")) : TerminalModeApplication.class$de$audi$app$terminalmode$events$TerminalModeEventBus).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$statemachine$IStateHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$statemachine$IStateHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.statemachine.IStateHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$statemachine$IStateHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$statemachine$StateHandlerImpl == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$statemachine$StateHandlerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.statemachine.StateHandlerImpl")) : TerminalModeApplication.class$de$audi$app$terminalmode$statemachine$StateHandlerImpl).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher = TerminalModeApplication.class$("de.audi.app.terminalmode.actionproxy.IActionProxyDispatcher")) : TerminalModeApplication.class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher).to(TerminalModeApplication.class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.actionproxy.ActionProxyDispatcherImpl")) : TerminalModeApplication.class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$FactoryResetMessageHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$FactoryResetMessageHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.FactoryResetMessageHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$FactoryResetMessageHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.ISmartphoneIntegrationDSIController")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController).toProvider(new TerminalModeApplication$1$4(this)).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$CommandListHelper == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$CommandListHelper = TerminalModeApplication.class$("de.audi.app.terminalmode.CommandListHelper")) : TerminalModeApplication.class$de$audi$app$terminalmode$CommandListHelper).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.SmartphoneIntegrationDSILifecycleController")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$INightDayModeHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$INightDayModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.INightDayModeHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$INightDayModeHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$NightDayModeHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$NightDayModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.NightDayModeHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$NightDayModeHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$device$IDeviceVariantsHandling == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$device$IDeviceVariantsHandling = TerminalModeApplication.class$("de.audi.app.terminalmode.device.IDeviceVariantsHandling")) : TerminalModeApplication.class$de$audi$app$terminalmode$device$IDeviceVariantsHandling).to(TerminalModeApplication.class$de$audi$app$terminalmode$device$DeviceVariantsHandling == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$device$DeviceVariantsHandling = TerminalModeApplication.class$("de.audi.app.terminalmode.device.DeviceVariantsHandling")) : TerminalModeApplication.class$de$audi$app$terminalmode$device$DeviceVariantsHandling).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.logging.TerminalModeLoggingDecoratorFactory")) : TerminalModeApplication.class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$audio$AudibleStateSyncer == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$audio$AudibleStateSyncer = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.AudibleStateSyncer")) : TerminalModeApplication.class$de$audi$app$terminalmode$audio$AudibleStateSyncer).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$HardKeyListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$HardKeyListener = TerminalModeApplication.class$("de.audi.app.terminalmode.HardKeyListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$HardKeyListener).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$combi$TerminalModeBapCombi == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$combi$TerminalModeBapCombi = TerminalModeApplication.class$("de.audi.app.terminalmode.combi.TerminalModeBapCombi")) : TerminalModeApplication.class$de$audi$app$terminalmode$combi$TerminalModeBapCombi).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisServiceTracker")) : TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisProvider")) : TerminalModeApplication.class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$ExternalEventsListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$ExternalEventsListener = TerminalModeApplication.class$("de.audi.app.terminalmode.ExternalEventsListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$ExternalEventsListener).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$SDSAppHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SDSAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.SDSAppHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$SDSAppHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$TMInterAppHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$TMInterAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.TMInterAppHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$TMInterAppHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$AutomaticDeviceActivator == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$AutomaticDeviceActivator = TerminalModeApplication.class$("de.audi.app.terminalmode.AutomaticDeviceActivator")) : TerminalModeApplication.class$de$audi$app$terminalmode$AutomaticDeviceActivator).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.NewDeviceHMIHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.CurrentPlayingTrackHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler).asSingleton();
        injector$Binder.forScope(ITerminalLogger$LogScope.HMI).bind(TerminalModeApplication.class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.SmartphoneRouteGuidanceHMIHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.HighPriorityResourceTracker")) : TerminalModeApplication.class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.MFLPhoneButtonsListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$device$TMDeviceStorekeeper == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$device$TMDeviceStorekeeper = TerminalModeApplication.class$("de.audi.app.terminalmode.device.TMDeviceStorekeeper")) : TerminalModeApplication.class$de$audi$app$terminalmode$device$TMDeviceStorekeeper).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$interapp$BluetoothWaker == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$interapp$BluetoothWaker = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.BluetoothWaker")) : TerminalModeApplication.class$de$audi$app$terminalmode$interapp$BluetoothWaker).asSingleton();
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$utils$reactive$properties$PropertyFactory == null ? (TerminalModeApplication.class$de$audi$atip$utils$reactive$properties$PropertyFactory = TerminalModeApplication.class$("de.audi.atip.utils.reactive.properties.PropertyFactory")) : TerminalModeApplication.class$de$audi$atip$utils$reactive$properties$PropertyFactory).toInstance(LoggingPropertyFactory.create((LogChannel)terminalModeLogger.main(), (int)1078071040));
        injector$Binder.bind(TerminalModeApplication.class$de$audi$atip$utils$reactive$bindings$IServiceBindings == null ? (TerminalModeApplication.class$de$audi$atip$utils$reactive$bindings$IServiceBindings = TerminalModeApplication.class$("de.audi.atip.utils.reactive.bindings.IServiceBindings")) : TerminalModeApplication.class$de$audi$atip$utils$reactive$bindings$IServiceBindings).toInstance(ServiceBindings.create(this.val$pContext));
        injector$Binder.bind(TerminalModeApplication.class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.OnlinePOICallHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler).asSingleton();
    }

    private void bindAndroidAuto2(Injector$Binder injector$Binder) {
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager$SmartphoneType")) : TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType).toInstance(SmartphoneManager$SmartphoneType.ANDROIDAUTO2);
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.IDSIAndroidAuto2TransferObjectFactory")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.DSIAndroidAuto2TransferObjectFactory")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$org$dsi$ifc$androidauto2$DSIAndroidAuto2 == null ? (TerminalModeApplication.class$org$dsi$ifc$androidauto2$DSIAndroidAuto2 = TerminalModeApplication.class$("org.dsi.ifc.androidauto2.DSIAndroidAuto2")) : TerminalModeApplication.class$org$dsi$ifc$androidauto2$DSIAndroidAuto2).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.DSIAndroidAuto2Proxy")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.IAndroidAuto2RequestHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2RequestHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2DSIManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManagerListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener).to(TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2ListenerDistributor")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener == null ? (TerminalModeApplication.class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener = TerminalModeApplication.class$("org.dsi.ifc.androidauto2.DSIAndroidAuto2Listener")) : TerminalModeApplication.class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener).toProvider(new TerminalModeApplication$1$5(this)).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.DSIAndroidAuto2DSIController")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2Subsystem")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem).asSingleton();
        TerminalModeApplication$1$6 terminalModeApplication$1$6 = new TerminalModeApplication$1$6(this);
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.ITMDeviceSubsystem")) : TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem).toProvider(terminalModeApplication$1$6).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.IDSIControllerStateListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener).toProvider(terminalModeApplication$1$6).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.ITerminalModeDSIKeyEventsController")) : TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2KeyEventsController")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2EventListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.mic.IAndroidAuto2MicHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.mic.AndroidAuto2MicHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.nav.IAndroidAuto2NavHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.nav.AndroidAuto2NavHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.audio.IAndroidAuto2AudioHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.audio.AndroidAuto2AudioHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.video.IAndroidAuto2VideoHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.video.AndroidAuto2VideoHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.ANDROIDAUTO2).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.voice.AndroidAuto2VoiceSessionHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler).asSingleton();
    }

    private void bindCarplay(Injector$Binder injector$Binder) {
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager$SmartphoneType")) : TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType).toInstance(SmartphoneManager$SmartphoneType.CARPLAY);
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.CarplayDSILifecycleController")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.IDSICarplayTransferObjectFactory")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.DSICarplayTransferObjectFactory")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarplaySmartphoneProperties")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarPlayDSIManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager).asSingleton();
        TerminalModeApplication$1$7 terminalModeApplication$1$7 = new TerminalModeApplication$1$7(this);
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.ICarplayDSIControllerListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener).toProvider(terminalModeApplication$1$7).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.ITMDeviceSubsystem")) : TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem).toProvider(terminalModeApplication$1$7).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).toProvider(terminalModeApplication$1$7).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManagerListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener).to(TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.DSICarplaySafe")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.DSICarplaySafeProxy")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARPLAY).bind(TerminalModeApplication.class$org$dsi$ifc$carplay$DSICarplayListener == null ? (TerminalModeApplication.class$org$dsi$ifc$carplay$DSICarplayListener = TerminalModeApplication.class$("org.dsi.ifc.carplay.DSICarplayListener")) : TerminalModeApplication.class$org$dsi$ifc$carplay$DSICarplayListener).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.CarplayDSILifecycleController$DSICarplayListenerImpl")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl).asSingleton();
    }

    private void bindCarlife(Injector$Binder injector$Binder) {
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager$SmartphoneType")) : TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType).toInstance(SmartphoneManager$SmartphoneType.CARLIFE);
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$org$dsi$ifc$carlife$DSICarlife == null ? (TerminalModeApplication.class$org$dsi$ifc$carlife$DSICarlife = TerminalModeApplication.class$("org.dsi.ifc.carlife.DSICarlife")) : TerminalModeApplication.class$org$dsi$ifc$carlife$DSICarlife).to(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carlife.DSICarlifeProxy")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManagerListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener).to(TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$SmartphoneManager).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeListenerDistributor")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$org$dsi$ifc$carlife$DSICarlifeListener == null ? (TerminalModeApplication.class$org$dsi$ifc$carlife$DSICarlifeListener = TerminalModeApplication.class$("org.dsi.ifc.carlife.DSICarlifeListener")) : TerminalModeApplication.class$org$dsi$ifc$carlife$DSICarlifeListener).toProvider(new TerminalModeApplication$1$8(this)).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carlife.CarlifeDSIController")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeSubsystem")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem).asSingleton();
        TerminalModeApplication$1$9 terminalModeApplication$1$9 = new TerminalModeApplication$1$9(this);
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.ITMDeviceSubsystem")) : TerminalModeApplication.class$de$audi$app$terminalmode$ITMDeviceSubsystem).toProvider(terminalModeApplication$1$9).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.IDSIControllerStateListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener).toProvider(terminalModeApplication$1$9).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.ITerminalModeDSIKeyEventsController")) : TerminalModeApplication.class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController).to(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeKeyEventsController")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeEventListener")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.DSIMHIConstantsMapper")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIRequestModeHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeHMISetModeHandler")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler).asSingleton();
        injector$Binder.forScope(SmartphoneManager$SmartphoneType.CARLIFE).bind(TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager == null ? (TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIAppNotInstalledManager")) : TerminalModeApplication.class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager).asSingleton();
    }

    static /* synthetic */ IFrameworkAccess access$000(TerminalModeApplication$1 terminalModeApplication$1) {
        return terminalModeApplication$1.val$pFramework;
    }
}

