/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface HMIPopUpsSWDL {
    public static final int POPUP_SWDLPOPUP_ID;
    public static final int POPUP_SETTINGSUPDATEINTERRUPTSD_ID;
    public static final int POPUP_SETTINGSUPDATESUMMARYFAILURE_ID;
    public static final int POPUP_SETTINGSUPDATESUMMARYSUCCESSFUL_ID;
    public static final int POPUP_SETTINGS_POPUP_NAVI_NEW_DATA_AVAILABLE_LICENCE_AVAILABLE_ID;
    public static final int POPUP_SETTINGS_POPUP_NAVI_NEW_DATA_AVAILABLE_LICENCE_NOT_AVAILABLE_ID;
    public static final int POPUP_SETTINGS_POPUP_NAVI_LICENCE_GETTTING_INVALID_ID;
    public static final int POPUP_SETTINGS_POPUP_GEN_NEW_DATA_AVAILABLE_ID;
    public static final int POPUP_SETTINGS_UPDATE_SOURCE_INCOMPATIBLE_DATA_ID;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SOURCE_CONFIRMATION_ID;
    public static final int POPUP_SETTINGS_ONLINE_UPDATE_FAILURE_RETRY_POSSIBLE_ID;
    public static final int POPUP_SETTINGS_ONLINE_UPDATE_FAILURE_ID;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_ACCESS_FAILURE_ID;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_INCOMPATIBLE_DATA_ID;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_NO_DATA_ID;
    public static final int POPUP_SETTINGS_POPUP_ONLINE_UPDATE_SERVER_FAILURE_ID;
    public static final int POPUP_SWDLSUMMARYCHANGED_ID;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SYSTEM_PROPOSAL_DISCLAIMER_ID;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SYSTEM_PROPOSAL_ID;
    public static final int POPUP_SETTINGS_POPUP_NAVI_NEW_DATA_AVAILABLE_LICENCE_DESTINATION_ID;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_NAV_DB_SUMMARY_UOTA_SUCCESSFUL_ID;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_PPOI_SUMMARY_UOTA_SUCCESSFUL_ID;
    public static final int POPUP_SETTINGS_POPUP_UPDATE_SYSTEM_PROPOSAL_DESTINATION_ID;
}

