/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerFocusAddressBook {
    public static final int FOCUS_ADDRESSBOOK_ADDRESS_IS_AVAILABLE;
    public static final int FOCUS_ADDRESSBOOK_BUSINESS_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE;
    public static final int FOCUS_ADDRESSBOOK_BUSINESS_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE1;
    public static final int FOCUS_ADDRESSBOOK_EMAIL_ADDRESS_IS_AVAILABLE;
    public static final int FOCUS_ADDRESSBOOK_PRIVATE_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE;
    public static final int FOCUS_ADDRESSBOOK_PRIVATE_NAVIGATION_DESTINATION_IS_ALREADY_AVAILABLE1;
    public static final int FOCUS_ADDRESSBOOK_TELEPHONE_NUMBER_IS_AVAILABLE;
}

