/*
 * Decompiled with CFR 0.152.
 */
package de.audi.atip.hmi;

public interface IDrawerFocusMessaging {
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_A_TELEPHONE_NUMBER;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_A_V_CARD;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_ATTACHMENTS;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_EXTRACTED_EMAIL_ADDRESSES;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_EXTRACTED_TELEPHONE_NUMBERS;
    public static final int FOCUS_MESSAGING_ELEMENT_CONTAINS_NAVIGATION_DATA;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_DELETED;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_DRAFT;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_INBOX;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_OUTBOX;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_ROOT;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_SENT;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_LOCATED_IN_FOLDER_USERDEFINED;
    public static final int FOCUS_MESSAGING_ELEMENT_IS_STORED_ON_S_I_M_CARD;
    public static final int FOCUS_MESSAGING_READOUT_OF_ELEMENT_IS_SUPPORTED_BY_THE_SYSTEM;
}

