/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.online;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIDESTINATIONIMPORT_ENTRIES = 1;
    public static final int ATTRIBUTE_ID_DSIONLINEESIMTRAFFICNOTIFICATION_ESIMNOTIFICATION = 1;
    public static final int ATTRIBUTE_ID_DSIONLINEPICNAV_SYNCSTATUS = 1;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_APPLICATIONSTATE = 1;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_DEVICEENUMERATOR = 3;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_EXTERNALPROFILEINFO = 4;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_COREPROFILEINFO = 5;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICESTATE = 6;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICELIST = 7;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_PROFILESTATE = 8;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICES = 9;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SERVICEREGISTRATION = 10;
    public static final int ATTRIBUTE_ID_DSIONLINESERVICEREGISTRATION_SPINREQUIRED = 11;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFIC_CONSUMERREADY = 1;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFIC_WANTONLINETRAFFICDATA = 2;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFICLIGHTINFO_TRAFFICLIGHTINFO = 1;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFICLIGHTINFO_TRAFFICLIGHTSPEED = 2;
    public static final int ATTRIBUTE_ID_DSIONLINETRAFFICLIGHTINFO_TRAFFICLIGHTTIME = 3;
}

