/*
 * Decompiled with CFR 0.152.
 */
package de.audi.app.terminalmode.core;

import de.audi.app.terminalmode.IContext;
import de.audi.app.terminalmode.ITerminalLogger;
import de.audi.app.terminalmode.ITerminalModeComponent;
import de.audi.app.terminalmode.ITerminalModeConfiguration;
import de.audi.app.terminalmode.SmartphoneManager;
import de.audi.app.terminalmode.core.ITerminalModeApplicationFactory;
import de.audi.app.terminalmode.core.TerminalModeContext;
import de.audi.app.terminalmode.device.DeviceManager;
import de.audi.app.terminalmode.dsi.smartphoneintegration.SmartphoneIntegrationDSILifecycleController;
import de.audi.app.terminalmode.logging.TerminalModeLogger;
import de.audi.app.terminalmode.osgi.ServiceManagerImpl;
import de.audi.app.terminalmode.util.DispatcherProxy;
import de.audi.app.terminalmode.util.StreamableStorageContainer;
import de.audi.atip.base.IFrameworkAccess;
import de.audi.atip.job.JobLogger;
import de.audi.atip.utils.dispatching.DispatcherBaseAdapter;
import de.audi.atip.utils.generics.GIterator;
import de.audi.atip.utils.generics.GList;
import de.audi.atip.utils.generics.Generics;
import de.audi.atip.utils.injector.IInjector;
import de.audi.atip.utils.injector.Injector;
import de.audi.atip.utils.reactive.bindings.ServiceBindings;
import de.audi.atip.utils.reactive.properties.LoggingPropertyFactory;
import de.audi.tghu.command.CommandListManager;
import de.esolutions.fw.util.commons.job.DispatcherBase;
import de.esolutions.fw.util.commons.job.StatisticInterceptor;
import org.dsi.ifc.androidauto2.DSIAndroidAuto2Listener;
import org.dsi.ifc.carlife.DSICarlifeListener;
import org.osgi.framework.BundleContext;

public class TerminalModeApplication {
    private static final String LOGCLASS = "TerminalModeApplication";
    private final TerminalModeContext contextBuilder;
    private final IContext context;
    private final GList<ITerminalModeComponent> terminalModeComponents = Generics.newArrayList();
    private final IInjector injector;
    static /* synthetic */ Class class$de$audi$atip$base$IFrameworkAccess;
    static /* synthetic */ Class class$de$audi$app$terminalmode$ITerminalModeConfiguration;
    static /* synthetic */ Class class$org$osgi$framework$BundleContext;
    static /* synthetic */ Class class$de$audi$atip$hmi$IHMIServiceApp;
    static /* synthetic */ Class class$de$audi$atip$storage$IStorageAccess;
    static /* synthetic */ Class class$de$esolutions$fw$util$commons$timeout$ITimeSource;
    static /* synthetic */ Class class$de$audi$app$terminalmode$ITerminalLogger;
    static /* synthetic */ Class class$de$audi$atip$log$LogChannel;
    static /* synthetic */ Class class$de$esolutions$fw$util$commons$job$DispatcherBase;
    static /* synthetic */ Class class$de$audi$atip$utils$dispatching$IDispatcher;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$SmartphoneProperties;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties;
    static /* synthetic */ Class class$de$audi$app$terminalmode$util$IStreamableStorageContainer;
    static /* synthetic */ Class class$de$audi$app$terminalmode$audio$AudioManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$audio$IAudioManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$device$TMDeviceFactory;
    static /* synthetic */ Class class$de$audi$app$terminalmode$core$TerminalModeContext;
    static /* synthetic */ Class class$de$audi$app$terminalmode$IContext;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager;
    static /* synthetic */ Class class$de$audi$tghu$command$CommandListManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$device$DeviceManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$device$IDeviceManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$osgi$ServiceManagerImpl;
    static /* synthetic */ Class class$de$audi$app$terminalmode$osgi$IServiceManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$PhoneAppHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$NaviAppHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl;
    static /* synthetic */ Class class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$bt$dsi$BTDSIController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider;
    static /* synthetic */ Class class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl;
    static /* synthetic */ Class class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$events$TerminalModeEventBus;
    static /* synthetic */ Class class$de$audi$app$terminalmode$events$IEventBus;
    static /* synthetic */ Class class$de$audi$app$terminalmode$statemachine$StateHandlerImpl;
    static /* synthetic */ Class class$de$audi$app$terminalmode$statemachine$IStateHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl;
    static /* synthetic */ Class class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher;
    static /* synthetic */ Class class$de$audi$app$terminalmode$FactoryResetMessageHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$CommandListHelper;
    static /* synthetic */ Class class$de$audi$app$terminalmode$NightDayModeHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$INightDayModeHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$device$DeviceVariantsHandling;
    static /* synthetic */ Class class$de$audi$app$terminalmode$device$IDeviceVariantsHandling;
    static /* synthetic */ Class class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory;
    static /* synthetic */ Class class$de$audi$app$terminalmode$audio$AudibleStateSyncer;
    static /* synthetic */ Class class$de$audi$app$terminalmode$HardKeyListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$combi$TerminalModeBapCombi;
    static /* synthetic */ Class class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker;
    static /* synthetic */ Class class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider;
    static /* synthetic */ Class class$de$audi$app$terminalmode$ExternalEventsListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$SDSAppHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$TMInterAppHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$AutomaticDeviceActivator;
    static /* synthetic */ Class class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$device$TMDeviceStorekeeper;
    static /* synthetic */ Class class$de$audi$app$terminalmode$interapp$BluetoothWaker;
    static /* synthetic */ Class class$de$audi$atip$utils$reactive$properties$PropertyFactory;
    static /* synthetic */ Class class$de$audi$atip$utils$reactive$bindings$IServiceBindings;
    static /* synthetic */ Class class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy;
    static /* synthetic */ Class class$org$dsi$ifc$androidauto2$DSIAndroidAuto2;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$SmartphoneManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor;
    static /* synthetic */ Class class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem;
    static /* synthetic */ Class class$de$audi$app$terminalmode$ITMDeviceSubsystem;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl;
    static /* synthetic */ Class class$org$dsi$ifc$carplay$DSICarplayListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy;
    static /* synthetic */ Class class$org$dsi$ifc$carlife$DSICarlife;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor;
    static /* synthetic */ Class class$org$dsi$ifc$carlife$DSICarlifeListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler;
    static /* synthetic */ Class class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager;
    static /* synthetic */ Class class$de$audi$app$terminalmode$audio$SpeechReset;

    public TerminalModeApplication(final BundleContext bundleContext, final IFrameworkAccess iFrameworkAccess, final ITerminalModeConfiguration iTerminalModeConfiguration, ITerminalModeApplicationFactory iTerminalModeApplicationFactory) {
        this.injector = Injector.createInjector(new Injector.IConfig(){

            public void configure(Injector.Binder binder) {
                binder.bind(class$de$audi$atip$base$IFrameworkAccess == null ? (class$de$audi$atip$base$IFrameworkAccess = TerminalModeApplication.class$("de.audi.atip.base.IFrameworkAccess")) : class$de$audi$atip$base$IFrameworkAccess).toInstance(iFrameworkAccess);
                binder.bind(class$de$audi$app$terminalmode$ITerminalModeConfiguration == null ? (class$de$audi$app$terminalmode$ITerminalModeConfiguration = TerminalModeApplication.class$("de.audi.app.terminalmode.ITerminalModeConfiguration")) : class$de$audi$app$terminalmode$ITerminalModeConfiguration).toInstance(iTerminalModeConfiguration);
                binder.bind(class$org$osgi$framework$BundleContext == null ? (class$org$osgi$framework$BundleContext = TerminalModeApplication.class$("org.osgi.framework.BundleContext")) : class$org$osgi$framework$BundleContext).toInstance(bundleContext);
                binder.bind(class$de$audi$atip$hmi$IHMIServiceApp == null ? (class$de$audi$atip$hmi$IHMIServiceApp = TerminalModeApplication.class$("de.audi.atip.hmi.IHMIServiceApp")) : class$de$audi$atip$hmi$IHMIServiceApp).toInstance(iFrameworkAccess.getHmiServiceApp());
                binder.bind(class$de$audi$atip$storage$IStorageAccess == null ? (class$de$audi$atip$storage$IStorageAccess = TerminalModeApplication.class$("de.audi.atip.storage.IStorageAccess")) : class$de$audi$atip$storage$IStorageAccess).toInstance(iFrameworkAccess.getStorageMgr());
                binder.bind(class$de$esolutions$fw$util$commons$timeout$ITimeSource == null ? (class$de$esolutions$fw$util$commons$timeout$ITimeSource = TerminalModeApplication.class$("de.esolutions.fw.util.commons.timeout.ITimeSource")) : class$de$esolutions$fw$util$commons$timeout$ITimeSource).toInstance(iFrameworkAccess.getMonotonicTimeSource());
                TerminalModeLogger terminalModeLogger = new TerminalModeLogger(iFrameworkAccess);
                binder.bind(class$de$audi$app$terminalmode$ITerminalLogger == null ? (class$de$audi$app$terminalmode$ITerminalLogger = TerminalModeApplication.class$("de.audi.app.terminalmode.ITerminalLogger")) : class$de$audi$app$terminalmode$ITerminalLogger).toInstance(terminalModeLogger);
                binder.bind(class$de$audi$atip$log$LogChannel == null ? (class$de$audi$atip$log$LogChannel = TerminalModeApplication.class$("de.audi.atip.log.LogChannel")) : class$de$audi$atip$log$LogChannel).toInstance(terminalModeLogger.main());
                binder.forScope(ITerminalLogger.LogScope.HMI).bind(class$de$audi$atip$log$LogChannel == null ? (class$de$audi$atip$log$LogChannel = TerminalModeApplication.class$("de.audi.atip.log.LogChannel")) : class$de$audi$atip$log$LogChannel).toInstance(terminalModeLogger.hmi());
                DispatcherBase dispatcherBase = iFrameworkAccess.getDispatcherManager().createDispatcher("TerminalMode", new JobLogger(terminalModeLogger.dispatcher()));
                dispatcherBase.addInterceptor(new StatisticInterceptor(dispatcherBase, new JobLogger(terminalModeLogger.dispatcher()), 1000, 0));
                binder.bind(class$de$esolutions$fw$util$commons$job$DispatcherBase == null ? (class$de$esolutions$fw$util$commons$job$DispatcherBase = TerminalModeApplication.class$("de.esolutions.fw.util.commons.job.DispatcherBase")) : class$de$esolutions$fw$util$commons$job$DispatcherBase).toInstance(dispatcherBase);
                binder.bind(class$de$audi$atip$utils$dispatching$IDispatcher == null ? (class$de$audi$atip$utils$dispatching$IDispatcher = TerminalModeApplication.class$("de.audi.atip.utils.dispatching.IDispatcher")) : class$de$audi$atip$utils$dispatching$IDispatcher).toInstance(new DispatcherBaseAdapter(dispatcherBase));
                binder.bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager$ISmartphoneProperties")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager$ISmartphoneProperties).to(class$de$audi$app$terminalmode$smartphone$SmartphoneProperties == null ? (class$de$audi$app$terminalmode$smartphone$SmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.SmartphoneProperties")) : class$de$audi$app$terminalmode$smartphone$SmartphoneProperties).asSingleton();
                this.bindAndroidAuto2(binder);
                this.bindCarplay(binder);
                this.bindCarlife(binder);
                binder.bind(class$de$audi$app$terminalmode$util$IStreamableStorageContainer == null ? (class$de$audi$app$terminalmode$util$IStreamableStorageContainer = TerminalModeApplication.class$("de.audi.app.terminalmode.util.IStreamableStorageContainer")) : class$de$audi$app$terminalmode$util$IStreamableStorageContainer).toProvider(new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return new StreamableStorageContainer(iFrameworkAccess.getStorageMgr(), ((ITerminalLogger)iInjector.getInstance(class$de$audi$app$terminalmode$ITerminalLogger == null ? (class$de$audi$app$terminalmode$ITerminalLogger = TerminalModeApplication.class$("de.audi.app.terminalmode.ITerminalLogger")) : class$de$audi$app$terminalmode$ITerminalLogger)).main(), 1008, 1);
                    }
                }).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$audio$IAudioManager == null ? (class$de$audi$app$terminalmode$audio$IAudioManager = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.IAudioManager")) : class$de$audi$app$terminalmode$audio$IAudioManager).to(class$de$audi$app$terminalmode$audio$AudioManager == null ? (class$de$audi$app$terminalmode$audio$AudioManager = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.AudioManager")) : class$de$audi$app$terminalmode$audio$AudioManager).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$device$TMDeviceFactory == null ? (class$de$audi$app$terminalmode$device$TMDeviceFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.device.TMDeviceFactory")) : class$de$audi$app$terminalmode$device$TMDeviceFactory).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$IContext == null ? (class$de$audi$app$terminalmode$IContext = TerminalModeApplication.class$("de.audi.app.terminalmode.IContext")) : class$de$audi$app$terminalmode$IContext).to(class$de$audi$app$terminalmode$core$TerminalModeContext == null ? (class$de$audi$app$terminalmode$core$TerminalModeContext = TerminalModeApplication.class$("de.audi.app.terminalmode.core.TerminalModeContext")) : class$de$audi$app$terminalmode$core$TerminalModeContext).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).to(class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy == null ? (class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.DSISmartphoneManagerProxy")) : class$de$audi$app$terminalmode$dsi$DSISmartphoneManagerProxy).asSingleton();
                binder.bind(class$de$audi$tghu$command$CommandListManager == null ? (class$de$audi$tghu$command$CommandListManager = TerminalModeApplication.class$("de.audi.tghu.command.CommandListManager")) : class$de$audi$tghu$command$CommandListManager).toProvider(new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return new CommandListManager("TerminalModeCLM", (IFrameworkAccess)iInjector.getInstance(class$de$audi$atip$base$IFrameworkAccess == null ? (class$de$audi$atip$base$IFrameworkAccess = TerminalModeApplication.class$("de.audi.atip.base.IFrameworkAccess")) : class$de$audi$atip$base$IFrameworkAccess), ((ITerminalLogger)iInjector.getInstance(class$de$audi$app$terminalmode$ITerminalLogger == null ? (class$de$audi$app$terminalmode$ITerminalLogger = TerminalModeApplication.class$("de.audi.app.terminalmode.ITerminalLogger")) : class$de$audi$app$terminalmode$ITerminalLogger)).commandList(), null, null);
                    }
                }).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener == null ? (class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.HardKeyDSIListener")) : class$de$audi$app$terminalmode$smartphone$HardKeyDSIListener).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$device$IDeviceManager == null ? (class$de$audi$app$terminalmode$device$IDeviceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.device.IDeviceManager")) : class$de$audi$app$terminalmode$device$IDeviceManager).to(class$de$audi$app$terminalmode$device$DeviceManager == null ? (class$de$audi$app$terminalmode$device$DeviceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.device.DeviceManager")) : class$de$audi$app$terminalmode$device$DeviceManager).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener == null ? (class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.ISMIDSIControllerListener")) : class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISMIDSIControllerListener).toProvider(new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return ((DeviceManager)iInjector.getInstance(class$de$audi$app$terminalmode$device$DeviceManager == null ? (class$de$audi$app$terminalmode$device$DeviceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.device.DeviceManager")) : class$de$audi$app$terminalmode$device$DeviceManager)).createSMDControllerListener();
                    }
                }).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$osgi$IServiceManager == null ? (class$de$audi$app$terminalmode$osgi$IServiceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.osgi.IServiceManager")) : class$de$audi$app$terminalmode$osgi$IServiceManager).to(class$de$audi$app$terminalmode$osgi$ServiceManagerImpl == null ? (class$de$audi$app$terminalmode$osgi$ServiceManagerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.osgi.ServiceManagerImpl")) : class$de$audi$app$terminalmode$osgi$ServiceManagerImpl).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$PhoneAppHandler == null ? (class$de$audi$app$terminalmode$PhoneAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.PhoneAppHandler")) : class$de$audi$app$terminalmode$PhoneAppHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$NaviAppHandler == null ? (class$de$audi$app$terminalmode$NaviAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.NaviAppHandler")) : class$de$audi$app$terminalmode$NaviAppHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler == null ? (class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMKeyEventsHandler")) : class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl == null ? (class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.keypanel.TMDSIKeyPanelControllerImpl")) : class$de$audi$app$terminalmode$dsi$keypanel$TMDSIKeyPanelControllerImpl).asSingleton();
                Class clazz = iTerminalModeConfiguration.isTouchScreenInputWidget() ? (class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener == null ? (class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMTouchscreenVBListener")) : class$de$audi$app$terminalmode$keyevents$TMTouchscreenVBListener) : (class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener == null ? (class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMVirtualButtonListener")) : class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener);
                binder.bind(class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener == null ? (class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMVirtualButtonListener")) : class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener).to(clazz).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider == null ? (class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider = TerminalModeApplication.class$("de.audi.app.terminalmode.bt.dsi.IBTDSIControllerListenerUpdateProvider")) : class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider).to(class$de$audi$app$terminalmode$bt$dsi$BTDSIController == null ? (class$de$audi$app$terminalmode$bt$dsi$BTDSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.bt.dsi.BTDSIController")) : class$de$audi$app$terminalmode$bt$dsi$BTDSIController).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager == null ? (class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.IDiagnosisManager")) : class$de$audi$app$terminalmode$diagnosis$IDiagnosisManager).to(class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl == null ? (class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisManagerImpl")) : class$de$audi$app$terminalmode$diagnosis$DiagnosisManagerImpl).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$events$IEventBus == null ? (class$de$audi$app$terminalmode$events$IEventBus = TerminalModeApplication.class$("de.audi.app.terminalmode.events.IEventBus")) : class$de$audi$app$terminalmode$events$IEventBus).to(class$de$audi$app$terminalmode$events$TerminalModeEventBus == null ? (class$de$audi$app$terminalmode$events$TerminalModeEventBus = TerminalModeApplication.class$("de.audi.app.terminalmode.events.TerminalModeEventBus")) : class$de$audi$app$terminalmode$events$TerminalModeEventBus).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$statemachine$IStateHandler == null ? (class$de$audi$app$terminalmode$statemachine$IStateHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.statemachine.IStateHandler")) : class$de$audi$app$terminalmode$statemachine$IStateHandler).to(class$de$audi$app$terminalmode$statemachine$StateHandlerImpl == null ? (class$de$audi$app$terminalmode$statemachine$StateHandlerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.statemachine.StateHandlerImpl")) : class$de$audi$app$terminalmode$statemachine$StateHandlerImpl).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher == null ? (class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher = TerminalModeApplication.class$("de.audi.app.terminalmode.actionproxy.IActionProxyDispatcher")) : class$de$audi$app$terminalmode$actionproxy$IActionProxyDispatcher).to(class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl == null ? (class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.actionproxy.ActionProxyDispatcherImpl")) : class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$FactoryResetMessageHandler == null ? (class$de$audi$app$terminalmode$FactoryResetMessageHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.FactoryResetMessageHandler")) : class$de$audi$app$terminalmode$FactoryResetMessageHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController == null ? (class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.ISmartphoneIntegrationDSIController")) : class$de$audi$app$terminalmode$dsi$smartphoneintegration$ISmartphoneIntegrationDSIController).toProvider(new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return ((SmartphoneIntegrationDSILifecycleController)iInjector.getInstance(class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController == null ? (class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.SmartphoneIntegrationDSILifecycleController")) : class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController)).getSMIDSIController();
                    }
                }).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$CommandListHelper == null ? (class$de$audi$app$terminalmode$CommandListHelper = TerminalModeApplication.class$("de.audi.app.terminalmode.CommandListHelper")) : class$de$audi$app$terminalmode$CommandListHelper).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController == null ? (class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.SmartphoneIntegrationDSILifecycleController")) : class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$INightDayModeHandler == null ? (class$de$audi$app$terminalmode$INightDayModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.INightDayModeHandler")) : class$de$audi$app$terminalmode$INightDayModeHandler).to(class$de$audi$app$terminalmode$NightDayModeHandler == null ? (class$de$audi$app$terminalmode$NightDayModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.NightDayModeHandler")) : class$de$audi$app$terminalmode$NightDayModeHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$device$IDeviceVariantsHandling == null ? (class$de$audi$app$terminalmode$device$IDeviceVariantsHandling = TerminalModeApplication.class$("de.audi.app.terminalmode.device.IDeviceVariantsHandling")) : class$de$audi$app$terminalmode$device$IDeviceVariantsHandling).to(class$de$audi$app$terminalmode$device$DeviceVariantsHandling == null ? (class$de$audi$app$terminalmode$device$DeviceVariantsHandling = TerminalModeApplication.class$("de.audi.app.terminalmode.device.DeviceVariantsHandling")) : class$de$audi$app$terminalmode$device$DeviceVariantsHandling).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory == null ? (class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.logging.TerminalModeLoggingDecoratorFactory")) : class$de$audi$app$terminalmode$logging$TerminalModeLoggingDecoratorFactory).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$audio$AudibleStateSyncer == null ? (class$de$audi$app$terminalmode$audio$AudibleStateSyncer = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.AudibleStateSyncer")) : class$de$audi$app$terminalmode$audio$AudibleStateSyncer).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$HardKeyListener == null ? (class$de$audi$app$terminalmode$HardKeyListener = TerminalModeApplication.class$("de.audi.app.terminalmode.HardKeyListener")) : class$de$audi$app$terminalmode$HardKeyListener).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$combi$TerminalModeBapCombi == null ? (class$de$audi$app$terminalmode$combi$TerminalModeBapCombi = TerminalModeApplication.class$("de.audi.app.terminalmode.combi.TerminalModeBapCombi")) : class$de$audi$app$terminalmode$combi$TerminalModeBapCombi).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker == null ? (class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisServiceTracker")) : class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider == null ? (class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisProvider")) : class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$ExternalEventsListener == null ? (class$de$audi$app$terminalmode$ExternalEventsListener = TerminalModeApplication.class$("de.audi.app.terminalmode.ExternalEventsListener")) : class$de$audi$app$terminalmode$ExternalEventsListener).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$SDSAppHandler == null ? (class$de$audi$app$terminalmode$SDSAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.SDSAppHandler")) : class$de$audi$app$terminalmode$SDSAppHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$TMInterAppHandler == null ? (class$de$audi$app$terminalmode$TMInterAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.TMInterAppHandler")) : class$de$audi$app$terminalmode$TMInterAppHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$AutomaticDeviceActivator == null ? (class$de$audi$app$terminalmode$AutomaticDeviceActivator = TerminalModeApplication.class$("de.audi.app.terminalmode.AutomaticDeviceActivator")) : class$de$audi$app$terminalmode$AutomaticDeviceActivator).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler == null ? (class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.NewDeviceHMIHandler")) : class$de$audi$app$terminalmode$hmi$NewDeviceHMIHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler == null ? (class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.CurrentPlayingTrackHandler")) : class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler).asSingleton();
                binder.forScope(ITerminalLogger.LogScope.HMI).bind(class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler == null ? (class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.SmartphoneRouteGuidanceHMIHandler")) : class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker == null ? (class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.HighPriorityResourceTracker")) : class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener == null ? (class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.MFLPhoneButtonsListener")) : class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$device$TMDeviceStorekeeper == null ? (class$de$audi$app$terminalmode$device$TMDeviceStorekeeper = TerminalModeApplication.class$("de.audi.app.terminalmode.device.TMDeviceStorekeeper")) : class$de$audi$app$terminalmode$device$TMDeviceStorekeeper).asSingleton();
                binder.bind(class$de$audi$app$terminalmode$interapp$BluetoothWaker == null ? (class$de$audi$app$terminalmode$interapp$BluetoothWaker = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.BluetoothWaker")) : class$de$audi$app$terminalmode$interapp$BluetoothWaker).asSingleton();
                binder.bind(class$de$audi$atip$utils$reactive$properties$PropertyFactory == null ? (class$de$audi$atip$utils$reactive$properties$PropertyFactory = TerminalModeApplication.class$("de.audi.atip.utils.reactive.properties.PropertyFactory")) : class$de$audi$atip$utils$reactive$properties$PropertyFactory).toInstance(LoggingPropertyFactory.create(terminalModeLogger.main(), 1000000));
                binder.bind(class$de$audi$atip$utils$reactive$bindings$IServiceBindings == null ? (class$de$audi$atip$utils$reactive$bindings$IServiceBindings = TerminalModeApplication.class$("de.audi.atip.utils.reactive.bindings.IServiceBindings")) : class$de$audi$atip$utils$reactive$bindings$IServiceBindings).toInstance(ServiceBindings.create(bundleContext));
                binder.bind(class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler == null ? (class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.OnlinePOICallHandler")) : class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler).asSingleton();
            }

            private void bindAndroidAuto2(Injector.Binder binder) {
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType == null ? (class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager$SmartphoneType")) : class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType).toInstance(SmartphoneManager.SmartphoneType.ANDROIDAUTO2);
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory == null ? (class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.IDSIAndroidAuto2TransferObjectFactory")) : class$de$audi$app$terminalmode$dsi$androidauto2$IDSIAndroidAuto2TransferObjectFactory).to(class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory == null ? (class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.DSIAndroidAuto2TransferObjectFactory")) : class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2TransferObjectFactory).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$org$dsi$ifc$androidauto2$DSIAndroidAuto2 == null ? (class$org$dsi$ifc$androidauto2$DSIAndroidAuto2 = TerminalModeApplication.class$("org.dsi.ifc.androidauto2.DSIAndroidAuto2")) : class$org$dsi$ifc$androidauto2$DSIAndroidAuto2).to(class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy == null ? (class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.DSIAndroidAuto2Proxy")) : class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2Proxy).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.IAndroidAuto2RequestHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$IAndroidAuto2RequestHandler).to(class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2RequestHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2RequestHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).to(class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2DSIManager")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2DSIManager).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManagerListener")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener).to(class$de$audi$app$terminalmode$SmartphoneManager == null ? (class$de$audi$app$terminalmode$SmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager")) : class$de$audi$app$terminalmode$SmartphoneManager).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2ListenerDistributor")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener == null ? (class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener = TerminalModeApplication.class$("org.dsi.ifc.androidauto2.DSIAndroidAuto2Listener")) : class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener).toProvider(new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        DSIAndroidAuto2Listener dSIAndroidAuto2Listener = (DSIAndroidAuto2Listener)iInjector.getInstance(object, class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2ListenerDistributor")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2ListenerDistributor);
                        DispatcherBase dispatcherBase = (DispatcherBase)iInjector.getInstance(class$de$esolutions$fw$util$commons$job$DispatcherBase == null ? (class$de$esolutions$fw$util$commons$job$DispatcherBase = TerminalModeApplication.class$("de.esolutions.fw.util.commons.job.DispatcherBase")) : class$de$esolutions$fw$util$commons$job$DispatcherBase);
                        return DispatcherProxy.create(class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener == null ? (class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener = TerminalModeApplication.class$("org.dsi.ifc.androidauto2.DSIAndroidAuto2Listener")) : class$org$dsi$ifc$androidauto2$DSIAndroidAuto2Listener, dSIAndroidAuto2Listener, dispatcherBase);
                    }
                }).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController == null ? (class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.androidauto2.DSIAndroidAuto2DSIController")) : class$de$audi$app$terminalmode$dsi$androidauto2$DSIAndroidAuto2DSIController).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2Subsystem")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem).asSingleton();
                Injector.IProvider iProvider = new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return iInjector.getInstance(SmartphoneManager.SmartphoneType.ANDROIDAUTO2, class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2Subsystem")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem);
                    }
                };
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$ITMDeviceSubsystem == null ? (class$de$audi$app$terminalmode$ITMDeviceSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.ITMDeviceSubsystem")) : class$de$audi$app$terminalmode$ITMDeviceSubsystem).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener == null ? (class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.IDSIControllerStateListener")) : class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController == null ? (class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.ITerminalModeDSIKeyEventsController")) : class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController).to(class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2KeyEventsController")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2KeyEventsController).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2EventListener")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2EventListener).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.mic.IAndroidAuto2MicHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$mic$IAndroidAuto2MicHandler).to(class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.mic.AndroidAuto2MicHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$mic$AndroidAuto2MicHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.nav.IAndroidAuto2NavHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$nav$IAndroidAuto2NavHandler).to(class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.nav.AndroidAuto2NavHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$nav$AndroidAuto2NavHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.audio.IAndroidAuto2AudioHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$audio$IAndroidAuto2AudioHandler).to(class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.audio.AndroidAuto2AudioHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$audio$AndroidAuto2AudioHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.video.IAndroidAuto2VideoHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$video$IAndroidAuto2VideoHandler).to(class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.video.AndroidAuto2VideoHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$video$AndroidAuto2VideoHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.ANDROIDAUTO2).bind(class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.voice.AndroidAuto2VoiceSessionHandler")) : class$de$audi$app$terminalmode$smartphone$androidauto2$voice$AndroidAuto2VoiceSessionHandler).asSingleton();
            }

            private void bindCarplay(Injector.Binder binder) {
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType == null ? (class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager$SmartphoneType")) : class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType).toInstance(SmartphoneManager.SmartphoneType.CARPLAY);
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController == null ? (class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.CarplayDSILifecycleController")) : class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory == null ? (class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.IDSICarplayTransferObjectFactory")) : class$de$audi$app$terminalmode$dsi$carplay$IDSICarplayTransferObjectFactory).to(class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory == null ? (class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.DSICarplayTransferObjectFactory")) : class$de$audi$app$terminalmode$dsi$carplay$DSICarplayTransferObjectFactory).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties == null ? (class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarplaySmartphoneProperties")) : class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager == null ? (class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarPlayDSIManager")) : class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager).asSingleton();
                Injector.IProvider iProvider = new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return iInjector.getInstance(SmartphoneManager.SmartphoneType.CARPLAY, class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager == null ? (class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarPlayDSIManager")) : class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager);
                    }
                };
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener == null ? (class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.ICarplayDSIControllerListener")) : class$de$audi$app$terminalmode$dsi$carplay$ICarplayDSIControllerListener).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$ITMDeviceSubsystem == null ? (class$de$audi$app$terminalmode$ITMDeviceSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.ITMDeviceSubsystem")) : class$de$audi$app$terminalmode$ITMDeviceSubsystem).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManagerListener")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener).to(class$de$audi$app$terminalmode$SmartphoneManager == null ? (class$de$audi$app$terminalmode$SmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager")) : class$de$audi$app$terminalmode$SmartphoneManager).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe == null ? (class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.DSICarplaySafe")) : class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafe).to(class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy == null ? (class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.DSICarplaySafeProxy")) : class$de$audi$app$terminalmode$dsi$carplay$DSICarplaySafeProxy).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARPLAY).bind(class$org$dsi$ifc$carplay$DSICarplayListener == null ? (class$org$dsi$ifc$carplay$DSICarplayListener = TerminalModeApplication.class$("org.dsi.ifc.carplay.DSICarplayListener")) : class$org$dsi$ifc$carplay$DSICarplayListener).to(class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl == null ? (class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carplay.CarplayDSILifecycleController$DSICarplayListenerImpl")) : class$de$audi$app$terminalmode$dsi$carplay$CarplayDSILifecycleController$DSICarplayListenerImpl).asSingleton();
            }

            private void bindCarlife(Injector.Binder binder) {
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType == null ? (class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager$SmartphoneType")) : class$de$audi$app$terminalmode$SmartphoneManager$SmartphoneType).toInstance(SmartphoneManager.SmartphoneType.CARLIFE);
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$org$dsi$ifc$carlife$DSICarlife == null ? (class$org$dsi$ifc$carlife$DSICarlife = TerminalModeApplication.class$("org.dsi.ifc.carlife.DSICarlife")) : class$org$dsi$ifc$carlife$DSICarlife).to(class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy == null ? (class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carlife.DSICarlifeProxy")) : class$de$audi$app$terminalmode$dsi$carlife$DSICarlifeProxy).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager).to(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIManager")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIManager).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManagerListener")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManagerListener).to(class$de$audi$app$terminalmode$SmartphoneManager == null ? (class$de$audi$app$terminalmode$SmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.SmartphoneManager")) : class$de$audi$app$terminalmode$SmartphoneManager).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeListenerDistributor")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$org$dsi$ifc$carlife$DSICarlifeListener == null ? (class$org$dsi$ifc$carlife$DSICarlifeListener = TerminalModeApplication.class$("org.dsi.ifc.carlife.DSICarlifeListener")) : class$org$dsi$ifc$carlife$DSICarlifeListener).toProvider(new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        DSICarlifeListener dSICarlifeListener = (DSICarlifeListener)iInjector.getInstance(object, class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeListenerDistributor")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeListenerDistributor);
                        DispatcherBase dispatcherBase = (DispatcherBase)iInjector.getInstance(class$de$esolutions$fw$util$commons$job$DispatcherBase == null ? (class$de$esolutions$fw$util$commons$job$DispatcherBase = TerminalModeApplication.class$("de.esolutions.fw.util.commons.job.DispatcherBase")) : class$de$esolutions$fw$util$commons$job$DispatcherBase);
                        return DispatcherProxy.create(class$org$dsi$ifc$carlife$DSICarlifeListener == null ? (class$org$dsi$ifc$carlife$DSICarlifeListener = TerminalModeApplication.class$("org.dsi.ifc.carlife.DSICarlifeListener")) : class$org$dsi$ifc$carlife$DSICarlifeListener, dSICarlifeListener, dispatcherBase);
                    }
                }).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController == null ? (class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.carlife.CarlifeDSIController")) : class$de$audi$app$terminalmode$dsi$carlife$CarlifeDSIController).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeSubsystem")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem).asSingleton();
                Injector.IProvider iProvider = new Injector.IProvider(){

                    public Object provide(IInjector iInjector, Object object) {
                        return iInjector.getInstance(SmartphoneManager.SmartphoneType.CARLIFE, class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeSubsystem")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem);
                    }
                };
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$ITMDeviceSubsystem == null ? (class$de$audi$app$terminalmode$ITMDeviceSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.ITMDeviceSubsystem")) : class$de$audi$app$terminalmode$ITMDeviceSubsystem).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener == null ? (class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.IDSIControllerStateListener")) : class$de$audi$app$terminalmode$dsi$IDSIControllerStateListener).toProvider(iProvider).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController == null ? (class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.ITerminalModeDSIKeyEventsController")) : class$de$audi$app$terminalmode$keyevents$ITerminalModeDSIKeyEventsController).to(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeKeyEventsController")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeKeyEventsController).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeEventListener")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeEventListener).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper == null ? (class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.DSIMHIConstantsMapper")) : class$de$audi$app$terminalmode$smartphone$carlife$DSIMHIConstantsMapper).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIRequestModeHandler")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeHMISetModeHandler")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeHMISetModeHandler).asSingleton();
                binder.forScope(SmartphoneManager.SmartphoneType.CARLIFE).bind(class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIAppNotInstalledManager")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager).asSingleton();
            }
        }, iFrameworkAccess.isSimulator());
        this.contextBuilder = (TerminalModeContext)this.injector.getInstance(class$de$audi$app$terminalmode$IContext == null ? (class$de$audi$app$terminalmode$IContext = TerminalModeApplication.class$("de.audi.app.terminalmode.IContext")) : class$de$audi$app$terminalmode$IContext);
        this.context = this.contextBuilder;
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager == null ? (class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.IDSISmartphoneManager")) : class$de$audi$app$terminalmode$smartphone$IDSISmartphoneManager));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$audio$AudioManager == null ? (class$de$audi$app$terminalmode$audio$AudioManager = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.AudioManager")) : class$de$audi$app$terminalmode$audio$AudioManager));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$device$DeviceManager == null ? (class$de$audi$app$terminalmode$device$DeviceManager = TerminalModeApplication.class$("de.audi.app.terminalmode.device.DeviceManager")) : class$de$audi$app$terminalmode$device$DeviceManager));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController == null ? (class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController = TerminalModeApplication.class$("de.audi.app.terminalmode.dsi.smartphoneintegration.SmartphoneIntegrationDSILifecycleController")) : class$de$audi$app$terminalmode$dsi$smartphoneintegration$SmartphoneIntegrationDSILifecycleController));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl == null ? (class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.actionproxy.ActionProxyDispatcherImpl")) : class$de$audi$app$terminalmode$actionproxy$ActionProxyDispatcherImpl));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$statemachine$StateHandlerImpl == null ? (class$de$audi$app$terminalmode$statemachine$StateHandlerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.statemachine.StateHandlerImpl")) : class$de$audi$app$terminalmode$statemachine$StateHandlerImpl));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$PhoneAppHandler == null ? (class$de$audi$app$terminalmode$PhoneAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.PhoneAppHandler")) : class$de$audi$app$terminalmode$PhoneAppHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$NaviAppHandler == null ? (class$de$audi$app$terminalmode$NaviAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.NaviAppHandler")) : class$de$audi$app$terminalmode$NaviAppHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$INightDayModeHandler == null ? (class$de$audi$app$terminalmode$INightDayModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.INightDayModeHandler")) : class$de$audi$app$terminalmode$INightDayModeHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$device$IDeviceVariantsHandling == null ? (class$de$audi$app$terminalmode$device$IDeviceVariantsHandling = TerminalModeApplication.class$("de.audi.app.terminalmode.device.IDeviceVariantsHandling")) : class$de$audi$app$terminalmode$device$IDeviceVariantsHandling));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler == null ? (class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMKeyEventsHandler")) : class$de$audi$app$terminalmode$keyevents$TMKeyEventsHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener == null ? (class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener = TerminalModeApplication.class$("de.audi.app.terminalmode.keyevents.TMVirtualButtonListener")) : class$de$audi$app$terminalmode$keyevents$TMVirtualButtonListener));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(SmartphoneManager.SmartphoneType.CARPLAY, class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager == null ? (class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarPlayDSIManager")) : class$de$audi$app$terminalmode$smartphone$carplay$CarPlayDSIManager));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(SmartphoneManager.SmartphoneType.CARPLAY, class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties == null ? (class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carplay.CarplaySmartphoneProperties")) : class$de$audi$app$terminalmode$smartphone$carplay$CarplaySmartphoneProperties));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(SmartphoneManager.SmartphoneType.ANDROIDAUTO2, class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem == null ? (class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.androidauto2.AndroidAuto2Subsystem")) : class$de$audi$app$terminalmode$smartphone$androidauto2$AndroidAuto2Subsystem));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(SmartphoneManager.SmartphoneType.CARLIFE, class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeSubsystem")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeSubsystem));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(SmartphoneManager.SmartphoneType.CARLIFE, class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIRequestModeHandler")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIRequestModeHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(SmartphoneManager.SmartphoneType.CARLIFE, class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager == null ? (class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.carlife.CarlifeDSIAppNotInstalledManager")) : class$de$audi$app$terminalmode$smartphone$carlife$CarlifeDSIAppNotInstalledManager));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$audio$AudibleStateSyncer == null ? (class$de$audi$app$terminalmode$audio$AudibleStateSyncer = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.AudibleStateSyncer")) : class$de$audi$app$terminalmode$audio$AudibleStateSyncer));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$HardKeyListener == null ? (class$de$audi$app$terminalmode$HardKeyListener = TerminalModeApplication.class$("de.audi.app.terminalmode.HardKeyListener")) : class$de$audi$app$terminalmode$HardKeyListener));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$combi$TerminalModeBapCombi == null ? (class$de$audi$app$terminalmode$combi$TerminalModeBapCombi = TerminalModeApplication.class$("de.audi.app.terminalmode.combi.TerminalModeBapCombi")) : class$de$audi$app$terminalmode$combi$TerminalModeBapCombi));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker == null ? (class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisServiceTracker")) : class$de$audi$app$terminalmode$diagnosis$DiagnosisServiceTracker));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider == null ? (class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider = TerminalModeApplication.class$("de.audi.app.terminalmode.diagnosis.DiagnosisProvider")) : class$de$audi$app$terminalmode$diagnosis$DiagnosisProvider));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$ExternalEventsListener == null ? (class$de$audi$app$terminalmode$ExternalEventsListener = TerminalModeApplication.class$("de.audi.app.terminalmode.ExternalEventsListener")) : class$de$audi$app$terminalmode$ExternalEventsListener));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$SDSAppHandler == null ? (class$de$audi$app$terminalmode$SDSAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.SDSAppHandler")) : class$de$audi$app$terminalmode$SDSAppHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$TMInterAppHandler == null ? (class$de$audi$app$terminalmode$TMInterAppHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.TMInterAppHandler")) : class$de$audi$app$terminalmode$TMInterAppHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$AutomaticDeviceActivator == null ? (class$de$audi$app$terminalmode$AutomaticDeviceActivator = TerminalModeApplication.class$("de.audi.app.terminalmode.AutomaticDeviceActivator")) : class$de$audi$app$terminalmode$AutomaticDeviceActivator));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler == null ? (class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.CurrentPlayingTrackHandler")) : class$de$audi$app$terminalmode$hmi$CurrentPlayingTrackHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(ITerminalLogger.LogScope.HMI, class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler == null ? (class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.hmi.SmartphoneRouteGuidanceHMIHandler")) : class$de$audi$app$terminalmode$hmi$SmartphoneRouteGuidanceHMIHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider == null ? (class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider = TerminalModeApplication.class$("de.audi.app.terminalmode.bt.dsi.IBTDSIControllerListenerUpdateProvider")) : class$de$audi$app$terminalmode$bt$dsi$IBTDSIControllerListenerUpdateProvider));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$FactoryResetMessageHandler == null ? (class$de$audi$app$terminalmode$FactoryResetMessageHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.FactoryResetMessageHandler")) : class$de$audi$app$terminalmode$FactoryResetMessageHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker == null ? (class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.HighPriorityResourceTracker")) : class$de$audi$app$terminalmode$interapp$HighPriorityResourceTracker));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener == null ? (class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener = TerminalModeApplication.class$("de.audi.app.terminalmode.smartphone.MFLPhoneButtonsListener")) : class$de$audi$app$terminalmode$smartphone$MFLPhoneButtonsListener));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$interapp$BluetoothWaker == null ? (class$de$audi$app$terminalmode$interapp$BluetoothWaker = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.BluetoothWaker")) : class$de$audi$app$terminalmode$interapp$BluetoothWaker));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$device$TMDeviceStorekeeper == null ? (class$de$audi$app$terminalmode$device$TMDeviceStorekeeper = TerminalModeApplication.class$("de.audi.app.terminalmode.device.TMDeviceStorekeeper")) : class$de$audi$app$terminalmode$device$TMDeviceStorekeeper));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler == null ? (class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler = TerminalModeApplication.class$("de.audi.app.terminalmode.interapp.OnlinePOICallHandler")) : class$de$audi$app$terminalmode$interapp$OnlinePOICallHandler));
        this.terminalModeComponents.add((ITerminalModeComponent)this.injector.getInstance(class$de$audi$app$terminalmode$audio$SpeechReset == null ? (class$de$audi$app$terminalmode$audio$SpeechReset = TerminalModeApplication.class$("de.audi.app.terminalmode.audio.SpeechReset")) : class$de$audi$app$terminalmode$audio$SpeechReset));
        this.terminalModeComponents.add(iTerminalModeApplicationFactory.createActionProxy(this.context));
        this.terminalModeComponents.add(iTerminalModeApplicationFactory.createHmiApplication(this.context));
        this.terminalModeComponents.addAll(iTerminalModeApplicationFactory.getVariantComponents(this.context));
    }

    public void init() {
        if (!this.context.getConfiguration().isTerminalMode()) {
            this.context.getLogger().main().log(1000000, "[%1.init] TerminalMode is not coded. Return.", (Object)LOGCLASS);
            return;
        }
        this.context.getDispatcher().start();
        this.context.getCommandListManager().start();
        GIterator<ITerminalModeComponent> gIterator = this.terminalModeComponents.iterator();
        while (gIterator.hasNext()) {
            gIterator.next().init();
        }
        this.context.getChoiceModel(4044).setValue(this.context.getConfiguration().isTerminalMode() ? 1 : 0);
        this.context.getEventBus().startupFinished();
    }

    public void deinit() {
        GIterator<ITerminalModeComponent> gIterator = this.terminalModeComponents.iterator();
        while (gIterator.hasNext()) {
            gIterator.next().deinit();
        }
        this.context.getDispatcher().stop();
        this.context.getCommandListManager().destroy();
        ((ServiceManagerImpl)this.injector.getInstance(class$de$audi$app$terminalmode$osgi$ServiceManagerImpl == null ? (class$de$audi$app$terminalmode$osgi$ServiceManagerImpl = TerminalModeApplication.class$("de.audi.app.terminalmode.osgi.ServiceManagerImpl")) : class$de$audi$app$terminalmode$osgi$ServiceManagerImpl)).cleanup();
        ((LoggingPropertyFactory)this.injector.getInstance(class$de$audi$atip$utils$reactive$properties$PropertyFactory == null ? (class$de$audi$atip$utils$reactive$properties$PropertyFactory = TerminalModeApplication.class$("de.audi.atip.utils.reactive.properties.PropertyFactory")) : class$de$audi$atip$utils$reactive$properties$PropertyFactory)).dispose();
        ((ServiceBindings)this.injector.getInstance(class$de$audi$atip$utils$reactive$bindings$IServiceBindings == null ? (class$de$audi$atip$utils$reactive$bindings$IServiceBindings = TerminalModeApplication.class$("de.audi.atip.utils.reactive.bindings.IServiceBindings")) : class$de$audi$atip$utils$reactive$bindings$IServiceBindings)).dispose();
    }

    public TerminalModeContext getContextBuilder() {
        return this.contextBuilder;
    }

    static /* synthetic */ Class class$(String string) {
        try {
            return Class.forName(string);
        }
        catch (ClassNotFoundException classNotFoundException) {
            throw new NoClassDefFoundError().initCause(classNotFoundException);
        }
    }
}

