/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.startup;

public class Consts {
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSROOT = 1;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSTUNER = 2;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMEDIA = 3;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSADDRESSBOOK = 4;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSPHONE = 5;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSNAV = 6;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSINFO = 7;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSCAR = 8;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSAUDIO = 9;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSDS = 10;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSWDL = 11;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEARLYAPPS = 12;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSPOSTSTARTUP = 13;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSCOMMUNICATION = 14;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSIPSERVICES = 15;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSGEMMI = 16;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSBAPKOMBI = 17;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSBLUETOOTH = 18;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSBROWSER = 19;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEXPLORER = 20;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSCALENDAR = 21;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSPICTURESTORE = 22;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSTREETVIEW = 23;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMOBILITYHORIZON = 24;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEXBOXM = 25;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMIRRORLINK = 26;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSFA = 27;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSEARCH = 28;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSDIAGNOSIS = 29;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSASIALANGUAGESUPPORT = 30;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSEXLAP = 31;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSTVTUNER = 32;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMEDIAONLINE = 33;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSMEDIAROUTER = 34;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSRADIODATASERVER = 35;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSSMARTPHONEINTEGRATION = 36;
    public static final int ATTRIBUTE_ID_DSISTARTUP_DOMAINSTATUSWIRELESSCHARGER = 37;
}

