/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.speechrec;

public class Consts {
    public static final int ATTRIBUTE_ID_DSISPEECHREC_LANGUAGE = 1;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_AVAILABLELANGUAGES = 2;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ABORTED = 3;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_FAILURE = 4;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_RECOGNIZERSTATE = 5;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ABSOLUTECONFIDENCETHRESHOLD = 6;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_MAXCOMMANDNBESTLISTSIZE = 8;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_MAXSLOTNBESTLISTSIZE = 9;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_CONFIDENCEREJECTTHRESHOLD = 10;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_UTTERANCESTARTTIMEOUT = 11;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_RECOGNITIONTIMEOUT = 12;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_UNAMBIGUOUSRESULTTHRESHOLD = 13;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_UNAMBIGUOUSRESULTRANGE = 14;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_FIRSTLEVELSIZE = 15;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_SDSAVAILABILITY = 16;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_TEMPORARYG2PLANGUAGECHANGEACTIVE = 18;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_AVAILABLEPROFILES = 19;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_GRAMMARSTATUS = 20;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_GRAMMARSTATE = 21;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_NBESTLIST = 22;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ASRPARAMETERCONFIGURATION = 23;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_VDEMEDIUMSTATE = 24;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_AVAILABLESLMLANGUAGES = 25;
    public static final int ATTRIBUTE_ID_DSISPEECHREC_ONLINECAPABILITIES = 26;
}

