/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carlight;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTVIEWOPTIONS = 1;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTCOLOUR = 7;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTSTATE = 8;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTENVIRONMENT = 9;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTSPEED = 10;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTTEMPERATURE = 11;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTBRIGHTNESS = 27;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET1 = 29;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET2 = 30;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET3 = 31;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET4 = 32;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET5 = 33;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET6 = 34;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET7 = 35;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONSET8 = 36;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE1 = 37;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE2 = 38;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE3 = 39;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE4 = 40;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE5 = 41;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE6 = 42;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE7 = 43;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTILLUMINATIONPROFILE8 = 44;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTACTIVEPROFILE = 45;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTAMBIENTLIGHTCOLOR = 46;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTCONTOURLIGHTCOLOR = 47;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTFOLLOWUPTIME = 48;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTRGBCOLORLISTUPDATEINFO = 49;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTRGBCOLORLISTTOTALNUMBEROFELEMENTS = 50;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_INTLIGHTDOORCONTACT = 52;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTVIEWOPTIONS = 12;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTCOMINGHOME = 13;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLEAVINGHOME = 14;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTSWITCHONSENSITIVITY = 15;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTDAYLIGHT = 16;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTTOURIST = 17;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTADAPTIVE = 18;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTHEADLIGHTSYSTEM = 19;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTGLIDINGSYSTEM = 20;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTMOTORWAYBLINKING = 21;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTMASKEDHIGHBEAM = 22;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLAMPERRORDETECTION = 23;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLAMPERRORDETECTIONTRAILER = 24;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTSENSORERRORDETECTION = 25;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTLASERLIGHT = 51;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTAUTOMATICLIGHT = 28;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTSIGNATURELIGHT = 53;
    public static final int ATTRIBUTE_ID_DSICARLIGHT_EXTLIGHTHEADLIGHTRANGE = 54;
}

