/*
 * Decompiled with CFR 0.152.
 */
package de.audi.app.sds.evo.testsupport;

import de.audi.app.sdsmanager.testsupport.SLMRulesMap;
import java.util.HashMap;
import java.util.Map;

public class SLMRulesMapEvo
extends SLMRulesMap {
    protected Map createFilledMap() {
        HashMap hashMap = new HashMap();
        hashMap.put(new Integer(283), new String[]{"system_help"});
        hashMap.put(new Integer(800243), new String[]{"navigation_POI_call"});
        hashMap.put(new Integer(281), new String[]{"system_help_car"});
        hashMap.put(new Integer(287), new String[]{"system_help_media"});
        hashMap.put(new Integer(285), new String[]{"system_help_tone"});
        hashMap.put(new Integer(258), new String[]{"phone_redial"});
        hashMap.put(new Integer(259), new String[]{"phone_call_mailbox"});
        hashMap.put(new Integer(257), new String[]{"phone_call_lists"});
        hashMap.put(new Integer(262), new String[]{"system_addressbook"});
        hashMap.put(new Integer(260), new String[]{"phone_start_number_dialog"});
        hashMap.put(new Integer(300095), new String[]{"phone_favorites"});
        hashMap.put(new Integer(200149), new String[]{"media_select_multi_slot.TITLE_NM", "media_select_multi_slot.ALBUM_NM"});
        hashMap.put(new Integer(400332), new String[]{"navigation_no_uturn"});
        hashMap.put(new Integer(2200090), new String[]{"online_adb_dictate_mail"});
        hashMap.put(new Integer(200151), new String[]{"media_select_multi_slot.TITLE_NM", "media_select_multi_slot.ARTIST_NM"});
        hashMap.put(new Integer(200164), new String[]{"media_select_multi_slot.ARTIST_NM", "media_select_multi_slot.ALBUM_NM", "media_select_multi_slot.TITLE_NM"});
        hashMap.put(new Integer(2200088), new String[]{"online_adb_dictate.PHONETYPE_NM"});
        hashMap.put(new Integer(2300041), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(2200095), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(400328), new String[]{"navigation_voice_guidance_short"});
        hashMap.put(new Integer(400330), new String[]{"navigation_voice_guidance_traffic"});
        hashMap.put(new Integer(2200092), new String[]{"online_adb_dictate_sms.PHONETYPE_NM"});
        hashMap.put(new Integer(200157), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(400324), new String[]{"navigation_voice_guidance_complete"});
        hashMap.put(new Integer(200156), new String[]{"media_select_device_sd.SDCARD_NR"});
        hashMap.put(new Integer(0x219212), new String[]{"online_read_new_message"});
        hashMap.put(new Integer(400326), new String[]{"navigation_voice_guidance_off"});
        hashMap.put(new Integer(2200080), new String[]{"online_read_message"});
        hashMap.put(new Integer(317), new String[]{"system_menue"});
        hashMap.put(new Integer(400320), new String[]{"navigation_map_destination"});
        hashMap.put(new Integer(2200086), new String[]{"online_reply_message"});
        hashMap.put(new Integer(200155), new String[]{"media_select_device_cd.DISC_NR"});
        hashMap.put(new Integer(319), new String[]{"system_tone"});
        hashMap.put(new Integer(400322), new String[]{"navigation_map_overview"});
        hashMap.put(new Integer(2200084), new String[]{"online_forward_message"});
        hashMap.put(new Integer(318), new String[]{"system_map"});
        hashMap.put(new Integer(200132), new String[]{"media_select_folder_audiobook"});
        hashMap.put(new Integer(2200074), new String[]{"online_dictate_sms"});
        hashMap.put(new Integer(289), new String[]{"system_help_office"});
        hashMap.put(new Integer(2200072), new String[]{"online_dictate_sms_contact.CONTACT_NM", "online_dictate_sms_contact.PHONETYPE_NM"});
        hashMap.put(new Integer(291), new String[]{"system_help_map"});
        hashMap.put(new Integer(200128), new String[]{"media_browse_playmore"});
        hashMap.put(new Integer(2200078), new String[]{"online_read_new_sms"});
        hashMap.put(new Integer(292), new String[]{"system_help_navigation"});
        hashMap.put(new Integer(200129), new String[]{"media_select_folder_title"});
        hashMap.put(new Integer(200130), new String[]{"media_select_folder_podcast"});
        hashMap.put(new Integer(2200076), new String[]{"online_read_sms"});
        hashMap.put(new Integer(200131), new String[]{"media_select_folder_genre"});
        hashMap.put(new Integer(295), new String[]{"system_help_online"});
        hashMap.put(new Integer(2200066), new String[]{"online_dictate_mail"});
        hashMap.put(new Integer(400341), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(297), new String[]{"system_help_phone"});
        hashMap.put(new Integer(2200064), new String[]{"online_dictate_mail_contact.CONTACT_NM"});
        hashMap.put(new Integer(299), new String[]{"system_help_tuner"});
        hashMap.put(new Integer(2200070), new String[]{"online_dictate_message"});
        hashMap.put(new Integer(400337), new String[]{"navigation_destination_poi_vicinity.POI_CATEGORY"});
        hashMap.put(new Integer(301), new String[]{"system_help_SDS_adjustments"});
        hashMap.put(new Integer(2200068), new String[]{"online_dictate_message_contact.CONTACT_NM", "online_dictate_message_contact.PHONETYPE_NM"});
        hashMap.put(new Integer(400339), new String[]{"navigation_destination_poi_along_route.POI_CATEGORY"});
        hashMap.put(new Integer(400338), new String[]{"navigation_destination_poi_destination.POI_CATEGORY"});
        hashMap.put(new Integer(400298), new String[]{"navigation_myaudi_destinations"});
        hashMap.put(new Integer(100132), new String[]{"tuner_frequency_AM_KOR.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(400296), new String[]{"navigation_last_destinations"});
        hashMap.put(new Integer(100134), new String[]{"tuner_frequency_FM_KOR.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(200119), new String[]{"media_select_folder_playlist"});
        hashMap.put(new Integer(400302), new String[]{"navigation_traffic_use_bypass"});
        hashMap.put(new Integer(200118), new String[]{"media_select_folder_movie"});
        hashMap.put(new Integer(100128), new String[]{"tuner_frequency_FM_JP.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(400303), new String[]{"navigation_map_autocolor"});
        hashMap.put(new Integer(400300), new String[]{"navigation_range_info"});
        hashMap.put(new Integer(100130), new String[]{"tuner_frequency_AM_JP.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(200123), new String[]{"media_select_folder_composer"});
        hashMap.put(new Integer(100141), new String[]{"tuner_station_list_historylist"});
        hashMap.put(new Integer(400290), new String[]{"navigation_calc_alternate_routes"});
        hashMap.put(new Integer(200122), new String[]{"media_select_folder_artist"});
        hashMap.put(new Integer(200121), new String[]{"media_select_folder_album"});
        hashMap.put(new Integer(400288), new String[]{"navigation_block_route_distance.DISTANCE", "navigation_block_route_distance.UNIT"});
        hashMap.put(new Integer(200120), new String[]{"media_select_folder_favorite"});
        hashMap.put(new Integer(100142), new String[]{"tuner_waveband_SDARS"});
        hashMap.put(new Integer(200127), new String[]{"media_select_single_slot_artist.ARTIST_NM"});
        hashMap.put(new Integer(400294), new String[]{"navigation_favorites"});
        hashMap.put(new Integer(200126), new String[]{"media_select_single_slot_title.TITLE_NM"});
        hashMap.put(new Integer(100136), new String[]{"tuner_frequency_AM_AUS.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(200125), new String[]{"media_select_multi_slot.ARTIST_NM", "media_select_multi_slot.ALBUM_NM"});
        hashMap.put(new Integer(400292), new String[]{"navigation_destination_info"});
        hashMap.put(new Integer(200124), new String[]{"media_select_single_slot_album.ALBUM_NM"});
        hashMap.put(new Integer(100138), new String[]{"tuner_frequency_FM_AUS.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(200098), new String[]{"media_select_device_wlan"});
        hashMap.put(new Integer(200099), new String[]{"media_select_device_ami"});
        hashMap.put(new Integer(327), new String[]{"system_tuner"});
        hashMap.put(new Integer(400314), new String[]{"navigation_map_2D"});
        hashMap.put(new Integer(324), new String[]{"system_pause"});
        hashMap.put(new Integer(200097), new String[]{"media_select_device_jukebox"});
        hashMap.put(new Integer(325), new String[]{"system_next_page"});
        hashMap.put(new Integer(400312), new String[]{"navigation_map_traffic"});
        hashMap.put(new Integer(200102), new String[]{"media_select_device_sd.SDCARD_NR"});
        hashMap.put(new Integer(322), new String[]{"system_cancel"});
        hashMap.put(new Integer(200103), new String[]{"media_select_device_usb.USB_NR"});
        hashMap.put(new Integer(100145), new String[]{"tuner_select_station.CHANNEL_NM"});
        hashMap.put(new Integer(323), new String[]{"system_car"});
        hashMap.put(new Integer(400318), new String[]{"navigation_map_3D"});
        hashMap.put(new Integer(200100), new String[]{"media_select_device_cd_changer"});
        hashMap.put(new Integer(320), new String[]{"system_previous_page"});
        hashMap.put(new Integer(200101), new String[]{"media_select_device_online.ONLINE_MEDIUM_NM"});
        hashMap.put(new Integer(321), new String[]{"system_bordcomputer"});
        hashMap.put(new Integer(400316), new String[]{"navigation_map_2D_north"});
        hashMap.put(new Integer(200106), new String[]{"media_select_device_by_name.DEVICE_NM"});
        hashMap.put(new Integer(200107), new String[]{"media_select_device_ipod"});
        hashMap.put(new Integer(200104), new String[]{"media_select_device_bluetooth"});
        hashMap.put(new Integer(332), new String[]{"system_correction"});
        hashMap.put(new Integer(400305), new String[]{"navigation_map_range"});
        hashMap.put(new Integer(400304), new String[]{"navigation_map_day"});
        hashMap.put(new Integer(330), new String[]{"system_favorites"});
        hashMap.put(new Integer(331), new String[]{"system_office"});
        hashMap.put(new Integer(400310), new String[]{"navigation_map_google"});
        hashMap.put(new Integer(328), new String[]{"system_media"});
        hashMap.put(new Integer(329), new String[]{"system_online"});
        hashMap.put(new Integer(400308), new String[]{"navigation_map_night"});
        hashMap.put(new Integer(300097), new String[]{"navigation_adb_navigate.ADDRESSTYPE_NM"});
        hashMap.put(new Integer(300096), new String[]{"phone_dial_type.PHONETYPE_NM"});
        hashMap.put(new Integer(100102), new String[]{"tuner_frequency_FM_NAR.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(400265), new String[]{"navigation_destination_adb_contact.CONTACT_NM", "navigation_destination_adb_contact.ADDRESSTYPE_NM"});
        hashMap.put(new Integer(100101), new String[]{"tuner_frequency_AM_NAR.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(100099), new String[]{"tuner_DAB_station_ensemble.ENSEMBLE_NM"});
        hashMap.put(new Integer(400268), new String[]{"navigation_cancel_routeguidance"});
        hashMap.put(new Integer(400270), new String[]{"navigation_destination_entry"});
        hashMap.put(new Integer(100097), new String[]{"tuner_select_station.STATION_NM"});
        hashMap.put(new Integer(300102), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(100111), new String[]{"tuner_waveband_DAB"});
        hashMap.put(new Integer(300106), new String[]{"phone_ADB_Call_Contact_Plain.CONTACT_NM"});
        hashMap.put(new Integer(100108), new String[]{"tuner_waveband_commonlist"});
        hashMap.put(new Integer(100107), new String[]{"tuner_waveband_AM"});
        hashMap.put(new Integer(400263), new String[]{"navigation_destination_address"});
        hashMap.put(new Integer(100104), new String[]{"tuner_online_station.ONLINE_STATION_NM"});
        hashMap.put(new Integer(400280), new String[]{"online_search"});
        hashMap.put(new Integer(400282), new String[]{"online_search_slot"});
        hashMap.put(new Integer(100117), new String[]{"tuner_station_list_presetlist"});
        hashMap.put(new Integer(400284), new String[]{"navigation_home_address"});
        hashMap.put(new Integer(100115), new String[]{"tuner_waveband_onlineradio"});
        hashMap.put(new Integer(100112), new String[]{"tuner_waveband_FM"});
        hashMap.put(new Integer(400286), new String[]{"navigation_traffic_situation"});
        hashMap.put(new Integer(400272), new String[]{"navigation_poi_next_restaurant"});
        hashMap.put(new Integer(100124), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(366), new String[]{"media_play_music"});
        hashMap.put(new Integer(400274), new String[]{"navigation_poi_next_resting_place"});
        hashMap.put(new Integer(100125), new String[]{"tuner_frequency_AM_EU_ROW.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(400276), new String[]{"navigation_poi_next_restroom"});
        hashMap.put(new Integer(100123), new String[]{"tuner_traffic_on"});
        hashMap.put(new Integer(400278), new String[]{"navigation_poi_filling_station"});
        hashMap.put(new Integer(100121), new String[]{"tuner_traffic_off"});
        hashMap.put(new Integer(100087), new String[]{"tuner_frequency_FM_EU_ROW.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(700045), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(400388), new String[]{"navigation_destination_poi_address_oneshot.POI_CATEGORY"});
        hashMap.put(new Integer(255), new String[]{"phone_ADB_Call_Commands_Public.CONTACT_NM", "phone_ADB_Call_Commands_Public.PHONETYPE_NM"});
        hashMap.put(new Integer(252), new String[]{"system_navigation"});
        hashMap.put(new Integer(253), new String[]{"system_telephone"});
        hashMap.put(new Integer(2200062), new String[]{"online_read_mail"});
        hashMap.put(new Integer(2200060), new String[]{"online_read_new_mail"});
        return hashMap;
    }
}

