/*
 * Decompiled with CFR 0.152.
 */
package de.audi.app.sds.evo.testsupport;

import de.audi.app.sdsmanager.testsupport.SLMRulesMap;
import java.util.HashMap;
import java.util.Map;

public class SLMRulesMapEvo
extends SLMRulesMap {
    @Override
    protected Map createFilledMap() {
        HashMap hashMap = new HashMap();
        hashMap.put(new Integer(283), new String[]{"system_help"});
        hashMap.put(new Integer(-214627328), new String[]{"navigation_POI_call"});
        hashMap.put(new Integer(281), new String[]{"system_help_car"});
        hashMap.put(new Integer(287), new String[]{"system_help_media"});
        hashMap.put(new Integer(285), new String[]{"system_help_tone"});
        hashMap.put(new Integer(258), new String[]{"phone_redial"});
        hashMap.put(new Integer(259), new String[]{"phone_call_mailbox"});
        hashMap.put(new Integer(257), new String[]{"phone_call_lists"});
        hashMap.put(new Integer(262), new String[]{"system_addressbook"});
        hashMap.put(new Integer(260), new String[]{"phone_start_number_dialog"});
        hashMap.put(new Integer(1066664960), new String[]{"phone_favorites"});
        hashMap.put(new Integer(-720567552), new String[]{"media_select_multi_slot.TITLE_NM", "media_select_multi_slot.ALBUM_NM"});
        hashMap.put(new Integer(-870644224), new String[]{"navigation_no_uturn"});
        hashMap.put(new Integer(445784320), new String[]{"online_adb_dictate_mail"});
        hashMap.put(new Integer(-687013120), new String[]{"media_select_multi_slot.TITLE_NM", "media_select_multi_slot.ARTIST_NM"});
        hashMap.put(new Integer(-468909312), new String[]{"media_select_multi_slot.ARTIST_NM", "media_select_multi_slot.ALBUM_NM", "media_select_multi_slot.TITLE_NM"});
        hashMap.put(new Integer(412229888), new String[]{"online_adb_dictate.PHONETYPE_NM"});
        hashMap.put(new Integer(-1994906880), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(529670400), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(-937753088), new String[]{"navigation_voice_guidance_short"});
        hashMap.put(new Integer(-904198656), new String[]{"navigation_voice_guidance_traffic"});
        hashMap.put(new Integer(479338752), new String[]{"online_adb_dictate_sms.PHONETYPE_NM"});
        hashMap.put(new Integer(-586349824), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(-1004861952), new String[]{"navigation_voice_guidance_complete"});
        hashMap.put(new Integer(-603127040), new String[]{"media_select_device_sd.SDCARD_NR"});
        hashMap.put(new Integer(311566592), new String[]{"online_read_new_message"});
        hashMap.put(new Integer(-971307520), new String[]{"navigation_voice_guidance_off"});
        hashMap.put(new Integer(278012160), new String[]{"online_read_message"});
        hashMap.put(new Integer(317), new String[]{"system_menue"});
        hashMap.put(new Integer(-1071970816), new String[]{"navigation_map_destination"});
        hashMap.put(new Integer(378675456), new String[]{"online_reply_message"});
        hashMap.put(new Integer(-619904256), new String[]{"media_select_device_cd.DISC_NR"});
        hashMap.put(new Integer(319), new String[]{"system_tone"});
        hashMap.put(new Integer(-1038416384), new String[]{"navigation_map_overview"});
        hashMap.put(new Integer(345121024), new String[]{"online_forward_message"});
        hashMap.put(new Integer(318), new String[]{"system_map"});
        hashMap.put(new Integer(-1005780224), new String[]{"media_select_folder_audiobook"});
        hashMap.put(new Integer(177348864), new String[]{"online_dictate_sms"});
        hashMap.put(new Integer(289), new String[]{"system_help_office"});
        hashMap.put(new Integer(143794432), new String[]{"online_dictate_sms_contact.CONTACT_NM", "online_dictate_sms_contact.PHONETYPE_NM"});
        hashMap.put(new Integer(291), new String[]{"system_help_map"});
        hashMap.put(new Integer(-1072889088), new String[]{"media_browse_playmore"});
        hashMap.put(new Integer(244457728), new String[]{"online_read_new_sms"});
        hashMap.put(new Integer(292), new String[]{"system_help_navigation"});
        hashMap.put(new Integer(-1056111872), new String[]{"media_select_folder_title"});
        hashMap.put(new Integer(-1039334656), new String[]{"media_select_folder_podcast"});
        hashMap.put(new Integer(210903296), new String[]{"online_read_sms"});
        hashMap.put(new Integer(-1022557440), new String[]{"media_select_folder_genre"});
        hashMap.put(new Integer(295), new String[]{"system_help_online"});
        hashMap.put(new Integer(43131136), new String[]{"online_dictate_mail"});
        hashMap.put(new Integer(-719649280), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(297), new String[]{"system_help_phone"});
        hashMap.put(new Integer(9576704), new String[]{"online_dictate_mail_contact.CONTACT_NM"});
        hashMap.put(new Integer(299), new String[]{"system_help_tuner"});
        hashMap.put(new Integer(110240000), new String[]{"online_dictate_message"});
        hashMap.put(new Integer(-786758144), new String[]{"navigation_destination_poi_vicinity.POI_CATEGORY"});
        hashMap.put(new Integer(301), new String[]{"system_help_SDS_adjustments"});
        hashMap.put(new Integer(76685568), new String[]{"online_dictate_message_contact.CONTACT_NM", "online_dictate_message_contact.PHONETYPE_NM"});
        hashMap.put(new Integer(-753203712), new String[]{"navigation_destination_poi_along_route.POI_CATEGORY"});
        hashMap.put(new Integer(-769980928), new String[]{"navigation_destination_poi_destination.POI_CATEGORY"});
        hashMap.put(new Integer(-1441069568), new String[]{"navigation_myaudi_destinations"});
        hashMap.put(new Integer(612827392), new String[]{"tuner_frequency_AM_KOR.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1474624000), new String[]{"navigation_last_destinations"});
        hashMap.put(new Integer(646381824), new String[]{"tuner_frequency_FM_KOR.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1223884032), new String[]{"media_select_folder_playlist"});
        hashMap.put(new Integer(-1373960704), new String[]{"navigation_traffic_use_bypass"});
        hashMap.put(new Integer(-1240661248), new String[]{"media_select_folder_movie"});
        hashMap.put(new Integer(545718528), new String[]{"tuner_frequency_FM_JP.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1357183488), new String[]{"navigation_map_autocolor"});
        hashMap.put(new Integer(-1407515136), new String[]{"navigation_range_info"});
        hashMap.put(new Integer(579272960), new String[]{"tuner_frequency_AM_JP.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1156775168), new String[]{"media_select_folder_composer"});
        hashMap.put(new Integer(763822336), new String[]{"tuner_station_list_historylist"});
        hashMap.put(new Integer(-1575287296), new String[]{"navigation_calc_alternate_routes"});
        hashMap.put(new Integer(-1173552384), new String[]{"media_select_folder_artist"});
        hashMap.put(new Integer(-1190329600), new String[]{"media_select_folder_album"});
        hashMap.put(new Integer(-1608841728), new String[]{"navigation_block_route_distance.DISTANCE", "navigation_block_route_distance.UNIT"});
        hashMap.put(new Integer(-1207106816), new String[]{"media_select_folder_favorite"});
        hashMap.put(new Integer(780599552), new String[]{"tuner_waveband_SDARS"});
        hashMap.put(new Integer(-1089666304), new String[]{"media_select_single_slot_artist.ARTIST_NM"});
        hashMap.put(new Integer(-1508178432), new String[]{"navigation_favorites"});
        hashMap.put(new Integer(-1106443520), new String[]{"media_select_single_slot_title.TITLE_NM"});
        hashMap.put(new Integer(679936256), new String[]{"tuner_frequency_AM_AUS.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1123220736), new String[]{"media_select_multi_slot.ARTIST_NM", "media_select_multi_slot.ALBUM_NM"});
        hashMap.put(new Integer(-1541732864), new String[]{"navigation_destination_info"});
        hashMap.put(new Integer(-1139997952), new String[]{"media_select_single_slot_album.ALBUM_NM"});
        hashMap.put(new Integer(713490688), new String[]{"tuner_frequency_FM_AUS.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1576205568), new String[]{"media_select_device_wlan"});
        hashMap.put(new Integer(-1559428352), new String[]{"media_select_device_ami"});
        hashMap.put(new Integer(327), new String[]{"system_tuner"});
        hashMap.put(new Integer(-1172634112), new String[]{"navigation_map_2D"});
        hashMap.put(new Integer(324), new String[]{"system_pause"});
        hashMap.put(new Integer(-1592982784), new String[]{"media_select_device_jukebox"});
        hashMap.put(new Integer(325), new String[]{"system_next_page"});
        hashMap.put(new Integer(-1206188544), new String[]{"navigation_map_traffic"});
        hashMap.put(new Integer(-1509096704), new String[]{"media_select_device_sd.SDCARD_NR"});
        hashMap.put(new Integer(322), new String[]{"system_cancel"});
        hashMap.put(new Integer(-1492319488), new String[]{"media_select_device_usb.USB_NR"});
        hashMap.put(new Integer(830931200), new String[]{"tuner_select_station.CHANNEL_NM"});
        hashMap.put(new Integer(323), new String[]{"system_car"});
        hashMap.put(new Integer(-1105525248), new String[]{"navigation_map_3D"});
        hashMap.put(new Integer(-1542651136), new String[]{"media_select_device_cd_changer"});
        hashMap.put(new Integer(320), new String[]{"system_previous_page"});
        hashMap.put(new Integer(-1525873920), new String[]{"media_select_device_online.ONLINE_MEDIUM_NM"});
        hashMap.put(new Integer(321), new String[]{"system_bordcomputer"});
        hashMap.put(new Integer(-1139079680), new String[]{"navigation_map_2D_north"});
        hashMap.put(new Integer(-1441987840), new String[]{"media_select_device_by_name.DEVICE_NM"});
        hashMap.put(new Integer(-1425210624), new String[]{"media_select_device_ipod"});
        hashMap.put(new Integer(-1475542272), new String[]{"media_select_device_bluetooth"});
        hashMap.put(new Integer(332), new String[]{"system_correction"});
        hashMap.put(new Integer(-1323629056), new String[]{"navigation_map_range"});
        hashMap.put(new Integer(-1340406272), new String[]{"navigation_map_day"});
        hashMap.put(new Integer(330), new String[]{"system_favorites"});
        hashMap.put(new Integer(331), new String[]{"system_office"});
        hashMap.put(new Integer(-1239742976), new String[]{"navigation_map_google"});
        hashMap.put(new Integer(328), new String[]{"system_media"});
        hashMap.put(new Integer(329), new String[]{"system_online"});
        hashMap.put(new Integer(-1273297408), new String[]{"navigation_map_night"});
        hashMap.put(new Integer(1100219392), new String[]{"navigation_adb_navigate.ADDRESSTYPE_NM"});
        hashMap.put(new Integer(0x40940400), new String[]{"phone_dial_type.PHONETYPE_NM"});
        hashMap.put(new Integer(109510912), new String[]{"tuner_frequency_FM_NAR.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1994717696), new String[]{"navigation_destination_adb_contact.CONTACT_NM", "navigation_destination_adb_contact.ADDRESSTYPE_NM"});
        hashMap.put(new Integer(92733696), new String[]{"tuner_frequency_AM_NAR.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(59179264), new String[]{"tuner_DAB_station_ensemble.ENSEMBLE_NM"});
        hashMap.put(new Integer(-1944386048), new String[]{"navigation_cancel_routeguidance"});
        hashMap.put(new Integer(-1910831616), new String[]{"navigation_destination_entry"});
        hashMap.put(new Integer(25624832), new String[]{"tuner_select_station.STATION_NM"});
        hashMap.put(new Integer(1184105472), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(260505856), new String[]{"tuner_waveband_DAB"});
        hashMap.put(new Integer(1251214336), new String[]{"phone_ADB_Call_Contact_Plain.CONTACT_NM"});
        hashMap.put(new Integer(210174208), new String[]{"tuner_waveband_commonlist"});
        hashMap.put(new Integer(193396992), new String[]{"tuner_waveband_AM"});
        hashMap.put(new Integer(-2028272128), new String[]{"navigation_destination_address"});
        hashMap.put(new Integer(143065344), new String[]{"tuner_online_station.ONLINE_STATION_NM"});
        hashMap.put(new Integer(-1743059456), new String[]{"online_search"});
        hashMap.put(new Integer(-1709505024), new String[]{"online_search_slot"});
        hashMap.put(new Integer(361169152), new String[]{"tuner_station_list_presetlist"});
        hashMap.put(new Integer(-1675950592), new String[]{"navigation_home_address"});
        hashMap.put(new Integer(327614720), new String[]{"tuner_waveband_onlineradio"});
        hashMap.put(new Integer(277283072), new String[]{"tuner_waveband_FM"});
        hashMap.put(new Integer(-1642396160), new String[]{"navigation_traffic_situation"});
        hashMap.put(new Integer(-1877277184), new String[]{"navigation_poi_next_restaurant"});
        hashMap.put(new Integer(478609664), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(366), new String[]{"media_play_music"});
        hashMap.put(new Integer(-1843722752), new String[]{"navigation_poi_next_resting_place"});
        hashMap.put(new Integer(495386880), new String[]{"tuner_frequency_AM_EU_ROW.AM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1810168320), new String[]{"navigation_poi_next_restroom"});
        hashMap.put(new Integer(461832448), new String[]{"tuner_traffic_on"});
        hashMap.put(new Integer(-1776613888), new String[]{"navigation_poi_filling_station"});
        hashMap.put(new Integer(428278016), new String[]{"tuner_traffic_off"});
        hashMap.put(new Integer(-142212864), new String[]{"tuner_frequency_FM_EU_ROW.FM_FREQUENCY_NR"});
        hashMap.put(new Integer(-1917974016), new String[]{"system_line_number.LIST_NR"});
        hashMap.put(new Integer(68945408), new String[]{"navigation_destination_poi_address_oneshot.POI_CATEGORY"});
        hashMap.put(new Integer(255), new String[]{"phone_ADB_Call_Commands_Public.CONTACT_NM", "phone_ADB_Call_Commands_Public.PHONETYPE_NM"});
        hashMap.put(new Integer(252), new String[]{"system_navigation"});
        hashMap.put(new Integer(253), new String[]{"system_telephone"});
        hashMap.put(new Integer(-24043264), new String[]{"online_read_mail"});
        hashMap.put(new Integer(-57597696), new String[]{"online_read_new_mail"});
        return hashMap;
    }
}

