/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.cardrivingcharacteristics;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLVIEWOPTIONS = 1;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLLIFTMODE = 2;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLCARJACKMODE = 3;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLTRAILERMODE = 4;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLLOADINGMODE = 5;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACTIVEPROFILE = 6;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACCESSIBLEAIRPROFILES = 7;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACCESSIBLEDRCPROFILES = 8;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLVEHICLESTATUS = 9;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACTIVEMODE = 46;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCEASYENTRY = 47;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCPITCHCONTROL = 48;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCSPECIALPOSITION = 49;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCPREVIEW = 50;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_EABCPREVIEWSTATE = 51;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLACTUATORINFO = 52;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAVIEWOPTIONS = 12;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAACTIVEPROFILE = 13;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMALISTUPDATEINFO = 14;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMACONTENT = 15;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMATRAILERDETECTION = 16;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMATRAILERSETTING = 17;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAPROGBUTTON = 18;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMASOUND = 45;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADVIEWOPTIONS = 19;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADCONTENT = 20;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADVEHICLEINFO = 21;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADCURRENTROLLANGLE = 22;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADCURRENTPITCHANGLE = 23;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADPOSMAXROLLANGLE = 24;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADNEGMAXROLLANGLE = 25;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADPOSMAXPITCHANGLE = 26;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_TADNEGMAXPITCHANGLE = 27;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_CHARISMAACTIVEOPERATIONMODE = 28;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLCURRENTLEVEL = 29;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLTARGETLEVEL = 30;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLHEIGHTINFO = 31;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLOPERATIONMESSAGES = 32;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERVIEWOPTIONS = 33;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERPOSITIONSELECTION = 34;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERSTATE = 35;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERACTUATION = 36;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERMESSAGES = 37;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SPOILERSYSTEMONOFF = 38;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLSNOWCHAINMODE = 39;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SUSPENSIONCONTROLVEHICLESTATECONTROL = 40;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDVIEWOPTIONS = 41;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDSYSTEMONOFF = 42;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDONOFF = 43;
    public static final int ATTRIBUTE_ID_DSICARDRIVINGCHARACTERISTICS_SOUNDSTYLE = 44;
}

