/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.navi.app.util;

public class Consts {
    public static final long TIME_MASK = -32768L;
    public static final long ETA_UPDATE_TIME = 1000L;
    public static final int DESTINATION_TYPE_CENTER = 1;
    public static final int DESTINATION_TYPE_STREET = 2;
    public static final int DESTINATION_TYPE_INTERSECTION = 3;
    public static final int DESTINATION_TYPE_HOUSE_NUMBER = 4;
    public static final int DESTINATION_TYPE_POI = 5;
    public static final int DESTINATION_TYPE_GEOPOS = 6;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_COUNTRY = 0;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_CITY = 1;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_STREET = 2;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_HOUSENUMBER = 3;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_POI = 4;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_NAVIGABLE = 5;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_GEOPOS = 6;
    public static final int NAV_DEST_FORM_CURSOR_POS_CHOICE_CROSSING = 7;
    public static final int NAV_DEST_FORM_DISABLED_ELEMENTS_CHOICE_NO_ELEMENT = 0;
    public static final int NAV_DEST_FORM_DISABLED_ELEMENTS_CHOICE_START_HN_STREET = 1;
    public static final int NAV_DEST_FORM_DISABLED_ELEMENTS_CHOICE_START_HN = 2;
    public static final int NAV_DEST_FORM_DISABLED_ELEMENTS_CHOICE_START = 3;
    public static final int NAV_DEST_UNAMBIGUOUS_SELECTION = 0;
    public static final int NAV_DEST_AMBIGUOUS_SELECTION = 1;
    public static final int NAVGUIDANCESTATE_ACTIVE = 2;
    public static final int NAVGUIDANCESTATE_INACTIVE = 0;
    public static final int ROUTE_CALC_TYPE_FAST = 0;
    public static final int ROUTE_CALC_TYPE_SHORT = 1;
    public static final int ROUTE_CALC_TYPE_ECO = 2;
    public static final int DONT_AVOID = 0;
    public static final int AVOID = 1;
    public static final int VIGNETTE_USE = 0;
    public static final int VIGNETTE_AVOID = 1;
    public static final int VIGNETTE_AVOID_EXCEPT_LIST = 2;
    public static final int TIME_DOMAIN_AUTO = 0;
    public static final int TIME_DOMAIN_USE = 1;
    public static final int TIME_DOMAIN_AVOID = 2;
    public static final int DYNAMIC_RG_AUTO = 0;
    public static final int DYNAMIC_RG_MANUAL = 1;
    public static final int DYNAMIC_RG_OFF = 2;
    public static final int MAX_PREVIEWLIST_LENGTH = 4;
    public static final int MAX_LAST_DEST_LIST_LENGTH = 50;
    public static final int MAX_NUMBER_OF_ON_ROAD_DESTINATIONS_MIB_HIGH = 10;
    public static final int MAX_NUMBER_OF_ON_ROAD_DESTINATIONS_MIB_STANDARD = 2;
    public static final int MAX_NUMBER_OF_WAYPOINTS = 20;
    public static final int MAX_SPELLER_TEXTFIELD_LENGTH = 128;
    public static final int MAX_STORE_SPELLER_TEXTFIELD_LENGTH = 40;
    public static final int HISTORY_ENTRY_LIST_OFFSET = -1;
    public static final String PHONE_APP_NAME = "AppPhone";
    public static final int ALTERNATIVE_ROUTE_ON = 0;
    public static final int ALTERNATIVE_ROUTE_OFF = 1;
    public static final int DEMO_MODE_ON = 0;
    public static final int DEMO_MODE_OFF = 1;
    public static final int ALTERNATIVE_ROUTES_COUNT = 3;
    public static final int ANNOUNCEMENT_ON_CALL_ON = 0;
    public static final int ANNOUNCEMENT_ON_CALL_OFF = 1;
    public static final int GUIDANCE_TIME_ETA_MODE = 0;
    public static final int GUIDANCE_TIME_RTT_MODE = 1;
    public static final int TRAFFIC_SIGN_DISPLAY_ON = 1;
    public static final int TRAFFIC_SIGN_DISPLAY_OFF = 0;
    public static final int RSE_CONFIRM_TRANSFER_ON = 0;
    public static final int RSE_CONFIRM_TRANSFER_OFF = 1;
    public static final int FUEL_WARNING_RECOMMENDATION_ON = 0;
    public static final int FUEL_WARNING_RECOMMENDATION_OFF = 1;
    public static final int OFFR_MEM_STATUS_FULL = 2;
    public static final int OFFR_MEM_STATUS_NEARLY_FULL = 1;
    public static final int OFFR_MEM_STATUS_OK = 0;
    public static final int OFFROAD_RECORDING_INACTIVE = 0;
    public static final int OFFROAD_RECORDING_ACTIVE = 1;
    public static final int NAV_OFFR_BT_TRACING_INACTIVE = 0;
    public static final int NAV_OFFR_BT_TRACING_ACTIVE = 1;
    public static final int NAV_OFFR_BT_TRACING_REVERSE_ACTIVE = 2;
    public static final int COMBI_STREETMODE_CURRENTSTREET = 0;
    public static final int COMBI_STREETMODE_TURNTOSTREET = 1;
    public static final byte[] FLAG_DEFAULT_VALUES = new byte[]{1, 0, 0, 1, 0, 0, 7, 1, 7, 1, 2, 1, 2, 7, 90, 70, 50, 100, 3, 3, 3};
    public static final int LI_COUNTRY_MODE = 0;
    public static final int LI_STATE_MODE = 1;
    public static final int IMAGE_NONE = -1;
}

