/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.mirrorlink;

public class Consts {
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DISCOVEREDDEVICES = 1;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DEVICECONNECTIONSTATUS = 3;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DEVICESOFTKEYS = 4;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_APPLICATIONSTATUS = 5;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SCREENORIENTATION = 6;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SHOWKEYBOARD = 7;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SCREENORIENTATIONAVAILABLE = 8;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SCREENROTATIONAVAILABLE = 9;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_AUDIOCONNECTIONREQUESTED = 10;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_AVAILABLEAPPLICATIONSLIST = 11;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SINGLEAPPLICATIONMODE = 12;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_PHONEVIEWAVAILABLE = 13;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_UNCERTIFIEDCONTENT = 14;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_DEVICESTATUS = 15;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SWAPSTATUS = 16;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SHOWNOTIFICATION = 17;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_NOTIFICATIONSERVICEENABLED = 18;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_LOCATIONDATASERVICESENABLED = 19;
    public static final int ATTRIBUTE_ID_DSIMIRRORLINK_SWITCHTOCLIENTNATIVEUI = 20;
}

