/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.dsi.carauxheatercooler;

public class Consts {
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERVIEWOPTIONS = 1;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERSTATE = 3;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERONOFF = 4;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERREMAININGTIME = 5;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERRUNNINGTIME = 6;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERMODE = 7;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERENGINEHEATER = 8;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERACTIVETIMER = 9;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTIMER1 = 10;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTIMER2 = 11;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTIMER3 = 12;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERDEFAULTSTARTMODE = 13;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERERRORREASON = 14;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERCURRENTHEATERSTATE = 15;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERPOPUP = 16;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERMODE2 = 17;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLEREXTENDEDCONDITIONING = 18;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERWINDOWHEATING = 19;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERUNLOCKCLIMATING = 20;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERTARGETTEMPERATURE = 21;
    public static final int ATTRIBUTE_ID_DSICARAUXHEATERCOOLER_AUXHEATERCOOLERAIRQUALITY = 22;
}

