/*
 * Decompiled with CFR 0.152.
 */
package de.audi.tghu.tuner.hmi.evohighscale;

import de.audi.atip.hmi.model.ListCell;
import de.audi.tghu.tuner.hmi.evohighscale.TunerScreenFactory;
import de.esolutions.hmi.widgets.audi.base.widgets.AbstractWidgetController;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.AxisConstraints;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayout;
import de.esolutions.hmi.widgets.audi.evo.gridlayout.GridLayoutHints;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.IconRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.LabelRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.high.widgets.MenuItemRendererHigh;
import de.esolutions.hmi.widgets.audi.evo.widgets.IconController;
import de.esolutions.hmi.widgets.audi.evo.widgets.LabelController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemColumnsConstraints;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.MenuItemController;
import de.esolutions.hmi.widgets.audi.evo.widgets.menu.list.ListItemFactory;

final class TunerScreenBag1$13
implements ListItemFactory {
    private final /* synthetic */ TunerScreenFactory val$factory;
    private final /* synthetic */ int val$terminalID;

    TunerScreenBag1$13(TunerScreenFactory tunerScreenFactory, int n) {
        this.val$factory = tunerScreenFactory;
        this.val$terminalID = n;
    }

    @Override
    public AbstractWidgetController createListItem(int n, ListCell[] listCellArray) {
        switch (n) {
            case 0: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout2 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints2 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints2.alignment = new int[]{8, 1, 8, 8};
                menuItemColumnsConstraints2.gaps = new int[]{0, 12, 12, 12, 0};
                menuItemColumnsConstraints2.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints2.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints2.hidemode = new int[]{0, 2, 0, 0};
                gridLayout2.setColumnConstraints(menuItemColumnsConstraints2);
                AxisConstraints axisConstraints2 = new AxisConstraints(1);
                axisConstraints2.alignment = new int[]{5};
                gridLayout2.setRowConstraints(axisConstraints2);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController2 = this.createCell(1);
                GridLayoutHints gridLayoutHints2 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController3 = this.createCell(2);
                GridLayoutHints gridLayoutHints3 = new GridLayoutHints(2, 0);
                gridLayoutHints3.widthMax = 162;
                gridLayoutHints3.widthMin = 162;
                gridLayoutHints3.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController4 = this.createCell(3);
                GridLayoutHints gridLayoutHints4 = new GridLayoutHints(3, 0);
                gridLayoutHints4.widthMax = 40;
                gridLayoutHints4.widthMin = 40;
                gridLayoutHints4.visibleConditions = -13;
                gridLayout2.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints2, gridLayoutHints3, gridLayoutHints4}, new Object[]{abstractWidgetController, abstractWidgetController2, abstractWidgetController3, abstractWidgetController4});
                GridLayoutHints gridLayoutHints5 = new GridLayoutHints(0, 0);
                gridLayoutHints5.hidemode = 0;
                GridLayout gridLayout3 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints3 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints3.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints3.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints3.hidemode = new int[]{2, 2, 2};
                gridLayout3.setColumnConstraints(menuItemColumnsConstraints3);
                AxisConstraints axisConstraints3 = new AxisConstraints(1);
                axisConstraints3.hidemode = new int[]{2};
                gridLayout3.setRowConstraints(axisConstraints3);
                AbstractWidgetController abstractWidgetController5 = this.createCell(4);
                GridLayoutHints gridLayoutHints6 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController6 = this.createCell(5);
                GridLayoutHints gridLayoutHints7 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController7 = this.createCell(6);
                GridLayoutHints gridLayoutHints8 = new GridLayoutHints(2, 0);
                gridLayout3.setCellConstraints(new GridLayoutHints[]{gridLayoutHints6, gridLayoutHints7, gridLayoutHints8}, new Object[]{abstractWidgetController5, abstractWidgetController6, abstractWidgetController7});
                GridLayoutHints gridLayoutHints9 = new GridLayoutHints(0, 1);
                gridLayoutHints9.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints5, gridLayoutHints9}, new Object[]{gridLayout2, gridLayout3});
                GridLayout gridLayout4 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints4 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints4.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints4.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints4.shrink = new float[]{1.0f, 0.0f};
                gridLayout4.setColumnConstraints(menuItemColumnsConstraints4);
                AxisConstraints axisConstraints4 = new AxisConstraints(5);
                axisConstraints4.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints4.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints4.size = new int[]{20, 16, 16, 16, 16};
                gridLayout4.setRowConstraints(axisConstraints4);
                GridLayout gridLayout5 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints5 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints5.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints5.shrink = new float[]{1.0f, 0.0f};
                gridLayout5.setColumnConstraints(menuItemColumnsConstraints5);
                AxisConstraints axisConstraints5 = new AxisConstraints(1);
                axisConstraints5.alignment = new int[]{5};
                gridLayout5.setRowConstraints(axisConstraints5);
                AbstractWidgetController abstractWidgetController8 = this.createCell(7);
                GridLayoutHints gridLayoutHints10 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController9 = this.createCell(8);
                GridLayoutHints gridLayoutHints11 = new GridLayoutHints(1, 0);
                gridLayout5.setCellConstraints(new GridLayoutHints[]{gridLayoutHints10, gridLayoutHints11}, new Object[]{abstractWidgetController8, abstractWidgetController9});
                GridLayoutHints gridLayoutHints12 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController10 = this.createCell(9);
                GridLayoutHints gridLayoutHints13 = new GridLayoutHints(1, 0);
                gridLayoutHints13.alignmentVert = 9;
                gridLayoutHints13.rowSpan = 5;
                gridLayoutHints13.widthMax = 216;
                gridLayoutHints13.widthMin = 216;
                gridLayoutHints13.visibleConditions = -13;
                GridLayout gridLayout6 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints6 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints6.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints6.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints6.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints6.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints6.hidemode = new int[]{2, 2, 2, 1};
                gridLayout6.setColumnConstraints(menuItemColumnsConstraints6);
                AxisConstraints axisConstraints6 = new AxisConstraints(1);
                axisConstraints6.alignment = new int[]{5};
                axisConstraints6.hidemode = new int[]{2};
                gridLayout6.setRowConstraints(axisConstraints6);
                AbstractWidgetController abstractWidgetController11 = this.createCell(10);
                GridLayoutHints gridLayoutHints14 = new GridLayoutHints(0, 0);
                gridLayout6.setCellConstraints(new GridLayoutHints[]{gridLayoutHints14}, new Object[]{abstractWidgetController11});
                GridLayoutHints gridLayoutHints15 = new GridLayoutHints(0, 1);
                GridLayoutHints gridLayoutHints16 = new GridLayoutHints(0, 2);
                GridLayoutHints gridLayoutHints17 = new GridLayoutHints(0, 3);
                gridLayout4.setCellConstraints(new GridLayoutHints[]{gridLayoutHints12, gridLayoutHints13, gridLayoutHints15, gridLayoutHints16, gridLayoutHints17}, new Object[]{gridLayout5, abstractWidgetController10, gridLayout6, abstractWidgetController5, abstractWidgetController7});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout4});
                menuItemController.add(abstractWidgetController2);
                menuItemController.add(abstractWidgetController9);
                menuItemController.add(abstractWidgetController8);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController3);
                menuItemController.add(abstractWidgetController11);
                menuItemController.add(abstractWidgetController5);
                menuItemController.add(abstractWidgetController6);
                menuItemController.add(abstractWidgetController7);
                menuItemController.add(abstractWidgetController10);
                menuItemController.add(abstractWidgetController4);
                return menuItemController;
            }
            case 1: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout7 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints7 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints7.alignment = new int[]{3, 8, 1};
                menuItemColumnsConstraints7.gaps = new int[]{0, 12, 12, 0};
                menuItemColumnsConstraints7.grow = new float[]{0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints7.shrink = new float[]{1.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints7.size = new int[]{164, -1, -1};
                menuItemColumnsConstraints7.hidemode = new int[]{0, 0, 2};
                gridLayout7.setColumnConstraints(menuItemColumnsConstraints7);
                AxisConstraints axisConstraints7 = new AxisConstraints(1);
                axisConstraints7.alignment = new int[]{5};
                gridLayout7.setRowConstraints(axisConstraints7);
                AbstractWidgetController abstractWidgetController = this.createCell(11);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController12 = this.createCell(0);
                GridLayoutHints gridLayoutHints18 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController13 = this.createCell(1);
                GridLayoutHints gridLayoutHints19 = new GridLayoutHints(2, 0);
                gridLayout7.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints18, gridLayoutHints19}, new Object[]{abstractWidgetController, abstractWidgetController12, abstractWidgetController13});
                GridLayoutHints gridLayoutHints20 = new GridLayoutHints(0, 0);
                gridLayoutHints20.hidemode = 0;
                GridLayout gridLayout8 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints8 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints8.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints8.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints8.hidemode = new int[]{2, 2, 2};
                gridLayout8.setColumnConstraints(menuItemColumnsConstraints8);
                AxisConstraints axisConstraints8 = new AxisConstraints(1);
                axisConstraints8.hidemode = new int[]{2};
                gridLayout8.setRowConstraints(axisConstraints8);
                AbstractWidgetController abstractWidgetController14 = this.createCell(4);
                GridLayoutHints gridLayoutHints21 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController15 = this.createCell(5);
                GridLayoutHints gridLayoutHints22 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController16 = this.createCell(6);
                GridLayoutHints gridLayoutHints23 = new GridLayoutHints(2, 0);
                gridLayout8.setCellConstraints(new GridLayoutHints[]{gridLayoutHints21, gridLayoutHints22, gridLayoutHints23}, new Object[]{abstractWidgetController14, abstractWidgetController15, abstractWidgetController16});
                GridLayoutHints gridLayoutHints24 = new GridLayoutHints(0, 1);
                gridLayoutHints24.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints20, gridLayoutHints24}, new Object[]{gridLayout7, gridLayout8});
                GridLayout gridLayout9 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints9 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints9.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints9.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints9.shrink = new float[]{1.0f, 0.0f};
                gridLayout9.setColumnConstraints(menuItemColumnsConstraints9);
                AxisConstraints axisConstraints9 = new AxisConstraints(5);
                axisConstraints9.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints9.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints9.size = new int[]{20, 16, 16, 16, 16};
                gridLayout9.setRowConstraints(axisConstraints9);
                GridLayout gridLayout10 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints10 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints10.gaps = new int[]{0, 22, 15, 0};
                menuItemColumnsConstraints10.shrink = new float[]{1.0f, 1.0f, 0.0f};
                gridLayout10.setColumnConstraints(menuItemColumnsConstraints10);
                AxisConstraints axisConstraints10 = new AxisConstraints(1);
                axisConstraints10.alignment = new int[]{5};
                gridLayout10.setRowConstraints(axisConstraints10);
                AbstractWidgetController abstractWidgetController17 = this.createCell(12);
                GridLayoutHints gridLayoutHints25 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController18 = this.createCell(7);
                GridLayoutHints gridLayoutHints26 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController19 = this.createCell(8);
                GridLayoutHints gridLayoutHints27 = new GridLayoutHints(2, 0);
                gridLayout10.setCellConstraints(new GridLayoutHints[]{gridLayoutHints25, gridLayoutHints26, gridLayoutHints27}, new Object[]{abstractWidgetController17, abstractWidgetController18, abstractWidgetController19});
                GridLayoutHints gridLayoutHints28 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController20 = this.createCell(9);
                GridLayoutHints gridLayoutHints29 = new GridLayoutHints(1, 0);
                gridLayoutHints29.alignmentVert = 9;
                gridLayoutHints29.rowSpan = 5;
                gridLayoutHints29.widthMax = 216;
                gridLayoutHints29.widthMin = 216;
                gridLayoutHints29.visibleConditions = -13;
                GridLayout gridLayout11 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints11 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints11.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints11.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints11.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints11.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints11.hidemode = new int[]{2, 2, 2, 1};
                gridLayout11.setColumnConstraints(menuItemColumnsConstraints11);
                AxisConstraints axisConstraints11 = new AxisConstraints(1);
                axisConstraints11.alignment = new int[]{5};
                axisConstraints11.hidemode = new int[]{2};
                gridLayout11.setRowConstraints(axisConstraints11);
                AbstractWidgetController abstractWidgetController21 = this.createCell(10);
                GridLayoutHints gridLayoutHints30 = new GridLayoutHints(0, 0);
                gridLayout11.setCellConstraints(new GridLayoutHints[]{gridLayoutHints30}, new Object[]{abstractWidgetController21});
                GridLayoutHints gridLayoutHints31 = new GridLayoutHints(0, 1);
                GridLayoutHints gridLayoutHints32 = new GridLayoutHints(0, 2);
                GridLayoutHints gridLayoutHints33 = new GridLayoutHints(0, 3);
                gridLayout9.setCellConstraints(new GridLayoutHints[]{gridLayoutHints28, gridLayoutHints29, gridLayoutHints31, gridLayoutHints32, gridLayoutHints33}, new Object[]{gridLayout10, abstractWidgetController20, gridLayout11, abstractWidgetController14, abstractWidgetController16});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout9});
                menuItemController.add(abstractWidgetController13);
                menuItemController.add(abstractWidgetController19);
                menuItemController.add(abstractWidgetController17);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController18);
                menuItemController.add(abstractWidgetController12);
                menuItemController.add(abstractWidgetController21);
                menuItemController.add(abstractWidgetController14);
                menuItemController.add(abstractWidgetController15);
                menuItemController.add(abstractWidgetController16);
                menuItemController.add(abstractWidgetController20);
                return menuItemController;
            }
            case 2: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout12 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints12 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints12.alignment = new int[]{8, 1, 8, 8};
                menuItemColumnsConstraints12.gaps = new int[]{0, 12, 12, 12, 0};
                menuItemColumnsConstraints12.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints12.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints12.hidemode = new int[]{0, 2, 0, 0};
                gridLayout12.setColumnConstraints(menuItemColumnsConstraints12);
                AxisConstraints axisConstraints12 = new AxisConstraints(1);
                axisConstraints12.alignment = new int[]{5};
                gridLayout12.setRowConstraints(axisConstraints12);
                AbstractWidgetController abstractWidgetController = this.createCell(0);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController22 = this.createCell(1);
                GridLayoutHints gridLayoutHints34 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController23 = this.createCell(2);
                GridLayoutHints gridLayoutHints35 = new GridLayoutHints(2, 0);
                gridLayoutHints35.widthMax = 162;
                gridLayoutHints35.widthMin = 162;
                gridLayoutHints35.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController24 = this.createCell(3);
                GridLayoutHints gridLayoutHints36 = new GridLayoutHints(3, 0);
                gridLayoutHints36.widthMax = 40;
                gridLayoutHints36.widthMin = 40;
                gridLayoutHints36.visibleConditions = -13;
                gridLayout12.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints34, gridLayoutHints35, gridLayoutHints36}, new Object[]{abstractWidgetController, abstractWidgetController22, abstractWidgetController23, abstractWidgetController24});
                GridLayoutHints gridLayoutHints37 = new GridLayoutHints(0, 0);
                gridLayoutHints37.hidemode = 0;
                GridLayout gridLayout13 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints13 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints13.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints13.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints13.hidemode = new int[]{2, 2, 2};
                gridLayout13.setColumnConstraints(menuItemColumnsConstraints13);
                AxisConstraints axisConstraints13 = new AxisConstraints(1);
                axisConstraints13.hidemode = new int[]{2};
                gridLayout13.setRowConstraints(axisConstraints13);
                AbstractWidgetController abstractWidgetController25 = this.createCell(4);
                GridLayoutHints gridLayoutHints38 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController26 = this.createCell(5);
                GridLayoutHints gridLayoutHints39 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController27 = this.createCell(6);
                GridLayoutHints gridLayoutHints40 = new GridLayoutHints(2, 0);
                gridLayout13.setCellConstraints(new GridLayoutHints[]{gridLayoutHints38, gridLayoutHints39, gridLayoutHints40}, new Object[]{abstractWidgetController25, abstractWidgetController26, abstractWidgetController27});
                GridLayoutHints gridLayoutHints41 = new GridLayoutHints(0, 1);
                gridLayoutHints41.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints37, gridLayoutHints41}, new Object[]{gridLayout12, gridLayout13});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout});
                menuItemController.add(abstractWidgetController22);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController23);
                menuItemController.add(abstractWidgetController25);
                menuItemController.add(abstractWidgetController26);
                menuItemController.add(abstractWidgetController27);
                menuItemController.add(abstractWidgetController24);
                return menuItemController;
            }
            case 3: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.alignment = new int[]{5, 9};
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout14 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints14 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints14.alignment = new int[]{8, 1, 8, 8};
                menuItemColumnsConstraints14.gaps = new int[]{0, 12, 12, 12, 0};
                menuItemColumnsConstraints14.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints14.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                gridLayout14.setColumnConstraints(menuItemColumnsConstraints14);
                AxisConstraints axisConstraints14 = new AxisConstraints(1);
                axisConstraints14.alignment = new int[]{5};
                gridLayout14.setRowConstraints(axisConstraints14);
                AbstractWidgetController abstractWidgetController = this.createCell(11);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController28 = this.createCell(1);
                GridLayoutHints gridLayoutHints42 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController29 = this.createCell(2);
                GridLayoutHints gridLayoutHints43 = new GridLayoutHints(2, 0);
                gridLayoutHints43.widthMax = 162;
                gridLayoutHints43.widthMin = 162;
                gridLayoutHints43.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController30 = this.createCell(3);
                GridLayoutHints gridLayoutHints44 = new GridLayoutHints(3, 0);
                gridLayoutHints44.widthMax = 40;
                gridLayoutHints44.widthMin = 40;
                gridLayoutHints44.visibleConditions = -13;
                gridLayout14.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints42, gridLayoutHints43, gridLayoutHints44}, new Object[]{abstractWidgetController, abstractWidgetController28, abstractWidgetController29, abstractWidgetController30});
                GridLayoutHints gridLayoutHints45 = new GridLayoutHints(0, 0);
                gridLayoutHints45.hidemode = 0;
                GridLayout gridLayout15 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints15 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints15.gaps = new int[]{0, 8, 8, 0};
                menuItemColumnsConstraints15.shrink = new float[]{1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints15.hidemode = new int[]{2, 2, 2};
                gridLayout15.setColumnConstraints(menuItemColumnsConstraints15);
                AxisConstraints axisConstraints15 = new AxisConstraints(1);
                axisConstraints15.hidemode = new int[]{2};
                gridLayout15.setRowConstraints(axisConstraints15);
                AbstractWidgetController abstractWidgetController31 = this.createCell(4);
                GridLayoutHints gridLayoutHints46 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController32 = this.createCell(5);
                GridLayoutHints gridLayoutHints47 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController33 = this.createCell(6);
                GridLayoutHints gridLayoutHints48 = new GridLayoutHints(2, 0);
                gridLayout15.setCellConstraints(new GridLayoutHints[]{gridLayoutHints46, gridLayoutHints47, gridLayoutHints48}, new Object[]{abstractWidgetController31, abstractWidgetController32, abstractWidgetController33});
                GridLayoutHints gridLayoutHints49 = new GridLayoutHints(0, 1);
                gridLayoutHints49.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints45, gridLayoutHints49}, new Object[]{gridLayout14, gridLayout15});
                GridLayout gridLayout16 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints16 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints16.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints16.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints16.shrink = new float[]{1.0f, 0.0f};
                gridLayout16.setColumnConstraints(menuItemColumnsConstraints16);
                AxisConstraints axisConstraints16 = new AxisConstraints(5);
                axisConstraints16.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints16.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints16.size = new int[]{20, 16, 16, 16, 16};
                gridLayout16.setRowConstraints(axisConstraints16);
                GridLayout gridLayout17 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints17 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints17.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints17.shrink = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints17.hidemode = new int[]{0, 2};
                gridLayout17.setColumnConstraints(menuItemColumnsConstraints17);
                AxisConstraints axisConstraints17 = new AxisConstraints(1);
                axisConstraints17.alignment = new int[]{5};
                gridLayout17.setRowConstraints(axisConstraints17);
                AbstractWidgetController abstractWidgetController34 = this.createCell(12);
                GridLayoutHints gridLayoutHints50 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController35 = this.createCell(8);
                GridLayoutHints gridLayoutHints51 = new GridLayoutHints(1, 0);
                gridLayout17.setCellConstraints(new GridLayoutHints[]{gridLayoutHints50, gridLayoutHints51}, new Object[]{abstractWidgetController34, abstractWidgetController35});
                GridLayoutHints gridLayoutHints52 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController36 = this.createCell(9);
                GridLayoutHints gridLayoutHints53 = new GridLayoutHints(1, 0);
                gridLayoutHints53.alignmentVert = 9;
                gridLayoutHints53.rowSpan = 5;
                gridLayoutHints53.widthMax = 216;
                gridLayoutHints53.widthMin = 216;
                gridLayoutHints53.visibleConditions = -13;
                GridLayout gridLayout18 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints18 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints18.alignment = new int[]{8, 8, 8, 3};
                menuItemColumnsConstraints18.gaps = new int[]{0, 15, 15, 0, 0};
                menuItemColumnsConstraints18.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints18.shrink = new float[]{0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints18.hidemode = new int[]{2, 2, 2, 1};
                gridLayout18.setColumnConstraints(menuItemColumnsConstraints18);
                AxisConstraints axisConstraints18 = new AxisConstraints(1);
                axisConstraints18.alignment = new int[]{5};
                axisConstraints18.hidemode = new int[]{2};
                gridLayout18.setRowConstraints(axisConstraints18);
                AbstractWidgetController abstractWidgetController37 = this.createCell(10);
                GridLayoutHints gridLayoutHints54 = new GridLayoutHints(0, 0);
                gridLayout18.setCellConstraints(new GridLayoutHints[]{gridLayoutHints54}, new Object[]{abstractWidgetController37});
                GridLayoutHints gridLayoutHints55 = new GridLayoutHints(0, 1);
                GridLayoutHints gridLayoutHints56 = new GridLayoutHints(0, 2);
                GridLayoutHints gridLayoutHints57 = new GridLayoutHints(0, 3);
                gridLayout16.setCellConstraints(new GridLayoutHints[]{gridLayoutHints52, gridLayoutHints53, gridLayoutHints55, gridLayoutHints56, gridLayoutHints57}, new Object[]{gridLayout17, abstractWidgetController36, gridLayout18, abstractWidgetController31, abstractWidgetController33});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout16});
                menuItemController.add(abstractWidgetController28);
                menuItemController.add(abstractWidgetController35);
                menuItemController.add(abstractWidgetController34);
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController29);
                menuItemController.add(abstractWidgetController37);
                menuItemController.add(abstractWidgetController31);
                menuItemController.add(abstractWidgetController32);
                menuItemController.add(abstractWidgetController33);
                menuItemController.add(abstractWidgetController36);
                menuItemController.add(abstractWidgetController30);
                return menuItemController;
            }
            case 4: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout19 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints19 = new MenuItemColumnsConstraints(5);
                menuItemColumnsConstraints19.alignment = new int[]{8, 1, 8, 1, 8};
                menuItemColumnsConstraints19.gaps = new int[]{0, 15, 12, 12, 12, 0};
                menuItemColumnsConstraints19.grow = new float[]{0.0f, 0.0f, 0.0f, 1.0f, 0.0f};
                menuItemColumnsConstraints19.shrink = new float[]{0.0f, 0.0f, 1.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints19.hidemode = new int[]{0, 0, 0, 0, 2};
                gridLayout19.setColumnConstraints(menuItemColumnsConstraints19);
                AxisConstraints axisConstraints19 = new AxisConstraints(1);
                axisConstraints19.alignment = new int[]{5};
                gridLayout19.setRowConstraints(axisConstraints19);
                AbstractWidgetController abstractWidgetController = this.createCell(13);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.widthMax = 30;
                gridLayoutHints.widthMin = 30;
                AbstractWidgetController abstractWidgetController38 = this.createCell(11);
                GridLayoutHints gridLayoutHints58 = new GridLayoutHints(1, 0);
                gridLayoutHints58.widthMax = 92;
                gridLayoutHints58.widthMin = 92;
                AbstractWidgetController abstractWidgetController39 = this.createCell(14);
                GridLayoutHints gridLayoutHints59 = new GridLayoutHints(2, 0);
                gridLayoutHints59.visibleConditions = -13;
                AbstractWidgetController abstractWidgetController40 = this.createCell(15);
                GridLayoutHints gridLayoutHints60 = new GridLayoutHints(3, 0);
                AbstractWidgetController abstractWidgetController41 = this.createCell(16);
                GridLayoutHints gridLayoutHints61 = new GridLayoutHints(4, 0);
                gridLayout19.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints58, gridLayoutHints59, gridLayoutHints60, gridLayoutHints61}, new Object[]{abstractWidgetController, abstractWidgetController38, abstractWidgetController39, abstractWidgetController40, abstractWidgetController41});
                GridLayoutHints gridLayoutHints62 = new GridLayoutHints(0, 0);
                GridLayout gridLayout20 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints20 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints20.gaps = new int[]{0, 15, 8, 8, 0};
                menuItemColumnsConstraints20.shrink = new float[]{0.0f, 1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints20.hidemode = new int[]{1, 2, 2, 2};
                gridLayout20.setColumnConstraints(menuItemColumnsConstraints20);
                AxisConstraints axisConstraints20 = new AxisConstraints(1);
                axisConstraints20.alignment = new int[]{5};
                axisConstraints20.hidemode = new int[]{2};
                gridLayout20.setRowConstraints(axisConstraints20);
                AbstractWidgetController abstractWidgetController42 = this.createCell(17);
                GridLayoutHints gridLayoutHints63 = new GridLayoutHints(0, 0);
                gridLayoutHints63.widthMax = 30;
                gridLayoutHints63.widthMin = 30;
                AbstractWidgetController abstractWidgetController43 = this.createCell(4);
                GridLayoutHints gridLayoutHints64 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController44 = this.createCell(5);
                GridLayoutHints gridLayoutHints65 = new GridLayoutHints(2, 0);
                AbstractWidgetController abstractWidgetController45 = this.createCell(6);
                GridLayoutHints gridLayoutHints66 = new GridLayoutHints(3, 0);
                gridLayout20.setCellConstraints(new GridLayoutHints[]{gridLayoutHints63, gridLayoutHints64, gridLayoutHints65, gridLayoutHints66}, new Object[]{abstractWidgetController42, abstractWidgetController43, abstractWidgetController44, abstractWidgetController45});
                GridLayoutHints gridLayoutHints67 = new GridLayoutHints(0, 1);
                gridLayoutHints67.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints62, gridLayoutHints67}, new Object[]{gridLayout19, gridLayout20});
                GridLayout gridLayout21 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints21 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints21.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints21.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints21.shrink = new float[]{1.0f, 0.0f};
                gridLayout21.setColumnConstraints(menuItemColumnsConstraints21);
                AxisConstraints axisConstraints21 = new AxisConstraints(5);
                axisConstraints21.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints21.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints21.size = new int[]{20, 16, 16, 16, 16};
                gridLayout21.setRowConstraints(axisConstraints21);
                GridLayout gridLayout22 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints22 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints22.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints22.shrink = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints22.hidemode = new int[]{2, 0};
                gridLayout22.setColumnConstraints(menuItemColumnsConstraints22);
                AxisConstraints axisConstraints22 = new AxisConstraints(1);
                axisConstraints22.alignment = new int[]{5};
                gridLayout22.setRowConstraints(axisConstraints22);
                AbstractWidgetController abstractWidgetController46 = this.createCell(18);
                GridLayoutHints gridLayoutHints68 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController47 = this.createCell(12);
                GridLayoutHints gridLayoutHints69 = new GridLayoutHints(1, 0);
                gridLayout22.setCellConstraints(new GridLayoutHints[]{gridLayoutHints68, gridLayoutHints69}, new Object[]{abstractWidgetController46, abstractWidgetController47});
                GridLayoutHints gridLayoutHints70 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController48 = this.createCell(9);
                GridLayoutHints gridLayoutHints71 = new GridLayoutHints(1, 0);
                gridLayoutHints71.alignmentVert = 9;
                gridLayoutHints71.rowSpan = 5;
                gridLayoutHints71.widthMax = 216;
                gridLayoutHints71.widthMin = 216;
                gridLayoutHints71.visibleConditions = -13;
                GridLayout gridLayout23 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints23 = new MenuItemColumnsConstraints(5);
                menuItemColumnsConstraints23.alignment = new int[]{8, 1, 8, 8, 3};
                menuItemColumnsConstraints23.gaps = new int[]{0, 22, 22, 15, 15, 0};
                menuItemColumnsConstraints23.grow = new float[]{0.0f, 1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints23.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints23.hidemode = new int[]{1, 0, 2, 2, 2};
                gridLayout23.setColumnConstraints(menuItemColumnsConstraints23);
                AxisConstraints axisConstraints23 = new AxisConstraints(1);
                axisConstraints23.alignment = new int[]{5};
                axisConstraints23.hidemode = new int[]{2};
                gridLayout23.setRowConstraints(axisConstraints23);
                AbstractWidgetController abstractWidgetController49 = this.createCell(19);
                GridLayoutHints gridLayoutHints72 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController50 = this.createCell(20);
                GridLayoutHints gridLayoutHints73 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController51 = this.createCell(21);
                GridLayoutHints gridLayoutHints74 = new GridLayoutHints(2, 0);
                AbstractWidgetController abstractWidgetController52 = this.createCell(22);
                GridLayoutHints gridLayoutHints75 = new GridLayoutHints(3, 0);
                AbstractWidgetController abstractWidgetController53 = this.createCell(10);
                GridLayoutHints gridLayoutHints76 = new GridLayoutHints(4, 0);
                gridLayout23.setCellConstraints(new GridLayoutHints[]{gridLayoutHints72, gridLayoutHints73, gridLayoutHints74, gridLayoutHints75, gridLayoutHints76}, new Object[]{abstractWidgetController49, abstractWidgetController50, abstractWidgetController51, abstractWidgetController52, abstractWidgetController53});
                GridLayoutHints gridLayoutHints77 = new GridLayoutHints(0, 1);
                GridLayout gridLayout24 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints24 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints24.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints24.shrink = new float[]{0.0f, 1.0f};
                gridLayout24.setColumnConstraints(menuItemColumnsConstraints24);
                AxisConstraints axisConstraints24 = new AxisConstraints(1);
                axisConstraints24.alignment = new int[]{5};
                gridLayout24.setRowConstraints(axisConstraints24);
                AbstractWidgetController abstractWidgetController54 = this.createCell(23);
                GridLayoutHints gridLayoutHints78 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController55 = this.createCell(24);
                GridLayoutHints gridLayoutHints79 = new GridLayoutHints(1, 0);
                gridLayout24.setCellConstraints(new GridLayoutHints[]{gridLayoutHints78, gridLayoutHints79}, new Object[]{abstractWidgetController54, abstractWidgetController55});
                GridLayoutHints gridLayoutHints80 = new GridLayoutHints(0, 2);
                GridLayout gridLayout25 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints25 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints25.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints25.shrink = new float[]{0.0f, 1.0f};
                gridLayout25.setColumnConstraints(menuItemColumnsConstraints25);
                AxisConstraints axisConstraints25 = new AxisConstraints(1);
                axisConstraints25.alignment = new int[]{5};
                gridLayout25.setRowConstraints(axisConstraints25);
                AbstractWidgetController abstractWidgetController56 = this.createCell(25);
                GridLayoutHints gridLayoutHints81 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController57 = this.createCell(26);
                GridLayoutHints gridLayoutHints82 = new GridLayoutHints(1, 0);
                gridLayout25.setCellConstraints(new GridLayoutHints[]{gridLayoutHints81, gridLayoutHints82}, new Object[]{abstractWidgetController56, abstractWidgetController57});
                GridLayoutHints gridLayoutHints83 = new GridLayoutHints(0, 3);
                GridLayout gridLayout26 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints26 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints26.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints26.shrink = new float[]{0.0f, 1.0f};
                gridLayout26.setColumnConstraints(menuItemColumnsConstraints26);
                AxisConstraints axisConstraints26 = new AxisConstraints(1);
                axisConstraints26.alignment = new int[]{5};
                gridLayout26.setRowConstraints(axisConstraints26);
                AbstractWidgetController abstractWidgetController58 = this.createCell(27);
                GridLayoutHints gridLayoutHints84 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController59 = this.createCell(28);
                GridLayoutHints gridLayoutHints85 = new GridLayoutHints(1, 0);
                gridLayout26.setCellConstraints(new GridLayoutHints[]{gridLayoutHints84, gridLayoutHints85}, new Object[]{abstractWidgetController58, abstractWidgetController59});
                GridLayoutHints gridLayoutHints86 = new GridLayoutHints(0, 4);
                gridLayout21.setCellConstraints(new GridLayoutHints[]{gridLayoutHints70, gridLayoutHints71, gridLayoutHints77, gridLayoutHints80, gridLayoutHints83, gridLayoutHints86}, new Object[]{gridLayout22, abstractWidgetController48, gridLayout23, gridLayout24, gridLayout25, gridLayout26});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout21});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController46);
                menuItemController.add(abstractWidgetController47);
                menuItemController.add(abstractWidgetController38);
                menuItemController.add(abstractWidgetController39);
                menuItemController.add(abstractWidgetController49);
                menuItemController.add(abstractWidgetController40);
                menuItemController.add(abstractWidgetController50);
                menuItemController.add(abstractWidgetController41);
                menuItemController.add(abstractWidgetController51);
                menuItemController.add(abstractWidgetController52);
                menuItemController.add(abstractWidgetController53);
                menuItemController.add(abstractWidgetController54);
                menuItemController.add(abstractWidgetController43);
                menuItemController.add(abstractWidgetController55);
                menuItemController.add(abstractWidgetController44);
                menuItemController.add(abstractWidgetController56);
                menuItemController.add(abstractWidgetController45);
                menuItemController.add(abstractWidgetController57);
                menuItemController.add(abstractWidgetController58);
                menuItemController.add(abstractWidgetController59);
                menuItemController.add(abstractWidgetController48);
                menuItemController.add(abstractWidgetController42);
                return menuItemController;
            }
            case 5: {
                MenuItemController menuItemController = new MenuItemController();
                menuItemController.setType(16);
                menuItemController.setRenderer(new MenuItemRendererHigh(menuItemController));
                GridLayout gridLayout = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints = new MenuItemColumnsConstraints(1);
                menuItemColumnsConstraints.grow = new float[]{1.0f};
                gridLayout.setColumnConstraints(menuItemColumnsConstraints);
                AxisConstraints axisConstraints = new AxisConstraints(2);
                axisConstraints.hidemode = new int[]{0, 2};
                gridLayout.setRowConstraints(axisConstraints);
                GridLayout gridLayout27 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints27 = new MenuItemColumnsConstraints(3);
                menuItemColumnsConstraints27.alignment = new int[]{8, 1, 8};
                menuItemColumnsConstraints27.gaps = new int[]{0, 15, 12, 0};
                menuItemColumnsConstraints27.shrink = new float[]{0.0f, 0.0f, 1.0f};
                gridLayout27.setColumnConstraints(menuItemColumnsConstraints27);
                AxisConstraints axisConstraints27 = new AxisConstraints(1);
                axisConstraints27.alignment = new int[]{5};
                gridLayout27.setRowConstraints(axisConstraints27);
                AbstractWidgetController abstractWidgetController = this.createCell(13);
                GridLayoutHints gridLayoutHints = new GridLayoutHints(0, 0);
                gridLayoutHints.widthMax = 30;
                gridLayoutHints.widthMin = 30;
                AbstractWidgetController abstractWidgetController60 = this.createCell(11);
                GridLayoutHints gridLayoutHints87 = new GridLayoutHints(1, 0);
                gridLayoutHints87.widthMax = 92;
                gridLayoutHints87.widthMin = 92;
                AbstractWidgetController abstractWidgetController61 = this.createCell(29);
                GridLayoutHints gridLayoutHints88 = new GridLayoutHints(2, 0);
                gridLayout27.setCellConstraints(new GridLayoutHints[]{gridLayoutHints, gridLayoutHints87, gridLayoutHints88}, new Object[]{abstractWidgetController, abstractWidgetController60, abstractWidgetController61});
                GridLayoutHints gridLayoutHints89 = new GridLayoutHints(0, 0);
                GridLayout gridLayout28 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints28 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints28.gaps = new int[]{0, 15, 8, 8, 0};
                menuItemColumnsConstraints28.shrink = new float[]{0.0f, 1.0f, 0.0f, 1.0f};
                menuItemColumnsConstraints28.hidemode = new int[]{1, 2, 2, 2};
                gridLayout28.setColumnConstraints(menuItemColumnsConstraints28);
                AxisConstraints axisConstraints28 = new AxisConstraints(1);
                axisConstraints28.alignment = new int[]{5};
                axisConstraints28.hidemode = new int[]{2};
                gridLayout28.setRowConstraints(axisConstraints28);
                AbstractWidgetController abstractWidgetController62 = this.createCell(17);
                GridLayoutHints gridLayoutHints90 = new GridLayoutHints(0, 0);
                gridLayoutHints90.widthMax = 30;
                gridLayoutHints90.widthMin = 30;
                AbstractWidgetController abstractWidgetController63 = this.createCell(4);
                GridLayoutHints gridLayoutHints91 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController64 = this.createCell(5);
                GridLayoutHints gridLayoutHints92 = new GridLayoutHints(2, 0);
                AbstractWidgetController abstractWidgetController65 = this.createCell(6);
                GridLayoutHints gridLayoutHints93 = new GridLayoutHints(3, 0);
                gridLayout28.setCellConstraints(new GridLayoutHints[]{gridLayoutHints90, gridLayoutHints91, gridLayoutHints92, gridLayoutHints93}, new Object[]{abstractWidgetController62, abstractWidgetController63, abstractWidgetController64, abstractWidgetController65});
                GridLayoutHints gridLayoutHints94 = new GridLayoutHints(0, 1);
                gridLayoutHints94.visibleConditions = -11;
                gridLayout.setCellConstraints(new GridLayoutHints[]{gridLayoutHints89, gridLayoutHints94}, new Object[]{gridLayout27, gridLayout28});
                GridLayout gridLayout29 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints29 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints29.gaps = new int[]{10, 0, 0};
                menuItemColumnsConstraints29.grow = new float[]{1.0f, 0.0f};
                menuItemColumnsConstraints29.shrink = new float[]{1.0f, 0.0f};
                gridLayout29.setColumnConstraints(menuItemColumnsConstraints29);
                AxisConstraints axisConstraints29 = new AxisConstraints(5);
                axisConstraints29.alignment = new int[]{5, 5, 5, 5, 5};
                axisConstraints29.gaps = new int[]{42, 18, 34, 20, 20, 0};
                axisConstraints29.size = new int[]{20, 16, 16, 16, 16};
                gridLayout29.setRowConstraints(axisConstraints29);
                GridLayout gridLayout30 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints30 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints30.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints30.shrink = new float[]{0.0f, 1.0f};
                menuItemColumnsConstraints30.hidemode = new int[]{2, 0};
                gridLayout30.setColumnConstraints(menuItemColumnsConstraints30);
                AxisConstraints axisConstraints30 = new AxisConstraints(1);
                axisConstraints30.alignment = new int[]{5};
                axisConstraints30.shrink = new float[]{0.0f};
                gridLayout30.setRowConstraints(axisConstraints30);
                AbstractWidgetController abstractWidgetController66 = this.createCell(18);
                GridLayoutHints gridLayoutHints95 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController67 = this.createCell(12);
                GridLayoutHints gridLayoutHints96 = new GridLayoutHints(1, 0);
                gridLayout30.setCellConstraints(new GridLayoutHints[]{gridLayoutHints95, gridLayoutHints96}, new Object[]{abstractWidgetController66, abstractWidgetController67});
                GridLayoutHints gridLayoutHints97 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController68 = this.createCell(9);
                GridLayoutHints gridLayoutHints98 = new GridLayoutHints(1, 0);
                gridLayoutHints98.alignmentVert = 9;
                gridLayoutHints98.rowSpan = 5;
                gridLayoutHints98.widthMax = 216;
                gridLayoutHints98.widthMin = 216;
                gridLayoutHints98.visibleConditions = -13;
                GridLayout gridLayout31 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints31 = new MenuItemColumnsConstraints(4);
                menuItemColumnsConstraints31.alignment = new int[]{1, 8, 8, 3};
                menuItemColumnsConstraints31.gaps = new int[]{0, 15, 15, 15, 0};
                menuItemColumnsConstraints31.grow = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints31.shrink = new float[]{1.0f, 0.0f, 0.0f, 0.0f};
                menuItemColumnsConstraints31.hidemode = new int[]{2, 2, 2, 2};
                gridLayout31.setColumnConstraints(menuItemColumnsConstraints31);
                AxisConstraints axisConstraints31 = new AxisConstraints(1);
                axisConstraints31.alignment = new int[]{5};
                axisConstraints31.hidemode = new int[]{2};
                gridLayout31.setRowConstraints(axisConstraints31);
                AbstractWidgetController abstractWidgetController69 = this.createCell(30);
                GridLayoutHints gridLayoutHints99 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController70 = this.createCell(21);
                GridLayoutHints gridLayoutHints100 = new GridLayoutHints(1, 0);
                AbstractWidgetController abstractWidgetController71 = this.createCell(22);
                GridLayoutHints gridLayoutHints101 = new GridLayoutHints(2, 0);
                AbstractWidgetController abstractWidgetController72 = this.createCell(10);
                GridLayoutHints gridLayoutHints102 = new GridLayoutHints(3, 0);
                gridLayout31.setCellConstraints(new GridLayoutHints[]{gridLayoutHints99, gridLayoutHints100, gridLayoutHints101, gridLayoutHints102}, new Object[]{abstractWidgetController69, abstractWidgetController70, abstractWidgetController71, abstractWidgetController72});
                GridLayoutHints gridLayoutHints103 = new GridLayoutHints(0, 1);
                GridLayout gridLayout32 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints32 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints32.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints32.shrink = new float[]{0.0f, 1.0f};
                gridLayout32.setColumnConstraints(menuItemColumnsConstraints32);
                AxisConstraints axisConstraints32 = new AxisConstraints(1);
                axisConstraints32.alignment = new int[]{5};
                gridLayout32.setRowConstraints(axisConstraints32);
                AbstractWidgetController abstractWidgetController73 = this.createCell(23);
                GridLayoutHints gridLayoutHints104 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController74 = this.createCell(24);
                GridLayoutHints gridLayoutHints105 = new GridLayoutHints(1, 0);
                gridLayout32.setCellConstraints(new GridLayoutHints[]{gridLayoutHints104, gridLayoutHints105}, new Object[]{abstractWidgetController73, abstractWidgetController74});
                GridLayoutHints gridLayoutHints106 = new GridLayoutHints(0, 2);
                GridLayout gridLayout33 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints33 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints33.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints33.shrink = new float[]{0.0f, 1.0f};
                gridLayout33.setColumnConstraints(menuItemColumnsConstraints33);
                AxisConstraints axisConstraints33 = new AxisConstraints(1);
                axisConstraints33.alignment = new int[]{5};
                gridLayout33.setRowConstraints(axisConstraints33);
                AbstractWidgetController abstractWidgetController75 = this.createCell(25);
                GridLayoutHints gridLayoutHints107 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController76 = this.createCell(26);
                GridLayoutHints gridLayoutHints108 = new GridLayoutHints(1, 0);
                gridLayout33.setCellConstraints(new GridLayoutHints[]{gridLayoutHints107, gridLayoutHints108}, new Object[]{abstractWidgetController75, abstractWidgetController76});
                GridLayoutHints gridLayoutHints109 = new GridLayoutHints(0, 3);
                GridLayout gridLayout34 = new GridLayout();
                MenuItemColumnsConstraints menuItemColumnsConstraints34 = new MenuItemColumnsConstraints(2);
                menuItemColumnsConstraints34.gaps = new int[]{0, 15, 0};
                menuItemColumnsConstraints34.shrink = new float[]{0.0f, 1.0f};
                gridLayout34.setColumnConstraints(menuItemColumnsConstraints34);
                AxisConstraints axisConstraints34 = new AxisConstraints(1);
                axisConstraints34.alignment = new int[]{5};
                gridLayout34.setRowConstraints(axisConstraints34);
                AbstractWidgetController abstractWidgetController77 = this.createCell(27);
                GridLayoutHints gridLayoutHints110 = new GridLayoutHints(0, 0);
                AbstractWidgetController abstractWidgetController78 = this.createCell(28);
                GridLayoutHints gridLayoutHints111 = new GridLayoutHints(1, 0);
                gridLayout34.setCellConstraints(new GridLayoutHints[]{gridLayoutHints110, gridLayoutHints111}, new Object[]{abstractWidgetController77, abstractWidgetController78});
                GridLayoutHints gridLayoutHints112 = new GridLayoutHints(0, 4);
                gridLayout29.setCellConstraints(new GridLayoutHints[]{gridLayoutHints97, gridLayoutHints98, gridLayoutHints103, gridLayoutHints106, gridLayoutHints109, gridLayoutHints112}, new Object[]{gridLayout30, abstractWidgetController68, gridLayout31, gridLayout32, gridLayout33, gridLayout34});
                menuItemController.setLayoutChoices(new GridLayout[]{gridLayout, gridLayout29});
                menuItemController.add(abstractWidgetController);
                menuItemController.add(abstractWidgetController66);
                menuItemController.add(abstractWidgetController67);
                menuItemController.add(abstractWidgetController60);
                menuItemController.add(abstractWidgetController61);
                menuItemController.add(abstractWidgetController69);
                menuItemController.add(abstractWidgetController70);
                menuItemController.add(abstractWidgetController71);
                menuItemController.add(abstractWidgetController72);
                menuItemController.add(abstractWidgetController73);
                menuItemController.add(abstractWidgetController63);
                menuItemController.add(abstractWidgetController74);
                menuItemController.add(abstractWidgetController64);
                menuItemController.add(abstractWidgetController75);
                menuItemController.add(abstractWidgetController65);
                menuItemController.add(abstractWidgetController76);
                menuItemController.add(abstractWidgetController77);
                menuItemController.add(abstractWidgetController78);
                menuItemController.add(abstractWidgetController68);
                menuItemController.add(abstractWidgetController62);
                return menuItemController;
            }
        }
        return null;
    }

    @Override
    public AbstractWidgetController createListItemNoData() {
        return null;
    }

    public AbstractWidgetController createCell(int n) {
        switch (n) {
            case 0: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(3);
                return labelController;
            }
            case 1: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -393871104});
                iconController.setModelColumn(9);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 2: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setTextIds(new int[]{1418395904, 1435173120, 1451950336, 1468727552, 1485504768, 1502281984, 1519059200, 1535836416, 1552613632, 1569390848, 1586168064, 1602945280, 1619722496, 1636499712, 1653276928, -1215692544, -1198915328, 1703608576, 1720385792, 1737163008, 1753940224, 1770717440, -1098252032, 1804271872, 1821049088, 1837826304, 1854603520, 1871380736, 1888157952, 1904935168, 1921712384, 1938489600});
                labelController.setModelColumn(4);
                return labelController;
            }
            case 3: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 864485632});
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 4: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(12);
                return labelController;
            }
            case 5: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setTextIds(new int[]{-1316224768, -1316224768, -1299447552});
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(18);
                return labelController;
            }
            case 6: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 7, 4, 2});
                labelController.setModelColumn(13);
                return labelController;
            }
            case 7: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setModelColumn(3);
                return labelController;
            }
            case 8: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -393871104});
                iconController.setModelColumn(9);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 9: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                return labelController;
            }
            case 10: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 344391936, -1383726848});
                iconController.setModelColumn(16);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 11: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(2);
                return labelController;
            }
            case 12: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(2, this.val$terminalID));
                labelController.setModelColumn(2);
                return labelController;
            }
            case 13: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 1166475520, 1183252736, 1200029952, 1216807168, 1233584384, 1250361600, 1267138816, 1283916032});
                iconController.setModelColumn(8);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 14: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(5);
                return labelController;
            }
            case 15: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(6);
                return labelController;
            }
            case 16: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -377093888, -511311616, -1417281280});
                iconController.setModelColumn(7);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 17: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127});
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 18: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 861, 862, 863, 864, 865, 866, 867, 868, 869, 870, 871, 872, 873, 874, 875, 876, 877, 878, 879, 880, 881, 882, 883, 884, 885, 886, 887, 888, 889, 890, 891, 892, 893, 894, 895, 896, 897, 898, 899, 900, 901, 902, 903, 904, 905, 906, 907, 908, 909, 910, 1166475520, 1183252736, 1200029952, 1216807168, 1233584384, 1250361600, 1267138816, 1283916032});
                iconController.setModelColumn(8);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 19: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(6, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(5);
                return labelController;
            }
            case 20: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(6, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(6);
                return labelController;
            }
            case 21: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, -377093888, -511311616, -1417281280});
                iconController.setModelColumn(7);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 22: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 1300693248, -494534400});
                iconController.setModelColumn(22);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 23: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 847708416});
                iconController.setModelColumn(14);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 24: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(12);
                return labelController;
            }
            case 25: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 864485632});
                iconController.setModelColumn(15);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 26: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(13);
                return labelController;
            }
            case 27: {
                IconController iconController = new IconController();
                IconRendererHigh iconRendererHigh = new IconRendererHigh(iconController);
                iconController.setRenderer(iconRendererHigh);
                iconController.setBitmaps(new int[]{127, 881262848});
                iconController.setModelColumn(21);
                iconController.setPreferredHeight(1);
                iconRendererHigh.setAlignment(1, 5);
                return iconController;
            }
            case 28: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(1, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(20);
                return labelController;
            }
            case 29: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelController.setModelColumn(3);
                return labelController;
            }
            case 30: {
                LabelController labelController = new LabelController();
                LabelRendererHigh labelRendererHigh = new LabelRendererHigh(labelController);
                labelController.setRenderer(labelRendererHigh);
                labelRendererHigh.setFonts(this.val$factory.getFonts(6, this.val$terminalID));
                labelController.setColorIndices(new int[]{1, 6, 4, 0});
                labelController.setModelColumn(3);
                return labelController;
            }
        }
        return null;
    }
}

