/*
 * Decompiled with CFR 0.152.
 */
package de.esolutions.fw.comm.asi.hmisync.media;

public interface ASIHMISyncMedia {
    public static final String IPL_COMM_UUID = "848d4459-b390-4cdf-b374-6d4783690a1b";
    public static final String IPL_COMM_INTERFACE_KEY = "ec49cac0-e751-57fe-b753-0d3e4dc75d6e";
    public static final String IPL_COMM_INTERFACE_VERSION = "4.8.2";
    public static final String IPL_COMM_MODULE_VERSION = "1.0.00";

    public static interface Consts {
        public static final int SOURCE_UNDEFINED = 0;
        public static final int SOURCE_DVDDRIVE = 1;
        public static final int SOURCE_SDCARD = 2;
        public static final int SOURCE_JUKEBOX = 3;
        public static final int SOURCE_USB = 4;
        public static final int SOURCE_DVD_CHANGER = 5;
        public static final int SOURCE_STATE_UNDEFINED = 0;
        public static final int SOURCE_STATE_EMPTY = 1;
        public static final int SOURCE_STATE_LOADING = 2;
        public static final int SOURCE_STATE_READY = 3;
        public static final int SOURCE_STATE_UNREADABLE = 4;
        public static final int SOURCE_STATE_NOT_SUPPORTED = 5;
        public static final int SOURCE_STATE_WRONG_REGION_CODE = 6;
        public static final int SOURCE_STATE_CHILDLOCK = 7;
        public static final int SOURCE_STATE_NO_PLAYABLE_FILES = 8;
        public static final int SOURCE_STATE_JUKEBOX_NOT_FILLED = 9;
        public static final int SOURCE_STATE_GENERIC_ERROR = 10;
        public static final int SOURCE_TYPE_UNDEFINED = 0;
        public static final int SOURCE_TYPE_FILESYSTEM = 1;
        public static final int SOURCE_TYPE_CDAUDIO = 2;
        public static final int SOURCE_TYPE_DVDVIDEO = 3;
        public static final int SOURCE_TYPE_IPOD = 4;
        public static final int SOURCE_TYPE_RCP = 5;
        public static final int SOURCE_FLAG_SYNCED_FILESYSTEM = 1;
        public static final int SOURCE_FLAG_SYNCED_METADATA = 2;
        public static final int SOURCE_FLAG_SYNCED_COVERART = 4;
        public static final int SOURCE_FLAG_SYNC_COMPLETE = 8;
        public static final int SOURCE_FLAG_SUPPORT_CAPABILITIES = 256;
        public static final int SOURCE_FLAG_CAPABILITY_PLAYER_COVERART = 512;
        public static final int SOURCE_FLAG_CAPABILITY_BROWSER_COVERART = 1024;
        public static final int SOURCE_FLAG_CAPABILITY_VIDEO = 2048;
        public static final int SOURCE_FLAG_CAPABILITY_PLAYMODES = 4096;
        public static final int SOURCE_FLAG_CAPABILITY_SEARCH = 8192;
        public static final int SOURCE_FLAG_CAPABILITY_CONTENT_BROWSING = 16384;
        public static final int SOURCE_FLAG_CAPABILITY_RAW_BROWSING = 32768;
        public static final int SOURCE_FLAG_CAPABILITY_IMPORT_DATA = 65536;
        public static final int ACTIVE_SOURCE_STATE_READY = 1;
        public static final int ACTIVE_SOURCE_STATE_LOADING = 2;
        public static final int ACTIVE_SOURCE_STATE_ON_CHANGE = 3;
        public static final int ACTIVE_SOURCE_STATE_NOT_ACTIVATEABLE = 4;
        public static final int ACTIVE_SOURCE_STATE_TEMP_CHILDLOCK = 5;
        public static final int PLAYLIST_FLAG_COMPLETE_UPDATE = 1;
        public static final int PLAYLIST_FLAG_INVALIDATED = 2;
        public static final int PLAYLIST_FLAG_COVERS_UPDATED = 4;
        public static final int PLAYLIST_FLAG_METADATA_UPDATED = 8;
        public static final int PLAYLIST_SUPPORT_STATEFLAGS = 256;
        public static final int PLAYMORE_CATEGORY_GENRE = 1;
        public static final int PLAYMORE_CATEGORY_ARTIST = 2;
        public static final int PLAYMORE_CATEGORY_ALBUM = 3;
        public static final int MEDIA_RESULTCODE_OK = 0;
        public static final int MEDIA_RESULTCODE_ERROR = 1;
        public static final int PLAYBACK_POSSIBLE_OK = 0;
        public static final int PLAYBACK_POSSIBLE_GENERIC_REASON = -1;
        public static final int PLAYER_CAPABILITY_SKIP_FWD = 1;
        public static final int PLAYER_CAPABILITY_SKIP_BWD = 2;
        public static final int PLAYER_CAPABILITY_BROWSE_WHILE_PLAY = 4;
        public static final int PLAYER_CAPABILITY_FAST_FWD = 8;
        public static final int PLAYER_CAPABILITY_FAST_BWD = 16;
        public static final int PLAYER_CAPABILITY_SLOMO_FWD = 32;
        public static final int PLAYER_CAPABILITY_SLOMO_BWD = 64;
        public static final int PLAYER_CAPABILITY_STILL_FWD = 128;
        public static final int PLAYER_CAPABILITY_STILL_BWD = 256;
        public static final int PLAYER_CAPABILITY_PLAY = 512;
        public static final int PLAYER_CAPABILITY_RESUME = 1024;
        public static final int PLAYER_CAPABILITY_PAUSE = 2048;
        public static final int PLAYER_CAPABILITY_STOP = 4096;
        public static final int PLAYER_CAPABILITY_SET_ENTRY = 8192;
        public static final int PLAYER_CAPABILITY_SET_TIME_POS = 16384;
        public static final int PLAYER_CAPABILITY_PLAYBACK_MODES = 32768;
        public static final int PLAYER_CAPABILITY_DETAIL_INFOS = 65536;
        public static final int PLAYER_CAPABILITY_PLAY_VIEW = 131072;
        public static final int PLAYER_CAPABILITY_PLAY_SIMILAR_ENTRIES = 262144;
        public static final int PLAYER_CAPABILITY_TOTAL_PLAYTIME = 524288;
        public static final int PLAYER_CAPABILITY_EXTENDED_PLAY_VIEW = 0x100000;
        public static final int PLAYER_CAPABILITY_PLAY_TIME = 0x200000;
        public static final int PLAYER_CAPABILITY_PLAYBACKMODE_TOGGLE = 0x400000;
        public static final int I18N_KEY_NOT_INTERNATIONALIZED = 0;
        public static final int I18N_KEY_PLAYLISTS = 1;
        public static final int I18N_KEY_ARTISTS = 2;
        public static final int I18N_KEY_UNKNOWN_ARTIST = 3;
        public static final int I18N_KEY_UNKNOWN_ARTISTS = 4;
        public static final int I18N_KEY_ALBUMS = 5;
        public static final int I18N_KEY_UNKNOWN_ALBUM = 6;
        public static final int I18N_KEY_UNKNOWN_ALBUMS = 7;
        public static final int I18N_KEY_GENRES = 8;
        public static final int I18N_KEY_UNKNOWN_GENRE = 9;
        public static final int I18N_KEY_UNKOWN_GENRES = 10;
        public static final int I18N_KEY_UNKNOWN_GENRES = 10;
        public static final int I18N_KEY_COMPOSERS = 11;
        public static final int I18N_KEY_MUSIC = 12;
        public static final int I18N_KEY_VIDEOS = 13;
        public static final int I18N_KEY_VOICEMEMOS = 15;
        public static final int I18N_KEY_AUDIOBOOKS = 16;
        public static final int I18N_KEY_PODCASTS = 17;
        public static final int I18N_KEY_ALL = 18;
        public static final int I18N_KEY_DYN_PLAYLIST_STARS0 = 19;
        public static final int I18N_KEY_DYN_PLAYLIST_STARS1 = 20;
        public static final int I18N_KEY_DYN_PLAYLIST_STARS2 = 21;
        public static final int I18N_KEY_DYN_PLAYLIST_STARS3 = 22;
        public static final int I18N_KEY_DYN_PLAYLIST_STARS4 = 23;
        public static final int I18N_KEY_DYN_PLAYLIST_STARS5 = 24;
        public static final int I18N_KEY_DYN_PLAYLIST_MOST_PLAYED = 25;
        public static final int I18N_KEY_DYN_PLAYLIST_LAST_PLAYED = 26;
        public static final int I18N_KEY_DYN_PLAYLIST_ON_THE_GO = 27;
        public static final int I18N_KEY_DYN_PLAYLISTS = 28;
        public static final int I18N_KEY_DYN_PLAYLIST_FAVORITEN = 29;
        public static final int I18N_KEY_VARIOUS_ARTISTS = 30;
        public static final int I18N_KEY_MUSIC_VIDEOS = 31;
        public static final int I18N_KEY_RENTED_MOVIES = 32;
        public static final int I18N_KEY_SONGS = 33;
        public static final int I18N_KEY_TV_SHOWS = 34;
        public static final int I18N_KEY_VIDEO_PLAYLISTS = 35;
        public static final int I18N_KEY_VIDEO_PODCASTS = 36;
        public static final int I18N_KEY_MOVIES = 37;
        public static final int I18N_KEY_NOT_PLAYABLE = 38;
        public static final int I18N_KEY_PLAYLISTS_AND_COVERS = 39;
        public static final int I18N_KEY_CDDA_TRACK = 40;
        public static final int I18N_KEY_DVDV_CHAPTER = 41;
        public static final int I18N_KEY_DVDA_AUDIO_TRACK = 42;
        public static final int I18N_KEY_DVDV_TITLE = 43;
        public static final int I18N_KEY_NOW_PLAYING = 44;
        public static final int I18N_KEY_UNKNOWN_TITLE = 45;
        public static final int I18N_KEY_ITUNES_UNIVERSITY = 46;
        public static final int I18N_KEY_GENIUS_PLAYLISTS = 47;
        public static final int I18N_KEY_DYN_PLAYLIST_LAST_COPIED = 48;
        public static final int I18N_KEY_ITUNES_RADIO = 49;
        public static final int I18N_KEY_UNKNOWN_COMPOSER = 50;
        public static final int I18N_KEY_UNKNOWN_COMPOSERS = 51;
        public static final int MEDIA_ENTRY_TYPE_UNDEFINED = 0;
        public static final int MEDIA_ENTRY_TYPE_FILE_AUDIO = 1;
        public static final int MEDIA_ENTRY_TYPE_FILE_VIDEO = 2;
        public static final int MEDIA_ENTRY_TYPE_FILE_PLAYLIST = 3;
        public static final int MEDIA_ENTRY_TYPE_FOLDER = 4;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_PLAYLIST = 5;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_ALBUM = 6;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_ARTIST = 7;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_GENRE = 8;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_DYNAMIC_PLAYLIST = 9;
        public static final int MEDIA_ENTRY_TYPE_UNDEFINED_VIDEO = 10;
        public static final int MEDIA_ENTRY_TYPE_FILE_AUDIO_ONLINE = 11;
        public static final int MEDIA_ENTRY_TYPE_FILE_AUDIO_ONLINE_UNDEFINED = 12;
        public static final int MEDIA_ENTRY_TYPE_FILE_VIDEO_ONLINE = 13;
        public static final int MEDIA_ENTRY_TYPE_FILE_VIDEO_ONLINE_UNDEFINED = 14;
        public static final int MEDIA_ENTRY_TYPE_FILE_RADIO_ONLINE = 15;
        public static final int MEDIA_ENTRY_TYPE_FILE_RADIO_ONLINE_UNDEFINED = 16;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_AUDIO = 17;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_TITLE = 18;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_COMPOSER = 19;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_PODCASTS = 20;
        public static final int MEDIA_ENTRY_TYPE_FOLDER_AUDIOBOOK = 21;
        public static final long MEDIA_INVALID_ID = 0L;
        public static final int PLAYBACKSTATE_PLAYING = 0;
        public static final int PLAYBACKSTATE_PAUSED = 1;
        public static final int PLAYBACKSTATE_SEEK_FORWARD = 2;
        public static final int PLAYBACKSTATE_SEEK_BACKWARD = 3;
        public static final int PLAYBACKSTATE_STOPPED = 4;
        public static final int PLAYBACKSTATE_NOT_READY = 5;
        public static final int PLAYBACKSTATE_PLAYING_MENU = 6;
        public static final int REPEATSTATE_OFF = 0;
        public static final int REPEATSTATE_TRACK = 1;
        public static final int REPEATSTATE_ALL = 2;
        public static final int SHUFFLESTATE_OFF = 0;
        public static final int SHUFFLESTATE_ALBUM = 1;
        public static final int SHUFFLESTATE_SONGS = 2;
        public static final int TOUCHEVENT_BUTTON_SELECT = 0;
        public static final int TOUCHEVENT_BUTTON_ACTIVATE = 1;
        public static final int DVD_VIDEO_COMMAND_MENU = 1;
        public static final int DVD_VIDEO_COMMAND_LEFT = 2;
        public static final int DVD_VIDEO_COMMAND_RIGHT = 3;
        public static final int DVD_VIDEO_COMMAND_UP = 4;
        public static final int DVD_VIDEO_COMMAND_DOWN = 5;
        public static final int DVD_VIDEO_COMMAND_OK = 6;
        public static final int DVD_VIDEO_COMMAND_EXIT = 7;
        public static final int CMD_BLOCKED_NONE = 0;
    }

    public static class ReplyIDs {
        public static final short indicationCmdBlocked = 35;
        public static final short responsePlayList = 9;
        public static final short responseSetPlaySelection = 10;
        public static final short responsePlayMoreFrom = 34;
        public static final short updateASIVersion = 21;
        public static final short updateRequestIDs = 32;
        public static final short updateReplyIDs = 31;
        public static final short updateSourceList = 30;
        public static final short updateActiveSlotState = 22;
        public static final short updatePlaybackState = 27;
        public static final short updateListState = 23;
        public static final short updatePlayerCapabilities = 38;
        public static final short updateMix = 24;
        public static final short updateRepeatTitle = 29;
        public static final short updateRepeatState = 41;
        public static final short updateShuffleState = 42;
        public static final short updatePlayingTrack = 28;
        public static final short updatePlayPosition = 25;
        public static final short updatePlaybackFolder = 26;
        public static final short updatePlaybackPossible = 37;

        public static short[] getIDs() {
            return new short[]{35, 9, 10, 34, 21, 32, 31, 30, 22, 27, 23, 38, 24, 29, 41, 42, 28, 25, 26, 37};
        }
    }

    public static class RequestIDs {
        public static final short activate = 0;
        public static final short resume = 11;
        public static final short pause = 6;
        public static final short skip = 19;
        public static final short seek = 12;
        public static final short stopSeek = 36;
        public static final short mix = 5;
        public static final short repeatTitle = 7;
        public static final short toggleRepeatState = 39;
        public static final short toggleShuffleState = 40;
        public static final short setEntry = 13;
        public static final short setTimePosition = 18;
        public static final short touchEvent = 20;
        public static final short executeDvdVideoCommand = 4;
        public static final short requestPlayList = 8;
        public static final short setPlaySelection = 17;
        public static final short playMoreFrom = 33;
        public static final short setNotification_14 = 14;
        public static final short setNotification_16 = 16;
        public static final short setNotification_15 = 15;
        public static final short clearNotification_1 = 1;
        public static final short clearNotification_3 = 3;
        public static final short clearNotification_2 = 2;

        public static short[] getIDs() {
            return new short[]{0, 11, 6, 19, 12, 36, 5, 7, 39, 40, 13, 18, 20, 4, 8, 17, 33, 14, 16, 15, 1, 3, 2};
        }
    }

    public static interface AttributesIDs {
        public static final long ASIVersion = 21L;
        public static final long RequestIDs = 32L;
        public static final long ReplyIDs = 31L;
        public static final long SourceList = 30L;
        public static final long ActiveSlotState = 22L;
        public static final long PlaybackState = 27L;
        public static final long ListState = 23L;
        public static final long PlayerCapabilities = 38L;
        public static final long Mix = 24L;
        public static final long RepeatTitle = 29L;
        public static final long RepeatState = 41L;
        public static final long ShuffleState = 42L;
        public static final long PlayingTrack = 28L;
        public static final long PlayPosition = 25L;
        public static final long PlaybackFolder = 26L;
        public static final long PlaybackPossible = 37L;
    }
}

